### ISSUE TITLE
Always logs "[CodePush] App is up to date" even after new release updates (iOS)

### ISSUE THREAD

**Issue by kevinejohn** [Microsoft/code-push#121]
I've been trying to get CodePush to work but haven't gotten it to recognize any release updates I push for iOS (Haven't tried Android yet).

Here were my steps I took after successfully registering: 

1. Followed all the install instructions listed here: https://microsoft.github.io/code-push/docs/react-native.html#link-3 including adding CodePush.sync() in the javascript and "jsCodeLocation = [CodePush bundleURL];" in the objective-c while adding the correct CodePush deployment key to the plist.

2. Build the new update with new JS changes:
$ react-native bundle --platform ios --entry-file index.ios.js --bundle-output codepush.js --dev false

3. Upload to Staging:
$ code-push release <MyCodePushAppName> codepush.js 2.2.2 -m

$ code-push deployment ls <MyCodePushAppName> --format json
[
  {
    "name": "Production",
    "package": {
      "description": "",
      "appVersion": "2.2.2",
      "isMandatory": true,
      "packageHash": "ac9c025...",
      "blobUrl": "https://codepush.blob.core.windows.net/storagev2/44232...",
      "size": 581785,
      "releaseMethod": "Upload",
      "uploadTime": 1453676143623,
      "label": "v3"
    }
  },
  {
    "name": "Staging",
    "package": {
      "description": "",
      "appVersion": "2.2.2",
      "isMandatory": true,
      "packageHash": "42b7402434fe6f...",
      "blobUrl": "https://codepush.blob.core.windows.net/storagev2/12vUhcHefwef...",
      "size": 581785,
      "releaseMethod": "Upload",
      "uploadTime": 1453675949367,
      "label": "v5"
    }
  }
]

Then when I run the app from XCode with the plist version set to 1.0.0 I always get the following log message with no updates:

2016-01-24 15:07:38.754 [trace][tid:com.facebook.React.JavaScript] [CodePush] Checking for update.
2016-01-24 15:07:38.952 [trace][tid:com.facebook.React.JavaScript] [CodePush] App is up to date.

Is there a way to debug this further to see why its not recognizing any new releases I push?

**Comment by lostintangent** [comment]
If the version in your Info.plist file is 1.0.0, then you need to pass that exact version to the call to the release command, otherwise, the server won't think the CodePush release is applicable to the client. If you call "code-push release [APP] codepush.js 1.0.0", the app should see the update (assuming that 1.0.0 is in fact our app version). Let me know how that guys!

**Comment by kevinejohn** [comment]
That was the problem. Thanks!

I saw the instruction to add the semver "(e.g. 1.0.0 not 1.0)" to the plist and then later when it describes pushing it references "1.0.3" which made me assume it has to be later then the previous app version. I missed the sentence where it tells you to use the exact version number on the build.

Thanks again

**Comment by lostintangent** [comment]
Yay! That is actually really great feedback!! I'll update the docs to not reference the 1.0.3 version since j totally agree that is confusing :) Thanks so much for the feedback and for trying out the service. Let us know if you hit any other issues.
