### ISSUE TITLE
[cordova] My app hangs in iOS simulator after implementing CodePush SDK (randomly)

### ISSUE THREAD

**Issue by jrebagliatti** [Microsoft/code-push#147]
Hi guys. I've followed the steps to implement CodePush in a blank Cordova app, and after adding the ```codePush.sync()``` call, my app hangs most of the times. I added the ```onStatusChange``` callback and confirmed that the function is called at least once before hanging. 

```javascript
    onDeviceReady: function () {
        codePush.sync(app.onStatusChange);
        app.receivedEvent('deviceready');
    },
```

I also found a workaround, which is to call the ```sync``` method from a ```setTimeout```, a second before initialization.

```javascript
    onDeviceReady: function () {
        setTimeout(function () {
            codePush.sync(app.onStatusChange);
        }, 1000);
        app.receivedEvent('deviceready');
    },
```

I'm deploying to the iOS simulator.

Any ideas?

Thanks,
Javier

**Comment by lostintangent** [comment]
@jrebagliatti That is bizarre! We haven't seen this issue before. If you take a look at the Safari developer console, what do you see the logs saying when you call `sync`? That might help provide some indication of the problem.

Additionally, just so I have some more detail:

1. Did the hang only happen after adding the call to `sync`? Specifically, just adding the CodePush plugin to your app didn't cause the hang?

2. Is `onDeviceReady` being called only once? If you added a breakpoint or a log message inside of it, would it be hit/logged multiple times? It's possible we have an issue with `sync` being run multiple times in parallel, so I just want to check if this is happening for you.

3. If you simply call `codePush.checkForUpdate` does the hang go away? I want to try to narrow down the issue to `sync` if possible, as opposed to any network activity generated by our SDK.

Thanks! Sorry for the inconvenience. We'll try to narrow down this problem ASAP :)

**Comment by jrebagliatti** [comment]
Thanks for your response @lostintangent!

Since the problem is in the app initialization I wasn't able to use the Safari developer console. Any trick I've tried to stop the initialization (and give me some time to start the console) makes the app to work properly...

Regarding your questions:
1. Just adding the plugin don't cause any problem
2. Yes, it is called only once. I've checked.
3. No, it seems to happen with any of the CodePush methods.

**Comment by lostintangent** [comment]
Did you try running "location.reload()" in the console to force a re-initialization to see the logs?

Also, could you answer question #2 above?

**Comment by jrebagliatti** [comment]
Thanks for all your help!. I've restarted the simulator and the app started work as expected, so I'm closing the issue. I think the issue could be related with the simulator and not with the CodePush API.

Just FYI reloading the page didn't help because the app worked nicely every time I reloaded it. Regarding the question #2 I was using ```cordova run ios```.

Thank you very much for your time!
