### ISSUE TITLE
there is something concern me

### ISSUE THREAD

**Issue by xhacker5000** [Microsoft/code-push#151]
our project really need code-push to update the logic where coding in react-native.
more and more user grow up in our App.
I am worry if someday code-push cannot bearer so many these user , you know ,more user , more network connection , I am worry code-push server will cannot response so fast , and the coding download server will be set in USA , the user who is my app almost from Asia , even now there's download speed is not satisfactory.

Is there any way to build project  like ``git-lab`` can allowed people created code-push service in their own server machine ?
that's would be nice , that's would be more powerful download speed and code-push users can balanced load handle the large user login scene.

I am appreciate what the code-push team done , If there some solution for this needed , that's would be awesome

**Comment by lostintangent** [comment]
You don't need to to worry about the ability of the CodePush service to handle the load of your users. We monitor the service's capacity/health very closely and adjust resources as needed. If you have a particularly high user audience (10s of millions+), and want to chat more about this, I would love to understand your concerns better.

That said, as you mentioned, our servers currently only run in the US, and so I can totally appreciate the network latency between Asia not being ideal. We plan to geo-distribute the service in the coming months as part of exiting the beta phase, but we don't have any firm dates yet for when that will happen unfortunately.

**Comment by lostintangent** [comment]
@xhacker5000 Is the main thing that concerns you the performance of the update download for your end-users? What about the update check itself? Does that seem too slow as well? If we were to geo-replicate the update contents to other regions (e.g. China), would that be satisfactory to improve the experience? 

Additionally, how do you find the performance of managing your account from the CLI? I'd be curious to know how critical you thought improvements to that part of the workflow is.

Thanks!

**Comment by lostintangent** [comment]
I'm going to close this issue for now since it isn't an actionable bug, but next sprint we're going to be investigating how to improve the perf outside of the US, so we'll keep you posted. Please re-open this issue if you want to continue discussing this. Thanks!

**Comment by norfish** [comment]
the service download speed is poor in asia, be sure
