### ISSUE TITLE
Code-Push Breaks with Push Notifications 

### ISSUE THREAD

**Issue by rajeevkannav** [Microsoft/code-push#159]
I am using [PushNotification](https://github.com/phonegap/phonegap-plugin-push) for cordova apps. My application.js code looks like  [Gist](https://gist.github.com/rajeevkannav/4b88157b814a933a5d64)

When i install above plugin and write required code Everything brakes and my app goes to first state of code-push. Any Idea ?

**Comment by lostintangent** [comment]
Hmm, we haven't heard of this issue before. Could you elaborate a little on what you mean by everything breaks? Are you getting exception messages in the console that indicate any issues, or is it just that the app is loading the binary version now instead of the latest a CodePush update?

**Comment by rajeevkannav** [comment]
it just that the app is loading the binary version now instead of the latest a CodePush update using PushNotification Code.

PS: You guys are doing best thing in Microsoft Thank you !

**Comment by lostintangent** [comment]
Could you check whether or not the issue occurs after simply adding the push plugin to your app, or if you need to add the init/config code that you mentioned in your gist? I'll investigate this ASAP to figure out what might be the issue. Thanks for reporting it.

**Comment by rajeevkannav** [comment]
fixed, issue was at our end

**Comment by lostintangent** [comment]
@rajeevkannav Thanks for letting us know!
