### ISSUE TITLE
[CLI] Is it possible to tell code-push cli to create archives in a separate directory?

### ISSUE THREAD

**Issue by okonon** [Microsoft/code-push#161]
[CLI] Is it possible to tell code-push cli to create archives in a separate directory? The problem is that right now cli creates zip files in the root of the project over time this becomes really messy

**Comment by lostintangent** [comment]
@okonon There isn't a way to do this right now, but the CLI should be deleting the zips it creates after a release is finished uploading, which would resolve the problem you're seeing.

Could you do me a favor and check whether it does this after a successful upload? I believe we have a bug where the zip doesn't get cleared if an error occurs during the upload, which we can definitely get fixed ASAP. I'm just curious though if you're seeing the zip remain after every release, successful or not.

Thanks for reporting this!
