### ISSUE TITLE
Linker error from cocoapods install

### ISSUE THREAD

**Issue by arthurpark** [Microsoft/code-push#163]
Hi, I'm trying to integrate RN with code push to existing iOS app. 

Integrating RN was successful (using cocoa pods).
Then I tried to add Code Push using cocoapods. `pod install` ran fine with code push, but when I tried to build the project, I get a linker error.

Here's the error message (truncated some paths)
```
duplicate symbol _OBJC_IVAR_$_SSZipArchive._zip in: ...libCodePush.a(SSZipArchive.o)
duplicate symbol _OBJC_IVAR_$_SSZipArchive._path in: ...libCodePush.a(SSZipArchive.o)
duplicate symbol _OBJC_CLASS_$_SSZipArchive in: ...libCodePush.a(SSZipArchive.o)
duplicate symbol _OBJC_METACLASS_$_SSZipArchive in: ...libCodePush.a(SSZipArchive.o)
duplicate symbol _OBJC_IVAR_$_SSZipArchive._filename in: ...libCodePush.a(SSZipArchive.o)

ld: 5 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

`SSZipArchive` was in already Podfile before adding code push.

Can you help me? Thanks.

**Comment by lostintangent** [comment]
Hey @arthurpark! The CodePush plugin ships with a copy of the `SSZipArchive` codebase, so if you're integrating it into a project that already includes it, you would get this error. Could you try something for me? If you update our `CodePush.podspec`, by turning this:

`s.source_files = 'ios/CodePush/*.{h,m}', 'ios/CodePush/SSZipArchive/*.{h,m}', 'ios/CodePush/SSZipArchive/aes/*.{h,c}', 'ios/CodePush/SSZipArchive/minizip/*.{h,c}'`

into this:

`s.source_files = 'ios/CodePush/*.{h,m}'`

and then re-running `pod install`, does that resolve the issue? I'll try this repro in a second, but this may be a quick work-around for you. I'm not sure what the right convention is here, but it's possible that we could ship with two pod specs, one with and without `SSZipArchive`, to better accomodate this scenario.

**Comment by arthurpark** [comment]
Ah, this worked. Thanks!!
