### ISSUE TITLE
New Website Logo: Hover

### ISSUE THREAD

**Issue by kevinejohn** [Microsoft/code-push#164]
I would like to add my app to the CodePush showcase!

- Name: Hover
- Homepage (or app store) url: http://www.hoverapp.io
- Brand Guidelines/Licensing: None
- Logo: http://a5.mzstatic.com/us/r30/Purple3/v4/ba/55/e6/ba55e6ee-71cf-b843-f592-0917c9b6c645/icon175x175.png

**Comment by lostintangent** [comment]
Hey @kevinejohn! It's exciting to see what you've been working on after talking to you a few times on GitHub :) Hover looks awesome! We'll add it to the showcase tomorrow. Thanks so much for reaching out.

**Comment by kevinejohn** [comment]
@lostintangent awesome. Thanks again for all the help!

**Comment by lostintangent** [comment]
This is now live! Thanks so much for using CodePush :D
