### ISSUE TITLE
there's always Server error when I upload my code

### ISSUE THREAD

**Issue by xhacker5000** [Microsoft/code-push#175]
Upload progress:[==================================================] 100% 0.0s
[Error]  Internal Server Error

Why ?
I just update 1.7.0-beta code-push-cli from 1.6.0

**Comment by xhacker5000** [comment]
and I use this shell 
``
react-native bundle --platform ios --entry-file index.ios.js --bundle-output main.jsbundle --dev false
code-push release time_castle_client main.jsbundle 1.0.1 --deploymentName "Staging" --description "发布" --mandatory true
``

**Comment by xhacker5000** [comment]
you can close this issue now , I found the problem what is I never upload the 1.0.0 version .
the shell is version 1.0.1 
But i think if there some tip will be fine

**Comment by dtivel** [comment]
Thanks for reporting the issue, xhacker5000.  I'll try to repro this and find a fix.

Damon

**Comment by dtivel** [comment]
Hi, xhacker5000.

I'm trying to repro this.  How large was your main.jsbundle file when the release failed with "Internal Server Error"?  Can you estimate how long it took between executing the `release` command and the failure occurring?

Thanks,

Damon

**Comment by xhacker5000** [comment]
OK,it's easy to reshow this bug, when I finish dinner I will comment here

**Comment by xhacker5000** [comment]
main.jsbundle less 1Mb and I sure it, when the command line show the 100% percent will wait 30 seconds, then show the error.

I have 2 apps in code push , I start try another app when the error apps faild more than 10 times, at the first time I thinks it maybe I update the cli version,But the other app was good for release cmd , successful in 1 time , then I found ther version arg where the shell I called is 1.0.1( no file I released until now ), then I change it to 1.0.0,  errors gone , release successd

**Comment by dtivel** [comment]
That's the curious part, the version --- as long as it is semver compliant --- should not matter.  1.0.1 should release just fine even if there isn't a preceding 1.0.0 release.

Here's a little test I just did with a brand new app:

    code-push app add MyApp
    Successfully added the "MyApp" app, along with the following default deployments:

[deployment keys omitted]

    code-push release MyApp main.jsbundle 1.0.1 --deploymentName "Staging" --description "first deployment" --mandatory true
    Upload progress:[==================================================] 100% 0.0s
    Successfully released an update containing the "main.jsbundle" file to the "Staging" deployment of the "MyApp" app.

**Comment by dtivel** [comment]
Hey, xhacker5000.

When you hit the "internal server error" are you behind a proxy server, like at work?

Thanks,

Damon

**Comment by xhacker5000** [comment]
No proxy here , it's director connection

**Comment by xhacker5000** [comment]
I guess the problem is the app was created at once, maybe it need sometime to work ok, old project which I already release it's fine

Oh I am Chinese user , network is little lag from your server, every time I release version the network speed is 4-5kb / sec ...network problem huh

**Comment by xhacker5000** [comment]
But I never seen the ''internal severe error ''  before create that App

**Comment by dtivel** [comment]
Apologies for the inconvenience.

We were hitting a Node.js default connection timeout of 2 minutes.  Uploading a large file over a slow network connection could hit this timeout.

I have increased the timeout.  Also, the server should now return an HTTP 408 (request timeout) instead of a 500 (internal server error) in case of a timeout.

Can you please try again and let me know the result?

Thanks,

Damon

**Comment by lostintangent** [comment]
@xhacker5000 We've resolved this issue on the server, so you shouldn't run into it anymore. Please re-open this if it occurs again. Thanks for the patience while we worked it out!

**Comment by LeBlaaanc** [comment]
Possible reoccurring in #235
