### ISSUE TITLE
New Website Logo: Taxfyle

### ISSUE THREAD

**Issue by kwcto** [Microsoft/code-push#177]
Name: Taxfyle
Homepage url: https://itunes.apple.com/us/app/taxfyle/id1058033104?mt=8
Brand Guidelines/Licensing: Use as you see fit when referencing the Taxfyle App.
Logo: https://s3.amazonaws.com/taxfyle-public/images/taxfyle-icon-1024px.png
Notes: Recently featured in #1 iOS App Store slot under "Best New Apps"

**Comment by lostintangent** [comment]
@kwcto Taxfyle looks awesome! Thanks for using CodePush and letting us know :) We'll add this to the showcase this afternoon.

**Comment by RuRios** [comment]
@kwcto The logo is now part of the showcase. Thanks for reaching out! :)
