### ISSUE TITLE
Electron support

### ISSUE THREAD

**Issue by mhagmajer** [Microsoft/code-push#190]
I'd like to do code-push updates for [Electron](http://electron.atom.io/). What would be the best way to go about that?

**Comment by lostintangent** [comment]
I don't know much about Electron, but I suspect we would need to create an implementation of our client SDK for it. It something that we've talked about before and would be very interested to help with if the community was interested enough.

**Comment by lostintangent** [comment]
Is this still something that folks would be interested in seeing?

**Comment by mhagmajer** [comment]
Yes, I'll definitely be working on that this quarter unless of course this
is already on the roadmap.

**Comment by lostintangent** [comment]
Awesome! It isn't currently on our roadmap, but I'm really excited to get this going, and help as much as possible :) If you're planning to kick-start this, do you think it makes sense for us to close this issue, since it isn't immediately actionable on our side? I would definitely want to treat the Electron SDK as a first-class citizen, and make sure it gets the right visibility, so we could make sure to link to the repo/docs once available.

**Comment by mhagmajer** [comment]
Sure. Feel free to close the issue and let's resume the discussion on a PR
once its out there. Thanks!

**Comment by lostintangent** [comment]
@mhagmajer Sounds good. Thanks!

**Comment by mhagmajer** [comment]
@lostintangent I'm going to try to leverage this first http://electron.atom.io/docs/api/auto-updater/ . An interesting thing about electron is that it runs JavaScript both on the host and client side of the application. This is contrary to React Native which of course runs Java / ObjectiveC code on Android, iOS respectively.

**Comment by lostintangent** [comment]
The existence of the auto-updater API is what has prevented us from prioritizing adding Electron support to CodePush. I think our feature set is still really compelling, but I want to make sure it's valuable enough before moving forward. For now, I think we're assuming that folks can get by with the Electron auto-updater and an open source server solution, but I'm interested to hear more if CodePush support for Electron would make sense.

**Comment by PierBover** [comment]
@lostintangent yes it would make sense.

Electron auto-updater still requires you to configure your own server...

**Comment by mhagmajer** [comment]
I agree, I played with this a little bit and would much prefer to have CodePush there instead. The caveat is being able to push code for both renderer (web browser) and main (node.js). Both would require restarting the app after restart.

**Comment by PierBover** [comment]
> Both would require restarting the app after restart.

I'd rather make my users deal with that (which is almost a standard at least in OSX) than having to deal with Squirrel.

**Comment by dovy** [comment]
Please, reopen this. We need electron support asap.

**Comment by PierBover** [comment]
We've been struggling for days to implement Squirrel on Electron and still haven't finished.

CodePush for Electron would be the best thing since sliced bread.

**Comment by dovy** [comment]
So... how can we help to implement this?

**Comment by PierBover** [comment]
Probably the only thing the community could do is to work on a plugin for electron, but without an effort from the CodePush team to implement stuff on the CLI and the server it would be useless.

**Comment by dovy** [comment]
:(

**Comment by piyushjo** [comment]
Hi guys, I noticed the recent activity on this thread and just want to say that our CodePush team is mainly focusing on the mobile experience at the moment so Electron is not on our priority. Having said this, we are monitoring the adoption of Electron and this may become important sometime in the future but just not yet. Thank you for the feedback.

**Comment by PierBover** [comment]
Thanks for the answer @piyushjo

**Comment by dovy** [comment]
Disappointing.

**Comment by okonon** [comment]
@piyushjo wondering if you guys changed your mind regarding Electron support?

CodePush for electron would be killer feature. More and more companies are starting adopt Electron due to hybrid nature of it for cost savings reasons.

**Comment by PierBover** [comment]
Like @piyushjo said Electron is more popular every day, but as of today there are no good solutions for updating an Electron app.

Squirrel is what the Electron team still recommends. It does the job on macOS but the server side implementation is up to each developer. On Windows it's not a great solution to the point that `electron-builder`, the most important project for packaging an Electron app is moving away to NSIS.

If CodePush implemented the whole solution from server to client like it did with Cordova, I and many others would gladly pay for it to move away from Squirrel.

**Comment by dovy** [comment]
+1

**Comment by jephtta** [comment]
any updates on this?

**Comment by veharrison** [comment]
I'm using auto update feature and for some reason it is downloading 5 to 8 MB file, even for a minor change. 
I would really like to have code push. Is on the todo list.

**Comment by rrigoni** [comment]
this ticket would be really valuable! Hope it gets back on track again!

**Comment by tudiantuan** [comment]
+1

**Comment by tnanhpt** [comment]
+ 1

**Comment by timnlupo** [comment]
+1
