### ISSUE TITLE
code-push-cli 1.9.0-beta breaks with "[Error]  Not Found"

### ISSUE THREAD

**Issue by dkokic** [Microsoft/code-push#193]
After being forced to upgrade code push CLI from 1.6.0-beta we are not able to manage our existing apps. We used special characters in the code-push apps' names so I suspect that might cause the trouble.
Anybody else hitting the same problem? Any solutions/workarounds?

**Comment by dtivel** [comment]
Hi, dkokic.

Can you tell me the special characters you used?

**Comment by dkokic** [comment]
wow ... this is quick response ... congrats ;-)

I used the following special characters: '(', ')' and '+'

**Comment by dtivel** [comment]
Thanks for the info.  Let me take a look.

**Comment by lostintangent** [comment]
I can repro the issue when adding a "+" to an app name. Parens seem to work fine, so I suspect the plus sign is the culprit here. Interestingly enough, after adding an app with a plus sign in the name, the "app ls" command always returns "[Error] Not Found", but all other commands work fine as long as you're not targeting the app name with the plus sign in it.

**Comment by dkokic** [comment]
exactly my problem ... any workarounds how to rename the apps? ... pity we have a customer presentation tomorrow :/

**Comment by lostintangent** [comment]
We can definitely rename the app for you to unblock you in the meantime while we investigate a longer term fix. Would you be cool with us simply replacing the plus sign with something? I just confirmed that the plus sign doesn't impact the creation or management of the app at all, but anything that tries to query it fails, so it we just replace the plus sign wjth something, everything works perfectly.

If you want to let us know your app name and what we can rename it to, we can take care of this ASAP. You can either mention it here or email me at joncart@microsoft.com.

**Comment by dkokic** [comment]
Thanks for your quick help. I just emailed you with my account details.

**Comment by lostintangent** [comment]
Absolutely! Apologies for the inconvenience here. We had actually looked through existing app name patterns to make sure we tested the entire CLI as part of the new release, but we seemingly missed the plus sign.

**Comment by lostintangent** [comment]
@dtivel Clearly something doesn't like the plus sign :) Should the CLI or server be rejecting this character or are we not properly encoding it somewhere?

**Comment by dtivel** [comment]
I believe it's a bug that plus signs are allowed in names.  I've created a task for fixing this on the server.

@dkokic, if you have any other entities (apps, deployments, etc.) which have a plus sign in them, please let me know; we can help rename them.  I'm sorry for the inconvenience.

Are you blocked for your presentation tomorrow?  Please let me know, and I can help unblock you.

**Comment by dkokic** [comment]
Thanks @dtivel ... it's already being handled by @lostintangent ;-)

**Comment by silhouettes** [comment]
Hey @dkokic, hope your presentation went well! Just so you know, we've deployed a fix on the server, and `+` characters should now be accepted in app and deployment names.

We've also re-validated all of the other special characters (including international characters). For future reference, only the following special characters are disallowed (and we enforce them on app creation):
`/`, `\`, `?`, `:`, control characters (unicode 0x00-0x1F and 0x7F-0x9F)

Sorry about the trouble, and please let us know if you run into any other issues!
