### ISSUE TITLE
update failed with image

### ISSUE THREAD

**Issue by aofeng2009** [Microsoft/code-push#195]
When i push an image why update failed? 
when i developing RN project on ios ,I use this "react-native bundle --parameter ios --entry-file index.ios.js --bundle-output ./bundles/xxxx.js --assets-dest ./bundles"
I see that the latest package has been downloaded,but restart app without any effect.

**Comment by lostintangent** [comment]
@aofeng2009 Are you naming your generated JS bundle "main.jsbundle"? Unless you customized the name you want CodePush to look for in Objective C (by using [CodePush bundleURLForResource]), then it will expect to find a file with that exact name in the update, and fail otherwise.

If you change your "--bundle-output" value to "./bundles/main.jsbundle", it should work for you. However, I would recommend using the release-react command in our CLI, as it simplifies a lot of this process and will name your JS bundle correctly (among other things).

**Comment by aofeng2009** [comment]
@lostintangent Thanks，I have met another problem that when i change the js file 'first' label  below
"<Image source={require('./ios/xxx.png')} style={styles.thumbnail}/>
          <Text>first</Text>
          <Text>secondText>
", I used the "react-native bundle --parameter ios --entry-file index.ios.js --bundle-output ./bundles/main.jsbundle --assets-dest ./bundles" ,without any effect,but when i change "xxxx.png" to another image it make  success. Any idea?

**Comment by lostintangent** [comment]
@aofeng2009 Could you clarify the issue you had in your second example? Did the update not work until you renamed your image path?

**Comment by aofeng2009** [comment]
Sorry. Maybe my question is not clear.
My steps:
1. In my index.ios.js i only change the 'first' label to "test"
2.Use the command ""react-native bundle --parameter ios --entry-file index.ios.js --bundle-output ./bundles/main.jsbundle --assets-dest ./bundles"  then "code-push release appName ./bundles 1.0.0"
without any effect.

**Comment by lostintangent** [comment]
@aofeng2009 Hmm that is strange. It's possible that the React Native packager could be caching the JS file and not updating it when you generate the new bundle. Could you try running "code-push release-react appName ios" instead to see if that works? That will handle generating the bundle and releasing it to CodePush, but will also ensure the packager cache is cleared before doing so.

**Comment by aofeng2009** [comment]
@lostintangent 
Follow your steps,when i run "code-push deployment ls listView", I found the package has been updated.
<img width="497" alt="2016-04-05 4 58 51" src="https://cloud.githubusercontent.com/assets/15798819/14276225/15040e50-fb50-11e5-9d2e-5e3bbab924f2.png"> 
but also without effect.

**Comment by lostintangent** [comment]
The fact that the "Install Metrics" column shows 1 pending install means that the client installed the update, but it hasn't been run yet. Have you killed and restarted the app and it still says pending? Also, can you confirm that your AppDelegate.m file is configured to use CodePush to load the JS bundle file? If not, then when you're app starts, the update would never be run.

**Comment by aofeng2009** [comment]
@lostintangent 
Strangely，maybe network is not connected or other reason.Finally it run successful! thank you.

**Comment by lostintangent** [comment]
@aofeng2009 I'm glad to hear it worked! Let us know if you run into any other issues.
