### ISSUE TITLE
App version vs target version

### ISSUE THREAD

**Issue by poshaughnessy** [Microsoft/code-push#196]
Hi. Thanks for CodePush! We did find one thing quite confusing though. On the homepage, the `code-push release` command is shown as follows:

```
code-push release <appName> <package> <appStoreVersion>
```

We took `appStoreVersion` to mean the new version, i.e. the version we are deploying with this release. It was only after reading the CLI help and other docs, that we realised this should be the *target* version (`<targetBinaryVersion>`), i.e. the versions we want to update.

Please could the homepage be updated so it is more in line with the [CLI docs](https://microsoft.github.io/code-push/docs/cli.html)?

```
code-push release <appName> <updateContents> <targetBinaryVersion> ...
```

**Comment by lostintangent** [comment]
Good catch! We definitely need to update the home to reflect the CLI docs, since we changed the parameter name to "targetBinaryVersion" precisely to try to help out with this confusion. I'll update that this morning.

**Comment by dtivel** [comment]
@poshaughnessy, I've updated the [home page](http://microsoft.github.io/code-push/) with your suggestion.  Thank you for the feedback.  Keep it coming!
