### ISSUE TITLE
Strange partial release issue

### ISSUE THREAD

**Issue by poshaughnessy** [Microsoft/code-push#197]
Apologies in advance that this is going to be a bit vague, but I thought I should post it anyway...

Back when we were [confused about the app version ](https://github.com/Microsoft/code-push/issues/196), we made a release of our new app version 1.3.1, setting the *target* version (by mistake) to 1.3.1.

Strangely, my version 1.3.0 of the app (downloaded via HockeyApp, so unfortunately I couldn't debug locally) _did_ still update to this 1.3.1 - but only partially! I saw one of our code changes come through, but not another. Even more strangely, both changes should have been within the same bundle.js JavaScript file. So I can't think why/how it could have only resulted in us seeing one, but not the other.

Afterwards, we released 1.3.2, setting the target version to 1.3.1, and we saw that come through fine (both changes).

Could there perhaps be a strange bug to do with setting an invalid target version...?

If this is not very helpful, I'd be happy to re-test again later, this time with a local development version of the app, and try to provide some more details!

**Comment by lostintangent** [comment]
@poshaughnessy Anytime you hit an issue, it's super helpful to let us know, so thanks so much. That said, I can't immediately think how this could have happened :) We definitely don't apply partial updates of the JS bundle (I wish our product was that smart!), so I can't explain how you would see some changes but not another, unless some of the changes didn't actually get bundled into the JS bundle file (e.g. a file wasn't saved, the packager's cache erroneously skipped a file).

Additionally, the versions that you mentioned you were releasing as are all valid, and don't represent "ranges" (e.g. setting a target binary version of "1.3.*" would match both "1.3.1" and "1.3.2"), so you shouldn't be seeing it be downloaded unless the version matches exactly.

We'll do some investigations on our end to see if this could be happening somehow, but if you do get a chance to try it again locally, that would be very helpful. Thanks again and stay tuned!

**Comment by dtivel** [comment]
@poshaughnessy, I wasn't able to reproduce this behavior myself.  Via HockeyApp I installed an app running version 1.3.0.  I then published an update via CodePush for version 1.3.1.  The app did not see the update, as expected.

As @lostintangent mentioned, CodePush doesn't (intentionally) apply partial updates, and as long as the version you specified when you released the update wasn't a range that included your app's binary version, I cannot see why you would be getting a partial update.

Can you still reproduce this behavior?  If yes, could you please send detailed repro steps?

**Comment by lostintangent** [comment]
@poshaughnessy We haven't been able to repro this issue unfortunately :( I'm going to close it for now, but if you experience this again, and could let us know more details about the repro steps/scenario, please re-open it, as we would love to address it ASAP. Thanks!
