### ISSUE TITLE
ios react native switch bundle problem

### ISSUE THREAD

**Issue by madcat** [Microsoft/code-push#202]
CodePush.setDeploymentKey("firstkey")
    jsCodeLocation = CodePush.bundleURLForResource("FirstApp")

first bundle loaded ok, and in FirstApp syncing is working fine as well.
when trying to e.g. click a button and load a second bundle as:

    CodePush.setDeploymentKey("secondkey")
    jsCodeLocation = CodePush.bundleURLForResource("SecondApp")

location is still pointing to the first one. how could I implement something like this?

**Comment by lostintangent** [comment]
@madcat Could you explain a little bit about what you're trying to achieve? When you say that you're trying to load a second bundle, do youj mean that you have a single iOS app that has multiple separate React Native views, and you want to update them with CodePush?

**Comment by madcat** [comment]
yes, a single iOS app that load the first React Native view, within which, when user clicks a button, calling native code to load the other React Native view.

usage like this is when the first view is the app itself, where the second view is different per user.

**Comment by lostintangent** [comment]
@madcat Unfortunately our plugin doesn't currently support hosting multiple separate React Native apps within the same process, which is why you're experiencing this issue.

**Comment by madcat** [comment]
thx! I will try to move the separation into the build process and pack into one bundle for each user.
