### ISSUE TITLE
New Website Logo: Simple Contacts

### ISSUE THREAD

**Issue by rquigley** [Microsoft/code-push#204]
Thanks! Love CodePush!

Please fill the following out:

- Name: Simple Contacts
- Homepage url: https://www.simplecontacts.com/
- Brand Guidelines/Licensing: none
- Logo: https://www.simplecontacts.com/static/img/app_icon.png

> Example:
>
> Name: Microsoft
> Homepage url: https://microsoft.com
> Brand Guidelines/Licensing: https://www.microsoft.com/en-us/legal/intellectualproperty/trademarks/usage/logo.aspx
> Logo: https://news.microsoft.com/microsoft-news-center-photos/msft_logo_rgb_c-gray/

**Comment by rub8n** [comment]
Hi @rquigley! Interesting concept! Hopefully you'll bring it to Washington soon. :)

We'll add this to the showcase soon. Thanks for using CodePush!

**Comment by rub8n** [comment]
Hi @rquigley!

The logo should be part of the showcase now.


Thanks for your support!
