### ISSUE TITLE
[release-react]  Deployment "Staging," does not exist.

### ISSUE THREAD

**Issue by udfalkso** [Microsoft/code-push#206]
*Command:*
```
code-push release-react MyApp android -d "Staging" -des "some update"
```

*Result:*
```
Running "react-native bundle" command:

node node_modules/react-native/local-cli/cli.js bundle --assets-dest /var/folders/j8/0051f_yn62g5gvd5l2xz04lw0000gn/T/CodePush --bundle-output /var/folders/j8/0051f_yn62g5gvd5l2xz04lw0000gn/T/CodePush/index.android.bundle --dev false --entry-file index.android.js --platform android --sourcemap-output some update
bundle: Created ReactPackager
bundle: start
bundle: finish
bundle: Writing bundle output to: /var/folders/j8/0051f_yn62g5gvd5l2xz04lw0000gn/T/CodePush/index.android.bundle
bundle: Writing sourcemap output to: some update
bundle: Closing client
bundle: Copying 11 asset files
bundle: Done writing bundle output
bundle: Done writing sourcemap output
bundle: Done copying assets

Releasing update contents to CodePush:

Upload progress:[==================================================] 100% 0.0s
[Error]  Deployment "Staging," does not exist.

```

This doesn't seem to work.  I'm on 1.10.0-beta.  I also tried without the quotes around Staging, same result.

```
$ code-push -v
1.10.0-beta
```

Thanks!

**Comment by geof90** [comment]
Hi @udfalkso, it appears there is an extra comma after "Staging,". Is that intentional? Also, to let us help you better, could u show us the exact command u ran and the matching output? The snippets u pasted doesnt seem to match (e.g. ommand doesnt include the option to generate sourcemaps but the output clearly shows it is trying to do so)

**Comment by udfalkso** [comment]
As you can see above (first line is the command I ran), I didn't put the comma there in my command.  Something else is adding it along the way.

The source map is also being added automatically, sorry for the mixup.  I was sanitizing my description a bit when copying the results here and forgot to change that part.  I've updated my note above with the exact command I ran and the output, but it's essentially the same.  

I'm on OSX.  Thanks

**Comment by geof90** [comment]
If you changed "-des" to "--des", does the problem still exist?

**Comment by udfalkso** [comment]
That fixed it, thanks!  My bad.  I suppose an "invalid parameter" error may have helped.

**Comment by geof90** [comment]
@udfalkso Completely agree. We will fix that. Glad you are unblocked!

**Comment by sanshanchuns** [comment]
appcenter version 1.1.11

Command 'codepush release -c ./ios/bundle/platform.ios.bundle -k keys/codepush_private.pem -t 5.3.0 -m true -a codepush-clubfactory.com/ClubFactory-iOS-Platform -d Staging' failed with exception "Deployment "Staging" does not exist."

**Comment by tiagonevestia** [comment]
@sanshanchuns  run command **_appcenter codepush deployment add Staging_**
