### ISSUE TITLE
Support for Info.plist files with different names

### ISSUE THREAD

**Issue by dudeinthemirror** [Microsoft/code-push#207]
In my project, I have:
```
MyApp.PROD-Info.plist
MyApp.DEV-Info.plist
MyApp.STAGING-Info.plist
```
corresponding to the 3 targets: MyApp.PROD, MyApp.DEV and MyApp.STAGING
I can't find a way to pass the plist file name when running `code-push react-native`
So, I am getting:
```
[Error]  Unable to find or read "Info.plist" in the "iOS/MyApp" or "iOS" folders.
```
The command I am running is:
```
/usr/local/bin/code-push release-react MyApp-iOS iOS \
--deploymentName STAGING \
--description "some description" \
--entryFile index.ios.js \
--mandatory
```
Thanks

**Comment by lostintangent** [comment]
@dudeinthemirror This is great feedback! We can definitely discuss adding this to support this scenario. In the meantime, the workaround is to specify the "--targetBinaryVersion" flag with the version from the respective plist file (e.g. "1.2.3"). The only reason that the release-react command tries to load the info.plist file is to infer the app version, so if you specify it explicitly, it won't even attempt to read the file and you won't get this error.

**Comment by dudeinthemirror** [comment]
Thanks for the quick turnaround @lostintangent !
So actually that is one thing I like about _not_ specifying the --targetBinaryVersion i.e the fact that it just takes it from the app :)

So what I ended up doing is I added a step in the build script that does this:
```
step="Hack: creating Info.plist as a copy of ${TARGET}-Info.plist"
echo "-----------------------------------------------------------------------------------------------"
echo "STEP: $step"
echo "-----------------------------------------------------------------------------------------------"
# This is a hack until I get an answer to :
# https://github.com/Microsoft/code-push/issues/207
PLIST_FILE=$(find . -name ${TARGET}-Info.plist -print 2>/dev/null)
[[ ! -z "$PLIST_FILE" ]] && cp $PLIST_FILE ./ios/Info.plist
```
Hope it will help others who encounter this error !

I strongly suggest you guys consider adding plist-file-name as an option. Xcode allows you to rename your Info.plist as needed, so in most large projects that will be the norm.
Thank you for a great tool!

**Comment by lostintangent** [comment]
That workaround would do as well :) I definitely agree that we should add this option, I just wanted to make sure you could get unblocked in the meantime. I'll use this issue to track this enhancement, since like you mentioned, this will definitely be a common need that I'd like to address ASAP.

**Comment by lostintangent** [comment]
@dudeinthemirror I just merged a PR that adds a new `--plistFilePrefix` parameter (aliased as `--pre`) to the `release-react` command. I believe this would allow releasing from your custom project structure, without needing to resort to explicitly setting the `--targetBinaryVersion` parameter. Let me know what you think! I'm going to close this for now based on this solution, but I would love any feedback you may have.

```shell
code-push release-react MyApp ios --pre "MyApp.STAGING-"
```

Additionally, we also added a new `--plistFile` parameter for scenarios where the location (or name) of the plist file is entirely arbitrary, and CodePush can't infer it on its own.

**Comment by dudeinthemirror** [comment]
Excellent ! That's exactly it. Thanks much for adding this.

**Comment by lostintangent** [comment]
@dudeinthemirror This feature has been released to NPM. You should be able to do the following once you upgrade:

```shell
code-push release-react MyApp ios --pre "MyApp.STAGING"
```

*Note that the trailing hyphen is optional, since we'll add it if it isn't specified.*
