### ISSUE TITLE
New Website Logo: TrackSat

### ISSUE THREAD

**Issue by joshuaferrara** [Microsoft/code-push#209]
Please fill the following out:

- Name: TrackSat
- Homepage (or app store) url: https://itunes.apple.com/us/app/tracksat/id1000281269?mt=8
- Brand Guidelines/Licensing: N/A
- Logo: https://cloud.githubusercontent.com/assets/248680/14614794/868e4912-0557-11e6-8677-09828c7fbcf6.png

Was directed here by email. Thank you!

> Example:
>
> Name: Microsoft
> Homepage url: https://microsoft.com
> Brand Guidelines/Licensing: https://www.microsoft.com/en-us/legal/intellectualproperty/trademarks/usage/logo.aspx
> Logo: https://news.microsoft.com/microsoft-news-center-photos/msft_logo_rgb_c-gray/

**Comment by silhouettes** [comment]
Hi @joshuaferrara, cool app! We'll work on adding your app to the 'Friends of CodePush' page :)

**Comment by rub8n** [comment]
Hi @joshuaferrara! Thanks again for reaching out. The change is now live!
