### ISSUE TITLE
New Website Logo: Kiwiship

### ISSUE THREAD

**Issue by allanjsx** [Microsoft/code-push#212]
- Name: Kiwiship
- Homepage (or app store) url: https://www.kiwiship.com
- Brand Guidelines/Licensing: N/A
- Logo: https://www.kiwiship.com/img/kiwi_logo.png

Thanks!

**Comment by lostintangent** [comment]
@allanjsx The app looks great! Thanks for using CodePush and letting us know. We'll add Kiwiship to the showcase first thing tomorrow :)

**Comment by rub8n** [comment]
Thanks for reaching out @allanjsx. Kiwiship is now part of the showcase!
