### ISSUE TITLE
WE must GZip the uploaded jS bunde

### ISSUE THREAD

**Issue by prateekbh** [Microsoft/code-push#213]
GZippping the uploaded jS bundle should be a must 
While releasing an update, downloading 200-300 kb vs 1-1.5 mb is a huge huge perf gain.
In areas of flacky or slow networks or even countries like  this would boosy the perf a lot

**Comment by lostintangent** [comment]
@prateekbh Are you using the release-react command in the CLI? That should be zipping up your JS bundle, so that your users will receive the zip instead of the loose JS bundle file.

**Comment by lostintangent** [comment]
@prateekbh Are you able to use the `release-react` command, which would zip up the contents automatically for you?

**Comment by prateekbh** [comment]
@lostintangent  yeah checked it.. did the required magic :)

**Comment by lostintangent** [comment]
OK cool :) I'm going to close this then since release-react is our primary recommendation now, and that should always result in content being zipped. Please re-open this if I missed anything or we should be considering further improvements. Thanks again for reporting it!
