### ISSUE TITLE
Add collaborator failing

### ISSUE THREAD

**Issue by kipricker** [Microsoft/code-push#214]
Using `code-push collaborator add <appName> <email>` as the "Owner" I am getting the following
```
[Error]  The specified resource does not exist.
RequestId:4b5582e9-0002-0105-0a62-9fa337000000
Time:2016-04-26T02:20:43.3726036Z
```

**Comment by lostintangent** [comment]
@kipricker Does the email address you're attempting to add as a collaborator represent an account that has already registered with CodePush? That error message is really poor, but it should only be happening if you're attempting to add a non-registered collaborator. If you have the person register an account with CodePush, you could then re-run this. Sorry for the issue!

**Comment by kipricker** [comment]
Oh, jeeze, thats the problem. I was thinking 'invite'. Thanks for the quick response!

**Comment by lostintangent** [comment]
@kipricker That's a completely reasonable thing to have thought :) We're going to improve this error message to better reflect what we say in our docs. Thanks so much for the feedback!
