### ISSUE TITLE
Possibility to set the memory limit

### ISSUE THREAD

**Issue by rik-smit** [Microsoft/code-push#215]
For our current React Native project the default node memory limit of 1,76GB is not enough to create a new release. 

When I execute `code-push release-react AppName android` I get the following error:
`FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory`

I have fixed it by updating the `runReactNativeBundleCommand` function. I add `"--max_old_space_size=4096"` to the `reactNativeBundleArgs` array first, so that the final command is 
`node --max_old_space_size=4096 node_modules/react-native/local-cli/cli.js bundle --assets-dest /tmp/CodePush --bundle-output /tmp/CodePush/index.android.bundle --dev false --entry-file index.android.js --platform android`

Is it possible to add an optional parameter to the release-react function, to be able to overwrite the memory limit?

**Comment by lostintangent** [comment]
@rik-smit Ah yeah, this makes sense to address in one way or another. Out of curiosity, how big is your app? We haven't seen this issue before, and we've definitely had users with big apps.

**Comment by rik-smit** [comment]
The whole folder is 889MB, and the biggest part of that are the node_modules (558MB). I did suspect that 1.76 GB would be enough then, but when I check the System Monitor I see that the memory usage of the Node process reaches 2,5GB

**Comment by lostintangent** [comment]
@rik-smit I'm going to close this for now since we haven't had any other reports of this issue, and I'd prefer to only add parameters to our CLI that are broadly applicable. Please feel free to re-open it if you think we should re-consider, but in the meantime, since you were able to unblock yourself, it seems potentially like an edge case that we can re-evaluate if it becomes a common issue. Thanks again!

**Comment by zk** [comment]
I've just run into this as well, how about an env var? I'm happy to patch if you all are open to it.

**Comment by silhouettes** [comment]
@zk if you're willing to submit a PR, and it is solid, we're happy to take it :)

**Comment by zk** [comment]
@silhouettes Great, I'll take a look. Thanks!
