### ISSUE TITLE
New Website Logo: Dutch home rentals

### ISSUE THREAD

**Issue by justim** [Microsoft/code-push#218]
- Name: Dutch home rentals
- App Store url: https://itunes.apple.com/us/app/dutch-home-rentals/id540376128
- Brand Guidelines/Licensing: n/a
- Logo: [app-logo_1024x1024](https://cloud.githubusercontent.com/assets/757292/14951280/2b08318c-1058-11e6-9e6f-8a0a865fcdab.png)

**Comment by rub8n** [comment]
Hi @justim! Thanks for using CodePush and letting us know. 

We'll add the app to the showcase in a few hours. :)

**Comment by rub8n** [comment]
Closing as the update should be live now. Let me know otherwise.

Thanks again!

**Comment by justim** [comment]
It's there, thanks!
