### ISSUE TITLE
Releasing new version when the versionName is dynamic

### ISSUE THREAD

**Issue by igalarzab** [Microsoft/code-push#229]
Hello,

I have some problems using code-push in react-native/Android when the versionName var is dynamic (and not an static string). You can reproduce the error with the following ``build.gradle`` file:

```groovy
def versionMajor = 1
def versionMinor = 2

defaultConfig {
    applicationId "com.mypackage"
    minSdkVersion Integer.parseInt(project.ANDROID_MIN_SDK_VERSION)
    targetSdkVersion Integer.parseInt(project.ANDROID_TARGET_SDK_VERSION)
    versionCode versionMajor * 100 + versionMinor
    versionName "${versionMajor}.${versionMinor}"
    ndk {
        abiFilters "armeabi-v7a", "x86"
    }
}
```

And this is the value of the ``buildGradle.android.defaultConfig`` dict when executing code-push (in the [following lines](https://github.com/Microsoft/code-push/blob/4a899e2a72b4490557738411487a9d58de816ac6/cli/script/command-executor.ts#L864))

```javascript
{
	applicationId: 'com.mypackage',
	minSdkVersion: 'Integer.parseInt(project.ANDROID_MIN_SDK_VERSION)',
	targetSdkVersion: 'Integer.parseInt(project.ANDROID_TARGET_SDK_VERSION)',
	versionCode: 'versionMajor * 100 + versionMinor',
	versionName: {},
	'': {},
	'"$.$"': '',
	ndk: {
		abiFilters: '"armeabi-v7a", "x86"'
	}
}
```

That raises the following error when trying to release a new version:

```
[Error]  buildGradle.android.defaultConfig.versionName.replace is not a function
```

Any way to fix this issue? Maybe providing a way to specify the version in a manual way using the CLI?

Thanks!

**Comment by dtivel** [comment]
I'm taking a look at this now.

**Comment by igalarzab** [comment]
Hi dtivel,

Thanks for the quick response!

I'm checking the code and I see that providing a ``--targetBinaryVersion`` causes code-push to ignore the ``build.gradle`` file, allowing me to release new versions.

I don't know how feasible is to start interpreting the gradle code to extract the real ``versionName``, so maybe fixing the [assumption of receiving a string](https://github.com/Microsoft/code-push/blob/4a899e2a72b4490557738411487a9d58de816ac6/cli/script/command-executor.ts#L865) (to avoid the crash) and giving a hint of the ``--targetBinaryVersion`` parameter existence is enough to fix the issue.

What do you think?

**Comment by dtivel** [comment]
I reproduced your issue.

Yep, you are right.  Using the `--targetBinaryVersion` allows you to specify the app version yourself, thereby bypassing the build.gradle parsing code.  I'll send out a pull request to improve the error handling in the CodePush CLI.

**Comment by igalarzab** [comment]
Cool, thanks!

**Comment by joshuapinter** [comment]
Any update to how difficult it would be to use the calculated string instead of having to explicitly set the `--targetBinaryVersion`? 

I've got a similar thing where I'm doing this: 

```gradle
def versionMajor = 6
def versionMinor = 4
def versionPatch = 3

versionCode versionMajor * 10000 + versionMinor * 100 + versionPatch
versionName "${versionMajor}.${versionMinor}.${versionPatch}"
```

**Comment by sergey-akhalkov** [comment]
Hi @joshuapinter, this feature looks difficult and I'm afraid if it even not possible to implement it, please let me explain why and let me know if I'm wrong - one or all of the variables in the `"${versionMajor}.${versionMinor}.${versionPatch}"` string can represent some calculations that developer implemented to compute the values of those variables, so without execution of gradle script we cannot be sure what the final value of those variables in the versionName string. 

The only way to release a CodePush update is to specify `--targetBinaryVersion` parameter as described above. 

Please let me know if you have any questions or see any issues.

**Comment by joshuapinter** [comment]
@sergey-akhalkov It's simpler than that but I imagine you would still need to execute gradle to get the final values. we literally just use `def` to make it easier to set the correct version and ensure that the `versionCode` represents it correctly.

No worries, for now we'll just use `--targetBinaryVersion`.
