### ISSUE TITLE
"An update is available but it is targeting a newer binary version..."

### ISSUE THREAD

**Issue by poshaughnessy** [Microsoft/code-push#231]
I have deployed an upgrade from version 1.5.0 to 1.5.1b. However, the v1.5.0 app logs say:

> [CodePush] An update is available, but it is targeting a newer binary version than you are currently running.
> [CodePush] App is up to date.

The code-push CLI lists the deployment:

> Label: v2
> No installs recorded
> App Version: 1.5.0
> Mandatory: Yes
> Release Time: 15 minutes ago
> Released By: [removed]
> Description: v1.5.1b   

Our sync code looks like this:

```
window.codePush.sync(null, {
      installMode: window.InstallMode.ON_NEXT_RESUME,
      mandatoryInstallMode: window.InstallMode.IMMEDIATE
    });
```

Thanks in advance if anyone can help me understand why the update wouldn't be getting applied?

p.s. This was using `code-push` version 1.8.0-beta and `cordova-plugin-code-push` v1.6.0-beta. I'm just going to try updating to `cordova-plugin-code-push` 1.7.1-beta...

**Comment by dtivel** [comment]
Is update v2 the latest update for the deployment?
Is the binary version of your app 1.5.0?

**Comment by poshaughnessy** [comment]
Hi. Yes v2 is the latest and 1.5.0 should be the binary version (Cordova applies the given version number to both the "Version" and "Build"). 

It worked after I upgraded to `cordova-plugin-code-push` v1.7.1-beta!:

> [CodePush] Checking for update.
> [CodePush] An update is available. {"appVersion":"1.5.0","deploymentKey":"[removed]","isMandatory":true,"label":"v2","packageHash":"[removed]","packageSize":2654833,"failedInstall":false}
> [CodePush] Downloading update
> ...
> [CodePush] First update: back up package information skipped.
> [CodePush] Install succeeded.

Only problem this time it didn't actually update until I put the app in the background and then resumed it. Shouldn't `mandatory` with `window.InstallMode.IMMEDIATE` mean it update immediately?

**Comment by dtivel** [comment]
Good news that upgrading to v1.7.1-beta resolved the update not being installed.

A mandatory update with the IMMEDIATE option should restart the app once the update is installed.  I'll investigate and get back to you.

**Comment by lostintangent** [comment]
@poshaughnessy Interestingly enough, we removed the `[CodePush] First update: back up package information skipped.` log message in `v1.7.1-beta`, so it's odd that you're seeing that in your console output.

**Comment by poshaughnessy** [comment]
Oh yeah, good spot! Sorry for the confusion, that must be because I did an `npm install` but I didn't do a clean Cordova build, so the actual plugin deployed to the phone wasn't updated.

Just tried again with a clean build (so should really be v1.7.1-beta this time) and this time it worked and updated immediately, once it had downloaded. So think we're all good. Thanks!

**Comment by lostintangent** [comment]
@poshaughnessy Awesome! Glad that fixed it for you :) Let us know if you run into any other problems.

**Comment by cxy200927099** [comment]
hi @lostintangent ： 
   I also have the same problem, but i do not use cordova-plugin-code-push; how can i fix this problem?
my code-push version is 1.12.6-beta, do i need update? how can i update code-push if need because i could not find any command just like 'code-push update'
thanks!

**Comment by sergey-akhalkov** [comment]
@cxy200927099, you are using the latest version of code-push, if you want to update it, you could run `npm install -g code-push-cli@latest` command.
>I also have the same problem, but i do not use cordova-plugin-code-push; how can i fix this problem?

Could you please create new issue and provide us with more details (current binary version of your app, deployment history - `code-push deployment history <appName> <deploymentName>`, version of `react-native-code-push`, repro steps)?

**Comment by cxy200927099** [comment]
@sergey-akhalkov,I'm sorry, reply late，i will do a new reply after test it
