### ISSUE TITLE
Is there any possible to keep login status for more than 1 account

### ISSUE THREAD

**Issue by xhacker5000** [Microsoft/code-push#232]
My company other project need transfer to my laptop , but my laptop is login my code-push account , if I need release that project , I need login the other account ,is there anyway to keep login status for both of them ?

**Comment by geof90** [comment]
Have you tried the [collaborators feature](https://github.com/Microsoft/code-push/tree/master/cli#app-collaboration)? You might want to add an account as a collaborator to both projects, that way you can publish releases to both apps using a single account.

**Comment by xhacker5000** [comment]
my friend has been use code-push transfer project to my account , but I still not see that ,why?

**Comment by geof90** [comment]
Really? Could you check that he added the exact same email that you are you using with your account? If it still doesn't work, let us know your email and we can check it for you.

**Comment by lostintangent** [comment]
@xhacker5000 Could you confirm that your friend transferred the app to the right account? Did you ever get this working? I'd like for us to investigate this ASAP otherwise, so if could update us on where things stand so here, we can try to make sure you're unblocked. Sorry for the inconvenience!

**Comment by lostintangent** [comment]
We aren't able to repro this issue, so I'm going to close it for now. Please re-open this if you're continuing to experience problems with the `code-push transfer` command, and we'll investigate it ASAP. Thanks!
