### ISSUE TITLE
[Error]  Internal Server Error

### ISSUE THREAD

**Issue by LeBlaaanc** [Microsoft/code-push#235]
I often get an internal server error when running various code-push cli commands, in this instance it was the `code-push login --accessKey`.

This sucks hard because it makes my CI builds fail :(

**Comment by LeBlaaanc** [comment]
Completely my bad, double check you don't have a malformed --accessKey.

**Comment by geof90** [comment]
Thanks for reporting @LeBlaaanc. It is definitely strange that it is saying Internal Server Error instead of just Invalid Access Key (which is what its supposed to say). I will take a look at it. By any chance, do you know if the access key you are sending has any particularly special characters?

**Comment by LeBlaaanc** [comment]
@geof90 I sent in a url of sorts (super awkward).

**Comment by geof90** [comment]
@LeBlaaanc Interesting to note. Thanks!
