### ISSUE TITLE
New Website Logo: ticketea

### ISSUE THREAD

**Issue by patoroco** [Microsoft/code-push#237]
Hi! There is our brand new app using RN + code-push! 💃 

- Name: ticketea
- Homepage url: https://www.ticketea.com
- AppStore: https://itunes.apple.com/es/app/entradas-teatro-y-conciertos/id1060067658?mt=8
- PlayStore: https://play.google.com/store/apps/details?id=com.ticketea.geminis 
- Brand Guidelines/Licensing: N/A
- Logo: http://f.cl.ly/items/0n3g3x2t0W0a0d0b1F0C/tkt-icon.png

**Comment by lostintangent** [comment]
Awesome! Thanks so much for using CodePush :) We'll get this up on the showcase this afternoon.

**Comment by rub8n** [comment]
Should be live now! Thanks!
