### ISSUE TITLE
New Website Logo: Fixt

### ISSUE THREAD

**Issue by esauter5** [Microsoft/code-push#238]
- Name: Fixt
- Homepage (or app store) url: https://www.fixt.co
- Brand Guidelines/Licensing: N/A
- Logo: http://a5.mzstatic.com/us/r30/Purple60/v4/04/0a/cd/040acdc0-11b3-5757-716d-b658d4bfca07/icon175x175.jpeg

**Comment by rub8n** [comment]
Thanks for reaching out @esauter5! We'll be adding Fixt to the showcase today. :)

**Comment by esauter5** [comment]
Great to hear, @rub8n. Thanks for the great work you all do :)

**Comment by rub8n** [comment]
Should be live now! Thanks for the kind words and your support!
