### ISSUE TITLE
New Website Logo: MovieLaLa Trailers

### ISSUE THREAD

**Issue by sahin** [Microsoft/code-push#240]
Please fill the following out:

- Name: MovieLaLa Trailers
- Homepage (or app store) url: https://movielala.com
- Brand Guidelines/Licensing: None
- Logo: http://a5.mzstatic.com/us/r30/Purple49/v4/dc/05/a9/dc05a9e5-04ef-6bff-eb86-bd057606eb3a/icon175x175.png

> Example:
>
> Name: Microsoft
> Homepage url: https://microsoft.com
> Brand Guidelines/Licensing: https://www.microsoft.com/en-us/legal/intellectualproperty/trademarks/usage/logo.aspx
> Logo: https://news.microsoft.com/microsoft-news-center-photos/msft_logo_rgb_c-gray/

**Comment by rub8n** [comment]
Hi @sahin! We'll be updating the showcase with MovieLaLa later today. Thanks for reaching out!

**Comment by sahin** [comment]
thx.

**Comment by rub8n** [comment]
Should be live now! Thanks!
