### ISSUE TITLE
Is Code-Push support rollback all android and ios?

### ISSUE THREAD

**Issue by tutumagi** [Microsoft/code-push#244]
I use react-native. when I run `code-push rollback App Production`,  are android app and ios app all rollback the latest version?

**Comment by lostintangent** [comment]
Running the rollback command on a specific app deployment would roll back all clients that were configured to query that deployment for updates. We recommend creating a seperate CodePush app for each platform (iOS and Android), and so if you went with that recommendation, then rolling back one of those app's deployments would only impact your iOS or Androis users. If you wanted to rollback everyone, then you'd need to rollback both app deployments.

If, however, you're deploying iOS and Android updates to the same CodePush app (we do not recommend doing this!), then performing a rollback on that single app's production deployment would roll back everyone.

**Comment by silhouettes** [comment]
@tutumagi, did that answer your question? I'm closing this issue for now, but feel free to re-open it if you need anything else.

**Comment by tutumagi** [comment]
Thanks. I will try to use the solution what @lostintangent  said.
