### ISSUE TITLE
[Docs] Does code-push patch update the assets too?

### ISSUE THREAD

**Issue by pke** [Microsoft/code-push#251]
Its unclear from the docs how to fix/path a broken release. Is that what the `patch` command is intended for? I guess not, as it seems to only update metadata.

**Comment by lostintangent** [comment]
Apologies for the confusion. I just updated the [docs](https://github.com/Microsoft/code-push/blob/master/cli/README.md#patching-update-metadata) to clarify that the patch command is strictly for modifying release metadata, not the update contents (which is currently immutable). I also added a note about the use of the rollback command to address broken releases.

Let me know if you think we can make the docs clearer. Thanks for the feedback here, we're always keen to improve our docs.

**Comment by pke** [comment]
Thanks for updating the docs. There is one "w" too much in "wwww" though ;)

**Comment by lostintangent** [comment]
Doh! That is what happens when you edit markdown on your phone on the bus :) Just fixed it!

**Comment by pke** [comment]
and if you don't do PR for someone else to look over it ;)
