### ISSUE TITLE
Apps using geolocation display weird confirmation dialog after code-push version is applied

### ISSUE THREAD

**Issue by pke** [Microsoft/code-push#254]
An app that uses the cordova-geolocation plugin to fetch the users location displays this dialog after the app has been updated using code-push:

![image](https://cloud.githubusercontent.com/assets/164625/16024362/c3399132-31c1-11e6-87bf-2964fecb04e0.png)

Is that a known issue?

The dialog was just fine, when the app downloaded from the store.

**Comment by scottbommarito** [comment]
Hello @pke, I was not aware of this before. When code-push downloads an update, it puts it in a place in iOS's reserved harddrive space for each app which is slightly different than where the app itself is, so I can imagine that the cryptic message is related to iOS being confused by this special location when asking for a permission. [As explained in this stack-overflow post,](http://stackoverflow.com/questions/28891339/fix-cordova-geolocation-ask-for-location-message) you should be able to specify the exact message that you will get asked by adding `NSLocationWhenInUseUsageDescription` to your Info.plist and specifying a more user friendly message, like `[App Name] would like to access your location when running and displayed.` Let me know if that helps!

**Comment by pke** [comment]
Thanks for the feedback. Hmmm it's unfortunate the cordova plugin does not plug this message by default. Changes to the `info.plist` cannot be checked in and will be lost after any cordova engine update. So changing it there does not seem very safe to me.

**Comment by lostintangent** [comment]
This is an unbelievably goofy limitation of the Cordova geolocation plugin. I would recommend using the [cordova-custom-config](https://www.npmjs.com/package/cordova-custom-config) plugin, which enables you to make Info.plist mods from your config.xml. This way you can overwrite platform-specific behavior in a way that won't be blown away when your platforms directory gets deleted/created.

If you check out the readme of the aforementioned plugin, you can see that it provides an example specifically for setting this NSLocationWhenInUseUsageDescription key :)

I can update our docs to call throw out if you think it's a reasonable solution. We could investigate solving it somehow from our plugin, but I'm not sure if we can in a clean way.

**Comment by pke** [comment]
Thank you @lostintangent I'll try the aformentioned plugin.

> We could investigate solving it somehow from our plugin, but I'm not sure if we can in a clean way.
Lets better not start another "Microsoft fixes vendor bugs" that worked so "well" in Windows by putting all the hard work in Microsofts hands and letting the vendor get away with bugs and awkward API usage.
You could however mention this problem and its solution in the FAQ, I think.

**Comment by lostintangent** [comment]
OK cool :) I'll use this bug to track adding a mention to our docs about this then. Thanks again for providing this feedback.

**Comment by pke** [comment]
hmmm using the config plugin does not seem to solve the issue. So it must be something in the cordova geolocation plugin.

**Comment by lostintangent** [comment]
Ugh that sucks. I guess I'll wait to update the docs then if this isn't even a valid solution.

**Comment by lostintangent** [comment]
@pke Were you able to figure anything out here? We can help investigate this issue if needed as well, just let us know!

**Comment by pke** [comment]
I was using both geolocation.getCurrentPosition and watchPosition right after each other.
I guess this caused a race condition to display 2 dialogs sometimes and the second dialog did not get the correct string translations for some reason unknown to me.

Since I changed my code to only call geolocation.watchPosition the correct dialog is displayed (with my customized messages even).

So I'll close for now, its nothing you and your team can actually solve. I will open an issue with the Cordova plugin to let them check why this code caused such problems.

**Comment by lostintangent** [comment]
Sounds good. Did you still need to use the Cordova-custom-configured plugin to explicitly set a message?

**Comment by pke** [comment]
Yes I did. Its nice to give the user some additional information about why you want to access her location.
