### ISSUE TITLE
How to use codepush with a CI? 

### ISSUE THREAD

**Issue by kennethlynne** [Microsoft/code-push#255]
When anything is merged to master our CI is set up to deploy through codepush. Whenever we change anything in our documentation or similar that does not change the package, it will break the build with the following message from codepush:

`The uploaded package is identical to the contents of the specified deployment's current release.`

We've been using this workaround `code-push release-react APP ios --entryFile index.ios.js || true` (notice the `|| true`), but this silences ALL errors. Not optimal at all.

How can we ignore only that error or skip deploying when the packages have not changed?

**Comment by silhouettes** [comment]
@kennethlynne, @nevir, @jsierles, @r-bansal, @heat - Thanks for reporting this! We have added a `--noDuplicateReleaseError` flag that is available in v1.12.5-beta: https://github.com/Microsoft/code-push/releases/tag/v1.12.5-beta. Please let us know if you find this useful!
