### ISSUE TITLE
Thread warning on iOS iPhone 4s

### ISSUE THREAD

**Issue by pke** [Microsoft/code-push#256]
I am getting this warning in xcode when launching the code-push enabled app on an `iPhone 4s`

```
2016-06-14 14:55:23.894 evopark[1623:1434671] THREAD WARNING: ['CodePush'] took '1082.812988' ms. Plugin should use a background thread.
```

Why does it take so long to initialise? How to move it to a background thread?

**Comment by lostintangent** [comment]
That's a good question. We'll investigate this and see if we can optimize it. Are you noticing any perceivable perf impact, or are you simply seeing that message?

**Comment by pke** [comment]
well it adds to the overal app launch delay, and I aim to keep it as short as possible (with webpack codesplitting)

**Comment by lostintangent** [comment]
Totally understood. I want is to have a negligee impact on app performance, so we will investigate this. I'm just not familiar with how this warning measurement is captured, so I was curious if you could notice an issue (1s is a long time) or not

**Comment by xlc** [comment]
I am also seeing this on iPad Air 2
> THREAD WARNING: ['CodePush'] took '11.366943' ms. Plugin should use a background thread.

I think this is where the warning come from:
https://github.com/apache/cordova-ios/blob/f75bf67438257132e739238ed579d73271b3a716/CordovaLib/Classes/Public/CDVCommandQueue.m#L189

Cordova-ios will show the warning if the plugin took more than 10ms.

This is the guide from Cordova about threading: https://cordova.apache.org/docs/en/latest/guide/platforms/ios/plugin.html#threading

**Comment by lostintangent** [comment]
@xlc Those are really helpful pointers! Thanks a lot. It's interesting that the warning doesn't log the method name as well, which would make this a lot more actionable :)

We'll investigate into this, and it should be straight forward for us to use that threading guidance to move any expensive native calls off of the UI thread.

**Comment by lostintangent** [comment]
@pke @xlc I just sent out a PR that I believe addresses this issue. We make use of a few other Cordova plugins, that don't seem to run potentially costly operations on a background thread, so this PR doesn't necessarily fix everything, but it ensures that our native code is doing the right thing and will address the warnings you were seeing.

**Comment by lostintangent** [comment]
This fix was just merged, and we'll release it to NPM in our next release. It didn't sound like either of you were blocked by this, but if you are, let us know so we can accelerate the release to NPM. Thanks again for the feedback!

**Comment by pke** [comment]
Thanks. No need to hurry with the NPM release though.
