### ISSUE TITLE
Use Case: Dekstop apps.

### ISSUE THREAD

**Issue by joeblew99** [Microsoft/code-push#259]
I think others might have asked this, but anyway, it would be really great if you supported desktops also.

**Comment by lostintangent** [comment]
@joeblew99 We'd definitely be interested in expanding CodePush to the desktop :) Was there a specific app platform you would be interested in having support for? Electron? React Native Desktop? Something else?

**Comment by joeblew99** [comment]
Thanks for your support on this.

I am still doing due diligence on the container but it's very likely to be
electron.

In terms of OS, it's OSX, windows and Linux.

I also code all my non front end code in golang so it can run anywhere. I
guess you would be coding your plugin as a node module ?

**Comment by lostintangent** [comment]
Yep, if we were to create an Electron client, it would likely be a Node module that was distributed via NPM.

**Comment by joeblew99** [comment]
i guess a node module is lowest common denominator in the front end
programming world.

I hate to be a picky bugger, but i think its best for Desktop i use this.
https://github.com/sanbornm/go-selfupdate
Then i can package everything including electron itself into the update.
Its analogous to how how CoreOS updates itself with Transaction AB updates

**Comment by joeblew99** [comment]
If you want  can close this ?

**Comment by lostintangent** [comment]
Makes sense. The primary reason we haven't prioritized desktop apps is because there are pretty good existing solutions (e.g. Electron has a built-in auto-updater module). I'll close this for now, but please let us know if you want us to re-consider doing something in this space. Thanks for the feedback!

**Comment by joeblew99** [comment]
did not know that about Electron. cheers

**Comment by PierBover** [comment]
Yes please, add support for Electron apps. Or at least add a Node API so we can get the files from the CodePush server and copy them to the relevant folder in the Electron app.

We are using CodePush for our Cordova apps and it would be awesome to use a single deploy platform for all our clients.

**Comment by goodhyun** [comment]
+1

**Comment by joeblew99** [comment]
@lostintangent 
I stopped using the standard Electron update methods, because its too limitting for me.
Why ?
I build Electron apps with golang, c#, java code underneath it. So its far easier or me to use golang based Packaging and Updating software.
I package using the standard tools for each os.
I use the golang asset packing to stuff the Electron assets inside the golang binary. This means that there are no files lying around. Its all just a single file.
- in the package is an electron app, and some golang, java and c' stuff
- the golang main func, starts up electron & any other things i need in a single proces.

For updates i just use the golang update services. There are many but here is one.
https://github.com/sanbornm/go-selfupdate


Not sure why i am telling you this. But i just found it much easier for my needs when i need to make apps with many dependencies underneath it.

**Comment by PierBover** [comment]
Hey @joeblew99 do you have a blog post or article that explains all that in more detail?

**Comment by joeblew99** [comment]
i have a public project here:

Its a bit messy still.... 🚨 

https://bitbucket.org/gedw99/md-desktop-x

Because i use golang, i also use golang to talk to Electron. This just involves using gopherjs.

As far as the packaging, i have not finished all the code for windows yet.

As far as the self updating, i have not put it in yet, but its very very easy with golang.

I plan to move the project to github in a week when its done, so others can use it.

If you want to help let me know. :)
