### ISSUE TITLE
Can I promote a specific label?

### ISSUE THREAD

**Issue by LeBlaaanc** [Microsoft/code-push#267]
It'd be awesome if I could promote a specific label, we basically have different targets to maintain on the same deployments and sometimes release updates to older targets.

**Comment by shishirx34** [comment]
I think it should be pretty straight forward to have this feature. We thought about this when we implemented the promote feature but we weren't sure if it would be valuable. For your example I think it would be useful.

```
code-push promote <AppName> <Deployment1> <Deployment2> -l <label to promote>
```

We can add an optional label parameter[default: latest label] to the promote command which would pick up the corresponding label from `Deployment1` and promote to `Deployment2`. Does this sound good to you?

I will add this item to our feature backlog, and use this issue to track it. We will keep you posted once we have it implemented.

**Comment by LeBlaaanc** [comment]
@shishirx34 sounds good to me, thanks.

**Comment by nevir** [comment]
We're also interested in this!

We'd like to move to a model where we have several code push lineages (every native `x.y` bump) in play at once.  Current approach might be to create a new deployment for each lineage, but that quickly gets cumbersome (especially when we have multiple deployments already)

**Comment by dbeard-groupon** [comment]
+1 Also very interested in this feature.

**Comment by silhouettes** [comment]
Tagging @chendo on this issue as he had a similar request.

**Comment by keertimaan** [comment]
@shishirx34 I am wondering if you have plans to address this issue soon?

**Comment by shishirx34** [comment]
@silhouettes should be able to answer it.

**Comment by keertimaan** [comment]
@silhouettes ^^^

**Comment by silhouettes** [comment]
@max-mironov Would you be able to implement this?

**Comment by max-mironov** [comment]
@silhouettes sure, I'll take this!

**Comment by sergey-akhalkov** [comment]
Closing this due to #394 has been merged, please feel free to reopen if needed.
