### ISSUE TITLE
latest version phonegap-build won't compile with code-push plugin

### ISSUE THREAD

**Issue by fbarletta** [Microsoft/code-push#268]
We are using the latest version of Cordova/PhoneGap. When we attempt to build the app using the latest version of phonegap-build, we get the following error.

`The following build commands failed: CompileC build/UPTOP.build/Release-iphoneos/UPTOP.build/Objects-normal/armv7/CodePush.o UPTOP/Plugins/cordova-plugin-code-push/CodePush.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler (1 failure)`

When we remove the plugin from the build, we can build successfully.

Anyone else have this issue?

**Comment by lostintangent** [comment]
@fbarletta Can you share what the actual failure was? I believe that message is just stating that the build command failed, but the output should also include a reason why. Thanks!

**Comment by lostintangent** [comment]
This has been addressed and released to NPM via the `v1.8.2-beta` release. Let us know if you run into any further issues. Thanks!

**Comment by fbarletta** [comment]
Thank you, Jonathan.

Would you like us to update anything on Git or help in any way?

On Thu, Jun 23, 2016 at 8:53 PM, Jonathan Carter <notifications@github.com>
wrote:

> This has been addressed and released to NPM via the v1.8.2-beta release.
> Let us know if you run into any further issues. Thanks!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Microsoft/code-push/issues/268#issuecomment-228228195>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AEHAc9CVOL5YRQWWck0FNIojnC-CEbT-ks5qOyqFgaJpZM4I9Rt_>
> .
>



-- 

Francis Barletta
CEO
UPTOP
www.liveuptop.com

**Comment by lostintangent** [comment]
If you could confirm that the latest release resolved your build issue, that would be awesome. We did a bunch of testing on our end, but I want to make sure you are unblocked.

**Comment by fbarletta** [comment]
Once we can confirm, we will let you know!

On Sun, Jun 26, 2016 at 1:07 PM, Jonathan Carter <notifications@github.com>
wrote:

> If you could confirm that the latest release resolved your build issue,
> that would be awesome. We did a bunch of testing on our end, but I want to
> make sure you are unblocked.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Microsoft/code-push/issues/268#issuecomment-228611247>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AEHAcytuNVA8RKzn36johFJIlyBNw9DUks5qPrG3gaJpZM4I9Rt_>
> .
>



-- 

Francis Barletta
CEO
UPTOP
www.liveuptop.com
