### ISSUE TITLE
Unintended reverts

### ISSUE THREAD

**Issue by Naoto-Ida** [Microsoft/code-push#270]
We currently use 2 keys.
One for deployment and the other for production.

I have a version of the app with the deployment key on Test Flight.
I download the app, it updates with the `codepush.sync({})`  method and I force an update.

It works, but occasionally reverts back to v1.
I'm not sure what causes this, wondering if anyone has encountered this.

**Comment by lostintangent** [comment]
@Naoto-Ida Could you provide an example of how you're calling `sync`? Are you explicitly passing a deployment key to it in order to dynamically switch keys, or are you configuring the keys statically in your `Info.plist` file and then creating TestFlight/production binary builds? Thanks! Apologies for this issue, we'll try to figure it out ASAP.

**Comment by lostintangent** [comment]
@Naoto-Ida Any updates here? We'd love to make sure you're unblocked, and can help diagnose this once we know a little more about your project setup.

Additionally, can you let us know where you are calling `sync`? Are you calling it in your root component's `componentDidMount` event handler?

**Comment by Naoto-Ida** [comment]
Sorry for the late reply, we've finally pushed a version of our app to the App Store with Code Push!
Thanks to you guys for the hard work.

Here is part of the code where I'm calling `sync` in the most top Component:

```
componentDidMount() {
        AppState.addEventListener("change", (newState) => {
            newState === "active" && codePush.sync({
                installMode: codePush.InstallMode.IMMEDIATE,
                mandatoryInstallMode: codePush.InstallMode.IMMEDIATE
            })
        })
})
```

For instance, we have v14 or something in `Staging`.
My colleague gets a 'flash' and updates to v14 forcefully.
Apparently it occasionally flashes, and reverts back to the bundle.

**Comment by lostintangent** [comment]
@Naoto-Ida Awesome! Could you share the app you're working on? We always like seeing what folks are building with CodePush :)

Regarding the rollback, you need to ensure that you call notifyAppReady (or sync) on app start in addition to in your app resume handler. This is what indicates that an update was successful to the CodePush runtime, and if it doesn't get called after an update was installed, the update could get rolled back.

For example, change your mount method like the following:

componentDidMount() {
        // Do an initial sync on app start instead of 
        // waiting until a resume to happen. Also, flag
        // any installed updates as being successful.
        codePush.sync();

        AppState.addEventListener("change", (newState) => {
            newState === "active" && codePush.sync({
                installMode: codePush.InstallMode.IMMEDIATE,
                mandatoryInstallMode: codePush.InstallMode.IMMEDIATE
            })
        })
})

**Comment by Naoto-Ida** [comment]
Thank you!
We just released [this app](http://iflyer.tv/en/article/2016/07/01/fujirock-powered-by-iflyer-app/) for Fuji Rock Festival, one of the biggest music festivals in Japan.

Thank you for the advice. I may have gotten those two things mixed up...

**Comment by lostintangent** [comment]
Very cool! If you get a chance to try out the above recommendation, please let us know if that removed the rollbacks, that way we can confirm that you're unblocked. Since this change only impacts JS, you can actually use CodePush to release an update that includes the neccessary `notifyAppReady`/`sync` call on app start and will prevent any further issues. Thanks!

**Comment by Naoto-Ida** [comment]
Thanks!

CodePush is great for us because with apps for festivals, the lineup is usually incrementally announced by the event organizer, and we want to keep the images available offline, which would result in resubmitting the app every week, which is very painful. Thanks for the wonderful work guys!

**Comment by lostintangent** [comment]
Yeah that's a really awesome use case :) Let me know if you'd be interested in having the app listed in our CodePush showcase, since this is definitely a cool use of the service, and the app looks great!

**Comment by Naoto-Ida** [comment]
Thank you! We've talked about it, and would be very interested!
We will be submitting through the showcase form probably this week.
Although we've been slowly switching to WebViews due to performance hits when using ListView components in React Native, which is very detrimental to an app with 200+ artist rows.

**Comment by silhouettes** [comment]
I am closing this as the issue seems to be resolved, but we look forward to your CodePush showcase submission!
