### ISSUE TITLE
Arbitrary deployment metadata

### ISSUE THREAD

**Issue by chendo** [microsoft/code-push#273]
We would like the ability to be able to set arbitrary metadata on a deployment so we can attach a git SHA to the release, so when a user first installs the app, it doesn't perform an unnecessary update.

**Comment by lostintangent** [comment]
@chendo This is something we hope to get to soon, since we hear this request pretty frequently.

That said, we actually want to solve the unnecessary update problem automatically, without any developer or app intervention. The server already has a hash of each update's contents, so we just need the hash of the binary-bundled content in order to no-op available updates that are equivalent to what the App Store version already included.

Our Cordova plugin already does this, and our React Native plugin will support this as of React Native 0.29.0 (we needed support from the RN packager), so depending on which platform your app is built on, we hope to help solve this without the need of the custom metadata feature.

**Comment by chendo** [comment]
Ah cool. We have a similar problem where if we build an APK with the newest code but haven't done a production code push, it will "upgrade" to the older version. I was hoping to use this arbitrary metadata to have a time stamp too.

**Comment by lostintangent** [comment]
Makes sense, yeah this feature would help solve that scenario as well. Regarding the time stamp, we should also just add that as well :) 

I want to enable the custom metadata feature, but also support mainline scenarios out of the box.

**Comment by chendo** [comment]
Nah, we're using Cordova. We see this because we built an APK but hadn't done a code push to production, so the hash would be different, but it would be doing a downgrade rather than an upgrade.

**Comment by lostintangent** [comment]
Ah OK got it. Apologies that I initially misunderstood you. Yeah, we definitely need to solve the issue of a client "upgrading" to an older version.

For this scenario, would it have solved your problem if you released a CodePush update that was equivalent to your APK contents? That way, the client would be able to detect an unnecessary update, and subsequent CodePush releases would actually be able to generate diffs beyond the binary contents as well.

We need to document this better, but in general, our recommendation is to release store updates to CodePush, to enable the aforementioned benefits.

**Comment by chendo** [comment]
Yeah it would, but we would like to build the production APK to make sure that's all good before we do a push to all users. Also, if we did a percentage rollout, would someone who downloads the new APK be potentially downgraded too?

**Comment by lostintangent** [comment]
When you generate a new production APK, are you also bumping the version? Or are you referring to an in-house/beta setup, where you have a release APK, but you haven't actually bumped the version yet?

If you are bumping the APK version, then you shouldn't have an issue with new clients upgrading to an older CodePush release as long as the existing CodePush releases aren't targeting the new APK's version. That is, unless you are explicitly targeting your CodePush releases at a range (e.g. "*").

The rollout feature works by segmenting users who would normally be elligle for a release, and only allowing it to a percentage of them. Therefore, using rollout wouldn't impact this issue you're seeing, since it wouldn't provide access to an update to a client that wasn't already eligible to it in the first place.

**Comment by geof90** [comment]
As a workaround, you could also use the [`description` parameter of the update](https://github.com/Microsoft/code-push/tree/master/cli#description-parameter-2) to encode custom metadata in JSON e.g. timestamps. When acquiring updates, you could use the ["advanced API" to `checkForUpdate`](https://github.com/Microsoft/cordova-plugin-code-push#codepushcheckforupdate), then `JSON.parse` the description metadata of the update, and decide whether or not to install it.

**Comment by chendo** [comment]
We want to build a production APK with the newest code to test and ensure everything is good before we code push an update out to users. So in the usual case where the plugins don't change, we wouldn't bump APK version.

@geof90 yeah that seems like what we'd have to do. We've actually disabled code push for now cause we launch next week and we occasionally see an issue where our Cordova app shows a blank screen after a code push update that we haven't had time to look into yet, so we'll have to re-visit post-launch

**Comment by geof90** [comment]
Can I clarify on your scenario? You built a production APK, but why were there CodePush updates being sent to that version? Are those updates just for sending updates to internal testers, or do they actually target real users? If it's just for internal testers, you could use the [`code-push patch --disabled` command](https://github.com/Microsoft/code-push/tree/master/cli#patching-update-metadata) to disable those updates after the app goes live on the app store.

Ah, that sucks that blank screen problem prevented you from using us. Feel free to let us know any information you have / repro steps when you have them and we will look into it right away.

**Comment by chendo** [comment]
@geof90 We have an older release on the production channel, so that update would have already gone out to users. 

I'll have more time to look in to that next week and I'll put the issue on the cordova plugin repo.

Super useful project though, keep up the good work 👍

**Comment by geof90** [comment]
But those updates on the production deployment would be targeting older versions (unless you are using a range like what @lostintangent said). Your new APK would have to be a newer version and won't get those updates, since the app stores don't let you publish an APK with the same version. Unless you are using a private app distribution mechanism?

**Comment by lostintangent** [comment]
In general, we need to improve the experience of detecting updates in an environment where the host binary hasn't bumped the version. Primarily, we see this in beta distribution scenarios (e.g. HockeyApp), which is effectively what it sounds like you're doing.

**Comment by chendo** [comment]
@geof90 We will be deploying to the Play Store, but we would still need to test with a release APK with the newest code first. So the easiest way is to have some timestamp in the deployment metadata so we don't go backwards, or just build an APK with code push disabled

**Comment by panarasi** [comment]
@sergey-akhalkov Can we investigate to see how this can be implemented please ?

**Comment by sergey-akhalkov** [comment]
@panarasi, I've investigated the way we could implement this feature in the same issue, please see investigation results here: https://github.com/Microsoft/react-native-code-push/issues/375#issuecomment-280572789

**Comment by iageoghe** [comment]
@sergey-akhalkov Your two implementations suggestions make sense. Please schedule with @pniko

**Comment by sergey-akhalkov** [comment]
Hi @iageoghe, got it, will do.

**Comment by sergey-akhalkov** [comment]
Hi @iageoghe, we've scheduled this with @pniko and this item will be implemented in order of priority, please let me know if you have any considerations or see any issues.

**Comment by adambene** [comment]
hey, is there an ETA for this feature?

**Comment by ruslan-bikkinin** [comment]
hi, @adambene, we are planning to pick it up after "brownfield" app support feature implementation which I am working on now. All issues marked as "prioritized" will be resolving soon.

**Comment by adambene** [comment]
@ruslan-bikkinin hi, thanks!

**Comment by sergey-akhalkov** [comment]
@ruslan-bikkinin, after implementing "support for brownfield apps" feature I believe we should start implementing this enhancement, please sync up with @pniko and confirm.

Regarding this feature details: I suggest to reserve the props that begin with underscores. For example, we could use such kind of props for the following purposes for example: 
1. `_gitRef` - store the reference to the commit (repo state) that has been used to generate js bundle file. This feature could help developers to determine what version of their code has been used for js bundle generation and fix issues.
2. `_reactNativeVersion` - may be helpful to determine what version of react-native is used for js bundle generation. We could warn the developer in case we have mismatch between versions of RN for 2 CodePush updates - the old one (that has been generated by an older version of RN) and new one that developer wants to release (that update is generated by the new version of RN). That mismatch may cause a lot of issues, so I believe that we should try to figure out how we could prevent it before developer released an update.

**Comment by mikewagz** [comment]
We'd also love to see custom metadata.  Thanks for working on this!

**Comment by nacho-carnicero** [comment]
Hi!

Has there been any progress on this? This is something that would be very useful to keep track of the deployments since codePush does not allow to customize the `label version` property.

**Comment by Pranit-Harekar** [comment]
@lostintangent @sergey-akhalkov @ruslan-bikkinin Is there any update on this feature? Sorry for tagging directly like this.

**Comment by saravanandm** [comment]
Any update on this feature?
