### ISSUE TITLE
CI strategies when using code-push in Cordova apps

### ISSUE THREAD

**Issue by pke** [Microsoft/code-push#274]
I just deployed our first production code update to out iOS app. Worked flawlessly.
However I did almost all of that by hand. Before our CI build chain included a `npm version patch` call and some `postversion` script to update the `config.xml` version as well but with code-push we can no longer use that, cause the `config.xml` must not be changed.

We use the ["standard" git workflow ](http://nvie.com/posts/a-successful-git-branching-model/) and this also does not work well when using code-push. The problem is: how does the CI server detects that a full appstore release is needed or only a `www` assets update (code-push).

Do you or any of the code-push users figured out a way to do that?
I am especially interested in keeping a "nightly" build for everying on the `develop` branch to be pushed to code-push `development` branch or if an app store release is needed (because plugins or config.xml settings have changed that effect the binary package) then an app store release should be automatically scheduled.

**Comment by silhouettes** [comment]
Just to acknowledge this, we would love to have better CI integration in general, beyond what we currently have. This is on our backlog, but it is at least a few months out, as we are currently focusing on crash and analytics integration.

It is also worth associating this with #252, which seems to be a big part of this.

**Comment by silhouettes** [comment]
Updated #252 with a possible way to implement it, feedback more than welcome!

**Comment by panarasi** [comment]
For nightly builds, you could check out Mobile Center's build process. Here is a video I did about continuous builds and Code Push - https://www.youtube.com/watch?v=lfqZ8Uy2p3U

**Comment by pke** [comment]
That is handling react native not cordova. But I'll give it a view and see if it could work with cordova.
