### ISSUE TITLE
New Website Logo: Fuji Rock Festival '16 App Powered By iFLYER

### ISSUE THREAD

**Issue by Naoto-Ida** [Microsoft/code-push#278]
Name: Fuji Rock Festival '16 App Powered By iFLYER
App Store url: https://itunes.apple.com/jp/app/fuji-rock-festival-16-app/id1112045623
Brand Guidelines/Licensing: Fuji Rock Festival®, the abbreviated common name Fuji Rock® and logos are registered trademarks of the Smash Corporation Ltd.
Logo: https://imgserv.iflyer.tv/bw_300/bh_300/1_3jj8oa0pbod61sty40x5i.png

Here is an article we wrote about the app, if any of you are interested.
http://iflyer.tv/ja/article/2016/07/01/fujirock-powered-by-iflyer-app/

Although we had some performance issues with React Native itself,
Code Push allowed us to do quick fixes that saved both us and the users some heartache.
Thanks!

**Comment by silhouettes** [comment]
Great!! We'll add you to the showcase today. I just read the article, the app looks very cool :)

**Comment by geof90** [comment]
Done! :beers:

**Comment by Naoto-Ida** [comment]
Thank you guys!
