### ISSUE TITLE
Is it possible to refresh the label of your builds

### ISSUE THREAD

**Issue by northkode** [microsoft/code-push#280]
Instead of the label incrementing to some huge number depending on code release.. 
are we able to do something like `code-push deployment <app-name> <development> --resetVersion`

which sets the version label to v1 again... 

not sure if this makes sense.. but if i have to release a binary version of the app to the respective stores.. and we went from 1.1.0 to 1.2.0 i would be interested in having my version numbers now reset to 1 for the new builds..

**Comment by slowsay** [comment]
me too,i don‘t know which one is the current version,

**Comment by geof90** [comment]
We will be adding support for having custom labels soon!

**Comment by slowsay** [comment]
there is also problem to update latest version ,but app display is still the old version

**Comment by slowsay** [comment]
"react-native-code-push": "^1.13.2-beta", is the package.json

**Comment by slowsay** [comment]
"react-native-code-push": "^1.13.2-beta", is the package.json

**Comment by slowsay** [comment]
info.plist ,setting production ，appstore app is not  hot update

**Comment by geof90** [comment]
@slowsay Could you open a new issue for the problem you're facing?

Also, did you use release-react to release the update? Is your targetBinaryVersion of the update the same as the one in production?

**Comment by slowsay** [comment]
i have soloved this problem , it 's component about "react-native-code-push" ，
the code is not detected when the tube error information, in webstorm.

**Comment by kristojorg** [comment]
Any update on when custom version labels will be out?

I would love to update my versioning to be MAJOR_BINARY_RELEASE.MINOR_BINARY_RELEASE.CODEPUSH_RELEASE

**Comment by pke** [comment]
The option for custom lables should be:

`--label default`
`--label gitversion`
`--label "My custom label"`


| value | description |
|------|--------|
|`default/legacy`| (codepush manages the incremental `vXX` label|
| `git`| the current branch commit id |
| `my custom label`| A user provided label |

I'd love to provide a PR but the source does not seem to be public.

**Comment by TombolaShepless** [comment]
Any word on this? The project as a whole seems to be slowing down, which is worrying me about adopting CodePush for our company.

**Comment by dkpalmer** [comment]
+1

**Comment by iageoghe** [comment]
@TombolaShepless @dkpalmer @kristojorg @pke Sorry for the super late response. We hear you and are taking your requests seriously. When I have a better sense of when we will start work on  label management I will let you all know.

**Comment by krewllobster** [comment]
Any updates on the custom labeling front?

**Comment by facundofarias** [comment]
Hi! Any news?
