### ISSUE TITLE
My Devices are not updating despite doing everything right

### ISSUE THREAD

**Issue by nuruddeensalihu** [Microsoft/code-push#281]
Hi,

I am trying to use this wonderful device and despite following the tut and documentations correctly, my app are not updating. In my config.xml i have

 ```
<access origin="*" />
<platform name="android">
        <allow-intent href="market:*" />
        <preference name="CodePushDeploymentKey" value="KEY-fLXW" />
    </platform>
    <platform name="ios">
        <allow-intent href="itms:*" />
        <allow-intent href="itms-apps:*" />
        <preference name="CodePushDeploymentKey" value="KEY-fLXW" />
    </platform>
```

In my index.js i have 

```
var app = {
    initialize: function() {
        this.bindEvents();
    },
    bindEvents: function() {
        document.addEventListener('deviceready', this.onDeviceReady, false);
    },
   onDeviceReady: function() {
        codePush.sync();
    }
}
app.initialize();
```

My CSP in index.html looks like 

` <meta http-equiv="Content-Security-Policy" content="default-src https://codepush.azurewebsites.net http://github.com https://*.googleapis.com:* https://*.polyfill.io:* https://*.google-analytics.com:* https://*.gstatic.com:* 'self' data: gap: https://ssl.gstatic.com 'unsafe-inline' 'unsafe-eval' 'self'; media-src *">`

I added two code-push apps. 

`code-push app add myapp-ios
`

and another for android. I copied the staging keys.  i Then run my app on my android phone.
`
Cordova run android -device`

I then release an android update
`
code-push release-cordova myapp-android android`

I tried numerous times yet my app is not updating . I confirmed my deviceReady event is being called yet still not update. Please what am i doing wrong? Any help would be appreciated.

**Comment by geof90** [comment]
To let us help you better, could you show us the output of your console logs?

**Comment by nuruddeensalihu** [comment]
@geof90 , its on mobile .However, on my attempt to test. I ran 
`
cordova emulate browser`

I then saw the two errors below in my console.

![image](https://cloud.githubusercontent.com/assets/12234030/16719621/44d88f42-475f-11e6-8962-545921cc6d4a.png)


Please thanks for your help once again.

**Comment by geof90** [comment]
Running on browser wouldn't work unfortunately. Are you able to attach the chrome debugger to the device? https://developer.chrome.com/devtools/docs/remote-debugging#debugging-webviews

**Comment by nuruddeensalihu** [comment]
@geof90 It seems to be trying the update now . I am not sure but its throwing the error 
`
file://android_assets/www/https%3A..... `

Could not be loaded ERR_NOT_FOUND.

**Comment by geof90** [comment]
Could you paste the entire output? You can mask out any deployment keys or secrets.

**Comment by nuruddeensalihu** [comment]
@geof90 It is working now. I can see something like below

![image](https://cloud.githubusercontent.com/assets/12234030/16723029/1154a020-477d-11e6-818a-9320e5290918.png)

However, I was trying to use notification before.

 ```
var updateDialogOptions = {
                    updateTitle: "You have an update",
                    optionalUpdateMessage: "Update available. Install?",
                    optionalIgnoreButtonLabel: "Nop",
                    optionalInstallButtonLabel: "Yep"
                };

codePush.sync({ updateDialog: updateDialogOptions});
```

as specified in the example here https://microsoft.github.io/code-push/docs/tutorials.html .  It seems to be part of the issue in my case. It works now that i changed it to 
`
codePush.sync();`

Its now working.

**Comment by geof90** [comment]
@nuruddeensalihu I see, the call you made to `codePush.sync()` is wrong. [The first parameter it expects is a `syncCallback`](https://github.com/Microsoft/cordova-plugin-code-push#codepushsync). Therefore, if you change that line to `codePush.sync(null, { updateDialog: updateDialogOptions})` it should work perfectly fine.
