### ISSUE TITLE
about hot update  for appstore app

### ISSUE THREAD

**Issue by slowsay** [Microsoft/code-push#282]
download app from appstore ,it's  not update,local test,the iphone is no problem to install

**Comment by geof90** [comment]
Is the app from the app store configured with a different deployment key? Could you paste the command you used to release the update?

**Comment by slowsay** [comment]
slowsay$ code-push release-react aya ios -d Production
Detecting ios app version:

Using the target binary version value "1.0.1" from "ios/aya/Info.plist".

Running "react-native bundle" command:

node node_modules/react-native/local-cli/cli.js bundle --assets-dest /var/folders/dt/875w0c7d1kj33nq0k1lnlbyw0000gn/T/CodePush --bundle-output /var/folders/dt/875w0c7d1kj33nq0k1lnlbyw0000gn/T/CodePush/main.jsbundle --dev false --entry-file index.ios.js --platform ios
[11:35:49 AM] <START> Building Dependency Graph
[11:35:49 AM] <START> Crawling File System
[11:35:50 AM] <START> find dependencies
[11:35:54 AM] <END>   Crawling File System (5218ms)
[11:35:54 AM] <START> Building in-memory fs for JavaScript
[11:35:55 AM] <END>   Building in-memory fs for JavaScript (322ms)
[11:35:55 AM] <START> Building in-memory fs for Assets
[11:35:55 AM] <END>   Building in-memory fs for Assets (233ms)
[11:35:55 AM] <START> Building Haste Map
[11:35:55 AM] <START> Building (deprecated) Asset Map
[11:35:55 AM] <END>   Building (deprecated) Asset Map (112ms)
[11:35:55 AM] <END>   Building Haste Map (400ms)
[11:35:55 AM] <END>   Building Dependency Graph (6203ms)
[11:36:14 AM] <END>   find dependencies (24202ms)
bundle: start
bundle: finish
bundle: Writing bundle output to: /var/folders/dt/875w0c7d1kj33nq0k1lnlbyw0000gn/T/CodePush/main.jsbundle
bundle: Done writing bundle output
bundle: Copying 5 asset files
bundle: Done copying assets

Releasing update contents to CodePush:

Upload progress:[==================================================] 100% 0.0s
Successfully released an update containing the "/var/folders/dt/875w0c7d1kj33nq0k1lnlbyw0000gn/T/CodePush" directory to the "Production" deployment of the "aya" app.

 Name       │ Update Metadata                │ Install Metrics       │
├────────────┼────────────────────────────────┼───────────────────────┤
│ Production │ Label: v12                     │ Active: 100% (2 of 2) │
│            │ App Version: 1.0.1             │ Total: 2              │
│            │ Mandatory: No                  │                       │
│            │ Release Time: 2 hours ago      │                       │
│            │ Released By: slowsay@gmail.com │                       │
├────────────┼────────────────────────────────┼───────────────────────┤
│ Staging    │ Label: v18                     │ No installs recorded  │
│            │ App Version: 1.0.1             │                       │
│            │ Mandatory: No                  │                       │
│            │ Release Time: 2 hours ago      │                       │
│            │ Released By: slowsay@gmail.com │                       │
└────────────┴────────────────────────────────┴───────────────────────┘

**Comment by Grodenn** [comment]
Do you have the same version on the update as on the app you have published on app store? For example you will not be able to push an update with version 1.0.1 if the appstore version is 1.0.0, instead you should change the build number to be able to push an update!

**Comment by slowsay** [comment]
appstore app version is 1.0.1

**Comment by geof90** [comment]
@slowsay from your post, I can see two active installs on the Production deployment, are those from your local testing?

Are you sure that the app you published to the app store has the Production deployment key specified in Info.plist?

Can you show us how you are calling `sync()`?

**Comment by slowsay** [comment]
import codepush from 'react-native-code-push';
export default class extends Component {
    componentDidMount() {
        codepush.sync({installMode: codepush.InstallMode.IMMEDIATE});
    }
}

**Comment by slowsay** [comment]
yes ,two active local testing
production and staging are the same version

**Comment by slowsay** [comment]
@geof90
rn version is 0.28, 
code-push verison is 1.12.1-beta,
Is that only reason?

**Comment by geof90** [comment]
@slowsay When you locally tested your app, did you test it with the "Release" configuration? I would try to mimic the exact configuration of the build sent to the app store in order to troubleshoot this. Right now there's too little information.

**Comment by slowsay** [comment]
@geof90 yes,i did,

**Comment by geof90** [comment]
If it works with the IPA file built with the release configuration, and it is the exact same one that you published to the app store, there's really no reason why it doesn't work when downloaded from the app store. I would check whether the one you published to the app store has indeed been configured properly.

**Comment by silhouettes** [comment]
@slowsay, did you still need help with this?

**Comment by silhouettes** [comment]
Feel free to re-open this if you still need help!
