### ISSUE TITLE
WebHook for install metrics

### ISSUE THREAD

**Issue by pke** [Microsoft/code-push#283]
What do you guys think how difficult it would be to provide a webhook for install metrics.

We have a dashboard where we would like to integrate the code-push metrics and polling the code-push API is not the most efficient way to keep the displayed data fresh.

It would be nice if the SDK would have a function to register a JS callback function that is called whenever the metrics update on the code push servers.

**Comment by geof90** [comment]
We actually had someone request for this feature and submit a PR on the React native SDK. You may want to use it for reference:

https://github.com/Microsoft/react-native-code-push/pull/379

The only hard part is that in Cordova, the report status JS function is called from native. We may need to register a global listener for this feature, which may not be the most ideal.

**Comment by pke** [comment]
It's not the client side I am talking about (hence why I posted the issue not not cordova-plugin-code-push).

Allow me to describe my current scenario: Our internal dashboard shows various metrics already. I'd like to add the deployment proliferation of our various white-label apps in that dashboard too.
At the moment I am using the SDKs `getDeploymentMetrics` in a 5 minute interval for each of our apps and deployment names (staging, production). But if course that is inefficient. Most of the time it returns the same data over several minutes or hours even.

So I thought you could implement, on the server, a Push-Service like URL with a **long running open HTTP connection** (see `PubNub`) or a **websocket** so that the code-push server could inform this channel (http connection or websocket) about deployment metrics updates. Since the server gets this information any time an app gets updated/rolled back it could either send the updated metrics right away or aggregate some and send them later.

That way we would not have to pull the information from the server, which is less ressource intensive on our side and your severs would also be less hammered by metric requests.

On the SDK client side I could be exposed as `on("metricsupdated", (deployment)`

**Comment by piyushjo** [comment]
Thank you for the feedback,
what data do you think will be useful to be exposed as part of this webhook like functionality? From the thread looks like you are mainly interested in metrics of how many users got the update rolled back. Anything else?

**Comment by pke** [comment]
I think the same data `code-push deployment ls` prints out. That would be UpdateMetrics, wouldn't it?
https://github.com/Microsoft/code-push/blob/master/definitions/rest-definitions.d.ts#L89

**Comment by heat** [comment]
a code-push deployment ls -format json as part of a pipe to a curl would be fine  to you isn't?

**Comment by pke** [comment]
@heat no, a pipe is not a webhook. I'd like the code-push server notify me about metric changes, not me polling them in any way (no pipe, no curl). Or I misunderstood you

**Comment by panarasi** [comment]
@pke Thanks a lot for the feature request. At this point, we do not plan to implement a WebHook. CodePush will expose the deployment metrics as a rest API, and we would recommend polling as a way to get the information.

**Comment by pke** [comment]
Too bad. Polling is very 2000 and network load unfriendly.
