### ISSUE TITLE
App freezes on update

### ISSUE THREAD

**Issue by viking2009** [Microsoft/code-push#284]
Please check this log. Real deployment key was replaced for security issue.

> Jul 18 18:31:50 <Warning>: [CodePush] Checking for update.
> Jul 18 18:31:51 <Warning>: [CodePush] An update is available. {"appVersion":"24.0.1","deploymentKey":"DEPLOYMENT_KEY","description":"","downloadUrl":"https://codepush.blob.core.windows.net/storagev2/BLOB","isMandatory":false,"label":"v2","packageHash":"fb6addc864445059957f6b8b11d5301e12a31ab2971924839d7d17a652210078","packageSize":7528307,"failedInstall":false}
> Jul 18 18:31:51 <Warning>: [CodePush] Downloading update
> Jul 18 18:32:37 <Warning>: File Transfer Finished with response code 200
> Jul 18 18:32:37 <Warning>: [CodePush] Package download success: {"deploymentKey":"DEPLOYMENT_KEY","description":"","label":"v2","appVersion":"24.0.1","isMandatory":false,"packageHash":"fb6addc864445059957f6b8b11d5301e12a31ab2971924839d7d17a652210078","isFirstRun":false,"failedInstall":false,"localPath":"cdvfile://localhost/library-nosync/codepush/download/update.zip"}
> Jul 18 18:32:37 <Warning>: [CodePush] Installing update
> Jul 18 18:32:45 <Warning>: THREAD WARNING: ['File'] took '4534.373047' ms. Plugin should use a background thread.
> Jul 18 18:32:46 <Warning>: [CodePush] Install succeeded.
> Jul 18 18:32:46 <Warning>: [CodePush] Update is installed and will be run on the next app restart.

on this stage
> THREAD WARNING: ['File'] took '4534.373047' ms. Plugin should use a background thread.

app freezes and doesn't respond to any actions.
The size of the file is ~7.5MB. Is it unzip stage? How we can solve the problem?

**Comment by geof90** [comment]
Dupe of https://github.com/Microsoft/cordova-plugin-code-push/issues/156. Sorry for the slow response, I have replied on the other thread.
