### ISSUE TITLE
New Website Logo: Liaoyuan

### ISSUE THREAD

**Issue by cnjsstong** [Microsoft/code-push#285]
Please fill the following out:

- Name: Liaoyuan
- Homepage (or app store) url: https://itunes.apple.com/us/app/liao-yuan/id1074472777
- Brand Guidelines/Licensing: Should appear on a white background.
- Logo: 
![1024](https://cloud.githubusercontent.com/assets/4534745/17106802/b7f84a48-525a-11e6-86a1-ed0d2c263c73.png)

**Comment by geof90** [comment]
Added!
