### ISSUE TITLE
New Website Logo: Zerocar

### ISSUE THREAD

**Issue by alma-socar** [Microsoft/code-push#288]
- Name: Zerocar
- Homepage (or app store) url: https://itunes.apple.com/us/app/zerocar-syeeolinghamyeon-jeloga/id1128309540?mt=8
- Logo: 

  ![zerocar-logo](https://cloud.githubusercontent.com/assets/16098076/17202090/fad940c8-54d1-11e6-97dc-452f612398ca.png)

**Comment by geof90** [comment]
Added!
