### ISSUE TITLE
Code-push on a regular web application? (non-Cordova, non-ReactNative)

### ISSUE THREAD

**Issue by af7** [Microsoft/code-push#289]
Use case:

We have created a TV set-top box application, with an Android launcher/wrapper, which eventually launches an `index.html` from the assets. 

This `index.html` has a `bundle.js` to provide the app functionality (this is a pure React project that compiles to a `bundle.js` using webpack, not "React Native").

As you can see we would like to have another script before we call `bundle.js` to do the following:

1. Read somehow the version of the `bundle.js` currently installed inside the assets (let's say that this is done).
2. Check on *code-push server* if a new `bundle.js` version is available.
3. If not, call the "assets-located" `bundle.js` and play as usual.
4. If yes (i.e. new version exists), fetch that `bundle.js` and store it inside the AsyncStorage of this Android app. Then, call *that* `bundle.js` instead and continue as usual.

(Note: Obviously the 1st task will have to read from the AsyncStorage for a bundle.js also in order to determine the version)

Is there a way to achieve such a workflow (or similar)?

Thank you!

**Comment by silhouettes** [comment]
I think that you'll basically be able to use our CLI to release updates and our server to store them, but you'll need to write the client-side acquisition code yourself. Your SDK would talk to the server via the `/updateCheck` route - [here](https://github.com/Microsoft/code-push/blob/master/sdk/script/acquisition-sdk.ts#L83) is some example code to give you an idea of what the route looks like.

Does that help? Please let me know if you need any further guidance!

**Comment by af7** [comment]
@silhouettes Thank you! I have to understand how to use this. It would be *great* if you could show a *complete example* of how this use case can be implemented. I am sure this will help many others because it will expand "Code Push" to an entire new ecosystem (web apps on TVs, web apps in general, etc.), not just Cordova and React Native.

Thanks again!

**Comment by silhouettes** [comment]
Hi @af7, I'm happy to answer any specific questions that you might have, but we don't currently have the resources to make a detailed example tailored to your scenario. For what you need, I think the [React Native plugin](https://github.com/Microsoft/react-native-code-push) is a good reference example in general, although you probably won't need to implement every single feature we've implemented there. The most relevant part to you would probably be how the [updateCheck ](https://github.com/Microsoft/react-native-code-push/blob/db3a9428dc256efecfd5b1dbe0d30144e9e98b53/CodePush.js#L11) call is constructed.

Does that help? I'm happy to answer specific questions if you have any.

**Comment by silhouettes** [comment]
Closing this issue for now, but feel free to come back with any further questions!
