### ISSUE TITLE
CodePush service is unavailable in China

### ISSUE THREAD

**Issue by talisk** [Microsoft/code-push#294]
Hi, 

I’m a developer from China. Today I find that the CodePush service is unavailable in China.

When I run `code-push release-react AppName ios` or `code-push release AppName release 1.0` in the project folder, the upload progress will stop in 72%, and show error: `[Error]  connect ETIMEDOUT 23.101.203.117:443` or `[Error]  getaddrinfo ENOTFOUND codepush-management.azurewebsites.net codepush-management.azurewebsites.net:443`

I run `ping 23.101.203.117:443` in the terminal and it tell me cannot resolve 23.101.203.117:443: Unknown host, although I was connect through a oversea proxy .

**Comment by piyushjo** [comment]
Hi there,
yes it is a known issue and something which is on our backlog to fix. The upload takes a long time and sees connection timeouts at times.

**Comment by beast** [comment]
maybe try this? http://codepush-managerment.19910225.com:8080/

**Comment by silhouettes** [comment]
@talisk - is this still happening for you?

As an update, we have rolled out a CDN for distributing the updates, which should speed up the download time globally. Update checks and release commands will still hit our main server, with the performance seeming to depend on where in China you are - we do have many Chinese customers, with a small subset of them reporting slow times.

**Comment by talisk** [comment]
@beast Is it a service powered by Microsoft offical organization?

**Comment by talisk** [comment]
@silhouettes Thx for your help. Now, CodePush networking performance in China is better than some month ago. But I still found some network error recently.

**Comment by beast** [comment]
@talisk It is certainly not.

**Comment by simongfxu** [comment]
I have did somespeed tests  [here](http://ce.cloud.360.cn/) using [https://codepush.azurewebsites.net/](https://codepush.azurewebsites.net/).

The result is quite frustrating.

**Comment by Palgie** [comment]
Seem to be also getting a few frequent timeouts from Taiwan too.

```
code-push access-key ls
[Error]  <html><head><title>500 - The request timed out.</title></head><body>  <font color ="#aa0000">         <h2>500 - The request timed out.</h2></font>  The web server failed to respond within the specified time.</body></html>
```

```
Enter your access key: xxxxxxx
[Error]  connect ETIMEDOUT 23.101.203.117:443
```

**Comment by sergey-akhalkov** [comment]
Closing this for now, please feel free to reopen if you see any issues.

**Comment by borisding1994** [comment]
Reverse proxy may be a good choice.

FYI

```conf
events {
    worker_connections  1024;
}


http {
    include       mime.types;
    default_type  application/octet-stream;
    keepalive_timeout  65;
proxy_temp_path   /var/tmp/nginx/proxy_temp_dir 1 2;
proxy_cache_path  /var/tmp/nginx/cache  levels=1:2 keys_zone=codepush:10m inactive=24h max_size=1g;

    server {
        listen       80;
        server_name  {#proxy.domain#};
	location / {
	proxy_redirect off;
	proxy_set_header X-Real-IP $remote_addr;
	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	proxy_set_header X-Forwarded-Proto https;
  	proxy_set_header Referer https://codepush.azurewebsites.net;
   	proxy_set_header Host codepush.azurewebsites.net;
	proxy_pass https://codepush.azurewebsites.net;
	subs_filter_types application/json; #subs_filtert end
    	subs_filter 'codepush.blob.core.windows.net' '{#cdn domian, like: qiniu.com upyun.com#}' g;
        proxy_cache codepush; 
        proxy_cache_valid 200 12h; 
        proxy_cache_use_stale  error timeout invalid_header updating
                               http_500 http_502 http_503 http_504;
	proxy_ignore_headers X-Accel-Expires Expires Cache-Control Set-Cookie;
        proxy_ignore_headers Set-Cookie;
        proxy_ignore_headers Cache-Control;
        proxy_hide_header Cache-Control;
        proxy_hide_header Set-Cookie;
	}
}

}
```

**Comment by ninechung** [comment]
@0xDing How to configure apache? plz help me.
