### ISSUE TITLE
why updates rolled back when i restarted my app?

### ISSUE THREAD

**Issue by cloudkay** [Microsoft/code-push#297]
I created a blank ionic app, and finished the steps as Getting Started. Code-push performed well when I released a new update. It's amazing.
But when I restarted my app, it rolled back to the initial version, got the logs:

> H:\cordova\CodePush>code-push debug android
> Listening for android debug logs (Press CTRL+C to exit)
> [04:07:14] Checking for update.
> [04:07:19] An update is available. {"appVersion":"0.0.1","deploymentKey":"JMFTiJ
> Eq_7ztiKR3gm6hUYXjFPkAEy0mxMWKW","description":"","downloadUrl":"https://codepus
> h.blob.core.windows.net/storagev2/JzCeV5TllpeS9ym1CkAv_QGsL3VYEy0mxMWKW","isMand
> atory":false,"label":"v5","packageHash":"c4305c440de831d9cb9ecd01b8306c147bf65bb
> 5a18aff6f88b10fb4f50b32e2","packageSize":1002,"failedInstall":false}
> [04:07:19] Downloading update
> [04:07:23] Package download success: {"deploymentKey":"JMFTiJEq_7ztiKR3gm6hUYXjF
> PkAEy0mxMWKW","description":"","label":"v5","appVersion":"0.0.1","isMandatory":f
> alse,"packageHash":"c4305c440de831d9cb9ecd01b8306c147bf65bb5a18aff6f88b10fb4f50b
> 32e2","isFirstRun":false,"failedInstall":false,"localPath":"cdvfile://localhost/
> files/codepush/download/update.zip"}
> [04:07:23] Installing update
> **[04:07:23]  Cannot perform diff-update.
> [04:07:23] An error occurred during sync.**
> ^C终止批处理操作吗(Y/N)? Y
> 
> H:\cordova\CodePush>code-push debug android
> Listening for android debug logs (Press CTRL+C to exit)
> [04:17:41] Sync already in progress.
> [04:17:41] Package download success: {"deploymentKey":"JMFTiJEq_7ztiKR3gm6hUYXjF
> PkAEy0mxMWKW","description":"","label":"v5","appVersion":"0.0.1","isMandatory":f
> alse,"packageHash":"c4305c440de831d9cb9ecd01b8306c147bf65bb5a18aff6f88b10fb4f50b
> 32e2","isFirstRun":false,"failedInstall":false,"localPath":"cdvfile://localhost/
> files/codepush/download/update.zip"}
> [04:17:41] Installing update
> [04:17:41] Install succeeded.
> [04:17:41] Update is installed and will be run on the next app restart.
> [04:17:42] Checking for update.
> [04:17:42] An update is available. {"appVersion":"0.0.1","deploymentKey":"JMFTiJ
> Eq_7ztiKR3gm6hUYXjFPkAEy0mxMWKW","description":"","downloadUrl":"https://codepus
> h.blob.core.windows.net/storagev2/pQBZsShSpK6HpG7sDL3BJvW0RCo8Ey0mxMWKW","isMand
> atory":false,"label":"v5","packageHash":"c4305c440de831d9cb9ecd01b8306c147bf65bb
> 5a18aff6f88b10fb4f50b32e2","packageSize":1652497,"failedInstall":true}
> **[04:17:42] An update is available, but it is being ignored due to have been prev
> iously rolled back.**

Any help? Thanks.

**Comment by geof90** [comment]
Does this happen all the time? Could you show us how you called `sync()`?

We have never seen this error before, it seems that its either a file IO error or the diff update that our server returned doesn't contain a manifest file, but I'm wondering how that is possible :/

https://github.com/Microsoft/cordova-plugin-code-push/blob/73a2c36f000ddaf5bb80a2530641905c14b1b537/www/localPackage.ts#L280

**Comment by cloudkay** [comment]
Thanks for your reply.
Yes, it happens every time.
I just create a blank app:

> ionic start codepush blank

And, call sync() in app.js:

```
angular.module('starter', ['ionic'])

  .run(function ($ionicPlatform, $rootScope) {
    $ionicPlatform.ready(function () {
      if (window.cordova && window.cordova.plugins.Keyboard) {
        // Hide the accessory bar by default (remove this to show the accessory bar above the keyboard
        // for form inputs)
        cordova.plugins.Keyboard.hideKeyboardAccessoryBar(true);

        // Don't remove this line unless you know what you are doing. It stops the viewport
        // from snapping when text inputs are focused. Ionic handles this internally for
        // a much nicer keyboard experience.
        cordova.plugins.Keyboard.disableScroll(true);
      }
      if (window.StatusBar) {
        StatusBar.styleDefault();
      }
      document.addEventListener("resume", function () {
        codePush.sync();
      });
     
    });
  })

```
I push the project to [https://github.com/cloudkay/test](https://github.com/cloudkay/test)

**Comment by cloudkay** [comment]
This issue happens in my another app. When restarts, app rolls back and gets log:
>"[CodePush] An update is available. 
{
    "appVersion": "2.0.3",
    "deploymentKey": "xxx",
    "description": "",
    "downloadUrl": "xxx",
    "isMandatory": false,
    "label": "v8",
    "packageHash": "23c6e81732bc379db11df80b3cc154df25e7a80e16372f801f57689ecdde9a57",
    "packageSize": 3230,
    **"failedInstall": true**
}", 
source: file:///android_asset/www/plugins/cordova-plugin-code-push/bin/www/codePushUtil.js (37)

Is it due to **"failedInstall": true** ?

**Comment by kinglionsoft** [comment]
I get the same issue. When restarts, app rolls back and launches the initial url:
> file:///android_asset/www/index.html

Console log shows:

>"[CodePush] An update is available. 
{
    "appVersion": "2.0.3",
    "deploymentKey": "xxx",
    "description": "",
    "downloadUrl": "xxx",
    "isMandatory": false,
    "label": "v8",
    "packageHash": "23c6e81732bc379db11df80b3cc154df25e7a80e16372f801f57689ecdde9a57",
    "packageSize": 3230,
    **"failedInstall": true**
}", 
source: file:///android_asset/www/plugins/cordova-plugin-code-push/bin/www/codePushUtil.js (37)

Is it due to **"failedInstall": true** ? 
I find the fragment on [cordova-plugin-code-push](https://github.com/Microsoft/cordova-plugin-code-push/blob/master/bin/www/codePush.js#L228). I'm confused why the the **failedInstall** is true after the updates has installed and new pages has shown.
Thanks.

**Comment by geof90** [comment]
Try changing it to this instead:
```
      codePush.sync() && document.addEventListener("resume", function () {
        codePush.sync();
      });
```

I suspect the event listener is only added after the app starts, so `codePush.sync()` is not called until the app next resumes from the background. During the time window from the app start to the app first resume, if the app is killed, [`codePush.notifyApplicationReady()`](https://github.com/Microsoft/cordova-plugin-code-push#codepushnotifyapplicationready) will not be called as part of `sync()`, so the update doesn't get "rubber stamped" as "successful", and rolls back.

**Comment by cloudkay** [comment]
Thanks @geof90 , I do as you said, and it works.

**Comment by lukasrein97** [comment]
Dont work for me im getting:
**Cannot read property 'sync' of undefined**

**Comment by max-mironov** [comment]
@lukasrein97 - hi, could you please be more specific about your problem? Do you have the exact repro steps as mentioned above?
If not could you please fill the new issue and provide us as much info about your problem as possible and we will try to identify the reason of the problem. Thanks in advance!

**Comment by lukasrein97** [comment]
Yeah 
So im working on Ionic 2 and I'm faceing 2 Problems! 

**First Problem: If you run "ionic build android --prod" instead of "ionic build android" the Plugin wont work anymore because you get Typestript: Cannot read property 'is' of undefinded.**
Notice: if you run the exactly same code with ionic build android the Code-Push works perfect!

**Second Problem: The Method with onResume dont work in my Project. If my App gets out back of the Background and on Resume gets called i get this Error: Typescript Error: Cannot read property 'sync' of undefined**
Notice: Normal startup works fine here only the Resume Method dont work.

This is my Code in my app.component.ts:
```
 this.platform.ready().then(() => { 

      this.codePushService.sync().subscribe((syncStatus) => {

        console.log('Sync Status: ', syncStatus);

        if (syncStatus === SyncStatus.UP_TO_DATE) {

          // facing some zoning problems here !!
          // why ??

          // forcing to run in the ngzone
          this._zone.run(() => {
            this.messageText = 'App is up to date !';
            console.log("App is up to date");
          });
        }

        switch (syncStatus) {
          case SyncStatus.IN_PROGRESS:
            this.messageText = 'An update is in progress ..';
            break;

          case SyncStatus.CHECKING_FOR_UPDATE:
            this.messageText = 'Checking for update ..';
            break;

          case SyncStatus.DOWNLOADING_PACKAGE:
            this.messageText = 'Downloading package ..';
            break;

          case SyncStatus.INSTALLING_UPDATE:
            this.messageText = 'Installing update ..';
            break;

          case SyncStatus.UPDATE_INSTALLED:
            this.messageText = 'Installed the update ..';
            const alert = this.alertCtrl.create({
              title: 'Update',
              message: 'A new update was installed and will be available on next app restart',
              buttons: ['OK']
            });
            alert.present();
            alert.onDidDismiss(() => {
            });
            break;

          case SyncStatus.ERROR:
            this.messageText = 'An error occurred :( ...';
            break;

          default:
            this.messageText = 'An unhandled sync status ..';
            break;
        }

      }) && document.addEventListener("resume", function () {
        this.codePushService.sync();
      });
```

**Comment by max-mironov** [comment]
@lukasrein97 I've created [separate issue ](https://github.com/Microsoft/cordova-plugin-code-push/issues/237)for your items (prefer not to reopen this one as seems that they are not related), will will try to address it soon.

**Comment by nisos-siddharth** [comment]
I have tried all the above solution, still the update is rolled back on app restart. The update installs properly on device resume from background, however if I kill the app from backgroud, I get the following message on next app restart:  `An update is available, but it is being ignored due to have been previously rolled back`. I am using Ionic2 and my code in app.component is as follows:

```
import { CodePush, InstallMode } from '@ionic-native/code-push';
@Component({
  templateUrl: 'app.html'
})
export class MyApp {
  iscodePushUpdate:boolean;
  constructor(public platform: Platform, private codePush: CodePush) {
    platform.ready().then(() => {
      this.platform.pause.subscribe(() => {
            if(this.iscodePushUpdate){
              this.codePush.restartApplication();
            }        
        });
      this.platform.resume.subscribe(() => {
          this.codePushSync();
      });
      this.codePushSync();      
    });
  }

codePushSync(){
  this.codePush.sync({installMode: InstallMode.ON_NEXT_RESTART}).subscribe((syncStatus) => {console.log(syncStatus)
        if(syncStatus == 1){
          this.iscodePushUpdate = true;
        }
      });
  const downloadProgress = (progress) => {console.log(`Downloaded ${progress.receivedBytes} of ${progress.totalBytes}`); }
  this.codePush.sync({installMode: InstallMode.ON_NEXT_RESTART}, downloadProgress).subscribe((syncStatus) => {
console.log(syncStatus);
  });
}
