### ISSUE TITLE
server open source?

### ISSUE THREAD

**Issue by pke** [Microsoft/code-push#30]
Did I just not see it or is the server code closed source?

**Comment by lostintangent** [comment]
Yeah, we've just open sourced the management CLI and the client plugins for Cordova and React Native thus far.

**Comment by pke** [comment]
Server code coming next?

**Comment by lostintangent** [comment]
It's definitely on our list of things we'd like to do. Part of our desire to release the service early was to get feedback from folks, particularly around scenarios that we know could be valuable (e.g. on-prem hosting of the service), but we just wanted to get validation that it is in fact valuable and/or a priority.

**Comment by pke** [comment]
Cool. Nice feature would be binary diff'ed updates from newest to all older versions. Like store apps are updated internally.

**Comment by chauthai** [comment]
+1 for server code! I would really like to hack it :smile: 
Have you taken a look at: https://github.com/nordnet/cordova-hot-code-push ?
