### ISSUE TITLE
there is a problem icon is not displayed.

### ISSUE THREAD

**Issue by jrz90000** [Microsoft/code-push#300]
Hello there
I use codepush updated, there is a problem icon is not displayed.

index.ios.js:
icon={require('./App/Img/icon-01.png')}

shell:
react-native bundle --parameter ios --entry-file index.ios.js --bundle-output ./bundles/SwitchCheck010000.js --assets-dest ./bundles

code-push release haixiong ./bundles 1.0.0

or

react-native bundle --platform ios --entry-file index.ios.js --bundle-output ./bundles/main.jsbundle --assets-dest ./bundles
code-push release haixiong ./bundles/main.jsbundle 1.0.0

Reference see the picture, how I need to show my image?

![img_9042](https://cloud.githubusercontent.com/assets/7508776/17648089/230d22e0-623c-11e6-8557-e88114189d60.PNG)

**Comment by geof90** [comment]
Change:

code-push release haixiong ./bundles/main.jsbundle 1.0.0

To:

code-push release haixiong ./bundles 1.0.0

You need to release the whole folder including the assets to CodePush, not just the bundle.

**Comment by silhouettes** [comment]
Hi @jrz90000, I'm assuming this solved your issue, but please feel free to continue commenting if it didn't!
