### ISSUE TITLE
Invalid access key

### ISSUE THREAD

**Issue by asadsahi** [Microsoft/code-push#304]
I have generated a new key for the app using cli and used the staging key in config.xml file. Got VSTS CI build for this app, but the codepush is failing in access key as shown below:

![image](https://cloud.githubusercontent.com/assets/3470892/17838089/5ed55a88-67bc-11e6-8605-ccf6c998ddcf.png)

Any idea why I am getting this error even got the same key copied in config.xml?

Note: I haven't deploy the app in android app store yet.

**Comment by silhouettes** [comment]
In CodePush, there are two types of keys.

The **deploymentKey** (e.g. staging/production) gives access for clients to download updates on a specific deployment, and can also be used as an identifier for the deployment.

The **accessKey** is a separate key that gives a developer access to publish updates on any app under their account. To configure VSTS, you will need one of these keys. From the CLI, you can run `code-push access-key ls` and `code-push access-key add ...` to get an access key for your build.

Does that solve the issue for you?

**Comment by asadsahi** [comment]
Indeed it has. 

Thanks @silhouettes
