### ISSUE TITLE
Code Signing Feature

### ISSUE THREAD

**Issue by andrewwebber** [Microsoft/code-push#307]
I have not spent to much time looking deep into the however my intuition is that a security enhancement could be in order.

I would like to see a workflow utilising signing (RSA or HMAC, etc.) and or encryption.
1. When an app is created via code-push cli a client side key is created for the app.
2. This key is used to at least sign the bundle 
3. An additional key is used to verify the bundle before in "getJSBundleFile"

This way the app developer can validate that the app bundle has not been modified by code push or some external entity.

This would be very attractive because without such a feature, within a thread analysis, developers need to explain to management that Microsoft can modify the app.

This would also reduce the likely-hood that developers will just try and re-implement the code push backend just to comply with security regulations.

The alternative of course would be to open source the code-push azure web app.

**Comment by silhouettes** [comment]
Hi @andrewwebber, this is being actively worked on and approaching completion! ETA is 1 week. I'll leave this open, but also link it to #233.

The current process I'm implementing is like this:

1. Ensure dev has procured a `{ <privateKey>, <publicKey> }` pair. Could be a .p12/.pem + .cer, or a KeyStore, or any number of things.
1. Ensure the dev has the `privateKey` on their dev machine, and the `publicKey` baked natively into their app store release.
1. When a release is made from the CLI, the directory contents are hashed. Basically: create a sorted array of key value pairs (one for each file in the release), of the format `<relativeFilePath>: <SHA256Hash>`. Stringify this array and hash that to get a single `directoryHash`.
1. Construct a [JSON Web Token](https://jwt.io/), with the claim `contentHash: <directoryHash>`. Sign it using RS256 with the developer's private key from the CLI locally on their machine.
1. Write the JWT to a file called `.codepushrelease` at the root of the package, before it is released to the CodePush server.
1. When the mobile app receives an update, the CodePush SDK will look for the `.codepushrelease` file, read the JWT out of it, verify it against the configured public key, and then hash the contents of the update and verify it against the hash on the JWT. The update will only be installed if this verification is successful.

Let me know if you have any thoughts or criticisms on this! I'm also looking for ideas on how to achieve (1) and (2). For example, what does the configuration and release process look like? Should the same private key be used across your whole account, or per app, or per deployment? Should dev/staging builds be signed, maybe with a common debug key?

**Comment by andrewwebber** [comment]
This is more than excellent news

My immediate reaction would be concern around whether the public key a self signed certificate or a public certificate with a valid certificate chain. Not having a completely valid certificate hierarchy may reduce developer barrier to entry (?). An hmac approach maybe to weak for some as the shared secret could be easily extracted from the application.

Future enhancements might be a pipeline/plugin/provider model within code push.getJSBundle allowing for cli and app side extensibility where by a policy could be included in the JWT defining how the bundle was created (metadata, hash algorithm, key type, etc) like Oauth2 JWT in ADFS 3.0. This would allow for cli defined hashing algorithms and etc for advanced users as well as adding custom validators to possibly extended or harden the promotion concept

**Comment by silhouettes** [comment]
Hey @andrewwebber, I'm sorry I completely missed your response! I've noted your point about extensibility - the current PR I have up at the moment covers just the basics, but leaves plenty of room in the future to extend it.

**Comment by andrewwebber** [comment]
@silhouettes No problem at all, thanks for getting back.

I'm really looking forward to trying it out, this will be a great security feature and such security features need to be in as early as possible from my opinion.

The only reason I mentioned the certificate hierarchy was due to my troubled experience validating certificates on some platforms (keychain, certificate store, etc.) If you can get around those platform issues and skip any chain validation requirements then awesome.

Thanks again for the great project.

**Comment by silhouettes** [comment]
Just to keep everyone in the loop - we were close to finishing the implementation of this, but we've run into some small difficulties with the verification process on iOS. The intention to complete this is there, but we're currently extremely back-logged, so this may be shelved for a month or two while we work through other more pressing issues. Thanks so much for your patience here!

**Comment by axemclion** [comment]
@sergey-akhalkov Can we pick up this work item ?

**Comment by silhouettes** [comment]
@axemclion - By the way, I soloed this feature for a while, so it might be good to go over the design together at some point just to make sure that it makes sense

**Comment by axemclion** [comment]
Yeah - thats what I meant when I said that @sergey-akhalkov can look over this.

**Comment by sergey-akhalkov** [comment]
@axemclion, got it, will do!

**Comment by ajwhite** [comment]
Had some similar thoughts that I opened up in the React Native project. Going to cross link those for reference. https://github.com/Microsoft/react-native-code-push/issues/749

Glad to see active discussions around this request.

**Comment by axemclion** [comment]
@ajwhite We are actively looking at this and should have a design for the community to review soon.

**Comment by eladmoshe** [comment]
Any update on the status of this feature? Once this is implemented this is going to be huge win for Code Push for enterprise apps. Code Push is probably a no-go for most of the people who have to fill and sign some ISO document once a year, and there are lots of those :)

**Comment by iageoghe** [comment]
@eladmoshe This is one of our top priorities and we are actively working on this feature now.

**Comment by sergey-akhalkov** [comment]
Hey guys, Code Signing feature has been [released](http://microsoft.github.io/code-push/articles/CodeSigningAnnouncement.html)! 
So I'm closing this issue, please feel free to create new one in case of any questions or issues.
