### ISSUE TITLE
Key (hidden) when running access-key list

### ISSUE THREAD

**Issue by LeBlaaanc** [Microsoft/code-push#310]
Hello,

I'd like to list out the access-key value and I can't seem to figure out how to do this with the CLI, if it's only possible to regenerate the key that's fine too but it seems the `code-push rm` command needs the access key for deletion. Can someone assist with accomplishing one of these goals? Thanks!

**Comment by LeBlaaanc** [comment]
To follow up on my own issue (and apologies for not just trying this the first time) it seems despite the documentation displaying `code-push access-key rm <accessKey>` which is a bit confusing it wants `code-push access-key rm <Description>`. There's also `-ttl` which isn't documented.

**Comment by silhouettes** [comment]
Hey Chris, I suspect you're on an older CLI, could you upgrade to the latest? I think all of the documentation will make sense at that point. I'm so sorry about the confusion!

**Comment by LeBlaaanc** [comment]
Shoot my mistake, I ran `npm -g install code-push` instead of `npm -g install code-push-cli` for the upgrade. Thanks for getting me back on track @silhouettes.
