### ISSUE TITLE
code-push add access-key --ttl parameter doesn't work?

### ISSUE THREAD

**Issue by LeBlaaanc** [Microsoft/code-push#311]
There's mention in the documentation of a `--ttl` parameter yet when I run something like `code-push access-key add "Bitrise" --ttl 360d` the command doesn't create an access-token. I am using code-push version `1.11.0-beta`.

**Comment by silhouettes** [comment]
Hey @LeBlaanc, the documentation only covers the latest version of the CLI - could you upgrade and then try again? I'm so sorry about the confusion!

**Comment by LeBlaaanc** [comment]
Shoot my mistake, I ran `npm -g install code-push` instead of `npm -g install code-push-cli` for the upgrade. Thanks for getting me back on track @silhouettes.
