### ISSUE TITLE
Get [Error]  Unauthorized

### ISSUE THREAD

**Issue by oney** [Microsoft/code-push#312]
I don't know if it happens for just me.
I run `code-push app ls`, and got `[Error]  Unauthorized`.
Whatever code-push command I run, I get `[Error]  Unauthorized`.
At last, I logout with `code-push logout`, and login, it went right.
I think we can have better responses than `[Error]  Unauthorized` to hint developers.

**Comment by geof90** [comment]
Sorry you went through that, if you upgrade the CLI to the latest version you should see a better error message, and we're working on a fix on the server side to give a better error message to users on the older CLIs too.

**Comment by ajwhite** [comment]
I had this same issue, had to log out and log back in

**Comment by geof90** [comment]
I have fixed this on the server end with a better error message, so I will close this.
