### ISSUE TITLE
code-push register doesn't take me to the URL

### ISSUE THREAD

**Issue by atsepkov** [Microsoft/code-push#314]
I've just set up CodePush and trying the register command:

    code-push register

It does spawn the browser window (as it states in the console), however, the browser does not navigate to any URL like the instructions claim, I'm simply looking at my home page.

Browser: Google Chrome Version 52.0.2743.116 (64-bit)
OS: OSX Yosemite 10.10.5 (14F1509)

**Comment by silhouettes** [comment]
Hi @atsepkov, that's bizarre - I'm unable to repro this, and haven't gotten any other reports. Does this still happen for you?

As a workaround in the meantime, the page that you want to go to is:

`https://codepush-management.azurewebsites.net/auth/register?hostname=<your-machine-name-here>`

**Comment by atsepkov** [comment]
Thanks! I've worked around this by setting Safari as default browser temporarily, so it's possible the issue is with my Chrome install or one of the extensions it uses, although I'm not able to pinpoint which one.

**Comment by silhouettes** [comment]
Thanks heaps for filing this issue and providing this information, it is very useful. There is definitely something strange here, as I can't repro it (admittedly I am on El Capitan, maybe it's the OS?).

As you are unblocked for now, I'm going to close this issue, but if anyone else runs into this I would love it if you could add on to the thread here to help us get it diagnosed!

**Comment by atsepkov** [comment]
Yep, I'm unblocked, thanks.
