### ISSUE TITLE
[Error]  Not Found from every command

### ISSUE THREAD

**Issue by weixingsun** [Microsoft/code-push#315]
Hi there,
Please help, my account is not working any more, but it was, Is there any recent change in the cli tool? 
------------------------------------------------------------
$ code-push -v
1.12.3-beta
$ code-push logout
Successfully logged-out. The session file located at /Users/user/.code-push.config has been deleted.

[Error]  Not Found
$ code-push login
A browser is being launched to authenticate your account. Follow the instructions it displays to complete your login.

Enter your access key:  

Successfully logged-in. Your session file was written to /Users/user/.code-push.config. You can run the code-push logout command at any time to delete this file and terminate your session.

$ code-push app ls
[Error]  Not Found
$ code-push access-key ls
[Error]  Not Found
$ code-push access-key list
[Error]  Not Found

thanks a lot

**Comment by piyushjo** [comment]
Could you try updating to the latest CLI version?

**Comment by silhouettes** [comment]
Hi @weixingsun, do you mind emailing us to let us know the email address associated with your account? This is very strange and we'll have to look into it. codepush@microsoft.com

**Comment by weixingsun** [comment]
I have updated my cli with 
sudo npm -i -g code-push-cli 
My version is 1.12.3-beta, is there something better version I can use?

Thank you

**Comment by silhouettes** [comment]
Hi @weixingsun, I did some testing, and I think what might have actually happened is that in the line `Enter your access key:`, the wrong key was entered. When I did this, I reproduced the exact symptoms that you saw. If you log out and then log in again, and follow all of the prompts from your browser, are you able to get it working?

We haven't seen this specific issue before, so there are a few blind spots here that we could improve. Either way, I'll leave this issue open to track:

1. Validating that the access key entered is correct
2. Displaying a better error message than `Not Found`

**Comment by SoHotSoup** [comment]
I'm getting the same error when trying to execute `app add` from code by using sdk (v1.10.0-beta) or by calling cli (v1.12.3-beta)
```javascript
codePushExec.execute({
  type: codePushCli.CommandType.appAdd,
  appName: 'newApp',
})
```

This is pretty weird because when I try to login with the exact same access key and run the same command from terminal it successfully adds new app.

**Comment by SoHotSoup** [comment]
Solved by adding new access-key to cli. 👍

**Comment by silhouettes** [comment]
Thanks @SoHotSoup! @weixingsun, were you able to resolve your issue?

In the meantime, I've fixed the error messages on the server for future people running into this issue, and they should go live within two days.

**Comment by silhouettes** [comment]
I have fixed the following issues:
1. Validating that the access key entered is correct
2. Displaying a better error message than Not Found

Please let us know if you still run into problems!
