### ISSUE TITLE
Server API: Stability on Heavy Loading

### ISSUE THREAD

**Issue by overminder** [Microsoft/code-push#316]
We use `react-native-code-push` in our production app and it works great. As the CodePush service is still in the beta status, I'm a bit concerned about its behavior on peak load conditions.

We will hold an in-app event in the coming weeks. Due to the large amount of the users that opens the app during that time (since the way that we use this library is that we call `codePush.sync()` at the app startup time), the app might put a heavy pressure (~2000 peak RPS for several seconds) on the CodePush server API (`https://codepush.azurewebsites.net/updateCheck` and `https://codepush.blob.core.windows.net/storagev2/`).

Will the blob storage keep up with this kind of loading? We are even considering doing a load test against the above API endpoints by ourselves - is that acceptable?

Thanks in advance.

**Comment by overminder** [comment]
Just found #151 which seemed to suggest that anything below 1M RPS should be fine, and that's three orders of magnitudes higher than our need. I suppose we don't need to worry about this..

**Comment by silhouettes** [comment]
Hi @overminder, thank you for contacting us about this. Supporting higher loads is a matter of scaling resources for us - we can indeed support 2000 RPS, ideally with advanced notice. Before we do this though, I'd just like to make sure that this requirement is what is actually needed - what kind of app are you developing, and why do you expect 2000 requests per second (as opposed to 2000 users distributed over a time period)? Are you expecting app downloads to occur during this peak period (i.e. 2000 concurrent blob downloads)?

We can support this, but as a side note if it helps as far as reassurance, even in the worst case scenario that a server outage happens, there should be no user-facing error in your app (assuming silent mode). It would simply mean that no update is detected/applied until the next successful update check.

If there is any part of the details that you want to keep private, or if you'd still like to perform your own load testing, you are also welcome to respond via email at codepush@microsoft.com.

**Comment by silhouettes** [comment]
Closing this issue as we communicated via email and the event proceeded without issue :) For anyone else with similar RPS requirements, please contact us!
