### ISSUE TITLE
New Website Logo: [insert name]

### ISSUE THREAD

**Issue by JayElPo** [Microsoft/code-push#317]
Please fill the following out:

- Name: Cdiscount
- Homepage (or app store) url: https://itunes.apple.com/fr/app/cdiscount/id398364165
- Brand Guidelines/Licensing: http://www.cdiscount.com
- Logo: https://lh3.googleusercontent.com/I4tSLeMEcdJ4e0LjTIxTD3pHG668JfQ88Y1RbSTJyvEbCzSJLVkCf6ZveJtUZ6ufkcU=w300-rw

> Example:
>
> Name: Microsoft
> Homepage url: https://microsoft.com
> Brand Guidelines/Licensing: https://www.microsoft.com/en-us/legal/intellectualproperty/trademarks/usage/logo.aspx
> Logo: https://news.microsoft.com/microsoft-news-center-photos/msft_logo_rgb_c-gray/

**Comment by silhouettes** [comment]
Apologies for the slow response! This seems to be a duplicate of #330, so I will close this one and resolve the other one. Do you have a preference for linking to the Play store or the iTunes store? We will show the link to the Play store in the meantime.
