### ISSUE TITLE
Updated Showcase Logo for Fixt

### ISSUE THREAD

**Issue by esauter5** [Microsoft/code-push#318]
Hi, we are already in the CodePush showcase, but would greatly appreciate it if you could update our logo as it has changed slightly.

Name: Fixt
Logo: http://a5.mzstatic.com/us/r30/Purple62/v4/7f/b3/66/7fb366c4-79fd-34e1-3037-ffc02d8a93f7/icon350x350.png

Thanks!

**Comment by silhouettes** [comment]
My sincere apologies for the slow response! We added your logo to our showcase last week. I hope you're enjoying CodePush!

**Comment by esauter5** [comment]
Thanks @silhouettes!
