### ISSUE TITLE
 Source URL is not in white list: 'https://codepushupdates.azureedge.net/**'

### ISSUE THREAD

**Issue by kinglionsoft** [Microsoft/code-push#319]
Today,  I commit a new release. App does not update, and logs show:

`FileTransfer: Source URL is not in white list: 'https://codepushupdates.azureedge.net/***`

I config the access urls as [http://microsoft.github.io/code-push/docs/cordova.html#link-2](http://microsoft.github.io/code-push/docs/cordova.html#link-2) said:
```
<access origin="https://codepush.azurewebsites.net" />
<access origin="https://codepush.blob.core.windows.net" />
```

Have you changed the host of api?

**Comment by silhouettes** [comment]
Hi @kinglionsoft, I'm so sorry about this. We rolled out a CDN (at `https://codepushupdates.azureedge.net`) to improve performance for all of our users, but we had not accounted for the fact that some of our users use a whitelist.

We have deployed a change to the server to revert this - you should see this within an hour from now. The CDN URL will now only get sent if we detect a newer SDK version than the ones currently released, and we will update the docs before we release a new SDK version.

Please let me know if this solved the issue for you, and if there's anything else we can do.

**Comment by ingageco** [comment]
Could the Content Security Policy meta tag setting also affect this? If so, why would the push work on android and the iOS sim, but not iOS production devices?

**Comment by cloudkay** [comment]
Got. Thanks.

**Comment by kinglionsoft** [comment]
I've added the new HOST to the white list, and the SYNC works fine. 
Thanks.

**Comment by af-inf** [comment]
Hello,

We white listed these 3 URLs on a hotel WIFI admin (to test if a react native app can access the internet without WIFI authentication) but unfortunately the code push did not happen. Should we white list something more?

**Comment by sergey-akhalkov** [comment]
Hi @af-inf, thanks for reaching us. Currently, we only have 3 URLs that you need to add to white list:
```xml
<access origin="https://codepush.azurewebsites.net" />
<access origin="https://codepush.blob.core.windows.net" />
<access origin="https://codepushupdates.azureedge.net" />
```
Please let me know if you have any questions.

**Comment by ajwhite** [comment]
We have some customers that have some rigid networking rules and generally do IP whitelisting.

Are these hosts backed by static IPs that folks could whitelist? Or are those dynamic and not necessarily consistent?

**Comment by sergey-akhalkov** [comment]
Hi @ajwhite, thanks for reaching us.
1. OUTBOUND IP ADDRESSES for https://codepush.azurewebsites.net - `23.101.204.168,23.101.207.119,23.101.205.109,23.101.198.154`
2. Regarding https://codepush.blob.core.windows.net and https://codepushupdates.azureedge.net - code-push-services location is West US, so you can download [Microsoft Azure Datacenter IP Ranges](https://www.microsoft.com/en-us/download/details.aspx?id=41653) and add IP addresses from `<Region Name="uswest">`

Please see [this article ](https://blogs.msdn.microsoft.com/waws/2017/02/01/how-do-i-determine-the-outbound-ip-addresses-of-my-azure-app-service/) for more details and let me know if you have any questions.
