### ISSUE TITLE
Bug when closing and opening app

### ISSUE THREAD

**Issue by alissonlinneker** [Microsoft/code-push#321]
Whenever I make updates to the app using the code-push, it redirects to a page:

file:///data/user/0/com.myapp/files/codepush/deploy/versions/e6cb4cdsc5e36226a7a3047dc217cafcc871a132f1c86b59c5fcdbd511b73802/www/index.html

But if I finalize the app and open it again, it returns to display the old version:

file:///android_asset/www/index.html

Why? How to fix?

**Comment by joomi** [comment]
I get the same issue
the app is redirected to 404 error page
It happens after a successful update.
How did you solve it?
