### ISSUE TITLE
[Error]  The specified resource does not exist.

### ISSUE THREAD

**Issue by nirajbrn** [Microsoft/code-push#322]
After login to code push, Trying to run any command (like : code-push whoami), getting following error:
[Error]  The specified resource does not exist.
RequestId:afa89d97-0002-0085-3410-1346c8000000
Time:2016-09-20T07:24:45.9351835Z

**Comment by silhouettes** [comment]
Could you try logging out and then in again? This kind of behavior is possible if the login key was pasted incorrectly when logging in (we will work on improving the error message).

If that doesn't work, could you email codepush@microsoft.com with your registered email address?

**Comment by silhouettes** [comment]
@nirajbrn, are you still seeing this? In the mean-time, I've fixed our error messages, so hopefully you won't see that specific error again.

**Comment by ethantran** [comment]
@silhouettes I am getting this error and sent an email about it.

**Comment by nirajbrn** [comment]
I was getting this error because, some one has re-logged to Code push account and access-key got changed. So, replace your old access key with one. Error will get resolved.
