### ISSUE TITLE
404 error page

### ISSUE THREAD

**Issue by joomi** [Microsoft/code-push#323]
I have an Angular 2 app wrapped with Cordova
When I update the app with code-push (the index.html is being moved from the original "file:///android_asset/www/" location and the base url tag is pointing to the wrong location)
The Angular router is not working correctly now.

Is there a way to update the files in the original location?

**Comment by silhouettes** [comment]
Hi @joomi, do you mind closing this issue and filing it on the CodePush Cordova repo? https://github.com/Microsoft/cordova-plugin-code-push
