### ISSUE TITLE
Cannot upload release bundle, "502 - Web server received an invalid response while acting as a gateway or proxy server."

### ISSUE THREAD

**Issue by silhouettes** [Microsoft/code-push#326]
(This issue was moved from https://github.com/Microsoft/react-native-code-push/issues/528, originally filed by @Ranatchai)

![screen shot 2559-09-25 at 10 03 06 pm](https://cloud.githubusercontent.com/assets/5508501/18816091/130af7f4-836c-11e6-9d76-20e7902c99c9.jpg)
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

* react-native-code-push version: 1.14.6-beta
* react-native version: 0.32.0
* iOS/Android version: iOS10
* bundle size after zip: 25 MB
* Repro steps:

1. run `code-push release-react [appName] ios -d Production`
2. finish bundle and start upload
3. stuck at 9% (sometime at 10%)

**Comment by silhouettes** [comment]
@Ranatchai - that's very unusual, and I'd like to get to the bottom of this. Could you try again one last time, and if it still fails, could you email us at codepush@microsoft.com with the following details?

- Your deployment key
- Approximate date/time that it failed for you
- Anything you're willing to share with us about your upload (e.g. your source, or the .jsbundle, or the final .zip)

I'll personally look through the server logs and/or try to reproduce it for you.

**Comment by opula** [comment]
Hi there,

I too am having the same issue.  Mine is with Cordova.  I updated to 1.12.5-beta but still the same.

**Comment by silhouettes** [comment]
@opula - I'm unable to reproduce this. Do you mind emailing us the same information?

**Comment by Ranatchai** [comment]
@silhouettes @opula 
I've found the solution when i try to get deployment key for you. it said
`"[Error]  The session or access key being used has expired, please run "code-push login" again. If you are on an older version of the CLI, you may need to run "code-push logout" first to clear the session cache."`

then i just run "code-push logout" then "code-push login" again then i can upload bundle success.

**Comment by silhouettes** [comment]
Thank you!! I will verify this in a few days, and if so, I'll try to improve the error message on releases when your session has expired.

@opula - thanks so much for the email. I will get to it in a few days (we are tremendously back-logged), but in the meantime, could you verify if this is the same issue that you faced? (if you run `code-push deployment ls`, and it succeeds, and then when you run `code-push release-cordova`, it fails, then it's a different problem)

**Comment by opula** [comment]
@Ranatchai Thanks so much. This worked perfectly!

**Comment by maxim-pop** [comment]
The issue was fixed on CLI side.
