### ISSUE TITLE
Can't upload code push release

### ISSUE THREAD

**Issue by srossokha** [Microsoft/code-push#328]
I can't upload release to the server, I'm received this issue:

Upload progress:[===========                                       ] 21% 13.7s[Error]  <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>502 - Web server received an invalid response while acting as a gateway or proxy server.</title>
<style type="text/css">

</style>
</head>
<body>
<div id="header"><h1>Server Error</h1></div>
<div id="content">
 <div class="content-container"><fieldset>
  <h2>502 - Web server received an invalid response while acting as a gateway or proxy server.</h2>
  <h3>There is a problem with the page you are looking for, and it cannot be displayed. When the Web server (while acting as a gateway or proxy) contacted the upstream content server, it received an invalid response from the content server.</h3>
 </fieldset></div>
</div>
</body>
</html>

**Comment by silhouettes** [comment]
Hi! Please see #326 - your session has likely expired and you need to log out and log in again.

Please let me know if this worked for you. I'll keep this issue open until we make the CLI release that will give a clearer error message.

**Comment by silhouettes** [comment]
We have released a new version of the CLI that fixes the error message. Please let me know if you still run into issues!

**Comment by slorber** [comment]
login again worked for me.
Had the issue today, with no error message upload stopped at 13% on iOS/Android

**Comment by srossokha** [comment]
Yes, it works after login again! Thanks a lot!!!
