### ISSUE TITLE
CodePush service should use Cache-Control header

### ISSUE THREAD

**Issue by rozele** [Microsoft/code-push#329]
In react-native-windows, the NetworkingModule used to power XHR requests has a built-in caching mechanism.  When the CodePush client makes an `updateCheck` API request, the URI is constant over time with changing data from the service, but the service does not use a `Cache-Control` header to let the client know it should not cache the response.  The cached response prevents the app from ever detecting that an update is available (e.g., in the case that you use ON_APP_RESUME).  Fixing this bug would also fix https://github.com/Microsoft/react-native-code-push/issues/546

**Comment by silhouettes** [comment]
I will address this early next week probably, unless this is needed urgently, in which case please let me know!

**Comment by rozele** [comment]
This is not urgent, CodePush users on Windows can still receive updates on app restart, but it's blocking for those who wish to check for updates on app resume or manually.  Thanks!

**Comment by silhouettes** [comment]
This is now live on the service. I'm closing this issue - please close the one on the react-native repo (Microsoft/react-native-code-push#546) if you think it's resolved!

**Comment by rozele** [comment]
Thanks @silhouettes!  I'll test it out now.
