### ISSUE TITLE
New Website Logo: Cdiscount

### ISSUE THREAD

**Issue by JayElPo** [Microsoft/code-push#330]
Please fill the following out:

- Name: Cdiscount
- Homepage (or app store) url: https://play.google.com/store/apps/details?id=cdiscount.mobile
- Brand Guidelines/Licensing: https://en.wikipedia.org/wiki/Cdiscount
- Logo: http://lh3.googleusercontent.com/a9li2oZgpi3BN1rLLOPvxFtUe8PN8VI-nmwwclqh5Bjrt_EM4dkqjYnU7osL9tdj0w=w300-rw

**Comment by silhouettes** [comment]
My sincere apologies for the slow response! We added your logo to our showcase last week. I hope you're enjoying CodePush!
