### ISSUE TITLE
`release-react` should work if `react-native` is not a dependency in package.json

### ISSUE THREAD

**Issue by silhouettes** [Microsoft/code-push#331]
This was originally filed in https://github.com/Microsoft/react-native-code-push/issues/555.

Currently, `release-react` will scan the package.json of the pwd, and abort if a `react-native` dependency is not found. However, as @scerelli mentioned:

> Usually, I put all dependencies into dev-dependencies because none are required for production since react-native will bundle what it's needed from imports. I suggest to walk even through the dev-dependencies

This issue has been encountered by one additional person in the past.

**Comment by panarasi** [comment]
@silhouettes Is there a reason we need to even look for this ? We could simply call `react-native bundle` and if react-native exists, regardless, we could publish it.

**Comment by silhouettes** [comment]
Two reasons I think:

1. We run `react-native` out of the node modules directory, I assume so that versioning is consistent.
2. It's important that the command is run out of the correct directory so that something unexpected isn't bundled.

Only two people have mentioned this though, so it's up to you if you think it's worth the effort.

**Comment by iageoghe** [comment]
@sergey-akhalkov, please add logic to also search search dev-dependencies if the initial search does not yield a `react-native` dependency.

**Comment by sergey-akhalkov** [comment]
Hi @iageoghe, I've published PR https://github.com/Microsoft/code-push/pull/475, so I'm closing this for now, please feel free to reopen and let me know if you have any questions or see any issues.

**Comment by G3z** [comment]
I currently have react native as a sub_dependency so it does not appear in the package.json.
react-native is in the correct `node_modules` folder but not in the package.json
