### ISSUE TITLE
Can't patch release to 100% using management SDK

### ISSUE THREAD

**Issue by daniel-beard** [Microsoft/code-push#332]
- Using the management SDK, I try to patch a release to `100%` that is at `99%` already, I get this error:

```
{"message":"Rollout value must be greater than \"99\", the existing value.","statusCode":409}
```

- I can patch to any number up to 100%, but not 100% itself.
- Code I'm using in JS: 

```
 return this.codePush.patchRelease(this.app, 
                this.from_env, 
                undefined, 
                { rollout: this.percentage });
```

- Note: I can however, release to `100%` when using the CLI: 
```
code-push patch TestApp TestEnv --rollout 100
```

**Comment by silhouettes** [comment]
The server expects a number from 1-100. Is it possible that the value of `this.percentage` is 1 here, instead of 100?

**Comment by daniel-beard** [comment]
@silhouettes double checked, the value is `100`. :/

**Comment by silhouettes** [comment]
I can't seem to reproduce this :( here is what I did:

```
code-push release-react a android --rollout 99
// From node:
codePush.patchRelease("a", "Staging", undefined, { rollout: 100 }).done();
```

I checked the deployment history between each command and it was as expected. Does it reproduce for you if you replace all of the variables in your example above with literals?

Note that the CLI just calls into the same management SDK: https://github.com/Microsoft/code-push/blob/master/cli/script/command-executor.ts#L1090

**Comment by daniel-beard** [comment]
@silhouettes thanks for the quick investigation. I'll try and reproduce again tomorrow and see if literals cause the same issue. Thanks!

**Comment by silhouettes** [comment]
Thanks, please keep me updated!

**Comment by daniel-beard** [comment]
@silhouettes this was user error. The type was a string rather than a number. Thanks for looking, this issue is invalid.

**Comment by silhouettes** [comment]
Ahh, that makes sense. Glad we could figure it out!
