### ISSUE TITLE
Can not perform rollback if deployment name is same as CodePush CLI command

### ISSUE THREAD

**Issue by ca057** [Microsoft/code-push#339]
As stated in the title, I want to perform a rollback of an code-push update. Apparently my deployment name is "release", so it is the same as the code-push command.

**Actual Behaviour**
If I run `code-push rollback <AppName> release`, it does not perform the rollback but instead shows me usage guide for the release command.

**Expected Behaviour**
If I run the command, it interprets "release" as deployment name and not as new command.

My code-push version is `1.12.6-beta`.

**Comment by max-mironov** [comment]
Hello @ca057 . fix for your issue is added as pull request to code-push repo at https://github.com/Microsoft/code-push/pull/360. Also you can try to update directly from my fork repo https://github.com/max-mironov/code-push/tree/update_yargs_to_6.5.0 if needed. Thank you!

**Comment by sergey-akhalkov** [comment]
Closing this due to fix #360 has been merged, please feel free to reopen if you see any issues or have any questions.
