### ISSUE TITLE
Exclude (or include specified) files with code-push release command

### ISSUE THREAD

**Issue by MrWillow** [Microsoft/code-push#342]
We run into an issue that our complete www directory is large (70 MB).
Most size is taken up by mp3 files.
Up till now we have been experiementing with code-push **release-cordova** ....

I can think of 2 solutions which I cannot implement.

Solution 1: Exclude a directory (or file type) in a code-push release, so the existing mp3-files stay on the devices, and we only update some js-files.
Is that possible?

Solution 2: Specify which files are released. 
This SHOULD be doable with "code-push release" instead of "code-push release-cordova", according to the manual.
eg:
code-push release myApp-Android "./platforms/android/assets/www/js/main.min.js"  "*" --deploymentName "Production" --description "Only js file" --mandatory

But that always end with error, like:
(via code-push debug android)

---

[02:06:52] Checking for update.
[02:06:53] An update is available. {"appVersion":"1.0.8","deploymentKey":"---Mydeploymentkey---","description":"versie","downloadUrl":"https://codepush.blob.core.windows.net/storagev2/pathremoved","isMandatory":true,"label":"v16","packageHash":"a754acc782c47bbce295fa187345a10444a105f271df5da1e3a8c91de654d9a4","packageSize":7,"failedInstall":false}
[02:06:53] Awaiting user action.
[02:06:57] Downloading update
[02:06:59] Package download success: {"deploymentKey":"---Mydeploymentkey---","description":"versie","label":"v16","appVersion":"1.0.8","isMandatory":true,"packageHash":"a754acc782c47bbce295fa187345a10444a105f271df5da1e3a8c91de654d9a4","isFirstRun":false,"failedInstall":false,"localPath":"cdvfile://localhost/files/codepush/download/update.zip"}
[02:07:02] Installing update
[02:07:06]  Could not unzip package. -1
[02:07:06] An error occurred during sync.

---

We don't seem to be able to release a single file, without forcing a download of 70 MB on the user.

What to do?

**Comment by frontweb** [comment]
@MrWillow did you find a solution to these scenarios?

**Comment by silhouettes** [comment]
@MrWillow @frontweb - although we ask that you upload your whole www directory with each release, the server performs file-based diffing, so only updated and new files are sent to client devices. In other words, we don't think you should have to perform the task of manually specifying which tasks to update as that has been automated on the server. Does this make sense?

**Comment by frontweb** [comment]
@silhouettes thanks for the clarification. So if I get it right, a file that exists in the /www folder at install time won't be deleted on a CodePush update if that file is not in the CodePush update, right?

**Comment by silhouettes** [comment]
You need to upload that file from the CLI to server regardless (or it will be deleted), but that file will not be sent from the server to your app if the app already has it. Hopefully I explained that well?

**Comment by frontweb** [comment]
@silhouettes yes, the explanation is clear now. thanks

**Comment by sergey-akhalkov** [comment]
Closing this, please feel free to reopen if needed.

**Comment by kbrownlees** [comment]
I have the use case where we store the env variables in javascript code. Things like the api url to call (staging or production), these are generated at build time. Since those will be updated in a code push update there is no way to 'promote' a build without being able to exclude that file. Am I missing something or is that simply not supported by codepush?

**Comment by arunharidas** [comment]
Question. If I put a XML file inside the android folder will codepush include it in the next push? If it won't this feature can be attained like that, right?

**Comment by kbrownlees** [comment]
@evillemez I managed to work around this by having a different index.html per build (eg index-staging.html), where each index loads the appropriate environment settings. The downside is you have to deploy all the index and configuration variations in every code push bundle so it makes the build system a bit more complex.

**Comment by chenyu1990** [comment]
I have multiple advertisers promoting user installations. I need to use the variables of the same project to distinguish which installation package belongs to which advertisers. If variable files cannot be excluded, I need to upload multiple copies
