### ISSUE TITLE
New Website Logo:天弘爱理财

### ISSUE THREAD

**Issue by debugcheck** [Microsoft/code-push#344]
Please fill the following out:

- Name: Tianhong Asset Management Co. , Ltd
- Homepage (or app store) url: http://www.thfund.com.cn/
- Brand Guidelines/Licensing: (or anything we need to know before using your logo)
- Logo: (svg if possible, pngs over 300x300px with transparent backgrounds are also acceptable)

> Example:
>
> Name: Microsoft
> Homepage url: https://microsoft.com
> Brand Guidelines/Licensing: https://www.microsoft.com/en-us/legal/intellectualproperty/trademarks/usage/logo.aspx
> Logo: https://news.microsoft.com/microsoft-news-center-photos/msft_logo_rgb_c-gray/

**Comment by timzaak** [comment]
@debugcheck   Is it fast enough in China? I mean because of GTW, this may cause network failure. If your app solve this problem, or the problem does not exist?

**Comment by debugcheck** [comment]
@timzaak  Yes,  in China,  App Store： https://itunes.apple.com/us/app/tian-hong-ai-li-cai-yu-e-bao/id1132006561?l=zh&ls=1&mt=8

**Comment by timzaak** [comment]
@debugcheck I want to know how to solve server network problem if it is ok to tell？

如果可以的话，我能否知道是怎么解决服务器端网络问题的吗？

**Comment by max-mironov** [comment]
@debugcheck - hi, could you please also provide us with logo so we can add this to our http://microsoft.github.io/code-push/community/friends.html page?

**Comment by max-mironov** [comment]
Closed for now, please feel free to reopen if needed.
