### ISSUE TITLE
Add error codes for server errors during release

### ISSUE THREAD

**Issue by SoHotSoup** [Microsoft/code-push#345]
Hi! Could you please add some error codes in errors that may happen while using CLI or SDK? For example, I want to handle this error:
```
{ message: 'The uploaded package was not released because it is identical to the contents of the specified deployment\'s current release.' }
```
And I don't want to match a handler dependent on an error message, it would be more error prone if there would be some code on each error.

 I'm using these versions:
```
"code-push": "^1.10.0-beta",
"code-push-cli": "1.12.3-beta",
```

**Comment by silhouettes** [comment]
Hi @SoHotSoup, would one of the following two options help solve your current situation?

1. The `--noDuplicateReleaseError` [flag](https://github.com/Microsoft/code-push/tree/master/cli#releasing-updates-general) in the CLI, which converts it from an error into a warning.
2. The latest [management SDK](https://github.com/Microsoft/code-push/tree/master/sdk), which indeed has [error codes](https://github.com/Microsoft/code-push/tree/master/sdk#error-handling)

**Comment by SoHotSoup** [comment]
Hey @silhouettes! Both would work for me! Thank you for the fast response!
