### ISSUE TITLE
Old Appversion in responce, App is not updating

### ISSUE THREAD

**Issue by vasani-arpit** [Microsoft/code-push#350]
when I fire up `codePush.sync(null,{installMode: InstallMode.IMMEDIATE});` from the console
it sends the following ajax request having version 7.1.8 in parameter
![code-push_issue_li 2](https://cloud.githubusercontent.com/assets/6497827/21050115/cc918a8c-be3e-11e6-8cb1-7e3ec04e8e62.jpg)

but in response I am getting old version.

![image](https://cloud.githubusercontent.com/assets/6497827/21049885/6399ad80-be3d-11e6-9307-3b12b0ef416d.png)

and in console I am getting
![image](https://cloud.githubusercontent.com/assets/6497827/21050265/b5914e7a-be3f-11e6-8f82-af496770642f.png)

although it says app is up to date but it's not.

here is my deploy history
![image](https://cloud.githubusercontent.com/assets/6497827/21050431/b0223926-be40-11e6-9047-ff6d911c1bfb.png)

Please Help. Thanks in Advance.

**Comment by max-mironov** [comment]
Hi @vasani-arpit, I've tried to reproduce the case you described above from scratch but with no success. Do you have a chance to verify your issue one more time with latest version of plugin/cli and let us know the results?

**Comment by vasani-arpit** [comment]
@max-mironov Thanks for looking into my issue.
I'll update plugin and cli and let you know. 

Thanks.
