### ISSUE TITLE
Which is the last react-native version supported?

### ISSUE THREAD

**Issue by benjaminb10** [Microsoft/code-push#353]
Hi, which is the last react-native version supported?

**Comment by vladimir-kotikov** [comment]
Hi @benjaminb10, please take a look at the compatibility table [here](https://github.com/Microsoft/react-native-code-push#supported-react-native-platforms)

**Comment by benjaminb10** [comment]
Thanks, 'cause this table is not up to date, seen here: http://microsoft.github.io/code-push/docs/react-native.html

![screenshot_2016-12-19 12 51 42_vkkmk1](https://cloud.githubusercontent.com/assets/2952678/21311923/fcae41da-c5e9-11e6-92d7-2d8d0ac2cf39.png)

**Comment by ms88privat** [comment]
Yes, could you please evaluate and update the table? Thanks for the effort.

**Comment by sergey-akhalkov** [comment]
@ms88privat, the website docs has been updated, thanks! Also in the future we'll probably have an automatic synchronization between the website and GitHub docs: https://github.com/Microsoft/react-native-code-push/pull/681
