### ISSUE TITLE
Description links to a parked domain

### ISSUE THREAD

**Issue by fson** [Microsoft/code-push#361]
The description of this repository links to codepush.tools, which is a parked domain.

---

<img width="885" alt="screen shot 2017-01-02 at 11 25 30" src="https://cloud.githubusercontent.com/assets/497214/21586871/6b22ceac-d0de-11e6-83ca-05ab9093853d.png">

---

<img width="656" alt="screen shot 2017-01-02 at 11 26 03" src="https://cloud.githubusercontent.com/assets/497214/21586873/6f2b1126-d0de-11e6-90cb-244629f9f926.png">

**Comment by vladimir-kotikov** [comment]
Thanks for reporting! [codepush.tools](http://codepush.tools) is now working
