### ISSUE TITLE
New Website Logo: Lusus

### ISSUE THREAD

**Issue by RemeJuan** [Microsoft/code-push#363]
Please fill the following out:

- Name: Lusus: Cycling Database
- Homepage (or app store) url: https://play.google.com/store/apps/details?id=com.lusus
- Brand Guidelines/Licensing: N/A
- Logo: https://drive.google.com/open?id=0B482XQosa0-UUWxUSDRFNmxlSDQ

**Comment by max-mironov** [comment]
@RemeJuan thanks, your logo has been added!
