### ISSUE TITLE
Is codepush still in active development? 

### ISSUE THREAD

**Issue by emmanuelbuah** [Microsoft/code-push#366]
Hi,

Thanks for all the hard work. I'd like to know if codepush is still in active development. The last blog post was April 16. There's about 6 PR etc. Any update on this ticket will be helpful. Thanks.

**Comment by ryanjsalva** [comment]
Yes, absolutely. The service is largely mature at this point, so most commits from the last 4 months have been either (a) bug fixes or (b) changes required by new versions of the React Native framework. 

I gave a talk about [the future of CodePush at Reactive Conf](https://youtu.be/OmuOWbsQLmc) just two months ago. Short version: the next major evolution will be integration with crash reporting and analytics.

**Comment by emmanuelbuah** [comment]
@ryanjsalva  Thanks a lot. Kudos for pushing ahead. Looking forward to taking codepush for a spin. Cheers!

**Comment by slorber** [comment]
Hey @ryanjsalva great to hear

Just wondering: why not all releases are published on npm?

**Comment by axemclion** [comment]
@slorber We just published the latest release for react native on codepush with 0.40. Are there other artifacts that are not published on npm ?

**Comment by slorber** [comment]
Hi,

I don't remember why I was posting here, I'm mostly a cordova codepush user so I may have replied to the wrong repo :)

**Comment by panarasi** [comment]
Thanks. Closing the issue.
