### ISSUE TITLE
Will code push support million requests ?

### ISSUE THREAD

**Issue by aravind12345** [Microsoft/code-push#367]
Does the bundle will be stored in code push server? in that case will it can handle million request? what is the latency ?

**Comment by silhouettes** [comment]
@aravind12345 - yes, the bundle is stored on the CodePush server and distributed via a CDN. The latency will depend on where in the world you are located and where our CDN nodes are - from the US we expect it to be 100 ms or less. I'm not sure what you mean when you say a million requests - we have easily served many millions of requests, but what time interval are we talking about here? How many daily/monthly active users do you have, or alternatively what is your peak requests per second?

For example, we have reached 2K RPS before and can likely scale further, it is a matter of understanding what your needs are.

**Comment by aravind12345** [comment]
@silhouettes  we have 700k daily active users and monthly 2M active users.  Our peak request per second would reach 5K RPS.

**Comment by silhouettes** [comment]
Hi @aravind12345, @maxim-pop and I have discussed this and we're comfortable supporting this load, we'll just need to scale out beforehand. Before we do this, could you email us at codepush@microsoft.com with some more details:

- What is your company or app?
- When do you intend to start?

**Comment by silhouettes** [comment]
Hi @aravind12345, we have not heard back from you. Did you still have this RPS requirement?

**Comment by aravind12345** [comment]
we already released into production.  our app gas reached 100k updates
already

**Comment by silhouettes** [comment]
Okay no worries! Clearly we are able to handle the load, and our monitoring shows no issues. Feel free to contact us if you have any other scalability concerns.
