### ISSUE TITLE
Optional release for new binary version converted to mandatory?

### ISSUE THREAD

**Issue by adbl** [Microsoft/code-push#368]
We are in the process of integrating with Code Push, exciting!

I'm reading about "mandatory conversion" in https://github.com/Microsoft/code-push/tree/master/cli#mandatory-parameter

The upgrade reasoning makes sense. However, say that we have: 
- Binary version `A`, with updates:
   - `v1` optional
   - `v2` mandatory
- Binary version `B` (which in this case is released after `U2` and thus will contain it), with updates:
  - `v3` optional
  - `v4` optional

Will `v3` get converted to mandatory even though it is (perhaps strictly) targeting a new binary version? If so, what can I do to avoid that?

**Comment by adbl** [comment]
We want to avoid causing a bad UX (by restarting the app due to mandatory install), if the update is not needed.

**Comment by sergey-akhalkov** [comment]
@adbl - hi!
I've tried to reproduce provided use case and got following deployment history:
![image](https://cloud.githubusercontent.com/assets/4928157/22104900/7df87d66-de52-11e6-8c51-86f99c877cf6.png)
According to `getUpdateMetadata` method output 
![image](https://cloud.githubusercontent.com/assets/4928157/22104941/ad976aa0-de52-11e6-92a3-086eaff447a0.png)
server does not convert optional release `v3` to mandatory in case optional release belongs to another `App Version`.
To make sure if `isMandatory` property is really represents managed by CodePush server value I've created following deployment history:
![image](https://cloud.githubusercontent.com/assets/4928157/22106596/7ddc05ac-de5a-11e6-8d95-51c4ebaeb02b.png)
and got following `getUpdateMetadata` method output:
![image](https://cloud.githubusercontent.com/assets/4928157/22106609/957d8564-de5a-11e6-8870-e0c135e04af7.png)

**Comment by adbl** [comment]
Excellent, thanks!
