### ISSUE TITLE
Feature Request: Ability to execute custom command after react-native build

### ISSUE THREAD

**Issue by ThisIsMissEm** [Microsoft/code-push#371]
One of the things we do as part of releasing a new version of our application (react-native powered) is to upload sourcemaps and compiled javascript to Sentry, so that we can demangle stacktraces.

We release our application using:

```
code-push release-react OurApp ios -m -d production
```

(It works great!)

However, we currently have to build our application multiple times just to get the correct data to ship to sentry. I can see that `code-push release-react` does support source maps, so what I'm wanting is a hook which is the execution of an environment variable pre-push, e.g.,

```
CODE_PUSH_PRERELEASE=`scripts/sentry.sh
```

Which is executed at this line, just before `release`: https://github.com/Microsoft/code-push/blob/master/cli/script/command-executor.ts#L1284

It should be called with the `outputFolder`, `appVersion`, `platform`, `bundleName` and `sourcemapOutput` values; This would allow our sentry script to look something like:

```
#!/bin/bash

# immediately fail if an error occurs
set -e

# always execute in the context of the code-push build directory:
cd "$(dirname "$1")"

VERSION=$2
ORGANIZATION_SLUG="my-org"
PROJECT_SLUG="my-app-$PLATFORM-$STAGE"

echo "Creating Release $PROJECT $VERSION"

curl https://sentry.io/api/0/projects/$ORGANIZATION_SLUG/$PROJECT_SLUG/releases/ \
  -X POST \
  -H "Authorization: Bearer $TOKEN" \
  -H 'Content-Type: application/json' \
  -d "{\"version\": \"$VERSION\"}"

echo -e "\nUploading Bundle"

curl https://sentry.io/api/0/projects/$ORGANIZATION_SLUG/$PROJECT_SLUG/releases/$VERSION/files/ \
  -X POST \
  -H "Authorization: Bearer $TOKEN" \
  -F file=@$4 \
  -F name="/$4"

echo -e "\nUploading Bundle Sourcemap"

curl https://sentry.io/api/0/projects/$ORGANIZATION_SLUG/$PROJECT_SLUG/releases/$VERSION/files/ \
  -X POST \
  -H "Authorization: Bearer $TOKEN" \
  -F file=@$5 \
  -F name="/$5"
```

Note: `$STAGE` and `$TOKEN` are environment variables from the environment in which the `code-push` command was run, that is, it's environment passes through to the child command, rather than the child command being executed in a completely pristine environment.

Essentially the script changes directory into the build output directory, and then uploads a bunch of files to sentry for a specific release.

By having this hook, it'll enable us to streamline our deployments, cutting our the bundle build just so that we can upload it to sentry.

**Comment by sergey-akhalkov** [comment]
@ThisIsMissEm, I've recently implemented `--outputDir=PATH` parameter https://github.com/Microsoft/code-push/pull/382 that needed to specify folder PATH where assets, js bundle and sourcemap files will be written. Please let me know if it works for you.

**Comment by sergey-akhalkov** [comment]
@ThisIsMissEm, just a friendly ping.

**Comment by ThisIsMissEm** [comment]
@sergey-akhalkov this should work for us; will have to look at it later though.

**Comment by sergey-akhalkov** [comment]
@ThisIsMissEm, thank you, closing this for now, please feel free to reopen if needed.
