### ISSUE TITLE
New Website Logo: Axsy

### ISSUE THREAD

**Issue by csun-axsy** [Microsoft/code-push#372]
Please fill the following out:

- Name: Axsy
- Homepage (or app store) url: https://www.axsy.com/
- Brand Guidelines/Licensing: None
- Logo: PNG attached

Thanks.
![axsy logo - square](https://cloud.githubusercontent.com/assets/25183247/22035491/2851b066-dcbe-11e6-9fbb-ced7f03c786f.png)

**Comment by max-mironov** [comment]
@csun-axsy thanks, your logo has been added!
