### ISSUE TITLE
I cannot log to my account anymore

### ISSUE THREAD

**Issue by jsappme** [Microsoft/code-push#374]
$ code-push login

I click on Microsoft Personal and it redirects me to:
https://codepush-management.azurewebsites.net/auth/callback/microsoft?code=M1f4f8195-c66c-7400-b9b2-6b8216f5e80f&state=RqxOE72urGumMFtTYrDeWTAk

giving me an Internal Server Error

**Comment by sergey-akhalkov** [comment]
@jsappme, are you still not able to log in? Could you please look at Internal Server Error in developer tools and check console log if it contains any details (exception message or probably stack trace)? Also it would be helpful if you could tell me your version of `code-push-cli` (just execute `code-push -v` command).
Just to clarify, what is the reason you tried to re-login (probably session expires or another machine is used to login)?

**Comment by axemclion** [comment]
@jsappme You may also have to update the CLI to the latest version. Can you please let us know if you are still having trouble ?

**Comment by bmwertman** [comment]
I'm just beginning to setup code-push and am seeing the same error. I initially set my app up with Hockeyapp and Fastlane. My Hockeyapp account shows that code-push has an active client token.

**Comment by sergey-akhalkov** [comment]
@bmwertman, could you please execute `code-push -v` command to let us know what version of `code-push-cli` is in use? Also it would be helpful if you could share us with "Internal Server Error" details - is there something else beside error message (probably console log output).

**Comment by bmwertman** [comment]
Yes, code-push version is 1.12.6-beta Here is a  screen shot of the error along with the console output.
![screen shot 2017-02-01 at 8 46 16 am](https://cloud.githubusercontent.com/assets/2573903/22511113/8f7cbaf6-e862-11e6-9b43-fd7b44c25381.png)

**Comment by bmwertman** [comment]
I should add; I deleted the token from Hockeyapp and closed my Visual Studio Team Services account that created the token in Hockeyapp. 

I actually started trying to use VSTS. But moved to Fastlane when I couldn't get my Cordova build working correctly on VSTS. 

I was thinking this may free up my app to generate a new authorization. But I was getting this same error before doing both of those things.

**Comment by silhouettes** [comment]
Hey @bmwertman, could you contact codepush@microsoft.com and send us the email associated with your account?

**Comment by bmwertman** [comment]
Yes, one second.

**Comment by bmwertman** [comment]
Sent.

**Comment by bmwertman** [comment]
@silhouettes were you able to find anything with the account associated with my email?

**Comment by silhouettes** [comment]
@bmwertman - Apologies, there is a lot on my plate at the moment, I will try my best to update you within a day :)

**Comment by bmwertman** [comment]
Cool, just checking in. Thanks!

**Comment by samuelplaymore** [comment]
@silhouettes Sorry to bother you, I encountered the same error. I cannot login to my account and got the same "Internal error". I have just sent my account information to the email codepush@microsoft.com . Would you mind to have a look? thanks.

**Comment by axemclion** [comment]
@samuelplaymore We will look at it. In the meantime, can you confirm that you are using the latest version of the CLI ?

**Comment by samuelplaymore** [comment]
Hi,

yes. And I tried 'npm update'.
my version now is "1.12.6-beta".

Thanks.

**Comment by samuelplaymore** [comment]
@axemclion @silhouettes  Sorry to bother you. My update is urgent, would you mind to have a look?
thanks for your help.

**Comment by silhouettes** [comment]
I believe @sergey-akhalkov is investigating this!

**Comment by sergey-akhalkov** [comment]
Yes, I'm working on it, will let you know if I have any results.

**Comment by sergey-akhalkov** [comment]
Seems like there is something wrong with CodePush app permissions or with Microsoft account, because while investigating CodePush management server logs I've found, that there are exceptions with the following content:
```json
Couldn't get an email address from the microsoft OAuth provider for user
{"id":"somevalue","displayName":null,"name":{"familyName":null,"givenName":null},"emails":[],"photos":[{"value":"https://apis.live.net/v5.0/somevalue/picture"}],"provider":"windowslive","_raw":"{\r \"id\": \"somevalue\", \r \"name\": null, \r \"first_name\": null, \r \"last_name\": null, \r \"gender\": null, \r \"emails\": {\r \"preferred\": null, \r \"account\": null, \r \"personal\": null, \r \"business\": null\r }, \r \"locale\": null\r}","_json":{"id":"somevalue","name":null,"first_name":null,"last_name":null,"gender":null,"emails":{"preferred":null,"account":null,"personal":null,"business":null},"locale":null}}
```
As for me I've got following:
```json
{"id":"160a122831b082b8","displayName":"Sergey Akhalkov","name":{"familyName":"Akhalkov","givenName":"Sergey"},"emails":[{"value":"v-seakha@microsoft.com","type":"account","primary":true}],"photos":[{"value":"https://apis.live.net/v5.0/160a122831b082b8/picture"}],"provider":"windowslive","_raw":"{\r   \"id\": \"160a122831b082b8\", \r   \"name\": \"Sergey Akhalkov\", \r   \"first_name\": \"Sergey\", \r   \"last_name\": \"Akhalkov\", \r   \"gender\": null, \r   \"emails\": {\r      \"preferred\": \"v-seakha@microsoft.com\", \r      \"account\": \"v-seakha@microsoft.com\", \r      \"personal\": null, \r      \"business\": null\r   }, \r   \"locale\": \"en_US\"\r}","_json":{"id":"160a122831b082b8","name":"Sergey Akhalkov","first_name":"Sergey","last_name":"Akhalkov","gender":null,"emails":{"preferred":"v-seakha@microsoft.com","account":"v-seakha@microsoft.com","personal":null,"business":null},"locale":"en_US"}}
```
It is really weird that `user` object has no values for properties except id property. So the Internal Server Error occurs due to `"emails": []` array is empty.

So guys, could you please try clean browser cookies, login your MS accounts, then open https://account.live.com/consent/Manage page and remove permissions for `codepush-management.azurewebsites.net` app? Then just try to run `code-push login` again and accept permissions request.
Please let me know if any changes.

**Comment by samuelplaymore** [comment]
@sergey-akhalkov thanks for your help. My problem was resolved. Btw, it was so strange that my basic information (i.e First Name and Last Name) were missed in the Microsoft Account. After filling the basic info, the "code-push login" worked properly. Thanks.

**Comment by sergey-akhalkov** [comment]
@samuelplaymore, great, thanks for the response! I've updated my comment to make sure basic info is filled.

**Comment by silhouettes** [comment]
Great work @sergey-akhalkov :) Seeing as this has not happened before this period, I'm wondering if something about Microsoft accounts changed (e.g. email addresses became optional, or some new way of generating accounts with no email was created). If possible, could you try to implement a fix on the service that does not throw an exception, and displays a more user friendly error message?

**Comment by sergey-akhalkov** [comment]
@silhouettes, got it, will do.

**Comment by sergey-akhalkov** [comment]
Closing this for now due to CodePush server has been updated to show the instruction that describes how to avoid the issue.
