### ISSUE TITLE
More informative error when login/logout is required

### ISSUE THREAD

**Issue by alexdunae** [Microsoft/code-push#375]
```
$ code-push -v
1.10.0-beta
```

When running `code-push release-react` the upload kept timing out with a server 500 error.  I eventually figured out that my session had expired and needed to logout and then login again.  Ideally there would have been a login/logout message instead of just timing out.

Thanks for Code Push -- it's great!

**Comment by sergey-akhalkov** [comment]
@alexdunae - hi, thank you!
This issue was fixed in https://github.com/Microsoft/code-push/releases/tag/v1.12.6-beta, so you need just to run `[sudo] npm install code-push-cli@latest -g` command to upgrade your `code-push` version.

**Comment by alexdunae** [comment]
Shoot -- sorry about that. Thanks for reply.
