### ISSUE TITLE
Add `bundleOutput` flag to release-react to save generated bundle into specified location

### ISSUE THREAD

**Issue by vladimir-kotikov** [Microsoft/code-push#376]
> @benedicthsieh commented on Dec 19, 2016
> We'd like to get the code bundle that is generated by release-react so that we can upload it to Sentry. We see that the bundle is put into a temporary directory, but it seems like that directory is cleaned up once the release is done. Is there a way to either retrieve the bundle afterwards (maybe with a code-push CL command), or preserve the output bundle that's created by release-react?

Copied from https://github.com/Microsoft/react-native-code-push/issues/646

**Comment by axemclion** [comment]
I think we should save both the source map and the bundle at a specified location. This could simply be a flag, something like `--outputDir=`.

**Comment by silhouettes** [comment]
This shouldn't be difficult to do - maybe we could ask one of the vendors to do it if the feature is well-specced?

**Comment by sergey-akhalkov** [comment]
Closing this due to https://github.com/Microsoft/code-push/pull/382 has been merged.
