### ISSUE TITLE
Updated React Native version support

### ISSUE THREAD

**Issue by fungilation** [Microsoft/code-push#378]
RN is now at 0.40 (0.41 in a few days). While CodePush only supports up to 0.35 according to docs.

Can I/we get a heads up on when is updated RN support coming? Thanks.

Note that 0.40 breaks backward compatibility in linking, so there probably needs to be a a major version bump. With a minor version update for 0.39 perhaps?

**Comment by sergey-akhalkov** [comment]
@fungilation,  sorry for the inconvenience, you probably have faced with out of date docs on [codepush.tools](codepush.tools) website, for now it should be fixed (I could see fresh version of [Supported React Native platforms](http://microsoft.github.io/code-push/docs/react-native.html#link-1) table) 
>Note that 0.40 breaks backward compatibility in linking

We've fixed this in [1.17.0 version](https://github.com/Microsoft/react-native-code-push/releases/tag/v1.17.0-beta) of `react-native-code-push`, please let me know if you see any issues or have any questions.

**Comment by fungilation** [comment]
Ah yes, I was basing lack of support on [the docs](http://microsoft.github.io/code-push/docs/react-native.html#link-1). Thanks for correcting me and the docs!
