### ISSUE TITLE
Add local runnable binary

### ISSUE THREAD

**Issue by slorber** [Microsoft/code-push#381]
Hi,

Would it be possible to make it easy to use a locally installed version of code-push. The idea is to fix the codepush version directly inside the devDependency of the projects so that users don't have to figure out which version to install etc.

I think it works like that in package.json:

```
  "bin": {
    "code-push": "./bin/runnable-file.js"
  },
```

And then we can run local command ./node_modules/.bin/code-push

**Comment by silhouettes** [comment]
I'm assuming you're referring to the CodePush CLI as opposed to the management SDK. In that case, I think you can do the following:

```
npm install --save-dev code-push-cli
node node_modules/code-push-cli/script/cli.js
```

Is this what you're looking for?

**Comment by sergey-akhalkov** [comment]
@slorber, please let us know if we could help you or if the issue has been resolved.

**Comment by slorber** [comment]
hmmm yes that seems to work thanks sorry for the delay
