### ISSUE TITLE
code-push: command not found when trying to registrer

### ISSUE THREAD

**Issue by gillesBzk** [Microsoft/code-push#383]
I try to use Code Push for react-Native  but when i try to register with code-push register
 i get a command not found.

I m on mac os 10.11.6 and i  have installed  :
react-native-code-push
-g code-push-cli

Here the process and the log 

npm install --save react-native-code-push@latest
gilless-MacBook-Pro:ParisFoodiesApp gillesB$ npm install --save react-native-code-push@latest
(node:5005) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
npm WARN update-linked node_modules/assets needs updating to 2.1.0 from 2.1.0 but we can't, as it's a symlink
ParisFoodiesApp@0.0.1 /Users/gillesB/ParisFoodiesApp
├─┬ react-native@0.35.0
│ └─┬ yeoman-generator@0.21.2
│   └── async@1.5.2 
├─┬ react-native-code-push@1.17.0-beta
.......

npm install -g code-push-cli

npm install -g code-push-cli
Password:
(node:5562) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
/usr/local/Cellar/node/6.3.1/bin/code-push -> /usr/local/Cellar/node/6.3.1/lib/node_modules/code-push-cli/script/cli.js
/usr/local/Cellar/node/6.3.1/lib
└── code-push-cli@1.12.6-beta

code-push register

code-push register
-bash: code-push: command not found

**Comment by sergey-akhalkov** [comment]
@gillesBzk, are you using Homebrew's version of the node? Could you please try to remove `prefix=/usr/local/Cellar/node/0.12.2_1/libexec/npm` line from `/usr/local/lib/node_modules/npm/npmrc` file and verify it it works for you?

**Comment by gillesBzk** [comment]
Hello Serge
Yes i have installed node via Homebrew
There is no npmrc
in /usr/local/lib/node_modules/npm/npmrc

**Comment by gillesBzk** [comment]
When i edit my nam config file i get
npm config edit
; save-dev=false
; save-exact=false
; save-optional=false
; save-prefix=^
; scope=
; searchopts=
; searchexclude=null
; searchsort=name
; shell=/bin/bash
; shrinkwrap=true
; sign-git-tag=false
; strict-ssl=true
; tag=latest
; tag-version-prefix=v
; tmp=/var/folders/mq/7sg6zgq50c15sw6q9wjw1nyw0000gp/T
; unicode=true
; unsafe-perm=true
; usage=false
; user=502
; userconfig=/Users/gillesB/.npmrc
; umask=18
; version=false
; versions=false
; viewer=man
; _exit=true
; globalignorefile=/usr/local/Cellar/node/6.3.1/etc/npmignore

So has you can see , i have not the line your talking about : prefix=/usr/local/Cellar/node/0.12.2_1/libexec/npm 
Regards
Gilles

**Comment by sergey-akhalkov** [comment]
@gillesBzk, seems like you have failed into this issue: https://gist.github.com/DanHerbert/9520689
To make global packages usable you should probably do following:  
>The final step is to add `~/.npm-packages/bin` to your PATH so npm and global npm packages are usable. To do this, add the following line to your ~/.bash_profile:
`export PATH="$HOME/.npm-packages/bin:$PATH"`
Now you can re-install any global npm packages you need without any problems.

Please let me know if it helps.

**Comment by gillesBzk** [comment]
Hello Sergey

I have Add export PATH="$HOME/.npm-packages/bin:$PATH"  to my bash_profile:
and Installed Code Push again

gilless-MacBook-Pro:~ gillesB$ sudo npm install -g code-push-cli
Password:
(node:5904) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
/usr/local/Cellar/node/6.3.1/bin/code-push -> /usr/local/Cellar/node/6.3.1/lib/node_modules/code-push-cli/script/cli.js
/usr/local/Cellar/node/6.3.1/lib
└─┬ code-push-cli@1.12.6-beta 
  └─┬ code-push@1.10.2-beta
    └─┬ superagent-proxy@1.0.2
      └─┬ proxy-agent@2.0.0
        └─┬ pac-proxy-agent@1.0.0
          └─┬ pac-resolver@1.2.6
            ├─┬ degenerator@1.0.4
            │ └── ast-types@0.9.5 
            └─┬ regenerator@0.8.46
              ├─┬ commoner@0.10.8
              │ └── recast@0.11.21 
              └── private@0.1.7 
 
And when i try to register i get the not found again

code-push register
-bash: code-push: command not found

Hope you can help me !!
Regards
Gilles

**Comment by sergey-akhalkov** [comment]
@gillesBzk, could you please try to re-install node as described in https://gist.github.com/DanHerbert/9520689?

**Comment by gillesBzk** [comment]
ok i will do and let u know

**Comment by gillesBzk** [comment]
Thanks, It Works !

**Comment by MrHubble** [comment]
My problem was with yarn and was fixed with: `export PATH="$PATH:$(yarn global bin)"`

**Comment by toguvr** [comment]
> export PATH="$PATH:$(yarn global bin)"

where you did this ?

**Comment by MrHubble** [comment]
In **.bash_profile**. This [stackoverflow question](https://stackoverflow.com/questions/30461201/how-do-i-edit-path-bash-profile-on-osx) may help.
