### ISSUE TITLE
New Website Logo: E-gazete: Günlük Gazete Keyfi

### ISSUE THREAD

**Issue by mehmetcanker** [Microsoft/code-push#384]
- Name: E-gazete: Günlük Gazete Keyfi
- Homepage (or app store) url: https://play.google.com/store/apps/details?id=com.readjournal.hurriyetegazete
- Brand Guidelines/Licensing: NONE
- Logo: https://lh3.googleusercontent.com/WFqtNJ4mXzUIfYqNIcLXf9Ua-NVkyamcuaGbtlWawZU6t6042PpioLqR0Nr5gtC2UIAQ=w300

**Comment by max-mironov** [comment]
@mehmetcanker thanks, your logo has been added!
