### ISSUE TITLE
Release on all platforms with one command

### ISSUE THREAD

**Issue by jr-k** [Microsoft/code-push#386]
Hello,

I've a question about releasing process.  I developed an application with react-native for both ios and android and for now when I need to send an update I'm doing that:

`code-push release-react myApp android -d Production -m true --des "some improvements"`

Then when I type `code-push deployment ls myApp` I see "Label v10" with my comments and so on. But now I want to send an update for ios too so I'm doing that:

`code-push release-react myApp ios -d Production -m true --des "some improvements"`

Now  when I type `code-push deployment ls myApp` I see "Label v11". But It makes no sense because it is the same package with same code. Is it possible to call a command which would look like `code-push release-react both` or somethin?

What is the correct way to deploy an unique package on multiple platforms ? 
Thanks !

**Comment by sergey-akhalkov** [comment]
@jr-k, from official documentation: 
>If your app targets both iOS and Android, we highly recommend creating separate apps with CodePush.
>...
>`code-push app add MyApp-Android`
>`code-push app add MyApp-iOS`
>...
>*NOTE: Using the same app for iOS and Android may cause installation exceptions because the CodePush update package produced for iOS will have different content from the update produced for Android.*

For more details please look at [App Management chapter](https://github.com/Microsoft/code-push/tree/master/cli#app-management)
Let me know if you have any questions or see any issues.

**Comment by jr-k** [comment]
Oops, sorry for the rtfm issue

**Comment by sergey-akhalkov** [comment]
@jr-k, no problem, closing the issue, feel free to reopen if needed.
