### ISSUE TITLE
release-cordova and cordova prepare

### ISSUE THREAD

**Issue by adriano-di-giovanni** [Microsoft/code-push#389]
I'd like to know why you need to `cordova prepare`. Is it just to take `merges/` into account? Do you include cordova files such as javascript code for plugins and the library itself?

**Comment by sergey-akhalkov** [comment]
@adriano-di-giovanni, thanks for the question.
`cordova prepare` command produces update contents that are stored in `myapp/platforms/android/assets/www` folder. This folder includes contents from `myapp/www` folder, plugins javascript files and some cordova platform-specific javascript files:
![image](https://cloud.githubusercontent.com/assets/4928157/22701756/a4289710-ed6f-11e6-959b-6a346f4b7e26.png)

**Comment by adriano-di-giovanni** [comment]
@sergey-akhalkov, thanks for your reply.

I'm going to ask you two more questions.

If I understand, I could also update `cordova.js` and javascript side of plugins. This could lead to inconsistencies between javascript and native sides of the cordova app. Am I correct? If so, why did you choose to include cordova-platform-specific javascript files? What are the benefits of this approach?

The reason why I opened the issue is as follows: I want my teammates to be able to release an update using CodePush and without having to deal with cordova. What if I release an update using the [general] command? Will the deployment preserve cordova-platform-specific javascript files?

Thanks

**Comment by srameshr** [comment]
@adriano-di-giovanni How do you manage your release cycles, syncing your code-push and app store releases? Some guidelines that has to be followed in order not to mess up?

**Comment by adriano-di-giovanni** [comment]
@srameshr, we're new to CodePush and we're investigating possible scenarios these days.

**Comment by srameshr** [comment]
@adriano-di-giovanni Same here. Had to rollback couple of times.

**Comment by sergey-akhalkov** [comment]
Closing this for now due to new one issue was created: https://github.com/Microsoft/code-push/issues/393 
Please feel free to reopen if needed.
