### ISSUE TITLE
Best practices to manage environments

### ISSUE THREAD

**Issue by adriano-di-giovanni** [Microsoft/code-push#390]
What are the best practices to manage staging and production environment for both Android and iOS?

We plan to specify the `deploymentKey` for production in `config.xml` and override it using [`SyncOptions`](https://microsoft.github.io/code-push/docs/cordova.html#syncoptions) if the app is in debug mode.

Any advice?

**Comment by sergey-akhalkov** [comment]
@adriano-di-giovanni, could you please look at [App Management](https://github.com/Microsoft/code-push/tree/master/cli#app-management) and [Deployment Management](https://github.com/Microsoft/code-push/tree/master/cli#deployment-management) chapters and let me know if you have any questions?

**Comment by adriano-di-giovanni** [comment]
@sergey-akhalkov, I already read both chapters. I'd like to know if best practices emerged in managing environments.

**Comment by sergey-akhalkov** [comment]
@adriano-di-giovanni, sorry for slow response. 
>I'd like to know if best practices emerged in managing environments.

I'd like to recommend you to use following workflow:
1. Debug - development. Code push is not being used here.
2. Stage - stable version for testing. Changes are pushed here from the Debug version.
3. Production - what customers run. Promote tested CodePush updates from Staging to Production.

Using this approach you have not to override deployment key from `config.xml`, you just could build 3 apps with different deployment keys are stored in `config.xml` file.

Please let me know if you have any questions.

**Comment by sergey-akhalkov** [comment]
@adriano-di-giovanni, just a friendly ping.

**Comment by adriano-di-giovanni** [comment]
Thanks for your reply.

We started using the approach you recommended. We then moved to another one.

We don't use config.xml to specify deployment keys. We use javascript and use different keys according to the type of build (debug, release).

**Comment by sergey-akhalkov** [comment]
@adriano-di-giovanni, thank you for response, closing this for now, please feel free to reopen if needed.
