### ISSUE TITLE
Production release, runs the command cordova build

### ISSUE THREAD

**Issue by srameshr** [Microsoft/code-push#392]
```
code-push release-cordova my_app ios -t 1.2.0  --description "Test" --build  deploymentName Production 
```

This command runs ```cordova build ios``` and not ```cordova build ios --release```

**Comment by max-mironov** [comment]
Hello @srameshr, we have implemented this in https://github.com/Microsoft/code-push/pull/409.
Closing this for now, please let us know if you see any issues or have any questions.

**Comment by gs-sramesh** [comment]
@max-mironov Thanks!
