### ISSUE TITLE
Can I use self code push server?

### ISSUE THREAD

**Issue by kimown** [Microsoft/code-push#398]
Like this issue https://github.com/Microsoft/code-push/issues/294 , the network is bad in china. 

So I want to know can we use a self server, like this question: http://stackoverflow.com/questions/37406913/can-developers-build-a-self-code-push-server-using-ms-code-push-service

**Comment by sergey-akhalkov** [comment]
@kimown, we do not have any plans to self-host CodePush, please let me know if I could help you somehow.

**Comment by axemclion** [comment]
@kimown You could try https://adtmag.com/articles/2016/11/01/react-native-ota.aspx, but we do not officially support self-hosting a server currently.

**Comment by sergey-akhalkov** [comment]
@kimown, closing this for now, please feel free to reopen if you have any questions.

**Comment by johnculviner** [comment]
This looks like an option, going to dig in further and I will report back if it is viable: https://github.com/lisong/code-push-server

**Comment by johnculviner** [comment]
Been playing with it a bit and https://github.com/lisong/code-push-server works great with ```CLI v2.0.2-beta``` CLI (latest right now). Complete feature parity with the Microsoft backend as far as I can tell. Would recommend giving it a shot if you do not want/cannot rely on Microsoft to store and serve up your code push assets.

**Comment by max-mironov** [comment]
Thanks for verifying @johnculviner. Could be useful if someone would like to go with this solution.

**Comment by alsotang** [comment]
@johnculviner oh,thank you, I will dig into lisong/code-push-server.

I work in a big company, so I cant use any services built from MS or google or FB. Sometimes make me hard to write code...

**Comment by frankychan007** [comment]
@johnculviner i was trying to use https://github.com/lisong/code-push-server. However, following the doc, i stuck in the part of storing bundle file in s3, any hints? Thanks!

**Comment by johnculviner** [comment]
@frankychan007 I ended up changing the code there to store as blobs that I gzipped into the database since I wanted the whole thing self contained
