### ISSUE TITLE
about version

### ISSUE THREAD

**Issue by workzhushengquan** [Microsoft/code-push#400]
code-push 1.12.6-beta
use code-push release myapp ./rnbundle 1.0 -d "Staging"
but i make release version app 1.0 , 1.0.1 and 1.2 
1.0 can check the update info
1.0.1 also can check the update info
why make this problem
1.2 can not check the update info , it is right

**Comment by max-mironov** [comment]
Hello @workzhushengquan, as far as I get you question you have the following:
a) released version 1.0 of the app 
b) received updates for 1.0 and do not received updates for 1.2 (which is correct)
c) is confused why 1.0.1 is also receiving the updates.

So the reason of why 1.0.1 is also getting the updates is that 
`semver.satisfies(1.0 1.0.1)` will return true. So by releasing version 1.0 you are getting updates for 1.0.x versions this way.

If you want to constrain the results to satisfy only 1.0.0 version of the app you can patch you release somehow like this:
`>code-push patch AppName Staging --label YourLabel --targetBinaryVersion 1.0.0`

Please let me know if it solves your problem.

**Comment by workzhushengquan** [comment]
@max-mironov thanks for your answer,it solves my problem!
through test , i turely found that the problem is release version
a) released version 1.1.3 of the app
b) received updates for 1.1.3 and do not received updates for 1.1.4 or 1.1.5 (which is correct)
finally,thanks again.

**Comment by max-mironov** [comment]
Thank you, feel free to open new tickets if any,
