### ISSUE TITLE
Is it possible to set an entry file path?

### ISSUE THREAD

**Issue by joeferraro** [Microsoft/code-push#403]
Our entry file(s) are located in src (and build) and not in the project root. Is it possible to specify an entry file when running `code-push release-react`?

code-push-cli version: 1.12.6-beta

Cheers

**Comment by sergey-akhalkov** [comment]
@joeferraro, you could specify entry file path using [this parameter](https://github.com/Microsoft/code-push/tree/master/cli#entry-file-parameter) when running `code-push release-react`.
Please let me know if it helps or if you have any questions.

**Comment by sergey-akhalkov** [comment]
@joeferraro, just a friendly ping.

**Comment by joeferraro** [comment]
@sergey-akhalkov cheers for the reply. We're going to test this week.

**Comment by max-mironov** [comment]
Hi @joeferraro, I'm closing the issue for now, please feel free to reopen it or create a new one if you see any problems with this when testing or have any questions.

**Comment by joeferraro** [comment]
@sergey-akhalkov @max-mironov confirmed as working for me. cheers, guys
