### ISSUE TITLE
App reverts to codepush version when new Binary is deployed

### ISSUE THREAD

**Issue by tavosansal** [Microsoft/code-push#404]
Hello,
I have the following scenario:

- App running version 1.3.7
- We did a codepush for a small bugfix that we did not want to do a new review process for since we were making some changes anyways.
- It worked perfectly and bugfix was deployed successfully
- Created a new build (v1.4.0) and deployed it to Testflight for beta testing
- Installed the new version via Testflight
- App opens and immediately reverts to the old version of the app
- We can tell is the old version because the UI is totally different. If you completely delete version 1.3.7 and install app from Testflight then everything works as expected. 

Would appreciate some help on why this is happening and how we can fix it.
Thanks.

cordova-plugin-code-push version: 1.9.2-beta
Cordova version: Latest
iOS/Android/Windows version: iOS
Does this reproduce on a debug build or release build? Release
Does this reproduce on a simulator, or only on a physical device? Physical

**Comment by silhouettes** [comment]
When you say reverts, do you mean it downloads the update that is on the CodePush server and reverts to that, or do you mean it loads an existing old update from disk?

**Comment by tavosansal** [comment]
@silhouettes I believe that I am experiencing this issue: https://github.com/Microsoft/cordova-plugin-code-push/issues/207 ... will try to update to the latest untagged version and see if that helps since I saw some commits that fixed this issue. Would be nice to have a new tag though.

**Comment by silhouettes** [comment]
Great! We would like to release/tag that ASAP, along with a few other fixes - we will be testing everything first, but if you could also let us know from your personal testing if it resolves your issue that would also be tremendously helpful.

**Comment by tavosansal** [comment]
Will do...I should have a build ready in a bit here. I will report back.

**Comment by tavosansal** [comment]
@silhouettes Seems like that fixed the problem. Thank you.

**Comment by silhouettes** [comment]
Thank you!
