### ISSUE TITLE
New Website Logo: [Partido 玩遊戲 | 交朋友]

### ISSUE THREAD

**Issue by dannyyaou** [Microsoft/code-push#407]
- Name: Partido 玩遊戲 | 交朋友
- Homepage (or app store) url: https://itunes.apple.com/tw/app/partido-wan-you-xi-jiao-peng/id1153371765?l=zh&mt=8
- Brand Guidelines/Licensing: Nothing
- Logo: http://i.imgur.com/x83KBVA.png

**Comment by max-mironov** [comment]
@dannyyaou thank you for your request, your logo has been added.
