### ISSUE TITLE
Errors when building android project React Native 0.43-rc1

### ISSUE THREAD

**Issue by RichardLindhout** [Microsoft/code-push#408]
See these pull requests
https://github.com/facebook/react-native/pull/12329
https://github.com/facebook/react-native/pull/12396

In the CodePushNativeModule.java we need to import 
import com.facebook.react.modules.core.ReactChoreographer;

And there are errors in
```
//                            getReactApplicationContext().runOnUiQueueThread(new Runnable() {
//                                @Override
//                                public void run() {
//                                    ReactChoreographer.getInstance().postFrameCallback(ReactChoreographer.CallbackType.TIMERS_EVENTS, new Choreographer.FrameCallback() {
//                                        @Override
//                                        public void doFrame(long frameTimeNanos) {
//                                            if (!latestDownloadProgress.isCompleted()) {
//                                                dispatchDownloadProgressEvent();
//                                            }
//
//                                            hasScheduledNextFrame = false;
//                                        }
//                                    });
//                                }
//                            });
```

**Comment by sergey-akhalkov** [comment]
@RichardLindhout, thanks for reporting the issue! 
Here is the PR fixing it: https://github.com/Microsoft/react-native-code-push/pull/735

**Comment by RichardLindhout** [comment]
Ah thank you, did not see that pull request!

**Comment by aslakagens** [comment]
When will this be fixed?

**Comment by silhouettes** [comment]
@aslakagens, the fix should be merged and published tomorrow or the day after.

**Comment by sergey-akhalkov** [comment]
Closing this due to https://github.com/Microsoft/react-native-code-push/pull/735 has been merged. Please feel free to reopen if need.

**Comment by silhouettes** [comment]
We will publish this on npm the same day that RN 0.43 exits RC.

**Comment by sergey-akhalkov** [comment]
We've released new version of React Native Module for CodePush: react-native-code-push@2.0.1-beta (it's available via npm), please let me know if you see any issues or have any questions.
