### ISSUE TITLE
code-push image upload process optimization

### ISSUE THREAD

**Issue by aaronorosen** [Microsoft/code-push#414]
I use code-push while i'm developing to quickly update my app and test it on my device. One bottleneck I've found in my development process is code-push can take close to a minute+ to upload a new release of my code. This could be sped up a good bit (and lots of bandwidth could be saved on the code-push server side) if code-push implemented a clientside diff and only pushed the files that have changed since the last push. 

I believe code-push implements this feature to this on it's backend to phoneclient to reduce download sizes.

**Comment by pniko** [comment]
Hi @aaronorosen, there are currently no plans to support client side diffing using CodePush today. We have built out an extensive backend to support managing and creating diffs from your releases that would be too difficult to bring into the CLI codebase without introducing a few other serious concerns. Our goal is to consistently deliver valid updates to your target devices and managing diffs on the servers allows us to accomplish this more reliably and secure.
