### ISSUE TITLE
Code Push no longer allowed by Apple?

### ISSUE THREAD

**Issue by pke** [Microsoft/code-push#415]
Read this message in the Apple dev forums:

https://forums.developer.apple.com/thread/73640

And it states:

>Your app, extension, and/or linked framework appears to contain code designed explicitly with the capability to change your app’s behavior or functionality after App Review approval, which is not in compliance with section 3.3.2 of the Apple Developer Program License Agreement and App Store Review Guideline 2.5.2. This code, combined with a remote resource, can facilitate significant changes to your app’s behavior compared to when it was initially reviewed for the App Store. While you may not be using this functionality currently, it has the potential to load private frameworks, private methods, and enable future feature changes.
This includes any code which passes arbitrary parameters to dynamic methods such as dlopen(), dlsym(), respondsToSelector:, performSelector:, method_exchangeImplementations(), and running remote scripts in order to change app behavior or call SPI, based on the contents of the downloaded script. Even if the remote resource is not intentionally malicious, it could easily be hijacked via a Man In The Middle (MiTM) attack, which can pose a serious security vulnerability to users of your app.
Please perform an in-depth review of your app and remove any code, frameworks, or SDKs that fall in line with the functionality described above before submitting the next update for your app for review."

This pretty much describes what code-push code does. Any word from MS about that?

**Comment by max-mironov** [comment]
Hi @pke, seems that the rejections only affect apps that use native code update technologies, like Rollout and JSPatch. 
Please see https://github.com/Microsoft/react-native-code-push/issues/748, https://github.com/Microsoft/cordova-plugin-code-push/issues/227 for more details.

**Comment by marcelaraujo** [comment]
@max-mironov @pke 

https://news.ycombinator.com/item?id=13817557

**Comment by max-mironov** [comment]
@marcelaraujo thanks for sharing this. Also please see the latest thread in RN repo: https://github.com/facebook/react-native/issues/13011. So seems that CodePush is not a culprit of the issue.

**Comment by max-mironov** [comment]
I'm closing the issue now as it turns out that code-push is valid for using with app store. Will reopen this one if any changes.

**Comment by dsernst** [comment]
The Man-in-the-Middle attack is unfortunately still relevant. See https://github.com/Microsoft/code-push/issues/233 for discussion and https://github.com/Microsoft/code-push/pull/309 for WIP solution.
