### ISSUE TITLE
Code push 

### ISSUE THREAD

**Issue by BJGDEV** [Microsoft/code-push#421]
Thanks so much for filing an issue or feature request! We will address it as soon as we can. Please follow these guidelines:

1. This repository is for the CodePush CLI and management SDK. For issues relating to the CodePush client SDK's, please see:
  * react-native-code-push: https://github.com/Microsoft/react-native-code-push
  * cordova-plugin-code-push: https://github.com/Microsoft/cordova-plugin-code-push
2. In your description, please include the version of `code-push-cli` or `code-push` that you are using.

**Comment by max-mironov** [comment]
@BJGDEV please review your issue and fill proper description otherwise this item will be closed as invalid.

**Comment by BJGDEV** [comment]
https://github.com/Microsoft/react-native-code-push

**Comment by silhouettes** [comment]
@BJGDEV closing this issue as unactionable, please file another issue with clear reproduction steps if you still need help.
