### ISSUE TITLE
bundle api endpoint

### ISSUE THREAD

**Issue by abelcha** [Microsoft/code-push#425]
Where can i fetch the js bundle of an app ?

I'm trying to do something like that: 
`wget https://codepush.azurewebsites.net/apps/myapp/downloadBundle?version=23&key=xxx`

**Comment by silhouettes** [comment]
From the CLI, please run the following command to get the download URL's for each release:

`code-push deployment history <app> <deployment> --format json`

Does this solve your question?

**Comment by abelcha** [comment]
Thanks,

Each deployment have a `blobUrl` key, that's what i was looking for.

**Comment by SudoPlz** [comment]
That's perfect, but how can I turn that blob to a file ? Is that blob a zip file?

**Comment by SudoPlz** [comment]
Leaving that here. That blob file is a zip file, that can be renamed to zip and examined.
