### ISSUE TITLE
How to remove the local package when app version is changed

### ISSUE THREAD

**Issue by victorhua** [Microsoft/code-push#427]
We are testing the codepush feature for our app, we noticed when app is upgraded through app store, the update through code push for the previous version still remain.
Here is an example:
1) App with version 1.0.0 installed.
2) pushed update v1 through codepush targeting 1.0.0
3) v1 is updated in App.
4) App is upgraded to version 1.0.1, but v1 update still remain.

If I uninstall 1.0.0 first, the version 1.0.1 app will not have v1 update. 

Is there a way to remove v1 update for the new version of app?

**Comment by victorhua** [comment]
This seems to related to https://github.com/Microsoft/cordova-plugin-code-push/issues/219, and after upgrade to cordova-plugin-code-push@1.9.3-beta, the problem is gone when testing on iPhone connected directly to Xcode.

**Comment by max-mironov** [comment]
@victorhua - got it, thanks for explanation. I believe your assumptions are correct and code-push-@1.9.3-beta should fix it. I'm closing the issue now, let is know if you have any questions further.
