### ISSUE TITLE
Cannot assign to read only property '0' of object '[object String]'

### ISSUE THREAD

**Issue by the-simian** [Microsoft/code-push#428]
|  application| code-push-cli  |
|--|--|
| Error | Cannot assign to read only property '0' of object '[object String]' |
| Version | 1.12.9-beta | 
|command to repro| code-push release-react CoolApp-Android android |

stacktrace in console:

```sh
Detecting android app version:

/usr/local/lib/node_modules/code-push-cli/node_modules/deep-assign/index.js:28
		to[key] = val;
		        ^

TypeError: Cannot assign to read only property '0' of object '[object String]'
    at assignKey (/usr/local/lib/node_modules/code-push-cli/node_modules/deep-assign/index.js:28:11)
    at assign (/usr/local/lib/node_modules/code-push-cli/node_modules/deep-assign/index.js:43:4)
    at assignKey (/usr/local/lib/node_modules/code-push-cli/node_modules/deep-assign/index.js:30:13)
    at assign (/usr/local/lib/node_modules/code-push-cli/node_modules/deep-assign/index.js:43:4)
    at deepAssign (/usr/local/lib/node_modules/code-push-cli/node_modules/deep-assign/index.js:64:3)
    at deepParse (/usr/local/lib/node_modules/code-push-cli/node_modules/gradle-to-js/lib/parser.js:135:27)
    at deepParse (/usr/local/lib/node_modules/code-push-cli/node_modules/gradle-to-js/lib/parser.js:137:27)
    at ReadStream.<anonymous> (/usr/local/lib/node_modules/code-push-cli/node_modules/gradle-to-js/lib/parser.js:392:13)
    at emitOne (events.js:96:13)
    at ReadStream.emit (events.js:189:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at ReadStream.Readable.push (_stream_readable.js:134:10)
    at onread (fs.js:1839:12)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:603:17)
```

**Comment by the-simian** [comment]
This references issue https://github.com/Microsoft/code-push/issues/420

**Comment by the-simian** [comment]
looking at this line: https://github.com/Microsoft/code-push/blob/master/cli/script/command-executor.ts#L905

I can see that the `.parseFile` function doesn't hit the catch, becuse I am not seing an error about being Unable to parse the gradlefile. It appears at face value to be dying in the `deep-assign` dependency that is used by `gradle-to-js`

**Comment by the-simian** [comment]
The problem appears to be in gradle-to-js. I'll submit an error report there.

**Comment by the-simian** [comment]
https://github.com/ninetwozero/gradle-to-js/issues/7

**Comment by the-simian** [comment]
Hey it seems that the problem fully lies in the underplaying gradle-to-js module, and I've submitted an issue there, since that's where it really belongs. I think its safe to close this, so I shall do so.

I've produced a very minimal example of the issue here that clearly proces its in the undelrying module: https://github.com/the-simian/gradle-to-js-test

**Comment by max-mironov** [comment]
Hey @the-simian, thank you for your great investigation! All this information will be very useful for anyone who can get this error in future! We are appreciating your help with this.

**Comment by Chubacca** [comment]
If anyone else is still having trouble with this - I just commented out almost my entire gradle file (but left the version section) and was able to release. You can do the same until the gradle-to-js issue is fixed.

**Comment by dluksza** [comment]
I have the same issue in v2.0.2-beta

**Comment by ruslan-bikkinin** [comment]
hi, @dluksza, we've been updated `gradle-to-json` to version 1.0.1 which has a fix for the issue and will release new code-push cli version soon. Can you please update from master to see if the issue is fixed?

**Comment by akshetpandey** [comment]
@ruslan-bikkinin I am also running into this issue and since neither yarn not npm support installing packages from a subfolder of a git repo, would it be possible to create a release tag from master called `master` or `next`.

**Comment by ruslan-bikkinin** [comment]
@akshetpandey feel free to create fork of code-push repo and use it.

**Comment by dluksza** [comment]
@ruslan-bikkinin is there any guide how to update to master?

btw. For me removing `dependences` section from `android/app/build.gradle` fixed this issue and was able to push code to server.

**Comment by ruslan-bikkinin** [comment]
@dluksza please follow these steps:

```shell
git clone git@github.com:Microsoft/code-push.git
cd code-push
npm i && gulp install && gulp link && gulp build
cd /path/to/your/app
#then you can use local code-push cli by executing this command
node path/to/cloned/code-push/cli/bin/script/cli.cli.js 
```

**Comment by dluksza** [comment]
@ruslan-bikkinin I can that this error does *not* occur on current `master` (HEAD commit: `f8932552024bd21936c2584973196521ce216484`). Any ideas when it will be released?

**Comment by ruslan-bikkinin** [comment]
@dluksza we are planning to release new version at the beginning of next week.
