### ISSUE TITLE
New Website Logo: Dashdoc

### ISSUE THREAD

**Issue by cosmith** [Microsoft/code-push#430]
Hi! We use Code Push in our new app and love it - especially the ability to fix critical bugs in the early stages. We'd love to be featured in the showcase page!

- Name: Dashdoc
- Homepage (or app store) url: https://www.dashdoc.eu/ (it's only in French for now)
- Brand Guidelines/Licensing: nothing in particular
- Logo: 
![icon_dashdoc_android](https://cloud.githubusercontent.com/assets/1194749/25000880/3b0d23d4-2043-11e7-8ca0-7d154a435fa6.png)

**Comment by iageoghe** [comment]
Updated!

**Comment by cosmith** [comment]
Thanks!
