### ISSUE TITLE
Code-push mandatory followed by non-mandatory update behaviour 

### ISSUE THREAD

**Issue by aaronorosen** [Microsoft/code-push#434]
I want to understand how code-push handles the following case:

1) user installs App. 
  - Then, a mandatory update is pushed out. 
  - Then, a non-mandatory update is pushed out.
  -  Now, the user opens the app again. 

In this above case does it matter that a mandatory update was ever pushed out to begin with to this user since a non-mandatory update was pushed out after the user opened the app again ? 

I'm also wondering about in the other cases where multiple updates are pushed out. When the user of the app opens the app I suppose they will only get the latest version of the app downloaded to their phone? Or does it download ever update and restart? 

Thanks

**Comment by sergey-akhalkov** [comment]
Hi @aaronorosen, thanks for reaching us. 
>In this above case does it matter that a mandatory update was ever pushed out to begin with to this user since a non-mandatory update was pushed out after the user opened the app again ?

I believe "[Mandatory parameter](https://github.com/Microsoft/code-push/tree/master/cli#mandatory-parameter)" should answer this question. Please let me know if it does not clear for you.

>I'm also wondering about in the other cases where multiple updates are pushed out. When the user of the app opens the app I suppose they will only get the latest version of the app downloaded to their phone? Or does it download ever update and restart?

The users will get the latest version of the released CodePush updates that targets to [appropriate binary version ](https://github.com/Microsoft/code-push/tree/master/cli#target-binary-version-parameter)of the app.

**Comment by aaronorosen** [comment]
Thanks @sergey-akhalkov  I should have read though the documentation more. This is well documented and explained clearly. Thanks :)
