### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by alexeyMohnatkin** [Microsoft/code-push#438]
I'm getting `Internal Server Error` on any query in cli. 
code-push v 1.12.9-beta

**Comment by bhansen77** [comment]
Same issue, just started happening about 30 minutes ago

**Comment by AmusedMe** [comment]
me too...

**Comment by kainolophobia** [comment]
Likewise!

**Comment by JakeRawr** [comment]
+1

**Comment by AmusedMe** [comment]
Now, recovered.

**Comment by max-mironov** [comment]
Hey guys, we've investigated for Azure logs, there were several errors here but looks like a tmp issue. We'll keep an eye on this. Closing it for now as seems the issue has been resolved, let us know if any problems.

**Comment by JakeRawr** [comment]
Hi, @max-mironov

Some of our users were experiencing very long downloading time within the past 24 hours? Is this a reported issue? 

Jake

**Comment by max-mironov** [comment]
hi @JakeRawr,thanks for reaching us. We haven't heard about this issue previously. Do you currently experience such kind of problems? Do you have any info about your users location/internet connection etc?

**Comment by kelset** [comment]
Hey @max-mironov, it's happening again now.
Running v2.0.1 of the cli.

**Comment by xwartz** [comment]
I'm getting the same issue now. 
code-push version: 2.1.6

**Comment by DCbryant** [comment]
I'm getting the same issue now.
code-push version: 2.1.9
