### ISSUE TITLE
Crash while restarting app after downloading new bundle  

### ISSUE THREAD

**Issue by thotegowda** [Microsoft/code-push#445]
App downloads updated bundle from server. But when tries to restart the app, it crashes. With lot of `Sync already in progress.` and `Loading bundle on resume` messages. 

```
ReactNativeJS: [CodePush] Downloading package.
ReactNativeJS: [CodePush] Installing update.
ReactNativeJS: [CodePush] Restarting app
ReactNative: [CodePush] Loading bundle on resume
ReactNativeJS: [CodePush] Sync already in progress.
ReactNative: [CodePush] Loading bundle on resume
ReactNativeJS: [CodePush] Sync already in progress.
ReactNative: [CodePush] Loading bundle on resume
...
<Continues for few seconds>
```
crash log says 
```
com.facebook.react.uimanager.IllegalViewOperationException: Trying to add unknown view tag: 4040
```
Update is complete as expected, when app is ran after crash. 

Any pointers to debug this issue?

**Comment by sergey-akhalkov** [comment]
Hi @thotegowda, thanks for reaching us, could you please take a look at https://github.com/Microsoft/react-native-code-push/issues/841 and verify if you have the same issue as there or not?

**Comment by thotegowda** [comment]
Thanks @sergey-akhalkov for quick response.  Its the same issue, but the work-around mentioned in the thread, i.e. dex-guard configuration, is not working. 

Its happening even in the debug build, where dex-guard is disabled.

**Comment by sergey-akhalkov** [comment]
@thotegowda, got it, thanks for the clarification. Could you please try to debug from [this point](https://github.com/Microsoft/react-native-code-push/blob/master/android/app/src/main/java/com/microsoft/codepush/react/CodePushNativeModule.java#L431) or share with us source code (minimal version of the app where the issue reproduces) if available?
Please let me know if you have any questions.

**Comment by thotegowda** [comment]
Hey @sergey-akhalkov, spent some time looking in to what is happening.  `CodePushNativeModule.java` looks in two ways to resolve `ReactInstanceManager` instance.  (1) method `getReactNativeHost()` of `ReactApplication` (2) `mReactInstanceManager` member in ReactActivity or its derived. 

In our case it was failing, because we had a static instance of `ReactNativeHost` (our's is a brownfield application and also have our own reasons for keeping it as a static instance). For time being, I have fixed this issue by deriving `Application` class with `ReactApplication` and return static instance of the `ReactNativeHost`.  

I think, we need a better approach for fetching ReactInstanceManager instance.  But we can close this issue. I have seen few discussions and PRs around this in `react-native-code-push`.

Thank you

**Comment by sergey-akhalkov** [comment]
Hey @thotegowda, got it, thanks for the clarification, please let us know if you see any issues or have any questions.
