### ISSUE TITLE
sometimes can not detect updates

### ISSUE THREAD

**Issue by cbjs** [Microsoft/code-push#448]
I have to rollback to some old release, and then release the new version again.

**Comment by max-mironov** [comment]
Hello @cbjs, thank you for reaching us. Could you describe your problem a little more?
What CLI/SDK versions you are using, the platform you are on? What is your deployment history looks like? How do you bootstrap codepush?

**Comment by cbjs** [comment]
@max-mironov 

cli version: 1.12.9-beta
sdk version: 2.0.3-beta
dev platform: ubuntu 16.04

history file
[history.txt](https://github.com/Microsoft/code-push/files/1024673/history.txt)

in index.js
check update automatically
```
import codePush from 'react-native-code-push';
// other code
export default codePush(Root);
```

in setting.js
check update manually
```
import codePush from 'react-native-code-push';
// other code
        onPress={ () => {
          codePush.checkForUpdate()
            .then((update) => {
              if (!update) {
                toast({msg: '已是最新版本.'});
              } else {
                codePush.sync({
                    updateDialog: {
                      appendReleaseDescription: true
                    },
                    installMode: codePush.InstallMode.IMMEDIATE
                });
              }
            });
        }}
```

both not working sometimes.

**Comment by max-mironov** [comment]
@cbjs - thank you for this!
And also just to make it clear - the problem is that when you rollback one release new release is created (e.g. v95 from your history) but users do not receive it? So you have to release one more version after that?

Can you confirm that all users do not receive update this way or only those who are e.g. on certain version of code-push update?

**Comment by cbjs** [comment]
no. 
when I promote a new release(v92), some of the users(specially, new user of v1.2.1) can not receive any update(including v91 from history).  but v90 user may receive this update(v92).

then I try to rollback to v90(v93 from history), and then promote the same release(v94). 
everything is good.

**Comment by cbjs** [comment]
@max-mironov 
it turns out it's my mistake.

thanks for your time~

**Comment by max-mironov** [comment]
@cbjs thanks for your reply. What was the problem so finally?

**Comment by cbjs** [comment]
@max-mironov 
I used android back button to exit app(Android default behavior), and found that the update didn't take effect.
It turns out I have to kill the app manually, then restart the app.

**Comment by max-mironov** [comment]
@cbjs thanks for the explanation!
