### ISSUE TITLE
Github authentication and multiple accounts

### ISSUE THREAD

**Issue by afilp** [Microsoft/code-push#449]
Hello,

Is it possible to have a "switch" account feature, so that we can be logged in 3 different accounts and just switch?

Why?

If someone works for 3 different teams, so he has 3 different github accounts (per team), he has to:

1. code-push logout
2. Github logout (from main one)
3. Github login to the other account (just for the authentication, not needed to use that one)
4. code-push login
5. Github logout
6. Github login (to the main one, so that he can still work on github under his "main" account, see history, etc.).

This process is not a "disaster", but requires several steps.

It would be nice if there was another way. I believe that "logging in to multiple accounts and then **switch** to the 'active' one" would solve the problem. We would always be logged in to 3 accounts initially and then we would only need to do the following:

1. code-push switch myaccount1  (or code-push session switch myaccount1)

What do you think of this?

If you have another way to solve the above problem, please let me know.

**Comment by sergey-akhalkov** [comment]
Hello @afilp, thank you for reaching us. 
The current workflow with single GitHub and single CodePush account fits for most of the users, so we've not heard such kind of requests before. Currently, we are extremely backlogged and working on other high requested features, but if you have time and ability you could try to publish PR that implements this functionality - we will be very grateful.

Please let me know if you have any questions or see any issues.

**Comment by max-mironov** [comment]
Hello @afilp, I know that it was discussed a long time ago but hope to hear you back :) 
So my point here - why don't you try to use different [access keys](https://github.com/Microsoft/code-push/tree/master/cli#access-keys) here, so this will eliminate the need to login-logout from you github accounts multiple times because it could be really frustrating. 
This way you will be not tightly coupled with your github acc and can do different things with code push at the same time. 

Please let me know what do you think about this?

**Comment by pniko** [comment]
Hi @afilp, if you add your secondary Github account as a collaborator on the application in Mobile Center or through the CLI you can theoretically log in under the other account to manage your CodePush application. We are working on supporting multiple Github accounts in Mobile Center for a single user, but its currently on our future roadmap.

**Comment by afilp** [comment]
@max-mironov @pniko Thank you! I eventually created 2 accounts in Mobile Center and have to login/logout. I will look in the access keys feature though, this sounds good!
