### ISSUE TITLE
GitHub account was deleted

### ISSUE THREAD

**Issue by luqiuyuan** [Microsoft/code-push#452]
Is that possible to restore a code-push account associated with a deleted GitHub account?

More specifically, I registered a code-push account using a GitHub account. However, I converted the GitHub account into an organization, which results in the GitHub account deleted. Now I cannot login with my code-push account anymore since the associated GitHub account does not exist anymore. Is that possible to restore my code-push account? for example associate it with another GitHub account?

**Comment by max-mironov** [comment]
Hi @luqiuyuan, I believe @pniko has already replied your question via email, just duplicate his answer here:

> You should be able to sign up with a new account and use the app transfer command in the CLI to move ownership to your new account. 

Please let us know if any issues.

**Comment by luqiuyuan** [comment]
Hi Max,

Thanks for your reply. I cannot do the transfer since I cannot login into
my original code-push account anymore.

Is that possible to transfer the app without login?

Best Regards,
Lu

**Comment by luqiuyuan** [comment]
I have tried to register a new GitHub account with the same email (possible because the previous Github account has already been deleted).

When trying to login with "code-push login", it said

<img width="714" alt="screen shot 2017-05-31 at 4 32 22 pm" src="https://cloud.githubusercontent.com/assets/27582026/26652774/fa854330-461e-11e7-9f91-108608df21ab.png">

When trying to register with "code-push register", it said

<img width="1007" alt="screen shot 2017-05-31 at 4 32 05 pm" src="https://cloud.githubusercontent.com/assets/27582026/26652792/0c721afa-461f-11e7-9ac8-7a5b0768ae45.png">

When trying to link with "code-push link", it said

<img width="665" alt="screen shot 2017-05-31 at 4 32 36 pm" src="https://cloud.githubusercontent.com/assets/27582026/26652805/1c304af2-461f-11e7-82a5-84d453514e0f.png">

The prompts are quite confusing

**Comment by max-mironov** [comment]
Hi @luqiuyuan, we are sorry about the inconvenience here but as for now we cannot move the apps to the new account due to security. 

The messages you receive states that your code push account with such email address is already associated with your previous github account (which was converted to an organization), so seems that you need to use other mail to register. 

After you create new CodePush account you can configure your app with new deployment keys and then release new binary version linked to this app.

**Comment by luqiuyuan** [comment]
Thanks Max, I got it

**Comment by max-mironov** [comment]
Thanks @luqiuyuan, I believe we can close the issue. Feel free to reach us if  needed.
