### ISSUE TITLE
Can't login to codepush

### ISSUE THREAD

**Issue by mliwski** [Microsoft/code-push#453]
Hi, I can't login to codepush with my microsoft account. When I registered I have used a previous existing account and registered with no problems (an release version also without a problem). But now I have changed my computer and when try to login to codepush I get the message 
```
You've successfully signed in your Microsoft account, but we couldn't get an email address from it.
Please fill the basic information (i.e. First/Last name, Email address) for your Microsoft account in case of absence, then try to run 'code-push login' again.
```
Sou I filled my information on microsoft account but still can't login ... also I tried to add an outlook account as an alias and try to login again but still the same message

Code push version: 1.12.9-beta
Email: conscientecolectivo@outlook.com.ar (If you need the original alias please let me know)

**Comment by sergey-akhalkov** [comment]
Hi @mliwski, thanks for reaching us, please take a look at https://github.com/Microsoft/code-push/issues/374#issuecomment-278912156
You probably have the same issue, please double check if you basic MS Account info is filled and make sure if your permissions are correct.

Please let me know if any updates.

**Comment by mliwski** [comment]
I confirmed that the information is filled an also the permissions OK (screen capture), but still can't login ...

Some other facts that maybe helps:

The console is still waiting for an access key
I'm from Argentina and the recent activity shows unusual activity (but can't accept  it as mine)
The browser response with 403 to the call https://codepush-management.azurewebsites.net/auth/callback/microsoft?code=XXXXd&state=XXXX (I obfuscated the response because don't know if compromises something)

![captura de pantalla 2017-06-01 a las 18 11 01](https://cloud.githubusercontent.com/assets/376015/26701222/9c26323a-46f6-11e7-845c-15d505c5657f.png)

**Comment by sergey-akhalkov** [comment]
@mliwski, do I get it right if the `You've successfully signed in your Microsoft account` message is gone, and currently you are receiving 403 from CodePush?
Did you tried to clear browser cache and cookies or just use another browser?

**Comment by mliwski** [comment]
No, it's the original message ( ... but we couldn't get an email address from it ... ), but the http response code is 403 . I have cleaned up cookies and cache but not worked. 

Now I tried with Safari and worked well. I will close this issue, but not sure if something was fixed from the server side or was just black magic 😃
