### ISSUE TITLE
Error 403 - This web app is stopped (`code-push release-react`)

### ISSUE THREAD

**Issue by cooperka** [Microsoft/code-push#454]
### Issue

Every time I try to `code-push release-react`, I get what looks like a `curl` dump of HTML containing the following error:

```html
        <div id="content">
            <h1 id="unavailable">Error 403 - This web app is stopped.</h1>
            <p id="tryAgain">The web app you have attempted to reach is currently stopped and does not accept any requests. Please try to reload the page or visit it again soon.</p>
            <p id="toAdmin">If you are the web app administrator, please find the common 403 error scenarios and resolution <a href="http://blogs.msdn.com/b/waws/archive/2016/01/05/azure-web-apps-error-403-this-web-app-is-stopped.aspx" target="_blank">here</a>. For further troubleshooting tools and recommendations, please visit <a href="https://portal.azure.com/">Azure Portal</a>.</p>
        </div>
```

The command used to work, and the last time I ran it successfully (just a few hours ago) it halted partway through with this error:

```console
bundle: Writing sourcemap output to: /Users/me/dev/MyApp/android

EISDIR: illegal operation on a directory, open '/Users/me/dev/MyApp/android'
[Error]  "react-native bundle" command exited with code 1.
```

Not sure if this earlier error is relevant or not.

### Notes

- Running CLI v1.12.9-beta

**Comment by iageoghe** [comment]
Hi Kevin,

The CodePush service is currently down for upgrades. The estimated time for the outage is approximately two hours.

If you would like to read more about the upgrades, you can do so here: https://aka.ms/cpandmc

Thank you for your patience.

Ian

Ian Geoghegan | Senior Program Manager
Mobile Developer Division
iageoghe@microsoft.com<mailto:iageoghe@microsoft.com>
707.206.8215 mobile

**Comment by cooperka** [comment]
Thanks for the info @iageoghe! It would be nice if the error message were more clear instead of just an HTML dump, but I'm glad it's just a quick upgrade.

**Comment by JAStanton** [comment]
Agreed with @cooperka the CLI should handle it more gracefully, especially because I am building off the CLI for my promotion pipeline, this was a weird one!!

**Comment by AndreyNikiforov** [comment]
How I would know that code-push is back online and I can resubmit CI failed builds?

**Comment by JAStanton** [comment]
@iageoghe I'm guessing that our clients will still be able to query / download code push bundles?

**Comment by iageoghe** [comment]
This should be the case. We should be back online shortly.

Ian

**Comment by sergey-akhalkov** [comment]
Hey guys, closing this issue, please feel free to reopen or create new one if needed. Please also let us know if you are experiencing any issues after CodePush upgrades.
