### ISSUE TITLE
Login failure message is unhelpful

### ISSUE THREAD

**Issue by ptarjan** [Microsoft/code-push#46]
When running 

```
$ code-push login
```

I end up at a URL after the OAuth 2 dance that is like: https://codepush.azurewebsites.net/auth/callback/github?code=...&state=... But the page only has a spaceship background and says

```
Account not found.
Have you registered with the CLI?
```

Wha do I do? I thought I was registering with the CLI by the above command.

**Comment by geof90** [comment]
Hi @ptarjan,

We have configured the server to now prompt you to go to our [website](http://microsoft.github.io/code-push/) to sign up for the closed beta if you log in without having been registered. Thanks for reporting!

**Comment by ptarjan** [comment]
Thanks. And feel free to let me into the beta :)
