### ISSUE TITLE
Use the same app for iOS and Android

### ISSUE THREAD

**Issue by farwayer** [Microsoft/code-push#460]
It is not possible to use the same app for iOS and Android build after Mobile Center integration. It is uncomfortably for such technologies as React Native because it forces to use name postfixes (such as app-ios, app-android) and several code-push keys groups.
Old behaviour with several build variants was more convenient. 

```sh
code-push app add test android,ios react-native 
[Error]  "android,ios" is an unsupported OS. Available options are "ios", "android", and "windows".

$ code-push app add test ios react-native
Successfully added the "test" app, along with the following default deployments:
...

$ code-push app add test android react-native
[Error]  Conflict error adding app. Does an app named "test" already exist?
```

**Comment by BretJohnson** [comment]
@farwayer Mobile Center will eventually have better support for cross-platform apps (like with React Native and Xamarin). That's definitely on our backlog, as we've gotten several requests for it, though it's still likely a few months out.
@iageoghe @panarasi Shorter term, allowing adding apps for multiple platforms at the same time, with a syntax like @farwayer suggests above (while still creating multiple apps, with a suffix, just doing it more automatically) may well make sense as a shortcut for folks. @iageoghe do you want to consider adding this to the backlog; it's probably at least worth a discussion.

**Comment by iageoghe** [comment]
@BretJohnson @sergey-akhalkov The syntax fix seems reasonable and like extremely low-hanging fruit; couldn't it be done from the CLI itself?

**Comment by BretJohnson** [comment]
@iageoghe Yeah, we could do it from the CLI itself. I would think we'd want to spec & do this (at a minimum) in the Mobile Center CLI.  We probably want other MC PMs to sign off on the naming convention too, just to ensure we are all bought in there.

**Comment by pniko** [comment]
Hi @farwayer, our backend is currently designed to support only a single OS today and there are no current plans in the future to change that. CodePush was recently merged into Mobile Center which requires a specific OS and platform to be set so it can enable additional features that correspond to each setting. We might revisit this down the road, but realistically it would be a mid-to-late 2018 implementation at best with our current roadmap.
