### ISSUE TITLE
UWP platform type not supported by CodePush

### ISSUE THREAD

**Issue by TheAdamizer** [Microsoft/code-push#462]
Hi there.  We have been running into this error since the 2.0.0 release.  Before we weren't running into any issues trying to use codepush for our uwp app: was this change intentional?
![codepush_error](https://cloud.githubusercontent.com/assets/10438809/26807753/d9bce612-4a47-11e7-901a-f78766bfa30e.png)

**Comment by sergey-akhalkov** [comment]
Hi @TheAdamizer, thanks for reaching us. I've tried to reproduce the issue but with no luck, do you still experiencing it?
If so, could you please try to login to [mobile.azure.com](https://mobile.azure.com) using your CodePush account and import your `<appName>` as `react-native windows`, then verify if the issue still reproduces?

**Comment by BretJohnson** [comment]
I should have mentioned this earlier, but a few days ago we did indeed have a bug where Windows support didn't work, but that got fixed early this week. So I'm pretty sure this is fixed & I'm going to go ahead and close it.  But @TheAdamizer please let us know if you see any other issues.
