### ISSUE TITLE
How to get Remote package appVersion?

### ISSUE THREAD

**Issue by booker-laputa** [Microsoft/code-push#463]
I am using 2.0.0-beta

I want users to update the new binary when there is one.

Is there a function to retrieve remote package appVersion?

I tried check checkForUpdate but it return nulls when there is a new update targeting newer binary version

**Comment by sergey-akhalkov** [comment]
Hi @booker-laputa, thank you for reaching us. CodePush SDK is designed to use current app version to check for updates, so in case current app version does not match with remote package appVersion - CodePush SDK will show that there is no updates available.
To notify users that new binary version is available you could simply release new CodePush update for old app version that will contain notification. With this approach your users won't wait until CodePush update for new binary version will be released. 

Please let me know if you have any questions.

**Comment by booker-laputa** [comment]
@sergey-akhalkov Thanks for your reply.
So I have to make two bundle update?
One for the old app version, displaying "new update" notification, and the other one for the new app version?

**Comment by sergey-akhalkov** [comment]
@booker-laputa, if I get it right, you only need to make CodePush update for the old app version. That update will show "new binary version available via app store" notification, so users will be able to install it.
There is no need to make additional update for new binary version or your app - only in case it requires some fixes and improvements.

Please let me know if you have any questions.

**Comment by booker-laputa** [comment]
@sergey-akhalkov 
Assumed I have app v1.0 and bundle v100 now.
After a while, I have a major update v2.0 and the bundle is updated as well .
I want to force users to update the binary to v2.0.

In this case, should I update a dedicated bundle targeting binary v1.0 for showing the new binary update notification?

Moreover, I wonder why the checkForUpdate return null, I have passed the deployment key to it.

**Comment by booker-laputa** [comment]
I'm sorry I post in the wrong repository, I will close it now

**Comment by sergey-akhalkov** [comment]
@booker-laputa, got it, please feel free to reopen if needed.
