### ISSUE TITLE
Can't login with access key

### ISSUE THREAD

**Issue by Z0mBee** [Microsoft/code-push#464]
Hi
I am having problems logging in to code-push with an access key. 
I created an access key with

`code-push access-key add "My Key"`

When I try to login with the generated access key with
`code-push login --accessKey <accessKey>`

I get
`[Error]  Invalid access key.`

Code push cli version: 2.0.0-beta
My code push account is authenticated with GitHub.

I tried it with a different account and older code push version and it didn't resolve my issue.

**Comment by sergey-akhalkov** [comment]
Hi @Z0mBee, thanks for reaching us and sorry for the inconvenience. I can confirm that I can also reproduce the issue, so we have started investigation and fixing. Will let you know if any updates.

**Comment by BretJohnson** [comment]
@Z0mBee - Thanks for reporting this. We found the problem and I believe we'll have a fix deployed in a few hours. I'll update this issue when the fix is deployed.

**Comment by BretJohnson** [comment]
@Z0mBee - We've deployed the fix now. Can you please try again (you'll have to recreate the access key) and ensure all looks good for you now.
