### ISSUE TITLE
Add "Change your github primary email carefully" warning while register CodePush account

### ISSUE THREAD

**Issue by sergey-akhalkov** [Microsoft/code-push#465]
As of now there are a lot of requests with the following content - "My primary GitHub email has been changed, so I can'not login to CodePush anymore". 

So it would  be useful to set up warning that will prints the following yellow message: "Before changing your primary GitHub email please transfer your CodePush app to a new organization using Mobile Center."

**Comment by BretJohnson** [comment]
@sergey-akhalkov Can you test and see if this applies to Mobile Center in general, not being able to login after changing primary GitHub email. If so, I wonder if there are workaround there.

**Comment by sergey-akhalkov** [comment]
Hi @BretJohnson, I've tried the following scenario:
1. `code-push logout`
2. change github primary email
3. logout form github
4. `code-push login` with github

and everything works well! 

Currently I'm searching for workarounds and let you know if any updates, but it seems like the issue is gone after migration - Mobile Center is able to login with github otherwise github primary email has been changed.

**Comment by sergey-akhalkov** [comment]
Hey guys, I've not found any workaround that could break login flow - I think that the only thing that could break it - is deleting github account, but I believe it is very uncommon case. We've discussed this use case with @pniko and believe that this has low priority and should be investigated later.

So closing this for now, we'll reopen it later if needed.
