### ISSUE TITLE
Cannot see apps for which I have been made a colaborator

### ISSUE THREAD

**Issue by mikehazell** [Microsoft/code-push#466]
`code-push-cli version: 2.0.0-beta`

I'm having an issue with the CLI. I have been added as a collaborator to an application but when I run `code-push app ls` the app is not listed.

I have tried the following:
- Looking at the app owners machine I am listed as a collaborator.
- I have double checked that the email listed is the same as what I get when I run `code-push 
whoami`
- Have logged out and re-authenticated (through github)
- Have updated `code-push-cli` to 2.0.0-beta
- I am able to create an app and then see the newly created app listed when I run `code-push app ls`
- I can see a different app listed for which I was made a collaborator

Any help here would be appreciated.

**Comment by mikehazell** [comment]
Ok, I worked it out. Didn't notice the emails coming in.

For future reference. You need to check your email and accept the invitation for each app you are added to.

Maybe you could update your documentation to say that the process has changed and collaborator needs to accept an invitation.

**Comment by BretJohnson** [comment]
Hi. Thanks for the feedback. We'll look at updating the CLI text and doc here to make this clearer, as I agree it can be confusing. I'll leave this issue open for now until we fix that.

**Comment by BretJohnson** [comment]
Ian suggested this message:
`Collaborator invitation email for <appName> sent to <email>"
instead of "Successfully added <userEmail> as a collaborator to the app <appName>.`
Will deploy an update soon with this.

**Comment by BretJohnson** [comment]
I just published an updated CLI (2.0.1-beta) that contains the improved add collaborator message above. Thanks for the feedback here, @mikehazell.

**Comment by jose920405** [comment]
The email never arrives for me

**Comment by max-mironov** [comment]
Hey @jose920405, I've just tested this functionallity with my friend and it works like a charm.
I've done it via old CLI:
`code-push collaborator add trak-android username@useremail.com`

Are you completely sure that you never mistype in the email or probably the email falls into junk mails?

**Comment by jose920405** [comment]
hi, thanks for answer

Yes, I'm checking and the mail never arrived. I sent the collaborator
invitation for 2 different apps and it does not arrive. I'm also checking
in spam

When i ran the command:

code-push collaborator add myApp user@email.com

i see this log:

`Collaborator invitation email for "myApp" sent to "user@email.com".`

related:

https://github.com/Microsoft/code-push/issues/466

**Comment by jose920405** [comment]
I just tried another account and if it works. I do not know why the other
email does not work. The only difference is that for the one that works is
a `@outlook.com` account and the one that does not work has a company domain

**Comment by max-mironov** [comment]
@jose920405 thanks for the info. Is it possible that company's domain mailbox has some kind of filter that rejects some external emails? If possible it would be great if you can get out this information from company admins and share result's with us.
