### ISSUE TITLE
"Something went wrong while fetching user profile. Please contact support"

### ISSUE THREAD

**Issue by lucasromanojf** [Microsoft/code-push#469]
Hi,

when I run "code-push login", it gives me an empty token. When I try to access https://mobile.azure.com/login, the message "Something went wrong while fetching user profile. Please contact support" is shown. 

Please, help me!

**Comment by lukemiles** [comment]
+1, happening to me to

**Comment by lukemiles** [comment]
>Update user profile failed, status code 503, status msg: Service Unavailable

Getting this message

**Comment by Clawg** [comment]
Same here

**Comment by sergey-akhalkov** [comment]
Hey guys, thanks for reaching us and sorry for the inconvenience. I've just successfully logged in and seems like the issue is gone, do you still experiencing it? We'll try to figure out what goes wrong and let you know if any updates.

**Comment by BretJohnson** [comment]
All - Is everything ok now? We did have a site outage, for like 25 minutes or so, at the time you were seeing this, so that's surely the cause. But let us know if you see any other issues.

**Comment by Clawg** [comment]
Everything is working for me now. I had to logout and get a new access token but it's seems fine now. Thanks

**Comment by Steffaan** [comment]
Down again? I can't do anything in AppCenter right now, trying for 10 minutes already. All it says is:
"Something went wrong while fetching user profile. Please contact support"

**Comment by chenyu1990** [comment]
+1, happening to me too

**Comment by ninjaengineers** [comment]
+1 hapenning now
