### ISSUE TITLE
"Talk to us" Reactiflux link is wrong on gh-pages

### ISSUE THREAD

**Issue by Chris92de** [Microsoft/code-push#47]
Hey there,
for linking Discord channels you have to create an Instant Invite instead of linking the channel link directly.
It's the up-facing arrow symbol. Make sure to go to Advanced Settings and set "Expire After" to "Never" before you generate one.

**Comment by lostintangent** [comment]
Doh! I was pretty sure I used the never expire option when I created the link, but it is definitely broken. Thanks for raising this issue!

**Comment by geof90** [comment]
Thanks for the pro tip. Fixed. :)
