### ISSUE TITLE
Unable to patch label

### ISSUE THREAD

**Issue by joeferraro** [Microsoft/code-push#472]
Hi I'm using `2.0.0-beta` of `code-push-cli` and I'm getting an error when trying to patch `label`:

#### Patching with just `--label`
```
code-push patch MyAppName Beta --label v0.0.2
```

###### Error Message
```
[Error]  At least one property must be specified to patch a release.
```

#### Patching with `--label` and `--description`
```
code-push patch MyAppName Beta --description "foo" --label v0.0.2
```

###### Error Message
```
[Error]  [{"field":"label","message":"Field is invalid"}]
```

**Comment by iageoghe** [comment]
Hi Joe, can you confirm that your label is indeed v0.0.2? 
Run the `code-push deployment h <appName> <deploymentName>` command to verify.

**Comment by BretJohnson** [comment]
@joeferraro - The label itself can't be changed. You can only use it to specify the particular release that you want to update other fields on.
@iageoghe - We could probably improve the usability here somehow, as it seems a bit confusing at first. I wonder if `Label` is really the best name for this thing. Maybe `Release Number` or something instead. We should at least improve the error message above.

**Comment by joeferraro** [comment]
Cheers guys, this is 100% my fault. Went on a coding bender over the weekend and encountered this in a late night haze. I was misinterpreting the nature of the `label` field and realize now I can simply use `description` to stamp my bundle version. I agree with @BretJohnson that the documentation could be made a bit clearer. I'll leave open for now if you guys would like. Cheers!

**Comment by iageoghe** [comment]
@joeferraro You coding bender helped reveal a weakness in our naming and for this we owe you thanks. Thank you! 
@BretJohnson I think you are correct.
