### ISSUE TITLE
Question: potential failure scenario

### ISSUE THREAD

**Issue by joncursi** [Microsoft/code-push#478]
I'm tempted to use CodePush, but I have thought of one failure scenario that I can't find any docs online about to ease my mind. Consider the following scenario:

Build and deploy version A of the app through the App Store.

Build and code push version B containing all JS changes.

Build and deploy version C containing native and Js changes through the App Store.

Build and code push version D of the app containing all JS changes.

Let's say a user downloaded the initial version of the app at version A. But they turned off automatic updates on the App Store. So over time, they will receive update B over the air from code push, but will not receive version C because that requires them to manually update the app.

Even worse, code pushing version D assumes your users are on version C with the prerequisite native code installed. In the user example above, the app would try to code push the user from version A -> version D and break the app, potentially losing a user altogether.

I know lots of people who have memory constraints on their phones and tablets which prevents them from upgrading the OS and apps from the store. So I feel like this is a legitimate use case / issue.

Can you please clarify how this scenario can be mitigated?

Thanks!

**Comment by iageoghe** [comment]
Hi @joncursi, CodePush handle lets you mange the situation you describe with [semantic versioning](http://semver.org/). Each time you make a [release](https://github.com/Microsoft/code-push/tree/master/cli#releasing-updates-general) with CodePush you specify the target binary version that your update should apply to. So in the scenario you describe above, CodePush version B would target binary version A and more importantly you would set CodePush version D to target the binary version that shipped with C and _exclude_ the binary version that shipped with A.

I encourage you to test this. You can do so fairly quickly and at no cost by building a test app and distributing it through [Mobile Center](https://mobile.azure.com/) for scenarios A and C and using the CodePush CLI release commands for B and D.
