### ISSUE TITLE
The app isn't updated

### ISSUE THREAD

**Issue by Borisboky** [Microsoft/code-push#479]
I'm trying to update my React Native app with Code Push. My code is as follows:

    export default class codePushTest extends Component {
        constructor(props) {
            super(props);
            this.state = {
                updateAvailable: false,
                downloadingUpdate: null,
                installingUpdate: null,
                downloadProgress: null,
            }
        }
    
        componentDidMount() {
            let self = this;
            codePush.checkForUpdate().then(update => {
                if (!update) {
                    self.setState({updateAvailable: false})
                }else{
                    self.setState({updateAvailable: true})
                }
            })
        }
    
        handleUpdate() {
            let self = this;
            const checkUpdateStatus = (status) => {
                switch (status) {
                    case codePush.SyncStatus.DOWNLOADING_PACKAGE:
                        self.setState({downloadingUpdate: true});
                        break;
                    case codePush.SyncStatus.INSTALLING_UPDATE:
                        self.setState({installingUpdate: true, downloadingUpdate: false});
                        break;
                    case codePush.SyncStatus.UPDATE_INSTALLED:
                        self.setState({installingUpdate: false, downloadingUpdate: false, updateInstalled: true});
                        break;
                }
            };
    
            const downloadProgress = (downloadedBytes, totalBytes) => {
                self.setState({downloadProgress: (downloadedBytes / totalBytes) * 100})
            };
    
            codePush.sync({updateDialog: false, installMode: codePush.InstallMode.IMMEDIATE}, checkUpdateStatus, downloadProgress)
        }
    
        renderButton(){
            if (this.state.updateAvailable){
                return (
                    <View style={{marginTop: 40}}>
                        <TouchableHighlight onPress={this.handleUpdate.bind(this)}>
                            <Text>An update is available.</Text>
                        </TouchableHighlight>
                    </View>
                )
            }
    
        }
    
        render() {
            return (
                <View style={styles.container}>
                    <Text style={styles.welcome}>Welcome message. </Text>
                    {this.renderButton()}
                </View>
            )
        }
    }

Thus, what I'm trying to do, is to check if there is an update available in `componentDidMount` and if it is, then update the state and depending on that state show update button.

But the problem is, when I push the code, and the simulator shows the newest code, but it still shows the button `An update is available`. 

If I change the content of my app and sent it to the code-push server with `code-push release-react AppName ios`, the button shows again, that is good. 
If I click on it the new content is shown and the button disappears and that is also good.

But the problem is if I refresh the app I get again the old content and the button is shown again. And if I click on it again, nothing happens.

Any idea what am I doing wrong?

**Comment by max-mironov** [comment]
Hi there @Borisboky, thanks for reaching us.

So could you please verify that you have wrapped you app within codepush as it is described in tutorial.
```
//add the following before registerComponent is called
let codePushOptions = { checkFrequency: codePush.CheckFrequency.MANUAL };
AppName = codePush(codePushOptions)(AppName);

AppRegistry.registerComponent("AppName", () => AppName);
```

Please let us know if the following fixed your issue.

**Comment by Borisboky** [comment]
No, I haven't wrapped it. It works after wrapping. 

P.S. It is not so obvious in the docs, for the most important part of the puzzle, at least for me. 

Anyway, thanks for the help. 👍

**Comment by max-mironov** [comment]
Thanks for feedback and quick turnaroud @Borisboky ! Will look at on how to improve this in our docs (also feel free to share your ideas or create a PR for this - that would be much appreciated). 

In the meanwhile I believe we can close the item if your issue was fixed.

**Comment by Borisboky** [comment]
Yes, you can close it. Thanks.
