### ISSUE TITLE
Support behind proxy?

### ISSUE THREAD

**Issue by TanTan-TT** [Microsoft/code-push#48]
Hi
I am behind proxy. Is there possible use proxy to access code-push command?

**Comment by geof90** [comment]
Hi @TanTan-TT, could you clarify what exactly you mean by "behind proxy"? What exact problems are you facing when you download the CLI and try to invoke it?

**Comment by TanTan-TT** [comment]
@geof90 My corp has proxy. So if I want to connect to Internet, I must configure http proxy such as 10.xx.xx.xx:80 in perference.

**Comment by lostintangent** [comment]
So you want the CLI to be able to connect to our service via your proxy? Are you configuring a proxy system-wide, or would you want to specify the IP/port to the CLI?

**Comment by lostintangent** [comment]
@TanTan-TT I'm going to close this bug for now since it isn't currently actionable for us. If you are still running into issues, and can let us know what would help unblock you, we can make the necessary changes. Thanks!
