### ISSUE TITLE
Replace Website Logo: Track Sats

### ISSUE THREAD

**Issue by joshuaferrara** [Microsoft/code-push#480]
HI all, I currently have my app listed in the showcase and would like to replace the current listing as our branding has changed. Thank you for your support and awesome product!

Please fill the following out:

- Name: Track Sats
- Homepage (or app store) url: https://tracksats.ferrara.space/
- Brand Guidelines/Licensing: N/A
- Logo: https://tracksats.ferrara.space/launcher.svg

> Example:
>
> Name: Microsoft
> Homepage url: https://microsoft.com
> Brand Guidelines/Licensing: https://www.microsoft.com/en-us/legal/intellectualproperty/trademarks/usage/logo.aspx
> Logo: https://news.microsoft.com/microsoft-news-center-photos/msft_logo_rgb_c-gray/

**Comment by iageoghe** [comment]
Hi Josh, would you please resubmit this asset as a png or jpeg? Thanks.

**Comment by iageoghe** [comment]
Updated!
