### ISSUE TITLE
How to list apps with os attribute?

### ISSUE THREAD

**Issue by adambene** [Microsoft/code-push#481]
version: `code-push-cli@2.0.1-beta / code-push@2.0.1-beta`

`code-push app ls` does not show the os attribute that was given at creation.

How to do that?

**Comment by sergey-akhalkov** [comment]
Hi @adambene, thanks for reaching us. I've seen that you've asked for this in Discord channel, has been your question resolved or do you need any help now? If I get it right - it would be convenient for you if apps table will also contain `os` and `platform` columns?

**Comment by adambene** [comment]
@sergey-akhalkov It was not clear for me what the `os` flag is for. If I am right, it is only for those who use the mobile.azure.com web interface. Anyway it would be convenient to include it in the table along with the platform. Thanks!

**Comment by sergey-akhalkov** [comment]
@adambene, got it, thanks for the clarification.

**Comment by BretJohnson** [comment]
This is a good suggestion.
@iageoghe I'm thinking we do it (at a a minimum) in the Mobile Center CLI. Would be handy for non-RN apps as well. Though having a standard OS suffix on app names lessens the need for this, still good to have.

**Comment by iageoghe** [comment]
Refinement added to larger feature request in queue.

**Comment by pniko** [comment]
Hi @adambene, we are currently working on bringing over all the CodePush commands to the Mobile Center CLI which will have support to list the OS associated with your application. This feature is on our roadmap to be delivered sometime over the next few months.
