### ISSUE TITLE
limit collaborator access to deployment

### ISSUE THREAD

**Issue by imreFitos** [Microsoft/code-push#483]
Is there a way to restrict a collaborator to "Staging" deployment, or do I have to setup a separate application to achieve this? Thanks

**Comment by max-mironov** [comment]
Hey @imreFitos, unfortunatelly there is no way currently to restrict the collaborator access to specific deployments. 
Please see [this reference](https://github.com/Microsoft/code-push/tree/master/cli#app-collaboration) for details. 

> Once added, all collaborators will immediately have the following permissions with regards to the newly shared app:
> 
> View the app, its collaborators, deployments and release history
> **Release updates to any of the app's deployments**

It could probably be a good enhancement although we haven't got any requests about this yet. So for now you could always create a separate app to achieve your requirements.

Please let us now if you have more questions about this.
