### ISSUE TITLE
Unable to remove the App from the list

### ISSUE THREAD

**Issue by Webrusterkk** [Microsoft/code-push#484]
Code-push-cli version  : v2.0.1 beta

┌─────────────────────────────┬─────────────────────┐
│ Name                                                                 │ Deployments                                │
├─────────────────────────────┼─────────────────────┤
│ Master-E.K-01  (Master E.K)                               │
├─────────────────────────────┼─────────────────────┤
│ Master-E.K-02  (Master E.K)                               │                                                      │
├─────────────────────────────┼─────────────────────┤
│ MasterEKiOS                                                      │ Production, Staging                      │
├─────────────────────────────┼─────────────────────┤
│ TCMAndroid                                                      │ Production, Staging                      │
├─────────────────────────────┼─────────────────────┤
│ TCMiOS                                                              │ Production, Staging                      │
└─────────────────────────────┴─────────────────────┘

When i tried to delete the Master-E.k-01 , i'm unable to delete it

`code-push app rm "Master-E.K-01  (Master E.K)"` 

Error Message:
**[Error]  App "Master-E.K-01  (Master E.K)" does not exist.**

Am i missing something? (by d way i don't how those Apps are created actually i created `MasterEKiOS` only .

**Comment by sergey-akhalkov** [comment]
Hi @Webrusterkk, thanks for reaching us. Could you please take a look at https://github.com/Microsoft/cordova-plugin-code-push/issues/257#issuecomment-309146483 and let me know if it helps?

**Comment by Webrusterkk** [comment]
@sergey-akhalkov  thanks for the reply,

after trying with the display name , i'm getting the following error:


```
E:\Projects\MasterEK_Mobile\iOS>code-push app rm "Master-E.K"
Are you sure you want to remove this app? Note that its deployment keys will be PERMANENTLY unrecoverable. (y/N): y
[Error]  App Master-E.K uses a platform type not supported by CodePush: "Objective-C-Swift"
```

**Comment by sergey-akhalkov** [comment]
@Webrusterkk, could you please try to login to [Mobile Center](https://mobile.azure.com/) using email that prints `code-push whoami` command and remove the using portal UI? Please let me know if any changes.

**Comment by Webrusterkk** [comment]
@sergey-akhalkov  there is a Problem over there, i am using feedback service through hockey app and its been integrated to there.. so my question is will that Hockey app name will be shown in `code-push app ls` ?

**Comment by sergey-akhalkov** [comment]
@Webrusterkk, could you please clarify what do you mean by "Hockey app name will be shown in `code-push app ls`"?
`code-push app ls` command displays the list of the apps that have been created by `code-push app add ...` command or in Mobile Center Portal.

**Comment by Webrusterkk** [comment]
@sergey-akhalkov  thanks for the clarification , i haven't created those two names `(Master-E.K-01,02)` . i'm not aware the we can use code-push through mobile center , so i haven't created from the mobile center

**Comment by sergey-akhalkov** [comment]
@Webrusterkk, is there a chance that you has been added as a [collaborator](https://github.com/Microsoft/code-push/tree/master/cli#app-collaboration) for those apps?

**Comment by Webrusterkk** [comment]
@sergey-akhalkov  i'm the collaborator for the apps in Hockeyapp , one with the MasterEKiOS was only created in the code-push only common thing that lies between three is that they share the common `package name`

**Comment by sergey-akhalkov** [comment]
@Webrusterkk, so, do I get it right if the issue is resolved now and you are able to delete those apps via Portal UI?

**Comment by Webrusterkk** [comment]
@sergey-akhalkov  actually they are the apps related to Hockey-app , why am i seeing in code-push cli ?

**Comment by sergey-akhalkov** [comment]
@Webrusterkk, could you please Open one of those apps -> Manage App -> Go to app settings -> Collaborators and share me with the list of collaborators? I believe you can see those apps because you are a collaborator for them.

**Comment by Webrusterkk** [comment]
@sergey-akhalkov  no please , i couldn't see them..

**Comment by sergey-akhalkov** [comment]
@Webrusterkk, if I get it right from your previous messages:
>Are they my HockeyApps?
>i'm the collaborator for the apps in Hockeyapp

you are a collaborator/owner for `Master-E.K-01 (Master E.K), Master-E.K-02 (Master E.K)` apps, that is the reason why you can see them in CodePush CLI too. Does it make sense?

**Comment by Webrusterkk** [comment]
@sergey-akhalkov  yup that makes sense , now coming to my question , i can't remove those app from cli? as i'm the Owner for those apps ...

**Comment by sergey-akhalkov** [comment]
Hi @Webrusterkk, sorry for the delayed response. Could you please provide us with the output of the following command `code-push collaborator ls "Master-E.K"` to make sure if you are collaborator if this app or not. In case you are collaborator you are not able to delete it. Please let us know if any updates.

**Comment by Webrusterkk** [comment]
This is the Error i'm getting after typing that command in `[Error]  App "Master-E.K" does not exist.`
So i tried with this command `code-push collaborator ls "Master-E.K-01"` this is the o/p i got


` krishna30kishore@gmail.com (Owner) │ venkatramanr@newmeksolutions.com  `

but again this was created in the Hockey App , so as i'm in the collaborator ls i can able to see this in my 
codepush cli ? if that is true then i'm owner for this hockey app for morethan a year and i have been using code-push from 6 months , i never seen this in the `code-push app ls` before .. was this included in any later version which i might have missed.

**Comment by sergey-akhalkov** [comment]
@Webrusterkk, could you please try to perform `code-push app rm "Master-E.K-01"` command instead of `code-push app rm "Master-E.K-01 (Master E.K)"` and let me know if there any changes?

**Comment by Webrusterkk** [comment]
@sergey-akhalkov  this is the error i'm getting

`[Error] Internal Server Error `

**Comment by sergey-akhalkov** [comment]
@Webrusterkk, got it, thank you, we'll try to figure out what goes wrong here and let you know if any updates.

**Comment by sergey-akhalkov** [comment]
@Webrusterkk, could you please try to remove your apps via Mobile Center Portal ones again and let me know if it works? We are trying to figure out if the issue is in code-push-cli or in code-push service itself. Thanks for the patience.

**Comment by Webrusterkk** [comment]
@sergey-akhalkov  `Master-E.K-01` and Master-E.K-02` are two apps that can be seen in the codepush cli ,in the Mobile Center this is the image ,
https://user-images.githubusercontent.com/11678494/28018182-dd820210-6599-11e7-9cd7-68b8be0192ba.PNG

so i couldn't figure out which one will be Master-E.K-01  or Master-E.K-02 that is related to the Code-push cli

**Comment by sergey-akhalkov** [comment]
@Webrusterkk, please try to open one of those apps and try to take a look at browser url to determine what the app has been opened. As for me I have app with name `rncp 210 release`, but my url looks like: `https://mobile.azure.com/users/sergey.akhalkov/apps/rncp210release/settings/details`. As you can see the system app name is `rncp210release` and user friendly app name is  `rncp 210 release`.
Please let me know if it helps.

**Comment by Webrusterkk** [comment]
@sergey-akhalkov  when i tried the way you said `https://mobile.azure.com/users/krishna30kishore-62z7/apps/Master-E.K-01/settings` that was my url in browser and it is asking for `Edit in HockeyAPp`  but no option to delete. Even i tried near the hamburger icon , `Copy app secret ` is only one i can see in the list

**Comment by sergey-akhalkov** [comment]
@Webrusterkk - could you please take a look at the following image and let me know if it helps?
![image](https://user-images.githubusercontent.com/4928157/28416602-568773f0-6d5d-11e7-86dd-fb3074dbe12d.png)

**Comment by sergey-akhalkov** [comment]
Do I get it right if there is now "Delete App" options?

**Comment by Webrusterkk** [comment]
Yes , there is no delete app option  , 

here is the image :  

![capture](https://user-images.githubusercontent.com/11678494/28418727-63a04c70-6d7a-11e7-9116-ccc58b220101.PNG)


Another app i.e `(MasterEKiOS)`   i can able to see the Delete Option and (i can able to delete this in Code-push cli itself , i tried before moving my app to appstore) . For reference please find the image:
![capture1](https://user-images.githubusercontent.com/11678494/28418817-c625087c-6d7a-11e7-85b7-4db10ed2885a.PNG)

**Comment by sergey-akhalkov** [comment]
@Webrusterkk, got it, thank you for the clarification. It looks weird, so I'll try to figure out what goes wrong here and let you know if any updates. Thanks for the patience.

**Comment by Webrusterkk** [comment]
@sergey-akhalkov  No -problem , any further info please do ask me , i will provide what ever info i can.

**Comment by sergey-akhalkov** [comment]
Hi @Webrusterkk, I've found out that Mobile Center (and CodePush too) does not currently support apps deletion that have been migrated from HockeyApp, but we are working on it. As workaround, you could try to delete the apps via HockeyApp portal itself.

Also, we are going to change "internal server error" message to more informative and user-friendly.

Please let me know if you have any questions or see any issues.

**Comment by Webrusterkk** [comment]
@sergey-akhalkov  in the `code-push app ls` is there a way to see the apps that are related to code-push only because want to keep it clean and focused to the deployment only, Hockey app we are using it as distribution , so  is there a chance to see the list only added through code-push ?

**Comment by sergey-akhalkov** [comment]
@Webrusterkk, unfortunately, I don't think so, we only have `code-push app ls` command that has  no additional parameters, so it prints all available apps only. I'll try to figure out what we could do here and let you know if any news.

**Comment by Webrusterkk** [comment]
@sergey-akhalkov  now i came to know that if there are no `Production/Staging` those apps are not created through code-push , before that we thought only apps related to code-push will be seen , now i will make aware of my team about this . thanks for the TIP :)

**Comment by pniko** [comment]
Hi @Webrusterkk, we are currently bringing over all the CodePush functionality into the Mobile Center CLI which supports deleting applications directly from it. Look out for an announcement sometime over the next few months with details regarding this. It should make managing apps and performing releases a lot more streamlined then it is today with just the CodePush CLI. Thanks!

**Comment by Webrusterkk** [comment]
@pniko  so we can do what ever the activites we are doing from CLI through the UI ?

**Comment by pniko** [comment]
@Webrusterkk with the exception of performing a release (promote excluded) everything should be able to be accomplished through the Mobile Center UI and CLI. Today you can manage your App using Mobile Center, but it doesn't currently have all the management functions for your deployments and releases. If you need to delete or transfer your application to a different account, logging into the UI is the recommended approach for the moment.
