### ISSUE TITLE
what's wrong ? 

### ISSUE THREAD

**Issue by Gavin-js** [Microsoft/code-push#487]
![image](https://user-images.githubusercontent.com/10543889/28570753-2a4fe36c-7172-11e7-8d4e-2f217b3c620c.png)

**Comment by sergey-akhalkov** [comment]
Hi @Gavin-js, thanks for reaching us. Please use `react-native-code-push` repo to create new issue using [this template](https://github.com/Microsoft/react-native-code-push/issues/new).
