### ISSUE TITLE
Question about rollout and disabling behavior

### ISSUE THREAD

**Issue by JAStanton** [Microsoft/code-push#490]
Here is the scenario... I deployed a new major version of the app via the app store. My first code-push for this major version is an experiment to 25% of my users. I pushed the experiment and I noticed a bug. I fixed the bug and I'm unsure how to proceed? I want to either rollback or update the 25% of the users... Here is what I did:

- I cannot rollback because there is nothing to rollback to (first release for this new major version)/
- I tried to promote from staging (with the fix) to production to 25% of users, however this *failed* because there was currently a rollout in progress.
- I decided to patched / disabled the rollout. 
- I then promoted from staging (with fix) to production to 25% of the users.

My questions: 
- I'm assuming the people that are now on a disabled build are rolled back?  Rolled back to whatever I bundled the app natively with?
- When I promoted again to 25% will it be the same 25%? 

this is the history:
```
// 1.10 build stable
├───────┼────────────────────────────────────────────────────────┼─────────────┼───────────┼───────────────────────────┼───────────────────────────────┤
│ v519  │ 9 days ago                                             │ 1.10.*      │ No        │ {"buildNum": 4116,        │ Active: X% (X of Y)           │
│       │ (Promoted v1011 from "staging")                        │             │           │ "shortCommit": "aa7c0d6"} │ Total: X                      │
├───────┼────────────────────────────────────────────────────────┼─────────────┼───────────┼───────────────────────────┼───────────────────────────────┤
// Between 9 days ago and 3 hours ago I pushed 1.11 to app store
// This is first code push promotion to 1.11 build. It was a rollout to 25% of users... This has a bug.
│ v520  │ 3 hours ago                                            │ 1.11.*      │ No        │ {"buildNum": 4200,        │ Active: X% (X of Y)           │
│       │ (Promoted v1026 from "staging")                        │             │           │ "shortCommit": "6f20f3f"} │ Total: X (X pending)          │
│       │                                                        │             │           │                           │ Disabled: Yes                 │
├───────┼────────────────────────────────────────────────────────┼─────────────┼───────────┼───────────────────────────┼───────────────────────────────┤
// this is the bug fix for the previous release (v520)
│ v521  │ 31 minutes ago                                         │ 1.11.*      │ No        │ {"buildNum": 4202,        │ Active: X% (X of Y)           │
│       │ (Promoted v1027 from "staging")                        │             │           │ "shortCommit": "ed53e79"} │ Total: X (X pending)          │
│       │                                                        │             │           │                           │ Rollout: 25%                  │
├───────┼────────────────────────────────────────────────────────┼─────────────┼───────────┼───────────────────────────┼───────────────────────────────┤
```

**Comment by iageoghe** [comment]
Hi, promoting or releasing with a rollout will not automatically target the same devices from a previous rollout. Indeed, that functionality does not currently exist. 

If you are at V1 with a rollout that has a bug, my recommendation is to make a release with the original bundle. Why? Currently we don't have a way to rollback to what was shipped with the binary. We have written a specification for this feature, but at the moment it is on our backlog. 

With a V2 that has you back where you started, you can proceed to make your patched release and roll it out to 25%. Does that make sense?

**Comment by JAStanton** [comment]
Makes sense to me. So what happened to my users that were on my release that I disabled? Do they stay on that release?

**Comment by iageoghe** [comment]
The users that actually downloaded it will stay on it until they upgrade to your new, baseline release. I would make that release mandatory.

**Comment by JAStanton** [comment]
@iageoghe this helped immensely thank you!
