### ISSUE TITLE
Authentication Failed screen on code-push login

### ISSUE THREAD

**Issue by blairvanderhoof** [Microsoft/code-push#493]
Getting an Authentication Failed screen when trying to do code-push login

![image](https://user-images.githubusercontent.com/833890/28885184-c5f8462c-7769-11e7-9b17-6d6128b01146.png)

**Comment by HsanBenJobrane** [comment]
Go check it now, it's working again

**Comment by JakeRawr** [comment]
This is happening now again

**Comment by crHand** [comment]
@JakeRawr It's working again!
