### ISSUE TITLE
No browser window is opened for `code-push register`

### ISSUE THREAD

**Issue by BrianSo** [Microsoft/code-push#496]
No browser window is opened after running the following command.
```
$ code-push register xxxxxx@hotmail.com
Please login to Mobile Center in the browser window we've just opened.

Enter your token from the browser:
```

code-push version: 2.0.2-beta
OS: macOS Sierra 10.12.3
Default web browser: Google Chrome

**Comment by max-mironov** [comment]
Hi there @BrianSo and thank for reaching us. 
At that moment I've tried to follow you repro steps and haven't seen any issues with this.
I've tried it with macOS Sierra 10.12.5, code-push 2.0.2-beta and Chrome browser also.

So can you please confirm that the issue is still active and reproducible for you?

**Comment by BrianSo** [comment]
Thank you!

At the time that v2.0.2-beta is not working, I tried other tools that also open browser and they worked (karma test and react native remote debugging). At that day I downgraded code-push to 2.0.1-beta and it worked. Today I reinstalled 2.0.2-beta and worked also.

Did you tried it in a brand new environment that have not installed code-push before? If yes I think we can close this now, otherwise I am going to test it on a new computer tomorrow.

**Comment by max-mironov** [comment]
@BrianSo I believe the problem could be related to some kind of server issue being temporary not available. I've tried it on my local machine and it has previous versions before. 
Anyway it would be great if you check out it once more on a new computer tomorrow and let us know the results.

**Comment by BrianSo** [comment]
Today I tried on a new computer and it worked. Maybe my case was a corner case.

**Comment by max-mironov** [comment]
Thanks for update @BrianSo and let us know if you see any issues with code push in future.

**Comment by herbertbruno** [comment]
@BrianSo i do not have access to the server browser.  i only have access to the terminal. when i try to login it gives me message "Please login to Mobile Center in the browser window we've just opened. 
Enter your token from the browser: "

Is there any other way to get the token manually

**Comment by BrianSo** [comment]
@herbertbruno I think you must register your account with a browser, but you can login later without using browser. You will use **access key**.

The following are copied from [https://microsoft.github.io/code-push/docs/cli.html](https://microsoft.github.io/code-push/docs/cli.html)

> Access Keys
> If you need to be able to authenticate against the CodePush service without launching a browser and/or without needing to use your GitHub and/or Microsoft credentials (e.g. in a CI environment), you can run the following command to create an “access key” (along with a name describing what it is for):
> ```
> code-push access-key add "VSTS Integration"
> ```
> For security, the key will only be shown once on creation, so remember to save it somewhere if needed! After creating the new key, you can specify its value using the --accessKey flag of the login command, which allows you to perform “headless” authentication, as opposed to launching a browser.
> ```
> code-push login --accessKey <accessKey>
> ```
> When logging in via this method, the access key will not be automatically invalidated on logout, and can be used in future sessions until it is explicitly removed from the CodePush server. However, it is still recommended that you log out once your session is complete, in order to remove your credentials from disk.

**Comment by herbertbruno** [comment]
it works. Thank you

**Comment by baartho** [comment]
There is definitely an intermittent problem happening with the Login feature. 

I was ran `code-push login` but it didn't open any browser window and showed an error saying `[Error]  A token must be specified.`. 

After waiting for a couple of minutes I ran the command again and it worked (I didn't even close the CMD console).
