### ISSUE TITLE
Management SDK, Uncaught TypeError: Invalid Version: at new SemVer (semver.js:293)

### ISSUE THREAD

**Issue by digaus** [Microsoft/code-push#497]
Wanted to use the management SDK with an Ionic App for easier management, getting this error when trying to create an instance of the CodePush class... any ideas?

```
Uncaught TypeError: Invalid Version: 
    at new SemVer (semver.js:293)
    at compare (semver.js:566)
    at Function.lt (semver.js:600)
    at Object.<anonymous> (patch-core.js:10)
    at Object.<anonymous> (patch-core.js:54)
    at __webpack_require__ (bootstrap 87b55b8980113f5c133b:54)
    at Object.<anonymous> (agent.js:6)
    at Object.<anonymous> (agent.js:106)
    at __webpack_require__ (bootstrap 87b55b8980113f5c133b:54)
    at Object.freeExports (index.js:10)
```

Code-Push CLI: 2.0.2-beta
Code-Push SDK: 2.0.2-beta

**Comment by max-mironov** [comment]
Hi @digaus 
Could you please share with us a minimum code (and even better exact repro steps of what you are doing) so we can try it on our machines and get out if is is working for us?

**Comment by digaus** [comment]
@max-mironov 
What I wantd to achive is an Ionic App using the management SDK. So I started a new blank Ionic project and ran `npm installed code-push --save`. Then I just imported and tried to use it:

```
import  CodePush = require('code-push');
export class HomePage {
    var codePush = new CodePush("myAccessKey");
    ...
}
```

**Comment by digaus** [comment]
Managed to get it to work with commenting out the superproxy. Works so far , not sure what it does thought
```
//var superproxy = require("superagent-proxy");
//superproxy(superagent);
```

**Comment by max-mironov** [comment]
@digaus Well, that looks strange but without debugging on sample its hard to say what's wrong here. Can we consider the issue to be resolved so far?

**Comment by digaus** [comment]
Yep looks like:)
