### ISSUE TITLE
Feature request: add code-push collaborator promote <appName> <person>

### ISSUE THREAD

**Issue by syzer** [Microsoft/code-push#498]
Currently, theres no way to change owner in cli, or i'm wrong?

**Comment by max-mironov** [comment]
Hi @syzer,
So I believe [Ownership Transfer](https://github.com/Microsoft/code-push/tree/master/cli#ownership-transfer) section of docs can answer your question. BTW do you have any objection in using Mobile Center for this?

**Comment by syzer** [comment]
Hi @max-mironov ,
No objection.. It's just a bit inconvenient, but can close.

**Comment by max-mironov** [comment]
Thanks for feedback, we'll try to improve the process going further.
