### ISSUE TITLE
[Error]  The session or access key being used is invalid

### ISSUE THREAD

**Issue by maggialejandro** [Microsoft/code-push#499]
Hi. I'm getting this error when trying to _code-push release-react_

> [Error]  The session or access key being used is invalid; please run "code-push login" again. If you are on an older version of the CLI, you may need to run "code-push logout" first to clear the session cache.

When trying to _code-push login_ I get this error:

![captura de pantalla 2017-08-22 a la s 17 27 07](https://user-images.githubusercontent.com/3394748/29585911-2d8a6004-875f-11e7-990d-a5de73d6dfc8.png)

Eventually, I get _Authentication succeeded_ but after I log in it throws me the same error when trying to _code-push release-react_ ([Error]  The session or access key being used is invalid[...])

On https://mobile.azure.com/settings/apitokens it show me "Too many requests"

![captura de pantalla 2017-08-22 a la s 17 29 16](https://user-images.githubusercontent.com/3394748/29585995-8205360e-875f-11e7-8e32-6219f314a646.png)

code-push v2.0.2-beta

any ideas?
Thanks in advance!

**Comment by jdgeier** [comment]
I'm getting this error too. I think it may be on Microsoft's side

**Comment by JesusTSeger** [comment]
Getting this as well. I reached out to Microsoft on twitter so if I hear back then I will pass that onto this thread.

**Comment by stinju** [comment]
FYI, issue just went away for me.

**Comment by maggialejandro** [comment]
Yes, it works fine right now.

El 22 ago. 2017 6:21 PM, stinju <notifications@github.com> escribió:

FYI, issue just went away for me.

**Comment by max-mironov** [comment]
Hey guys, sorry for that, service was temporary unavailable, the issue is mitigated now, thanks for reporting!
