### ISSUE TITLE
Crosswalk / 503 error on Dependencies

### ISSUE THREAD

**Issue by CogCR** [Microsoft/code-push#502]
Hi,
Since Saturday, one of links required for build  is generating error. 
Can we have these cloned and hosted on Azure to avoid these issues.

Thanks
 > Could not resolve org.xwalk:xwalk_core_library:23+.
         > Failed to list versions for org.xwalk:xwalk_core_library.
            > Unable to load Maven meta-data from https://download.01.org/crosswalk/releases/crosswalk/android/maven2/org/xwalk/xwalk_core_library/maven-metadata.xml.
               > Could not GET 'https://download.01.org/crosswalk/releases/crosswalk/android/maven2/org/xwalk/xwalk_core_library/maven-metadata.xml'. Received status code 503 from server: Service Unavailable

Thanks

**Comment by sergey-akhalkov** [comment]
Hi @CogCR, thanks for reaching us. 
Could you please clarify - are you trying to build your app via Mobile Center or on your local machine?
Also, have you seen this temporary workaround https://stackoverflow.com/a/46013326 ?

**Comment by CogCR** [comment]
Awesome. Will try the same and update. I am unable to use mobile center  as it still does not support cordova but only supports react. Thanls.

**Comment by sergey-akhalkov** [comment]
@CogCR, got it, please let me know if workaround helps. 
By the way, I believe the issue does not relate to CodePush itself, so I'm closing this.

Please feel free to create new issue if you have any questions or see any issues.

**Comment by CogCR** [comment]
Thanks Sergey for immediate help. This issue is not releated to codepush but download01.org was down.
Resolution for anybody who hits this later although this is already documented in stackoverflow:

A) Find the last working version at this location: Assuming this is X.X.X.X
In my case, the current version of X.X.X.X was 23.53.589.4:
**$APP_DIR\platforms\android\build\intermediates\exploded-aar\org.xwalk\xwalk_core_library**

B) Open.grade file at below location 
**$APP_DIR\platforms\android\cordova-plugin-crosswalk-webview** 

C) Modify as per below: 

 **dependencies {
        //compile xwalkSpec		
    compile 'org.xwalk:xwalk_core_library:X.X.X.X'
    }**

That's all. Now you can do your releases as usual.
