### ISSUE TITLE
New Website Logo: People of the Park

### ISSUE THREAD

**Issue by ReneKrewinkel** [Microsoft/code-push#505]
Name: People of the Park
App Store url: https://itunes.apple.com/nl/app/people-of-the-park/id1276036755
Logo: https://api.xhiby.com/image-cache/911b0f3d1aad319395133537c0a31f7a/icon/people-of-the-park.svg

**Comment by sergey-akhalkov** [comment]
Hi @nionata, your logo was added, thanks for this!
