### ISSUE TITLE
Get details of code push deployment

### ISSUE THREAD

**Issue by apolishch** [Microsoft/code-push#506]
Is it possible to find out what the version of code deployed to a code-push deployment is (e.g. a Git Sha or similiar)

**Comment by max-mironov** [comment]
Hi @apolishch, unfortunately I believe it is not. Probably you could put this information manually in the [description](https://github.com/Microsoft/code-push/tree/master/cli#description-parameter) parameter when releasing  new code-push update, although it is not super handy it could be a solution sometimes.

**Comment by apolishch** [comment]
Follow up question:

Is it possible to download (from the command line, the Azure GUI, or otherwise) the code that is in a particular deployment?

**Comment by sergey-akhalkov** [comment]
Hi @apolishch, yes, it's possible to download CodePush update contents: 
```bash
$ code-push deployment history rn048cp500-android Staging --format json
[
  {
    "description": "",
    "isDisabled": false,
    "isMandatory": false,
    "rollout": 100,
    "appVersion": "1.0",
    "packageHash": "a6db39de1ffa651c429008523c6229131afcb351bf00bda482dad85dd0905612",
    "blobUrl": "https://codepushint.blob.core.windows.net/storagev2/QKsbQkY7jOL8bv9eiBn7jHybaaxga81e9dfc-84e3-4c16-a9e5-f5181d4a844a",
    "size": 194463,
    "manifestBlobUrl": "https://codepushint.blob.core.windows.net/storagev2/9HmuKAbBAITz7Wh4YKVAK4HOZKxta81e9dfc-84e3-4c16-a9e5-f5181d4a844a",
    "releaseMethod": "Upload",
    "uploadTime": 1504528135925,
    "label": "v1",
    "releasedBy": "sergey.akhalkov@akvelon.com",
    "metrics": {
      "active": 1,
      "downloaded": 1,
      "failed": 0,
      "installed": 1,
      "totalActive": 1
    }
  }
]
```
The `blobUrl` field contains link to zip that you can download.

Please let me know if it helps or if you have any other questions.

**Comment by apolishch** [comment]
@sergey-akhalkov thanks so much! that is exactly what I was looking for :)

**Comment by max-mironov** [comment]
Thanks for quick reply @apolishch, I believe we can close the issue at that moment. Please feel free to reach us in case you have more q's.
