### ISSUE TITLE
CodePush from CI

### ISSUE THREAD

**Issue by pkwak-sf** [Microsoft/code-push#507]
Hello. I'm wondering if there is a way to publish on a CI machine/VM (CircleCI/azure mobile-center/etc) without logging into a user-account with username/pw on that machine.

Eg, by using a key or something, like
`> code-push release-react [app name] [platform] --key [some-key]`

Thanks!

**Comment by sergey-akhalkov** [comment]
Hi @pkwak-sf, thanks for reaching us.

You are probably looking for access keys, please take a look at this article https://github.com/Microsoft/code-push/tree/master/cli#access-keys and let me know if it helps.

Please also let me know if you have any other questions.

**Comment by pkwak-sf** [comment]
Exactly what I was after! Thank you!

**Comment by A-Tokyo** [comment]
@sergey-akhalkov How can I access the latest version of the docs you mentioned? Thanks a lot!

**Comment by A-Tokyo** [comment]
Latest docs link: https://www.npmjs.com/package/code-push-cli#access-keys

**Comment by alex-a-pereira** [comment]
@A-Tokyo thanks man!
