### ISSUE TITLE
[Android] Multi Deployment - (React Native) App always crashes

### ISSUE THREAD

**Issue by apolishch** [Microsoft/code-push#508]
After following the instructions here:
https://microsoft.github.io/code-push/docs/react-native.html#link-8

I have the following contents of my `app/build.gradle`:

```
    buildTypes {
        debug {
            buildConfigField "String", "CODEPUSH_KEY", '""'
            buildConfigField "Boolean", "PRODUCTION_RELEASE", "false"
        }

        staging {
            buildConfigField "String", "CODEPUSH_KEY", '"<% Correct Code push key goes here %>"'
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            signingConfig signingConfigs.stagingSigned
            buildConfigField "Boolean", "PRODUCTION_RELEASE", "false"
        }
        
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            signingConfig signingConfigs.releaseSigned
            buildConfigField "String", "CODEPUSH_KEY", '"<% Correct Code push key goes here %>"'
            buildConfigField "Boolean", "PRODUCTION_RELEASE", "true"
        }
    }
```

```
dependencies {
    .......
    debugCompile 'com.balsikandar.android:crashreporter:1.0.9'
    stagingCompile 'com.balsikandar.android:crashreporter:1.0.9'
}
```

Finally my `MainApplication.java`:
```
protected List<ReactPackage> getPackages() {
      ArrayList<ReactPackage> packageList = new ArrayList();
      ...
      packageList.add(new CodePush(BuildConfig.CODEPUSH_KEY, MainApplication.this, BuildConfig.DEBUG));
      if (BuildConfig.PRODUCTION_RELEASE == true) {
        packageList.add(new FIRAnalyticsPackage());
      }
      return packageList;
    }
```

When I run:
`react-native run-android`, this behaves as you would expect, e.g. Crash Reporting is installed, Firebase analytics does not run, and the local bundle is loaded

When I run 
`react-native run-android --variant=release`
It also behaves as you would expect, e.g. Crash Reporting is not installed, Firebase analytics runs, and the bundle is fetched from production.

When I run:
`react-native run-android --variant=staging`
Crash reporting installs, however the app crashes as soon as it is opened.

`code-push debug android` seems to show the file being loaded from localhost, not Code Push:
`[05:44:43] Loading JS bundle from "assets://index.android.bundle"`

The Crash report shows as seen in the screenshot below:
<img width="312" alt="screen shot 2017-09-06 at 5 55 27 pm" src="https://user-images.githubusercontent.com/286833/30124367-d3fb221a-932c-11e7-8ed9-257fe10adfda.png">

How have I misconfigured my staging build? Why is it attempting to read from the BatchedBridge rather than the Code Push Staging deployment?

**Comment by max-mironov** [comment]
Hey @apolishch, regarding to this section: https://github.com/Microsoft/react-native-code-push#android try to change `staging` config name to `releaseStaging` in accordance with the following:

> _NOTE:_ The naming convention for releaseStaging is significant due to this [line](https://github.com/facebook/react-native/blob/e083f9a139b3f8c5552528f8f8018529ef3193b9/react.gradle#L79).

**Comment by apolishch** [comment]
After changing the buildType to `releaseStaging` the problem persists

**Comment by max-mironov** [comment]
@apolishch got it, just to clarify, are you running `react-native run-android --variant staging` or `react-native run-android --variant releaseStaging`?

**Comment by apolishch** [comment]
@max-mironov `react-native run-android --variant=releaseStaging`
When running in simulator, this results in a permanent white screen
When running on device, this results in an identical crash report to the one above

**Comment by max-mironov** [comment]
@apolishch also can you please verify if we need to change ` stagingCompile 'com.balsikandar.android:crashreporter:1.0.9'` to ` releaseStagingCompile 'com.balsikandar.android:crashreporter:1.0.9'` in this case?

**Comment by apolishch** [comment]
@max-mironov Yup that was done

**Comment by sergey-akhalkov** [comment]
Hi @apolishch, please take a look at https://github.com/Microsoft/react-native-code-push/issues/991#issuecomment-328074153 - it might help you.

**Comment by max-mironov** [comment]
Hey @apolishch, did you get a chance to look at the link from above, do you have any updates on this?

**Comment by max-mironov** [comment]
Closing this for now, please feel free to reopen if the issue still persist (probably would be better to create in react-native repo as it seems more relevant to SDK rather than CLI)

**Comment by youngjuning** [comment]
https://github.com/youngjuning/youngjuning.github.io/issues/187
