### ISSUE TITLE
Cannot get update after rollback。

### ISSUE THREAD

**Issue by fenglu09** [Microsoft/code-push#509]
In my production environment， there are `70` rollbacks in one of my version.
And I found that，those device has rollbacked could not update to the version has rollbacked. 
Is there any way let those `70` devices udpate to the newest version?
It would be better if the devices has rollbacked could get update in the next update check.
```
├───────┼──────────────┼─────────────┼───────────┼─────────────┼──────────────────────────┤
│ v6    │ 5 days ago   │ 1.2.6       │ Yes       │             │ Active: 41% (157 of 386) │
│       │              │             │           │             │ Total: 157 (28 pending)  │
│       │              │             │           │             │ Rollbacks: 70            │
└───────┴──────────────┴─────────────┴───────────┴─────────────┴──────────────────────────┘
```
 `code-push` version: `2.0.1-beta`

**Comment by max-mironov** [comment]
Hey @fenglu09, so that's true and update that was once rolled back shouldn't be applied any more due to this [check](https://github.com/Microsoft/react-native-code-push/blob/master/CodePush.js#L362).

So you can produce new update targeting the same binary version and code push should try to apply it again to those devices. If they would be rolled back again then this update shouldn't be applied again.

Also there is [ignoreFailedUpdates](https://github.com/Microsoft/react-native-code-push/blob/85e094f7e11723b02b83fec1451bdae72764bc29/CodePush.js#L362) syncOption parameter that allows you to ignore failed updates but I'm not sure if it is a good idea to use it.

**Comment by fenglu09** [comment]
Thanks for you reply. If I produce new update targeting the same binary version, those devices has updated success will receive update again. It will make a bad user experience.
If I can produce update targeting some ` label`,  It will be better.

**Comment by max-mironov** [comment]
@fenglu09 I completely understand your concerns here but I believe that our release command doesn't have an option to determine whether it should be applied only to those devices that were already rolled back. 
Probably if you are on react-native you could try e.g. [ON_NEXT_SUSPEND](https://github.com/Microsoft/react-native-code-push/blob/master/docs/api-js.md#installmode) install mode to improve user experience and make the process of applying new updates less invasive.

**Comment by fenglu09** [comment]
Unfortunately , I'm on `Corodva`.  Is it possible  to support release update  target on `label`  or Update that was once rolled back  can be applied again ?

**Comment by max-mironov** [comment]
I'm not aware of any plans of supporting this feature in the nearest time, but what do you think of using 
`syncOptions.ignoreFailedUpdates = false` in your case? This way update will be installed even if it was rolled back previously.
Well, its not an ideal solution but you can add some modifications to the SDK to add e.g. max number of retries and limit the attempts to install that update to some kind of constant e.g. 5. 
But frankly I believe that the rule of thumb is that if update was rolled back it shouldn't be applied at all. 
It would be better to identify why the update was rolled back and that way to prevent such situations in future.

**Comment by fenglu09** [comment]
Maybe `syncOptions.ignoreFailedUpdates = false` is a solution. 
 How can I get the reason why the update was rolled back ?

**Comment by max-mironov** [comment]
@fenglu09 probably you could use some kind of crash reporting tools for that but please see similar question in cordova-code-push repository for more details: https://github.com/Microsoft/cordova-plugin-code-push/issues/140

**Comment by fenglu09** [comment]
Thanks for your help !  I'll  close this issue.
