### ISSUE TITLE
Multiple admins on team?

### ISSUE THREAD

**Issue by JAStanton** [Microsoft/code-push#515]
So I notice only 1 person on my team is able add deployments, is it possible that I can extend that ability to everyone my team? Or create multiple admins?

**Comment by max-mironov** [comment]
Hey @JAStanton, unfortunately this cannot be done via adding user as a collaborator but you can do this trick via mobile center functionality.  Please [follow this steps](https://github.com/Microsoft/code-push/tree/master/cli#ownership-transfer) to add new admins here.

**Comment by max-mironov** [comment]
Closing the item, please let us know if you have more questions.
