### ISSUE TITLE
Unclear from docs: are releases scrolled off the top of deployment history still available?

### ISSUE THREAD

**Issue by RoboTeddy** [Microsoft/code-push#518]
The docs for [Viewing Release History](https://microsoft.github.io/code-push/docs/cli.html#link-9) say

> You can view a history of the 50 most recent releases for a specific app deployment

Are releases that get scrolled off still available? Here's the sequence of events that lead me to ask:

(1) Someone installs an iOS app (binaryVersion=1.1)
(2) A new release with targetBinaryVersion="1.1" is released.
(3) The user happens not open their app for a long time, and so don't receive this new release.
(4) Meanwhile, an additional 75 releases are made with targetBinaryVersion="1.2". All releases targeting 1.1 have now been scrolled off the viewable deployment history.
(5) The user finally opens their binaryVersion=1.1 app. Do they still receive their 1.1 update?

I hope they do receive the update! If they don't:
* Doh! I have to work around this on my end
* It's rather counterintuitive -- let's document the fact that only the 50 most recent releases in a deployment can be downloaded by clients!

Thanks for the great project.

**Comment by sergey-akhalkov** [comment]
Hi @RoboTeddy, thanks for reaching us.
Yes, it probably would be helpful to document that only the 50 most recent releases in a deployment can be discovered and downloaded by clients, thank you!
By the way, you could avoid this limitation by creating new deployment and releasing new app binary version that will point to it.
`promote` feature also could help you to manage your production deployment - it will contain only "good and tested" releases from staging.

**Comment by max-mironov** [comment]
@RoboTeddy thanks for your feedback, we've added note about this here https://github.com/Microsoft/code-push/commit/e1c20ab0ab1cf855d0e35fc7873ddea41f952f31. Hope things would be clearer now.
