### ISSUE TITLE
New Website Logo: Arrow Card Mobile App

### ISSUE THREAD

**Issue by stantoncbradley** [Microsoft/code-push#519]
Please fill the following out:

- Name: Arrow Card Mobile App
- Homepage (or app store) url: https://itunes.apple.com/us/app/arrow-card/id1228440036
- Brand Guidelines/Licensing: none
- Logo: https://www.dropbox.com/s/ebuwrql1nj8tgwl/Arrow%20Up%20icon.svg?dl=0

> Example:
>
> Name: Microsoft
> Homepage url: https://microsoft.com
> Brand Guidelines/Licensing: https://www.microsoft.com/en-us/legal/intellectualproperty/trademarks/usage/logo.aspx
> Logo: https://news.microsoft.com/microsoft-news-center-photos/msft_logo_rgb_c-gray/

**Comment by max-mironov** [comment]
@stantoncbradley thank you for your request, your logo has been added.
