### ISSUE TITLE
how to show bundle version for users

### ISSUE THREAD

**Issue by adambene** [Microsoft/code-push#520]
Hello, which is the official way to show the bundle version on my app's UI?
The bundle version is bumped each time we release a CodePush version.

Label is not unique across apps/deployments.
Target binary version does not change after a CodePush release and promotion.

There is a field called `description` but I am curious about the official best practice.

**Comment by max-mironov** [comment]
Hello @adambene, AFAIK there is no official way to mark bundle versions of codepush releases for users. 
So its up to you to decide how you will distinguish different releases (of course if you ever need this). Probably you could use a combination of app version and label, may be you can pass additional info in `description` field like GUID on producing new release to extract it later. You can decide which way is more convenient to you.

**Comment by adambene** [comment]
Hello @max-mironov,
It is essential to know the version of the bundle when investigating bug reports.
An other use case is to verify that the new bundle version is released properly.
It would be nice to have the version number from the package.json in CodePush.
We can not use the label attribute, because it varies accross apps/deployments so we can not tag the release commit in git.
The only possibility to trace back a given released bundle to a git commit is to have a git tag (a version number) or a git commit hash in the description.

**Comment by adambene** [comment]
To sum it up, I have a feature request for a dedicated field to be able to track back a released bundle to a git commit.
Ideally this field should be extracted from the package.json's version field automatically.

**Comment by max-mironov** [comment]
@adambene thanks for feedback, please take a look at https://github.com/Microsoft/code-push/issues/273   if it is not something you are looking for?

**Comment by max-mironov** [comment]
@adambene thanks for feedback, please take a look at https://github.com/Microsoft/code-push/issues/273   if it is not something you are looking for?

**Comment by adambene** [comment]
@max-mironov well, it can be a solution. But versioning would be essential.

**Comment by max-mironov** [comment]
@adambene got it! Do you mind if we close this item in favor of #273 as seems that the latter should satisfy your needs?

**Comment by adambene** [comment]
@max-mironov if you don't think this as a core feature then #273 would be ok for me. Then you can close this issue. Thanks!

**Comment by sergey-akhalkov** [comment]
Hi @adambene, closing this because I think that "custom metadata" feature will be flexible enough to allow developers to store bundle version in their custom metadata.
