### ISSUE TITLE
New Website Logo: Sudzy POS

### ISSUE THREAD

**Issue by sudzy-group** [Microsoft/code-push#521]
- Name: Sudzy POS
- Homepage (or app store) url: https://business.sudzy.co 
- Brand Guidelines/Licensing: You can use our logo
- Logo: http://cdn.sudzy.co/icons/appstore.png

Thank you so much for your great work and time!

**Comment by max-mironov** [comment]
@sudzy-group - your logo has been added! Thank you!

**Comment by sudzy-group** [comment]
Thank you! Much appreciated!

Roy@ Sudzy team
