### ISSUE TITLE
metadata.label not populated on real device

### ISSUE THREAD

**Issue by agersoncgps** [Microsoft/code-push#522]
"react-native-code-push": "^5.1.0-beta",
"react-native": "^0.47.2",

When I run in the iOS simulator I get a value for metadata.label, however, when I run on a real device its blank.

```
componentDidMount() {
    codePush.getUpdateMetadata().then(metadata => {
      this.setState({
        code_push_label: metadata.label,
        code_push_version: metadata.appVersion,
        description: metadata.description
      });
    });
  }
```

**Comment by max-mironov** [comment]
Hello @agersoncgps, I have tried to reproduce your issue on my side but with no luck.
Everytime I hit `Press for Update Metadata` button I was able to get label parameter as expected. Tested on iPhone7 iOS11.0.

I've attached demo, so could you please take a look at this and let me know if you are able to reproduce issue with it on your side? (just do `npm i` and change deployment key to yours to test it).
[issue522.zip](https://github.com/Microsoft/code-push/files/1367929/issue522.zip)
Looking forward to get results from you.

**Comment by max-mironov** [comment]
@agersoncgps please let us know if you have a chance to look at this.

**Comment by max-mironov** [comment]
Closing this as of no response, please let us know if you need any assistance with this.
