### ISSUE TITLE
I used code push successfully updated xx.apk, but this has been installed apk version has not changed, which is why

### ISSUE THREAD

**Issue by heart-bool** [Microsoft/code-push#525]
![image](https://user-images.githubusercontent.com/26360445/31513861-347ef6be-afc2-11e7-9a51-bd76a56f7585.png)
The updated apk version has not changed. Is this normal? For example, I pushed an update to the code push server and changed the versionName in build.gradle to 1.0.1 (1.0.0 before). My problem is that the version installed before the update is 1.0.0, but After updating the version number is still 1.0.0. My understanding is that this version will change with the update, or is my understanding wrong?

**Comment by ruslan-bikkinin** [comment]
Hi @heart-bool and thanks for submitting the issue. It is impossible to change app version via code push, you need to release new appstore version for this.

**Comment by sergey-akhalkov** [comment]
Closing this, please feel free to reopen if needed.
