### ISSUE TITLE
CodePush deployment key

### ISSUE THREAD

**Issue by delanick** [Microsoft/code-push#526]
Hi, I never wrote down/saved my deployment keys for my apps - how do I view them? It's urgent please :)

Nick

**Comment by edimuj** [comment]
You can retrieve them using the following command:
code-push deployment ls [APP_NAME] -k

Docs: https://github.com/Microsoft/cordova-plugin-code-push#getting-started

**Comment by delanick** [comment]
@edimuj Thanks so much, I got them! Is there any way I can save them without having to write them down manually? Seeing as I can't copy and paste them :)

**Comment by edimuj** [comment]
Good to hear @delanick You could probably pipe the output of the command to a text file like this:
`code-push deployment ls [APP_NAME] -k > codepush_deployment_keys.txt`

**Comment by delanick** [comment]
Thanks so much @edimuj I managed to get it right. :-D
