### ISSUE TITLE
Code-push session

### ISSUE THREAD

**Issue by RobertPaul01** [Microsoft/code-push#527]
The command `code-push session ls` does not work for the cli like it says in https://github.com/Microsoft/code-push/blob/master/cli/README.md#authentication

I'm using code-push cli version 2.1.0-beta and code-push version 2.0.2-beta.

**Comment by ruslan-bikkinin** [comment]
Hi @RobertPaul01 and thanks for submitting the issue!

CodePush have been migrated to Mobile Center and authentication system have been changed too. Documentation part you are pointing is outdated. To reset your session you can use `mobile-center-cli` command `mobile-center tokens delete` or by using [Mobile Center site](https://mobile.azure.com/settings/apitokens).

Let us know, if you have any questions or need help.

**Comment by max-mironov** [comment]
@RobertPaul01 we have updated docs, thanks again for pointing at this.
