### ISSUE TITLE
Hook codePushStatusDidChange when not using codePush.sync() in react native

### ISSUE THREAD

**Issue by karan101292** [Microsoft/code-push#529]
Hi, I am implementing `codePush` default behavior i.e. check for update on APP_START and apply it on APP_RESTART. I am not calling `codePush.sync()` method anywhere and I want to hook `codePushStatusDidChange()` method to get update log. I am not getting how to achieve it? 
I am using react-native 0.44.0

**Comment by grabvinod** [comment]
Why this is closed any solution

**Comment by EhsanSarshar** [comment]
@karan101292 have you solved the issue
