### ISSUE TITLE
Unable to push a update (Urgent)

### ISSUE THREAD

**Issue by shashankvaibhav** [Microsoft/code-push#530]
Guys,
I was trying a rollout feature in my production app. But somehow I completely messed it up. Whenever I am trying to release a new update, I am getting this error 
**Please update the previous release to 100% rollout before releasing a new package**
Please help I have a buggy app in production and can't fix anything because of this.

and when I am trying to increase rollout using 
code-push patch MyApp Production -l v72 -r 100%
Its showing error-
[Error]  Cannot update rollout value for a completed rollout release.

Thanks

**Comment by ruslan-bikkinin** [comment]
Hi @shashankvaibhav and thanks for reaching us.
You can try to fix the issue by releasing [patch](https://github.com/Microsoft/code-push/tree/master/cli#patching-update-metadata) for update:
```shell
code-push patch YOUR_APP YOUR_DEPLOYMENT --disabled
```
Buggy app version will be marked as disabled and will be reverted to previous stable version. Then you can release new update resolving bugs.

Please let us know if this information helps you or any updates.

**Comment by shashankvaibhav** [comment]
Do I have to mention label anywhere?

**Comment by ruslan-bikkinin** [comment]
@shashankvaibhav 
Please try to to patch your release using `--rollout 100` key.

```shell
code-push patch YOUR_APP YOUR_DEPLOYMENT --rollout 100
```

**Comment by shashankvaibhav** [comment]
@ruslan-bikkinin 
After trying above command I get this error
[Error]  Cannot update rollout value for a completed rollout release.

Can't understand what is happening here

**Comment by ruslan-bikkinin** [comment]
@shashankvaibhav Coukld you please send us output of command execution:
```

**Comment by ruslan-bikkinin** [comment]
@shashankvaibhav Could you please send us the output of following command:
```shell
code-push deployment ls YOUR_APP
```

**Comment by shashankvaibhav** [comment]
┌────────────┬─────────────────────────────────────┬──────────────────────────────┐
│ Name       │ Update Metadata                     │ Install Metrics              │
├────────────┼─────────────────────────────────────┼──────────────────────────────┤
│ Production │ Label: v74                          │ Active: 0.25% (70 of 28,019) │
│            │ App Version: 5.1.7                  │ Total: 76 (4 pending)        │
│            │ Mandatory: Yes                      │                              │
│            │ Release Time: an hour ago           │                              │
│            │ Released By:@gmail.com │                              │
│            │ Description: heo                    │                              │
│            │ Disabled: Yes                       │                              │
├────────────┼─────────────────────────────────────┼──────────────────────────────┤
│ Staging    │ Label: v85                          │ No installs recorded         │
│            │ App Version: 5.1.7                  │ Rollout: 5%                  │
│            │ Mandatory: No                       │                              │
│            │ Release Time: 3 hours ago           │                              │
│            │ Released By: @gmail.com │                              │
└────────────┴─────────────────────────────────────┴──────────────────────────────┘

**Comment by shashankvaibhav** [comment]
@ruslan-bikkinin Got it.
It was my mistake rollout was set with staging. 

Thanks for helping

**Comment by ruslan-bikkinin** [comment]
@shashankvaibhav Do you need any more help here?

**Comment by shashankvaibhav** [comment]
No Thanks
