### ISSUE TITLE
New Website Logo: Convoy - Bike & Car Pool

### ISSUE THREAD

**Issue by InvertedX** [Microsoft/code-push#534]
Please fill the following out:

- Name: Convoy - Bike & Car Pool
- Homepage (or app store) url: https://convoy.co.in
- Logo: https://user-images.githubusercontent.com/6897265/32687070-f7fc9f14-c6d9-11e7-8784-8ea80e2da00b.png

**Comment by max-mironov** [comment]
As [CodePush](https://microsoft.github.io/code-push/index.html#getting_started) site is moving to [AppCenter](https://appcenter.ms/) currently we do not support such kind of requests, sorry for inconvenience.
