### ISSUE TITLE
Error renaming an App

### ISSUE THREAD

**Issue by haualan** [Microsoft/code-push#536]
I have been using the CLI for over a year without issues but starting this morning I am unable to access by app anymore.

The name of my app is contains a slash character "/" and i think this is interfering with the CLI's commands to your server. 

The app name is supposed to be "TestingProject" but for some reason a colleague's name started to prepend the name starting today and turned this to " kristo/TestingProject"

```

$ code-push app ls
┌───────────────────────┬─────────────────────────┐
│ Name                  │ Deployments             │
├───────────────────────┼─────────────────────────┤
│ SC_Android            │ alpha, Production       │
├───────────────────────┼─────────────────────────┤
│ kristo/TestingProject │ alpha, beta, Production │
└───────────────────────┴─────────────────────────┘


```

I can no longer rename the app or do codepushes... etc

```

$ code-push deployment ls kristo%2FTestingProject
[Error]  App "kristo%2FTestingProject" does not exist.
$ code-push deployment ls "kristo/TestingProject"
[Error]  Cannot GET /apps/kristo/TestingProject/deployments/

$ code-push deployment ls "kristo%2FTestingProject"
[Error]  App "kristo%2FTestingProject" does not exist.
$ code-push deployment ls "TestingProject"
[Error]  App "TestingProject" does not exist.


```

Can you edit the name of the app from your end?

**Comment by max-mironov** [comment]
Hello @haualan sorry for that, that looks a little bit strange, I've tried on my side and was able to get info for that apps in "ownerName/appName" format.

However can you try the following first to see if it helps:
1) Use new[ AppCenter CLI ](https://github.com/Microsoft/appcenter-cli)and try to rename the app with `appcenter apps update` command OR
2) Go to [AppCenter](https://appcenter.ms/) site and try to change the name of the app directly via UI

Please let us know if it helps.

**Comment by newyankeecodeshop** [comment]
@max-mironov Did CodePush or App Center recently change how applications are named? Our apps used to be named without an owner (e.g. "UpserveLive-Android") but recently when I do `code-push app list` the names are prefixed with our organization "Upserve" (e.g. "Upserve/UpersveLive-Android"). Our CLI scripts that reference the app name without the owner prefix now fail:
```
> code-push deployment ls UpserveLive-Android
[Error]  App "UpserveLive-Android" does not exist.
```

Is this new documented behavior? I can't find any documentation about this change.

**Comment by max-mironov** [comment]
@newyankeecodeshop - yep, codepush is moving to [AppCenter](https://appcenter.ms/) and as part of this change apps and users are migrated to AppCenter. Since now I believe it make sense to try new [AppCenter CLI](https://github.com/Microsoft/appcenter-cli) instead (old CodePush CLI would be deprecated on mid Oct 2018). 
Also more information about this could be found here: http://microsoft.github.io/code-push/

Probably our [migration guide](https://docs.microsoft.com/en-us/appcenter/distribution/codepush/migrationguide) could be useful when start working with AppCenter and appcenter CLI.

Please do not hesitate to reach us and send questions/feedback about new AppCenter - that would be much appreciated.

**Comment by max-mironov** [comment]
@haualan please let us know if you have a chance to look at this.

**Comment by haualan** [comment]
@max-mironov it turns out for my errors it was due to an old version of codepush CLI, after updating to the most recent version via npm, I get more meaningful error messages that I don't have the permission to change the name.

Other than that I confirm that I'm seeing the same problem as @newyankeecodeshop but it wasn't too much to handle for my team because our scripts to manage deployment only had a few places that refer to the app name and updating that to include the prefix "<ownerName>/" was not a big deal.

**Comment by max-mironov** [comment]
@haualan thanks for update! So I believe we can close this issue as it has been resolved. Please feel free to reach us if any more questions or troubles.
