### ISSUE TITLE
Large gzip Denial of Service on superagent is found by nsp

### ISSUE THREAD

**Issue by huhuanming** [Microsoft/code-push#540]
![image](https://user-images.githubusercontent.com/5743863/33558451-d1d903c2-d944-11e7-9670-6cb89b5cd34f.png)

```
code-push@1.11.2-beta:
  version "1.11.2-beta"
  resolved "http://registry.npm.taobao.org/code-push/download/code-push-1.11.2-beta.tgz#642f5199edb0fd6d6d300e439883b03b8b252737"
  dependencies:
    q "^1.4.1"
    recursive-fs "0.1.4"
    slash "1.0.0"
    superagent "^1.7.2"
    superagent-proxy "^1.0.0"
    yazl "^2.4.1"
```

This bug fixed in superagent 3.7.0, maybe we should try to update it.

**Comment by huhuanming** [comment]
Now could I create a PR for this?

**Comment by huhuanming** [comment]
But after checking 2.0.4, it fixed.
:-D

**Comment by huhuanming** [comment]
![image](https://user-images.githubusercontent.com/5743863/33697950-898b0898-db44-11e7-9016-766057136733.png)

But `superagent`'s versions is still 1.8.5.

Now could I create a PR to upgrade superagent to 3.7.0  for this?

**Comment by ruslan-bikkinin** [comment]
Thanks @huhuanming for your help, I'll take care of it and will keep you posted!

**Comment by ruslan-bikkinin** [comment]
@huhuanming I fixed it in #543. Do you have a chance to take a look at it and check whether it works for you or you have any more issues with that?

**Comment by huhuanming** [comment]
cool！u did it before me. 😄

let me check it.

**Comment by ruslan-bikkinin** [comment]
I am closing this issue because fix already in master. Thanks for catch @huhuanming !
