### ISSUE TITLE
What exactly mandatory does?

### ISSUE THREAD

**Issue by sospedra** [Microsoft/code-push#546]
Hello, I'm wondering what exactly mandatory mean?
The description says that without this flag releases are "optional". But I thought that all the users will install all the codepush new versions always. They are not asked for nothing anyway.

So, what's the difference between an optional release and a mandatory one? In which scenarios can an optional release not be installed? Can you provide any example?

Thanks 👍

**Comment by sergey-akhalkov** [comment]
Hi @sospedra, thanks for reaching us! 
First of all, please make sure you have read [mandatory-parameter](https://github.com/Microsoft/code-push/tree/master/cli#mandatory-parameter) article and js codepush options both for [React Native](https://github.com/Microsoft/react-native-code-push/blob/master/docs/api-js.md#codepushoptions) and [Cordova](https://github.com/Microsoft/cordova-plugin-code-push#syncoptions) 

>installMode (codePush.InstallMode) - Specifies when you would like to install optional updates (i.e. those that aren't marked as mandatory). Defaults to codePush.InstallMode.ON_NEXT_RESTART. Refer to the InstallMode enum reference for a description of the available options and what they do.

>mandatoryInstallMode (codePush.InstallMode) - Specifies when you would like to install updates which are marked as mandatory. Defaults to codePush.InstallMode.IMMEDIATE. Refer to the InstallMode enum reference for a description of the available options and what they do.

Another words, you can mark an update contains critical bugfix as mandatory so it will be installed on user devices immediately, without waiting for app resume or suspend, it depends on your configuration.

Please let me know if the provided info makes sense for you or if you have any questions.

**Comment by sospedra** [comment]
Considered solved ;)
