### ISSUE TITLE
Code Sign for the node module

### ISSUE THREAD

**Issue by pitAlex** [Microsoft/code-push#551]
I currently don't see an option to add the private key to signing the update through the SDK(node.js). Are there any plans to add it?

**Comment by max-mironov** [comment]
Hi there @pitAlex, thanks for asking. AFAIK we don't have any plans for doing this. 

Also just my point of view but SDK should be a thin layer that is placed between client and service (and it looks like that now). Adding `sign` option would require to move 
a) hashing 
b) singing 
c) validation of all of that stuff 
logic to the SDK and this will lead to significant growth for this class (also to avoid code duplication with CLI part we should share that logic probably somehow). Signing a package could be compared to the `bundle` operation. We do not have `bundleAndRelease` method for SDK as SDK is responsible only for creating new release on service, bundling the package is out of its scope. I believe the same thoughts could be applied to signing and if we ever need some kind of `signAndRelease` logic. 

But anyway that is only my opinion and we would be happy to hear what other people from the community think about it - we are all ears.

**Comment by sergey-akhalkov** [comment]
@pitAlex, just a friendly ping.

**Comment by pitAlex** [comment]
Well I just wanted to know if its available or not. I use the SDK to simplify the process of pushing app updates because our app has DEV, STAGE and PROD mode. There are actually 3 apps for both platforms. I use node scripts to sync web scripts to the cordova app, the SDK to push the updates for testing DEV and then the rest. So in my case it would of been nice to also have the signing in SDK.

**Comment by sergey-akhalkov** [comment]
Hi @pitAlex, please take a look at https://github.com/Microsoft/appcenter-cli/tree/master/src/commands/codepush/lib - you can reuse `sign` method from the `update-contents-tasks` folder for your own purposes.

I'm closing this, please feel free to reopen if needed.
