### ISSUE TITLE
Allow Passing Config to Metro Bundler from Client

### ISSUE THREAD

**Issue by MrLoh** [Microsoft/code-push#554]
Currently it is not possible to pass down a path to a metro config file to the codepush client. 

I am using a custom metro config file, to make metro play nicely along with symlinks in a monorepo setup. See https://github.com/facebook/metro/issues/1#issuecomment-333658773. If I add a `--config $PATH_TO_MY_CONFIG` option to the code here it all works: 

https://github.com/Microsoft/code-push/blob/39e957551318493ab8e62b398e2aa7245038c5aa/cli/script/command-executor.ts#L1450-L1457

I would be idealy if I could pass a `--metroConfig` option or the like to the codepush client to make it pick up the config file. 

### Environment

* code-push-cli 2.1.0-beta
* react-native-code-push version: ^5.1.1-beta
* react-native version: 0.50.4

**Comment by ruslan-bikkinin** [comment]
Hi @MrLoh and thanks for submitting the issue. According to [metro-bundler docs](https://facebook.github.io/metro/docs/en/configuration.html#content) you can setup bundler directly in `package.json` or via `metro.config.js`. Could you please let us know does it work for you or, otherwise, clarify why you want to use `--config` parameter?

**Comment by MrLoh** [comment]
Hi @ruslan-bikkinin thanks for your answer. Unfortunately simply naming a config file `metro.config.js` doesn't solve the issue since the packager is started from `./node_modules/react-native/local-cli/cli.js` and not from the current working directory so a config file added to the project root isn't read. Of course the code-push script could check for such a file to pass it automatically through the `--config` flag.

**Comment by ruslan-bikkinin** [comment]
Got it @MrLoh. I recommend you to use [general `code-push release` command](https://github.com/Microsoft/code-push/tree/master/cli#releasing-updates-general) for releasing updates - that will allow you to generate bundle by your own custom way including passing of `--config` parameter. Now your case seems very specific and does not affect most of the users of `release-react` command. We'll look for the similar feature requests in the future and in case there will be a lot of them we'll add this enhancement to our backlog and implement it. 
Please let us know if it helps or any updates.

**Comment by MrLoh** [comment]
I guess that’s a workaroudn at least. would it really be so bad to add support for metro config files. I understand you don't want to overload the client, but it's pretty standard that config files are supported, it's just because of metros weird setup from calling the binary from inside the node modules that the config file isn't picked up.
