### ISSUE TITLE
Cordova random rollbacks CodePush CLI

### ISSUE THREAD

**Issue by BbFGE** [Microsoft/code-push#555]
Phonegap Build
I have been using Phonegap Build to build both Android (apk) and iOS (ipa) files.
The documentation for Codepush (https://docs.microsoft.com/en-us/appcenter/distribution/codepush/cordova) states that the plugin is compatible with Phonegap Build. However, I have built apps for both iOS and Android (adding <preference name="android-build-tool" value="gradle" /> to the config.xml as recommended for Android) however, neither app would pick up new releases from Codepush - the app would simply display as per the original installation.

Random rollbacks
I have been having major setbacks testing Codepush with Android. I install the compiled app on a device, and it runs ok. I amend the app by making a minor change to the html file and use appcenter codepush release-cordova... to push out a new update.

I then run the app, close it and run it again. The first two or 3 updates will be correctly picked up. However, after this (and it is not consistent, it differs between devices when this happens), the next update fails and the app reverts to the installed version and in appcenter, the update is shown under 'Rollbacks'.

From that point, any new releases are ignored and the app stays on the installed version.
The only two fixes seem to be
1. Re-installing the app - this fixes it and it starts picking up new releases, until it fails again OR
2. Clearing the entire history for the deployment. Again, this fixes it until it fails again.

The update isn't crashing - I have merely changed some text in the index.html so it wouldn't crash (plus an update will install on one device but fail on another so it can't be that).

The app triggers the Codepush sync as follows : 
document.addEventListener("deviceready", onDeviceReady, false);

function onDeviceReady() {
	codePush.sync(null,{
		ignoreFailedUpdates : false
	});
}
I have tried it with and without the 'ignoreFailedUpdates' option, but it fails eventually either way.
I assume the problem is caused by the app failing to complete codePush.notifyApplicationReady, perhaps due to network problems. 

However, this seems to be a show-stopper in that it effectively makes Codepush unusable in the real world. There is no guarantee updates will reach users; worse still, if the update fails, the app rolls back to the last installed version and subsequently ignores all new updates, so they are stuck at an old version or have to go through the pain of re-installing the app. (Clearing the history for the deployment every time we do an update might work, but no guarantees).

As an example, I created an app that simly displayed some html, including a version number.
Build and installed 
'v1.00'
edited the html, changing the version to v1.01.
Release the update (having already set the app using appcenter apps set-current -a ...)
appcenter codepush release-cordova -d Staging
Open app, close it, open again
Correctly shows
'v1.01'
edited the html, changing the version to v1.02.
Release the update 
Open app, correctly shows
'v1.02'
Close it, then re-open it
Shows 'v1.00', and appcenter shows rollbacks.
I have tried using the '-m' option on appcenter codepush release-cordova
Also, I have tried it on both Android 6 and 7 with the same problems.

My questions are:
1. Is there anything else I can try to get the updates to install correctly, or, if they fail, NOT to freeze the app at its last installed state and ignore any future updates.
2. Is this a cordova problem or is the same thing likely to happen if I switched using React-Native?
3. Is  there a way to make Codepush work with Phonegap Build?#

We wanted to be able to roll out an app to our user base but without having to have them re-install on every small change. Codepush seemed a perfect solution, however, at the moment, is it is looking as if it simply isn't workable.

Any help would be much appreciated.

  <content src="index.html" />
    <access origin="*" />
    <platform name="android">
        <preference name="CodePushDeploymentKey" value="..." />
        <preference name="APP_SECRET" value="..." />
    </platform>
    <plugin name="cordova-plugin-code-push" spec="~1.11.2" />
    <plugin name="cordova-plugin-whitelist" spec="~1.3.3" />
    <plugin name="cordova-plugin-appcenter-analytics" spec="^0.1.3" />
    <plugin name="cordova-plugin-appcenter-crashes" spec="^0.1.3" />
    <engine name="android" spec="~7.0.0" />

**Comment by max-mironov** [comment]
Closing this as duplicate to https://github.com/Microsoft/cordova-plugin-code-push/issues/356.
As far as being cordova specific should be discussed further in cordova repo.
