### ISSUE TITLE
fatal error: 'React/RCTEventEmitter.h' file not found

### ISSUE THREAD

**Issue by jdnichollsc** [Microsoft/code-push#556]
Hi guys,

I'm getting the following issue after execute `react-native link react-native-code-push && react-native run-ios`:
```
/Users/jdnichollsc/myApp/node_modules/react-native-code-push/ios/CodePush/CodePush.h:6:9: fatal error: 'React/RCTEventEmitter.h' file not found
#import "React/RCTEventEmitter.h"   // Required when used as a Pod in a Swift project
        ^~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.


** BUILD FAILED **

The following build commands failed:
        CompileC /Users/jdnichollsc/myApp/ios/build/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/CodePush.build/Objects-normal/x86_64/CodePushDownloadHandler.o /Users/jdnichollsc/myApp/node_modules/react-native-code-push/ios/CodePush/CodePushDownloadHandler.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
```
**Info:**
react-native-cli: 2.0.1
react-native: 0.52.1

What do you think? Thanks in advance!

**Comment by max-mironov** [comment]
Hey @jdnichollsc, that is not easy to say what's going wrong here but probably you could share the smallest possible sample app with us so we could try it on our side? Please specify the code-push-react-native-plugin version also.
May be it make sense to create a new issue with all this information in [react-native-code-push](https://github.com/Microsoft/react-native-code-push) repository as this repo is mostly for CLI questions and general CodePush questions. 
Thanks!

**Comment by jdnichollsc** [comment]
Sorry guys, it was fixed removing all references of AppCenter, installing the packages again and runing `pod install` command from `ios` folder.
Thanks!

**Comment by max-mironov** [comment]
Thanks for update!

**Comment by jdnichollsc** [comment]
@max-mironov thanks for your quickly response and the excellent support! 👍

**Comment by dudeinthemirror** [comment]
I am having the same issue, just by installing `react-native-code-push` (via Cocoapods).
@jdnichollsc Can you please elaborate your statement: `fixed removing all references of AppCenter, installing the packages again`. Thanks

For reference, here is the environment:
node: v9.9.0
npm: 5.6.0
cocoapods: 1.3.1
Podfile

```
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, "11.0"
inhibit_all_warnings!

def available_pods
  # Pods for AppCenter
  pod 'AppCenterReactNativeShared', '~> 1.4.0'
  pod 'CodePush', :path => '../node_modules/react-native-code-push'   # <-- the only one added in this commit
end

target 'MyApp' do
  available_pods
end
```

In package.json:

```
 "react-native-code-push": "^5.3.2",
```

**Comment by jdnichollsc** [comment]
Ctrl + F, find all references of "AppCenter" and remove these lines of code (hardcore)

**Comment by dudeinthemirror** [comment]
@jdnichollsc got it, thanks, that did the trick. So, basically the undocumented feature here is that good old CodePush can still be implemented without the need for AppCenter. To the team behind AppCenter: thanks for all the hard work, but please allow CodePush to live independently. In many cases, we already have solutions implemented for crashes, data tracking, push notifications, etc. All we need is the awesomeness of CodePush. Keep it free and untangled! :)

**Comment by iamsoorena** [comment]
I have the same problem just there is no reference to `AppCenter` anywhere in the project. and running `pod install` over and over again didn't solve my problem.

**Comment by NickToropov** [comment]
Hi @iamsoorena, please check if your Podfile contains the following:
```
# React Native requirements
pod 'React', :path => '../node_modules/react-native', :subspecs => [
   'Core',
   'CxxBridge', # Include this for RN >= 0.47
   'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
   'RCTText',
   'RCTNetwork',
   'RCTWebSocket', # Needed for debugging
   'RCTAnimation', # Needed for FlatList and animations running on native UI thread
   # Add any other subspecs you want to use in your project
]
# Explicitly include Yoga if you are using RN >= 0.42.0
pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  
# CodePush plugin dependency
pod 'CodePush', :path => '../node_modules/react-native-code-push'
```
Please let me know if it was helpful.

**Comment by hungvu193** [comment]
thank you buddy, you save my day! :D

**Comment by abhaypai2611** [comment]
I am still facing this issue. Tried all the above mentioned solutions but it won't build.

react-native-cli: 2.0.1
react-native: 0.55.4
cocoapods: 1.5.3
node: v8.11.1
OS: macOS High Sierra 10.13.5

The error log is as follows:

`CompileC /Users/apai/Documents/Code/TestApps/test-mobile-app/ios/build/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/CodePush.build/Objects-normal/x86_64/CodePushDownloadHandler.o /Users/apai/Documents/Code/TestApps/test-mobile-app/node_modules/react-native-code-push/ios/CodePush/CodePushDownloadHandler.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/apai/Documents/Code/TestApps/test-mobile-app/ios/Pods
    export LANG=en_US.US-ASCII
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/apai/Library/sdk/platform-tools"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch x86_64 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=gnu11 -fobjc-arc -fobjc-weak -fmodules -gmodules -fmodules-cache-path=/Users/apai/Documents/Code/TestApps/test-mobile-app/ios/build/ModuleCache.noindex -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/Users/apai/Documents/Code/TestApps/test-mobile-app/ios/build/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -fmodule-name=CodePush -Wno-trigraphs -fpascal-strings -O0 -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Werror=return-type -Wdocumentation -Wunreachable-code -Wno-implicit-atomic-properties -Werror=deprecated-objc-isa-usage -Werror=objc-root-class -Wno-arc-repeated-use-of-weak -Wimplicit-retain-self -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wdeprecated-implementations -DPOD_CONFIGURATION_DEBUG=1 -DDEBUG=1 -DCOCOAPODS=1 -DOBJC_OLD_DISPATCH_PROTOTYPES=0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.4.sdk -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -mios-simulator-version-min=8.0 -g -Wno-sign-conversion -Winfinite-recursion -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wunguarded-availability -fobjc-abi-version=2 -fobjc-legacy-dispatch -index-store-path /Users/apai/Documents/Code/TestApps/test-mobile-app/ios/build/Index/DataStore -iquote /Users/apai/Documents/Code/TestApps/test-mobile-app/ios/build/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/CodePush.build/CodePush-generated-files.hmap -I/Users/apai/Documents/Code/TestApps/test-mobile-app/ios/build/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/CodePush.build/CodePush-own-target-headers.hmap -I/Users/apai/Documents/Code/TestApps/test-mobile-app/ios/build/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/CodePush.build/CodePush-all-non-framework-target-headers.hmap -ivfsoverlay /Users/apai/Documents/Code/TestApps/test-mobile-app/ios/build/Build/Intermediates.noindex/Pods.build/all-product-headers.yaml -iquote /Users/apai/Documents/Code/TestApps/test-mobile-app/ios/build/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/CodePush.build/CodePush-project-headers.hmap -I/Users/apai/Documents/Code/TestApps/test-mobile-app/ios/build/Build/Products/Debug-iphonesimulator/CodePush/include -I/Users/apai/Documents/Code/TestApps/test-mobile-app/ios/build/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/CodePush.build/DerivedSources/x86_64 -I/Users/apai/Documents/Code/TestApps/test-mobile-app/ios/build/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/CodePush.build/DerivedSources -F/Users/apai/Documents/Code/TestApps/test-mobile-app/ios/build/Build/Products/Debug-iphonesimulator/CodePush -F/Users/apai/Documents/Code/TestApps/test-mobile-app/ios/build/Build/Products/Debug-iphonesimulator/Base64 -F/Users/apai/Documents/Code/TestApps/test-mobile-app/ios/build/Build/Products/Debug-iphonesimulator/JWT -F/Users/apai/Documents/Code/TestApps/test-mobile-app/ios/build/Build/Products/Debug-iphonesimulator/React -F/Users/apai/Documents/Code/TestApps/test-mobile-app/ios/build/Build/Products/Debug-iphonesimulator/SSZipArchive -include /Users/apai/Documents/Code/TestApps/test-mobile-app/ios/Pods/Target\ Support\ Files/CodePush/CodePush-prefix.pch -MMD -MT dependencies -MF /Users/apai/Documents/Code/TestApps/test-mobile-app/ios/build/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/CodePush.build/Objects-normal/x86_64/CodePushDownloadHandler.d --serialize-diagnostics /Users/apai/Documents/Code/TestApps/test-mobile-app/ios/build/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/CodePush.build/Objects-normal/x86_64/CodePushDownloadHandler.dia -c /Users/apai/Documents/Code/TestApps/test-mobile-app/node_modules/react-native-code-push/ios/CodePush/CodePushDownloadHandler.m -o /Users/apai/Documents/Code/TestApps/test-mobile-app/ios/build/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/CodePush.build/Objects-normal/x86_64/CodePushDownloadHandler.o
In file included from /Users/apai/Documents/Code/TestApps/test-mobile-app/node_modules/react-native-code-push/ios/CodePush/CodePushDownloadHandler.m:1:
/Users/apai/Documents/Code/TestApps/test-mobile-app/node_modules/react-native-code-push/ios/CodePush/CodePush.h:6:9: fatal error: 'React/RCTEventEmitter.h' file not found
#import "React/RCTEventEmitter.h"   // Required when used as a Pod in a Swift project
        ^~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.`


`CompileC /Users/apai/Documents/Code/TestApps/test-mobile-app/ios/build/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/CodePush.build/Objects-normal/x86_64/CodePush.o /Users/apai/Documents/Code/TestApps/test-mobile-app/node_modules/react-native-code-push/ios/CodePush/CodePush.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/apai/Documents/Code/TestApps/test-mobile-app/ios/Pods
    export LANG=en_US.US-ASCII
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/apai/Library/sdk/platform-tools"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch x86_64 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=gnu11 -fobjc-arc -fobjc-weak -fmodules -gmodules -fmodules-cache-path=/Users/apai/Documents/Code/TestApps/test-mobile-app/ios/build/ModuleCache.noindex -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/Users/apai/Documents/Code/TestApps/test-mobile-app/ios/build/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -fmodule-name=CodePush -Wno-trigraphs -fpascal-strings -O0 -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Werror=return-type -Wdocumentation -Wunreachable-code -Wno-implicit-atomic-properties -Werror=deprecated-objc-isa-usage -Werror=objc-root-class -Wno-arc-repeated-use-of-weak -Wimplicit-retain-self -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wdeprecated-implementations -DPOD_CONFIGURATION_DEBUG=1 -DDEBUG=1 -DCOCOAPODS=1 -DOBJC_OLD_DISPATCH_PROTOTYPES=0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.4.sdk -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -mios-simulator-version-min=8.0 -g -Wno-sign-conversion -Winfinite-recursion -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wunguarded-availability -fobjc-abi-version=2 -fobjc-legacy-dispatch -index-store-path /Users/apai/Documents/Code/TestApps/test-mobile-app/ios/build/Index/DataStore -iquote /Users/apai/Documents/Code/TestApps/test-mobile-app/ios/build/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/CodePush.build/CodePush-generated-files.hmap -I/Users/apai/Documents/Code/TestApps/test-mobile-app/ios/build/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/CodePush.build/CodePush-own-target-headers.hmap -I/Users/apai/Documents/Code/TestApps/test-mobile-app/ios/build/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/CodePush.build/CodePush-all-non-framework-target-headers.hmap -ivfsoverlay /Users/apai/Documents/Code/TestApps/test-mobile-app/ios/build/Build/Intermediates.noindex/Pods.build/all-product-headers.yaml -iquote /Users/apai/Documents/Code/TestApps/test-mobile-app/ios/build/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/CodePush.build/CodePush-project-headers.hmap -I/Users/apai/Documents/Code/TestApps/test-mobile-app/ios/build/Build/Products/Debug-iphonesimulator/CodePush/include -I/Users/apai/Documents/Code/TestApps/test-mobile-app/ios/build/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/CodePush.build/DerivedSources/x86_64 -I/Users/apai/Documents/Code/TestApps/test-mobile-app/ios/build/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/CodePush.build/DerivedSources -F/Users/apai/Documents/Code/TestApps/test-mobile-app/ios/build/Build/Products/Debug-iphonesimulator/CodePush -F/Users/apai/Documents/Code/TestApps/test-mobile-app/ios/build/Build/Products/Debug-iphonesimulator/Base64 -F/Users/apai/Documents/Code/TestApps/test-mobile-app/ios/build/Build/Products/Debug-iphonesimulator/JWT -F/Users/apai/Documents/Code/TestApps/test-mobile-app/ios/build/Build/Products/Debug-iphonesimulator/React -F/Users/apai/Documents/Code/TestApps/test-mobile-app/ios/build/Build/Products/Debug-iphonesimulator/SSZipArchive -include /Users/apai/Documents/Code/TestApps/test-mobile-app/ios/Pods/Target\ Support\ Files/CodePush/CodePush-prefix.pch -MMD -MT dependencies -MF /Users/apai/Documents/Code/TestApps/test-mobile-app/ios/build/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/CodePush.build/Objects-normal/x86_64/CodePush.d --serialize-diagnostics /Users/apai/Documents/Code/TestApps/test-mobile-app/ios/build/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/CodePush.build/Objects-normal/x86_64/CodePush.dia -c /Users/apai/Documents/Code/TestApps/test-mobile-app/node_modules/react-native-code-push/ios/CodePush/CodePush.m -o /Users/apai/Documents/Code/TestApps/test-mobile-app/ios/build/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/CodePush.build/Objects-normal/x86_64/CodePush.o
In file included from /Users/apai/Documents/Code/TestApps/test-mobile-app/node_modules/react-native-code-push/ios/CodePush/CodePush.m:17:
/Users/apai/Documents/Code/TestApps/test-mobile-app/node_modules/react-native-code-push/ios/CodePush/CodePush.h:6:9: fatal error: 'React/RCTEventEmitter.h' file not found
#import "React/RCTEventEmitter.h"   // Required when used as a Pod in a Swift project
        ^~~~~~~~~~~~~~~~~~~~~~~~~`


`CompileC /Users/apai/Documents/Code/TestApps/test-mobile-app/ios/build/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/CodePush.build/Objects-normal/x86_64/CodePushConfig.o /Users/apai/Documents/Code/TestApps/test-mobile-app/node_modules/react-native-code-push/ios/CodePush/CodePushConfig.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/apai/Documents/Code/TestApps/test-mobile-app/ios/Pods
    export LANG=en_US.US-ASCII
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/apai/Library/sdk/platform-tools"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch x86_64 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=gnu11 -fobjc-arc -fobjc-weak -fmodules -gmodules -fmodules-cache-path=/Users/apai/Documents/Code/TestApps/test-mobile-app/ios/build/ModuleCache.noindex -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/Users/apai/Documents/Code/TestApps/test-mobile-app/ios/build/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -fmodule-name=CodePush -Wno-trigraphs -fpascal-strings -O0 -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Werror=return-type -Wdocumentation -Wunreachable-code -Wno-implicit-atomic-properties -Werror=deprecated-objc-isa-usage -Werror=objc-root-class -Wno-arc-repeated-use-of-weak -Wimplicit-retain-self -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wdeprecated-implementations -DPOD_CONFIGURATION_DEBUG=1 -DDEBUG=1 -DCOCOAPODS=1 -DOBJC_OLD_DISPATCH_PROTOTYPES=0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.4.sdk -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -mios-simulator-version-min=8.0 -g -Wno-sign-conversion -Winfinite-recursion -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wunguarded-availability -fobjc-abi-version=2 -fobjc-legacy-dispatch -index-store-path /Users/apai/Documents/Code/TestApps/test-mobile-app/ios/build/Index/DataStore -iquote /Users/apai/Documents/Code/TestApps/test-mobile-app/ios/build/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/CodePush.build/CodePush-generated-files.hmap -I/Users/apai/Documents/Code/TestApps/test-mobile-app/ios/build/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/CodePush.build/CodePush-own-target-headers.hmap -I/Users/apai/Documents/Code/TestApps/test-mobile-app/ios/build/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/CodePush.build/CodePush-all-non-framework-target-headers.hmap -ivfsoverlay /Users/apai/Documents/Code/TestApps/test-mobile-app/ios/build/Build/Intermediates.noindex/Pods.build/all-product-headers.yaml -iquote /Users/apai/Documents/Code/TestApps/test-mobile-app/ios/build/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/CodePush.build/CodePush-project-headers.hmap -I/Users/apai/Documents/Code/TestApps/test-mobile-app/ios/build/Build/Products/Debug-iphonesimulator/CodePush/include -I/Users/apai/Documents/Code/TestApps/test-mobile-app/ios/build/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/CodePush.build/DerivedSources/x86_64 -I/Users/apai/Documents/Code/TestApps/test-mobile-app/ios/build/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/CodePush.build/DerivedSources -F/Users/apai/Documents/Code/TestApps/test-mobile-app/ios/build/Build/Products/Debug-iphonesimulator/CodePush -F/Users/apai/Documents/Code/TestApps/test-mobile-app/ios/build/Build/Products/Debug-iphonesimulator/Base64 -F/Users/apai/Documents/Code/TestApps/test-mobile-app/ios/build/Build/Products/Debug-iphonesimulator/JWT -F/Users/apai/Documents/Code/TestApps/test-mobile-app/ios/build/Build/Products/Debug-iphonesimulator/React -F/Users/apai/Documents/Code/TestApps/test-mobile-app/ios/build/Build/Products/Debug-iphonesimulator/SSZipArchive -include /Users/apai/Documents/Code/TestApps/test-mobile-app/ios/Pods/Target\ Support\ Files/CodePush/CodePush-prefix.pch -MMD -MT dependencies -MF /Users/apai/Documents/Code/TestApps/test-mobile-app/ios/build/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/CodePush.build/Objects-normal/x86_64/CodePushConfig.d --serialize-diagnostics /Users/apai/Documents/Code/TestApps/test-mobile-app/ios/build/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/CodePush.build/Objects-normal/x86_64/CodePushConfig.dia -c /Users/apai/Documents/Code/TestApps/test-mobile-app/node_modules/react-native-code-push/ios/CodePush/CodePushConfig.m -o /Users/apai/Documents/Code/TestApps/test-mobile-app/ios/build/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/CodePush.build/Objects-normal/x86_64/CodePushConfig.o
In file included from /Users/apai/Documents/Code/TestApps/test-mobile-app/node_modules/react-native-code-push/ios/CodePush/CodePushConfig.m:1:
/Users/apai/Documents/Code/TestApps/test-mobile-app/node_modules/react-native-code-push/ios/CodePush/CodePush.h:6:9: fatal error: 'React/RCTEventEmitter.h' file not found
#import "React/RCTEventEmitter.h"   // Required when used as a Pod in a Swift project
        ^~~~~~~~~~~~~~~~~~~~~~~~~`


`** BUILD FAILED **`



`The following build commands failed:
	CompileC /Users/apai/Documents/Code/TestApps/test-mobile-app/ios/build/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/CodePush.build/Objects-normal/x86_64/CodePushDownloadHandler.o /Users/apai/Documents/Code/TestApps/test-mobile-app/node_modules/react-native-code-push/ios/CodePush/CodePushDownloadHandler.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)`

`Installing build/Build/Products/Debug-iphonesimulator/testMobileApp.app
Launching org.test.native.TestApps
org.test.native.TestApps: 23666`


We are facing this issue with our production app. I had to create a test app and reproduce this issue. Any help would be appreciated.

**Comment by hungvu193** [comment]
@abhaypai2611  You can try install code-push manual, dont use react-native link
https://github.com/Microsoft/react-native-code-push/blob/master/docs/setup-ios.md
https://github.com/Microsoft/react-native-code-push/blob/master/docs/setup-android.md
