### ISSUE TITLE
所有中国移动的网络连接不上更新服务器

### ISSUE THREAD

**Issue by MackYang** [Microsoft/code-push#558]
**# CMCC (China Mobile Network) net  can't connect the update server!**

Thanks so much for filing an issue or feature request! We will address it as soon as we can. Please follow these guidelines:

1. This repository is for the CodePush CLI and management SDK. For issues relating to the CodePush client SDK's, please see:
  * react-native-code-push: https://github.com/Microsoft/react-native-code-push
  * cordova-plugin-code-push: https://github.com/Microsoft/cordova-plugin-code-push
2. In your description, please include the version of `code-push-cli` or `code-push` that you are using.

**Comment by MackYang** [comment]
code-push version is 2.1.6
"appcenter-cli": "^1.0.8",

**Comment by Zakeelm** [comment]
Hey there! 

Sorry for the delayed response, are you still having this issue?

**Comment by MackYang** [comment]
yes,at same times

**Comment by Zakeelm** [comment]
Hey haven't heard from you in a while! Going to go ahead and close this. Feel free to respond in this thread if you would like to re-open it and discuss this further 😄

**Comment by 1104931825** [comment]
Can it be used in China?

**Comment by MackYang** [comment]
yes, at sametime
