### ISSUE TITLE
CLI Documentation has contradictory information on rollbacks

### ISSUE THREAD

**Issue by marfire** [Microsoft/code-push#559]
The [Rolling Back Updates](https://github.com/Microsoft/code-push/tree/39e957551318493ab8e62b398e2aa7245038c5aa/cli#rolling-back-updates) section says:

> A deployment's release history is immutable, so you cannot delete or remove an update once it has been released.

But a few paragraphs later, the [Clearing Release History](https://github.com/Microsoft/code-push/tree/39e957551318493ab8e62b398e2aa7245038c5aa/cli#clearing-release-history) section says:

> You can clear the release history associated with a deployment....

Unless I'm missing something, these two statements are directly contradictory.

**Comment by Zakeelm** [comment]
I can understand why this is a bit confusing. What we mean by this is the following: A deployment's release history is immutable, but you can use the clear command in order to "clean up" your deployment history. Using clear will make it so that your previous release history is no longer visible, but it doesn't affect the app itself.

**Comment by marfire** [comment]
> Using clear will make it so that your previous release history is no longer visible, but it doesn't affect the app itself.

Hmm. The documentation says "client devices configured to receive updates using its associated deployment key will no longer receive the updates that have been cleared". I would call that affecting the app, since it's preventing updates that would otherwise have taken place.

In any case, I think what you're saying is this: The *goal* of the clear command is aesthetic, to clean up the list of deployments shown when you run `code-push deployment history`. A *side effect* of doing that is that the clients can no longer see those cleared releases, which is why you should never do this in production.

If that's right, then my suggestion is to state the purpose of `clear` more explicitly in the documentation.

**Comment by Zakeelm** [comment]
Updated! I hope this helps
