### ISSUE TITLE
App rename in AppCenter not reflecting to the CLI

### ISSUE THREAD

**Issue by mnewmedia** [Microsoft/code-push#562]
appcenter version: 1.0.13

I renamed the app from `app` to `app-ios` in the App Center. But when using the CLI it still only know's about the old name `app` and not the new name `app-ios`.

After this I also renamed the Team form `my-team` to `team` and this worked like expected.

**Comment by Zakeelm** [comment]
Hey there!

In AppCenter, apps are technically given two names: name and descriptive name. The name is the name of the app used in URLs and the display name is the descriptive name of the app. I would suggest changing both of these to reflect this new change. This can be done using the `appcenter apps update` command with the -n flag for name and the -d flag for display name.

**Comment by mnewmedia** [comment]
You're right, my fault. sorry.
