### ISSUE TITLE
The newest version code-push-cli 2.1.7 cannot be installed via npm

### ISSUE THREAD

**Issue by hahtml** [Microsoft/code-push#565]
npm: 5.0.3
code-push-cli: 2.1.7

The newest version of code-push-cli is missing code-push-cli/script/cli.js file so that it cannot be installed via npm at all. No problem with 2.1.6 installation.

**Comment by pluberski** [comment]
I'm glad I'm not the only one running into this issue.  :D

**Comment by wzc5840** [comment]
me too!!!!!  In the end I had to install 2.1.6

**Comment by iTOYS** [comment]
Please check code-push@2.1.8

**Comment by wzc5840** [comment]
Perfect, I have installed code-push-cli@2.1.8 successfully!
