### ISSUE TITLE
Privacy Policy?

### ISSUE THREAD

**Issue by Rob117** [Microsoft/code-push#569]
Hi! My company is really interested in using CodePush to manage our entire app chain. We have a small problem, however.

On the main [site](https://microsoft.github.io/code-push/faq/index.html), when you scroll to the bottom and click on "Privacy", you get a 404 error. We deal in the medical industry and it is a hard requirement to know how you use our / our user's data. Could someone relink this page, please?

If this isn't the correct place to ask this, please point me in the direction to send an email and I'll get it done.

Thank you!

**Comment by Zakeelm** [comment]
Hey there! 

That website is deprecated. We now use the http://appcenter.ms for CodePush. The privacy policy can be found here: https://privacy.microsoft.com/en-us/privacystatement

**Comment by Rob117** [comment]
@Zakeelm Thank you so much!
