### ISSUE TITLE
Slow Propagation

### ISSUE THREAD

**Issue by jdadojr** [Microsoft/code-push#572]
After releasing, I monitor the metrics and looks like its slow as a snail in propagating the updates to the client

==============================
Production │ Label: v5                  │ Active: 0.62% (336 of 54,432) │
│            │ App Version: 9.0.0 - 9.0.5 │ Total: 336 (24 pending)       │
│            │ Mandatory: Yes             │ Rollbacks: 2                  │
│            │ Release Time: an hour ago  │                               │
│            │ Released By:               │         
==============================

Like it says, its been an hour and the Total is just 336? Am I reading this wrong?
When I manually install the 9.0.0 version the update immediately takes effect, however
versions 9.0.2 (very many) and 9.05(very few) are not updating (yet?).

Any insights?

**Comment by alexandergoncharov** [comment]
Hi @jdadojr 
Thanks for reporting and sorry for long delay!

Yeah, you read this correctly. For default `Mandatory` settings update is checking updates on every lunch app. I think that the reason of this is just not popular time for users as they didn't opened app in this hour. Possible it can be night or something like that.
Could you please clarify about next installations of this update?  Did all users get this update or issue is still here?

Thanks,
Alexander

**Comment by alexandergoncharov** [comment]
Hi @jdadojr ,

I'm going to close this issue as I haven't heard from you in a while. Please feel free to reopen it if you have any questions or you are again faced with this issue.

Thanks,
Alexander
