### ISSUE TITLE
Would you please add examples [release app and promote app]?

### ISSUE THREAD

**Issue by ray-shawn** [Microsoft/code-push#575]
I am using "code-push" 2.0.5 and I realize it is so hard to use it if we do not have examples or documents, would you please add them ?

**Comment by alexandergoncharov** [comment]
Hi @ray-shawn,

Unfortunately I'm going to close this issue as I haven't heard from you in a while.
Please feel free to reopen it or open one more if you have any questions.

Thanks,
Alexander
