### ISSUE TITLE
the app on the phone is not updated

### ISSUE THREAD

**Issue by 1104931825** [Microsoft/code-push#577]
Show successful release,but the app on the phone is not updated.  Is it necessary to set up a VPN?  Can this be used in China?

**Comment by alexandergoncharov** [comment]
Hi @1104931825 ,
Thanks for reporting!

I'm not sure about some blockers in China but we have some developers from China.
Possible the reason of issue can be in other things.
Could you please share logs, configuration for CodePush, platform, OS, and other info which can help us to find the reason of issue? 

Thanks,
Alexander

**Comment by NickToropov** [comment]
Hey! We haven’t heard from you in a while, so I am going to go ahead and close this issue. Feel free to reach us if you need any help with code-push.
