### ISSUE TITLE
Docs on GitHub Pages are outdated

### ISSUE THREAD

**Issue by angly-cat** [Microsoft/code-push#582]
The page of [`Supported React Native platforms` on GitHub Pages](http://microsoft.github.io/code-push/docs/react-native.html#link-1) mentions `v0.50` version at most, however [`README` of `react-native-code-push` repo](https://github.com/Microsoft/react-native-code-push#supported-react-native-platforms) mentions the most recent `v0.56` React Native version.

Seems that the GitHub Pages docs are outdated.

Please update.

**Comment by NickToropov** [comment]
Hi @angly-cat, thanks for posting the issue! Will fix it next week.

**Comment by alexandergoncharov** [comment]
Hi @angly-cat ,
Thanks for reporting!

This is deprecated docs. Please use Github docs:  https://github.com/Microsoft/react-native-code-push#supported-react-native-platforms and Microsoft AppCenter docs: https://docs.microsoft.com/en-us/appcenter/distribution/codepush/react-native#supported-react-native-platforms

Please let me know if you have any questions.

Thanks,
Alexander

**Comment by angly-cat** [comment]
> Microsoft AppCenter docs: https://docs.microsoft.com/en-us/appcenter/distribution/codepush/react-native#supported-react-native-platforms

Thanks. After creating this issue, I've stumbled upon these docs and started to use it.

> Please use Github docs: https://github.com/Microsoft/react-native-code-push#supported-react-native-platforms

README in that repo has links to `codepush.tools/*` (like http://codepush.tools/docs/getting-started.html for "getting started"), which redirect to those deprecated docs.

> This is deprecated docs.

The issue is that there isn't any deprecation watnings or notices. So may I suggest that you add such warnings/notices about that docs being outdated (or just plainly redirect to Microsoft AppCenter docs, which should be possible, because docs structure don't seem to change much)?

**Comment by alexandergoncharov** [comment]
@angly-cat, Links to old docs was changed with link to new docs. Also, all old docs pages will be redirected to new docs soon. I'm going to keep this open until it's done.

Please let me know if you have any questions.

**Comment by angly-cat** [comment]
> Links to old docs was changed with link to new docs. Also, all old docs pages will be redirected to new docs soon.

Good to hear, thanks.

> Please let me know if you have any questions.

No more question regarding this issue.

**Comment by alexandergoncharov** [comment]
Hi @angly-cat 

Implemented redirect logic. You can check just visit old docs. For example: http://microsoft.github.io/code-push/docs/react-native.html#link-1
You should be redirected to `docs.microsoft.com` site.

So, as issue was resolved I'm going to close this issue for now. Please feel free to reopen it if you have any questions.

Thanks,
Alexander
