### ISSUE TITLE
The update didn't really success. what's wrong with my code?

### ISSUE THREAD

**Issue by cabinhero** [Microsoft/code-push#588]
There is no error occurs in my updating progress: download the file->install update->restart the app->Checking for update->Reporting CodePush update success ()->App up to date.
There's nothing seems to be wrong. but the UI of my app doesn't change at all.  Can you give me some advice?

**Comment by yuri-kulikov** [comment]
Hi @cabinhero! Сan you provide more information about:
* What sdk do you use (react-native-code-push/cordova-plugin-code-push)?
* What versions of products do you use?
* On what platform (iOS/Android)?
* Maybe you can provide some simple reproducible demo.

That would be very helpful!

**Comment by cabinhero** [comment]
Hello, thanks a lot. I resolve the issue finally. I got this error due to I was running a debugger apk. When I run  a release apk, all updating works.

**Comment by NickToropov** [comment]
Hi @cabinhero I'm glad to hear you was able to resolve your issue.
Will close it but feel free to reopen it or create a new one if you have any questions.
Thanks for using CodePush!
