### ISSUE TITLE
Can anyone understand the error?

### ISSUE THREAD

**Issue by dc165015** [Microsoft/code-push#590]
I encountered the following error after I update from the app on client. The app on client did retrieve the update release. But then the error occured.

[app-scripts] [15:01:09]  console.error: [CodePush] An error has occured while installing the package. Could not get the package start
[app-scripts]             page. StackTrace: Error: An error has occured while installing the package. Could not get the package start
[app-scripts]             page at preInstallFailure
[app-scripts]             (http://192.168.2.3:8100/plugins/cordova-plugin-code-push/bin/www/localPackage.js:246:41) at
[app-scripts]             Object.callbackFromNative (http://192.168.2.3:8100/cordova.js:293:52) at processMessage
[app-scripts]             (http://192.168.2.3:8100/cordova.js:1114:17) at processMessages (http://192.168.2.3:8100/cordova.js:1137:9)
[app-scripts]             at http://192.168.2.3:8100/build/vendor.js:130322:26 at t.invoke
[app-scripts]             (http://192.168.2.3:8100/build/polyfills.js:3:14976) at r.run
[app-scripts]             (http://192.168.2.3:8100/build/polyfills.js:3:10143) at http://192.168.2.3:8100/build/polyfills.js:3:20242
[app-scripts]             at t.invokeTask (http://192.168.2.3:8100/build/polyfills.js:3:15660) at r.runTask
[app-scripts]             (http://192.168.2.3:8100/build/polyfills.js:3:10834)
Here is my config.xml

<?xml version='1.0' encoding='utf-8'?>
<widget id="cn.bookheart.app" version="0.0.2" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
  ...
  <content original-src="index.html" src="http://192.168.2.3:8100" />
  <access origin="*" />
  <allow-intent href="http://*/*" />
  <allow-intent href="https://*/*" />
  ...
  <platform name="android">
      <allow-intent href="market:*" />
      <preference name="AndroidLaunchMode" value="singleTask" />
      <preference name="android-build-tool" value="gradle" />
      ...
  </platform>
Here is my package.json

{
  "name": "example",
  "version": "0.0.2",
  "homepage": "http://example.com/",
  ...
I tried to reinstall platform android and then update release, but it was the same error. I use ionic 3.

**Comment by alexandergoncharov** [comment]
Hi @dc165015 
Thanks for reporting!

Could you please open this issue in [cordova-plugin-code-push ](https://github.com/Microsoft/cordova-plugin-code-push) with this [issue template](https://github.com/Microsoft/cordova-plugin-code-push/blob/master/.github/ISSUE_TEMPLATE.md)?
This additional information helps us understand this issue.
