### ISSUE TITLE
New Website Logo: HomeDruid

### ISSUE THREAD

**Issue by gagangoku** [Microsoft/code-push#592]
Please fill the following out:

- Name: HomeDruid
- Homepage (or app store) url: https://play.google.com/store/apps/details?id=com.homedruid.customer.app.rn.notificationtester, https://www.homedruid.com/
- Brand Guidelines/Licensing: Don't modify, use as is
- Logo: https://imageserver.homedruid.com/v1/image/get?id=277&ns=static

> Example:
>
> Name: Microsoft
> Homepage url: https://microsoft.com
> Brand Guidelines/Licensing: https://www.microsoft.com/en-us/legal/intellectualproperty/trademarks/usage/logo.aspx
> Logo: https://news.microsoft.com/microsoft-news-center-photos/msft_logo_rgb_c-gray/

**Comment by alexandergoncharov** [comment]
Hi @gagangoku ,
Thanks for reporting!

Could you please provide more details about your report? And what is your issue or questions?
As It isn't clear for now with provided info =)

Thanks,
Alexander

**Comment by gagangoku** [comment]
https://microsoft.github.io/code-push/community/friends.html asked me to fill this form to list our app as using Codepush.

Btw, have to say, it took me some time to setup codepush to work as expected, but I am liking it a lot :-) One major reason why i'm not using flutter.

**Comment by alexandergoncharov** [comment]
Oh, I see. Got it. Thanks for filling this! :)

**Comment by alexandergoncharov** [comment]
Hi @gagangoku,
Your app already added to friend page. Congratulations!
https://microsoft.github.io/code-push/community/friends.html 

So, I'm going to close this issue. Please feel free to reopen it if you have any questions.

Thanks,
Alexander

**Comment by gagangoku** [comment]
Thank you @alexandergoncharov 
One issue : the logo is getting cut off because of the border radius you've specified.
Can you please set border-radius to 0 for our icon.

<img width="207" alt="screen shot 2018-10-12 at 1 55 37 am" src="https://user-images.githubusercontent.com/544881/46831800-f81f8e80-cdc1-11e8-8ea3-0b9289d6e6b7.png">

**Comment by alexandergoncharov** [comment]
Answered in new issue: https://github.com/Microsoft/code-push/issues/596

**Comment by gagangoku** [comment]
Hi @alexandergoncharov 

I have migrated homedruid.com -> heloprotocol.in
Have raised a request for Helo Protocol in https://github.com/Microsoft/code-push/issues/626
Kindly remove homedruid.com from the list and add Helo.

Regards,
Gagan
