### ISSUE TITLE
Code Signing file not released

### ISSUE THREAD

**Issue by buddhamangler** [Microsoft/code-push#594]
2. In your description, please include the version of `code-push-cli` or `code-push` that you are using.

2.1.9

I'm getting an error in my app....

```
2018-10-08 15:09:30.583590-0500 REDACTED[318:29349] [CodePush] Error! Public key was provided but there is no JWT signature within app bundle to verify Possible reasons, why that might happen: 
1. You've been released CodePush bundle update using version of CodePush CLI that is not support code signing.
2. You've been released CodePush bundle update without providing --privateKeyPath option.
```

Here are the logs from my vsts bash task that releases to codepush...

```
2018-10-08T19:02:20.4280070Z Generated a release signature and wrote it to /Users/vsts/agent/2.140.2/work/r1/a/MobileBuild/drop/ios/.codepushrelease
2018-10-08T19:02:21.5212150Z 
2018-10-08T19:02:23.7921030Z Successfully released an update containing the "/Users/vsts/agent/2.140.2/work/r1/a/MobileBuild/drop/ios" directory to the "Test" deployment of the "REDACTED" app.
```

Here is the bash script that my task executes...

```
#!/usr/bin/env bash

set -e

npm install -g code-push-cli

code-push login --accessKey $1 || true

RELEASENOTES=$(<$6)

code-push release "$2" "$3" "$4" --deploymentName "$5" --description "$RELEASENOTES" --mandatory --privateKeyPath "$7" --noDuplicateReleaseError
```

The command looks like this...

`2018-10-08T19:02:12.0535090Z Formatted command: . '/Users/vsts/agent/2.140.2/work/r1/a/MobileBuild/drop/release/vsts-codepush-release.sh' "***" "REDACTED" "/Users/vsts/agent/2.140.2/work/r1/a/MobileBuild/drop/ios" "0.4" "Test" "/Users/vsts/agent/2.140.2/work/r1/a/MobileBuild/drop//versions/0.4.0.txt" "/Users/vsts/agent/2.140.2/work/_temp/private.pem"`

I used the cli to locate the blob url for my bundle, downloaded it, renamed to .zip, opened it and i can see that it does not include the .codepushrelease file.

What am I doing wrong here?

**Comment by buddhamangler** [comment]
React Native

**Comment by alexandergoncharov** [comment]
oh, Yeah. It is known issue about `release` command with private key. 
I recommend to use `appcenter` cli as this issues should be fixed there.
https://github.com/Microsoft/appcenter-cli

Also, Code-Push cli will be deprecated soon.

Please let me know if it was helpful or you have any questions.

**Comment by buddhamangler** [comment]
ahhhh, ok let me try that, thank you very much

**Comment by buddhamangler** [comment]
@alexandergoncharov thanks, it works.  btw, how come this repo doesn't have a fat warning about it being deprecated soon?  I may have missed it, but if it's not there it might not be a bad idea.
