### ISSUE TITLE
HomeDruid logo getting cut off

### ISSUE THREAD

**Issue by gagangoku** [Microsoft/code-push#596]
Thank you @alexandergoncharov for adding our logo

One issue : the logo is getting cut off because of the border radius you've specified.
Can you please set border-radius to 0 for our icon.

<img width="207" alt="screen shot 2018-10-12 at 1 55 37 am" src="https://user-images.githubusercontent.com/544881/46831800-f81f8e80-cdc1-11e8-8ea3-0b9289d6e6b7.png">

_Originally posted by @gagangoku in https://github.com/Microsoft/code-push/issues/592#issuecomment-429108533_

**Comment by alexandergoncharov** [comment]
Hi @gagangoku,

Yeah, possible we can just remove text and keep just logo without text for keeping similarity with other app? What do you think about it?

**Comment by gagangoku** [comment]
The text is useful since we're not a well known brand yet. Could you use this image instead : https://imageserver.homedruid.com/v1/image/get?id=309

Have added some padding in the image to ensure that the border radius does not cut off the text.

**Comment by gagangoku** [comment]
umm, just noticed our icon is not present on https://microsoft.github.io/code-push/community/friends.html anymore :-'(

**Comment by alexandergoncharov** [comment]
Hi @gagangoku,

Yeah, I had to do so for adding new image(as you just added empty border and framework didn't find diff between this 2 images).

At now all looks like great :)
Please check it here and let me know: https://microsoft.github.io/code-push/community/friends.html

**Comment by gagangoku** [comment]
Looks great @alexandergoncharov , thanks a ton !!

Btw, we have added some intelligence to our code push updates. I maintain the current appVersion in JS code and every time a code push update is found, it checks if the flags in description allow a silent update / user confirmation dialog. In case anyone is interested:

```
export const APP_VERSION = '3.0.3';
export function checkForCodepushUpdate() {
    let currentVersion = APP_VERSION;
    console.log('current app version: ', currentVersion);
    console.log('Checking for codepush update !');

    // Check for Codepush app update.
    codePush.checkForUpdate(CODEPUSH_DEPLOYMENT_KEY, (update) => {console.log('handleBinaryVersionMismatchCallback: ', update)})
        .then((update) => {
            if (update != null) {
                delete update['deploymentKey'];                         // Secret - should not be exposed
                console.log('Code push remote package: ', update);

                let desc = update['description'];
                let newVersion;
                if (desc.startsWith('version ')) {
                    newVersion = desc.split(' ')[1];
                    console.log('newVersion: ', newVersion);
                } else {
                    console.log('Could not infer version number from description. Ignoring codepush');
                    return;
                }

                if (currentVersion === newVersion) {
                    console.log('Exact same version. Ignoring codepush');
                    return;
                }
                let curSemVersion = semver(currentVersion);
                let newSemVersion = semver(newVersion);
                console.log('curSemVersion:', curSemVersion);
                console.log('newSemVersion:', newSemVersion);
                if (semver.major(curSemVersion) !== semver.major(newSemVersion)) {
                    console.log('Major version mismatch. Ignoring codepush');
                    return;
                }
                if (semver.lt(newSemVersion, curSemVersion)) {
                    console.log('Older version. Ignoring codepush');
                    return;
                }

                codePush.sync({
                    updateDialog: !desc.toLowerCase().includes('force-update-do-not-ask'),
                    installMode: codePush.InstallMode.IMMEDIATE,
                });
            } else {
                console.log('Code push remote package: null');
            }
        });
}

// Notify to codepush that current update version was successful.
export function codepushNotifyAppReady() {
    console.log('codePush.notifyAppReady:');
    codePush.notifyAppReady();
}
```

**Comment by alexandergoncharov** [comment]
Thanks for providing this additional info :)
