### ISSUE TITLE
rollback deployment

### ISSUE THREAD

**Issue by Nits7029** [Microsoft/code-push#597]
Hello,

I have accidentally remove deployment instead of clear, and my app is live in the play store as well as in app store.

So how i can rollback removed deployment so i don't need to change the API key

Please help me ASAP, thanks

**Comment by alexandergoncharov** [comment]
Hi @Nits7029 ,
Thanks for reporting!

I'm afraid it isn't possible to rollback removing deployment. So, you should create new binary version with new deployment key and update app in store.
Sorry for this.

Please let me know if it was helpful or you have any questions.

Thanks,
Alexander

**Comment by alexandergoncharov** [comment]
Hi @Nits7029,

I'm going to close this issue for now as I haven't heard from you in a while unfortunately.
Please feel free to reopen it if you have any questions.

Thanks,
Alexander
