### ISSUE TITLE
Can not use management SDK "The session or access key being used is invalid"

### ISSUE THREAD

**Issue by jay1337** [Microsoft/code-push#599]
Following https://docs.microsoft.com/en-us/appcenter/distribution/codepush/node with version 2.0.6 of code-push on Windows I'm stuck with this error:

`{ message: 'The session or access key being used is invalid; please run "code-push login" again. If you are on an older version of the CLI, you may need to run "code-push logout" first to clear the session cache.',
  statusCode: 401 }`

But I use for the acces key a valid ID returned in the first column by "appcenter tokens list".

Here is the exact code:

```
const CodePush = require('code-push');
const codePush = new CodePush('*********-****-****-******************');
(async () => {
	try {
		const res = await codePush.getDeployments('org/app');
		console.log('res', res);
	}
	catch (err) {
		console.log('err', err);
	}
})();
```

**Comment by NickToropov** [comment]
Hi @jay1337! Try to use `access key` not `ID`. Your current access key is located in `~/.code-push.config`. Or you can create a new one:
```
➜  NodeDemo appcenter tokens create -d "Some_description"
ID:          50ba798a-8bab-4c13-b861-038cef42853a
API Token:   b5efce78e005d1b83bd5101c4121387786df6517
Description: Some_description
Created at:  2018-10-16T10:20:23.000Z
```
and take `API Token`

**Comment by jay1337** [comment]
Thanks, it works.

You should definitely update the doc on https://docs.microsoft.com/en-us/appcenter/distribution/codepush/node:

> If you already created a token that you want to use here, then you can retrieve it by running appcenter tokens list and using the value of the ID column for the key you wish to use.

**Comment by NickToropov** [comment]
Yes, we definitely should! will keep it open until I or someone from the team updates docs.

**Comment by alexandergoncharov** [comment]
Hi @jay1337 ,

Docs are updated: https://docs.microsoft.com/en-us/appcenter/distribution/codepush/node#getting-started

So, I think that issue was resolved and I'm going to close this issue for now. Please feel free to reopen it if you have any questions.

Thanks,
Alexander
