### ISSUE TITLE
missing param Bucket

### ISSUE THREAD

**Issue by CveniEs** [Microsoft/code-push#600]
when I push the lastest version to server, I got the error, how should I do ? 
The commond line I use is：
$ code-push release-react newPatient ios --t 5.9.2 --dev false --d Staging --des "XXX" --m true

the error is :  
Upload progress:[==================================================] 100% 0.0s
[Error]  {"error":"missing param Bucket"}

**Comment by NickToropov** [comment]
Hi @CveniEs! Is the issue reproduced stably? What size of generated bundle? What versions of RN and plugin do you use and what are your dependencies? Also it would be helpful if you could provide a demo project.

**Comment by NickToropov** [comment]
Hey! 
We haven’t heard from you in a while, so I am going to go ahead and close this issue. Should you still have any questions, you can reopen the issue or if you prefer you can create a new one.
