### ISSUE TITLE
Code push updating app to the latest pushed version

### ISSUE THREAD

**Issue by monicse09ku** [Microsoft/code-push#602]
Hello,

My app version in the Google Play Store is 1.0.2. My first push to the code push is 1.0.3 which is two weeks earlier. Not I have updated to version 1.0.6 and pushed to code push. But my installed apps which is updated to version 1.0.3 by code push is not updating to latest version. And if I install again from play store, the app is still updating to version 1.0.3

`code-push release-react <app-name> android`
`code-push promote <app-name> Staging Production`

Why is this happening?

**Comment by alexandergoncharov** [comment]
Hi @monicse09ku ,
Thanks for reporting!

CodePush doesn't update binary version. It just replaced js part of app.
About binary versions: CodePush has `target version` setting which allow install current release only for current binary version of app. Foe example if you app is 1.0.2 and you make release with `target version` is 1.0.3 then your update should be ignored. For updating your 1.0.2 version app you should release update with 1.0.2 `target version`
Could you please share command which you used for releasing update?

Thanks,
Alexander

**Comment by monicse09ku** [comment]
Thanks @alexandergoncharov for your reply. I am not seeing the updates in my app view, I have hard coded the version number in my sidebar and not targeting any binary version because I need an overall update. But I am not getting the updates.

**Comment by alexandergoncharov** [comment]
@monicse09ku  Could you please provide logs during update?
You can grab it with AndroidStudio/adb logcat or XCode.

Also, I noticed from your duplicate issue that you used `release-react` command. This command use current project binary version as `target version` by default.

**Comment by monicse09ku** [comment]
how can I make all the previous versions to install the latest version?

**Comment by alexandergoncharov** [comment]
You should make one more release with `target version` as `*`. It allows to install release on all versions. But be careful with this approach as you had some binary changes behaviour can be unexpected.

Just add `--targetBinaryVersion *` to your `release-react` command.

Please let me know if it was helpful or you have any questions

**Comment by monicse09ku** [comment]
@alexandergoncharov thank you very much. This fixed my issue.

**Comment by alexandergoncharov** [comment]
That's great! Thanks for keeping us in touch!

As issues was resolved I'm going to close this issue for now.
Please feel free to reopen it if you have any questions.

Thanks,
Alexander

**Comment by monicse09ku** [comment]
dear @alexandergoncharov, 

Again I am facing an issue, I am trying the following code for updating my app

```code-push release-react <MY-App-Name> android --targetBinaryVersion *```

It should update the app to version 1.0.19 instead it is crashing and when I open it again, I can see that the app is updated to version 1.0.14;

Please tell me what I am doing wrong.

**Comment by alexandergoncharov** [comment]
Hi @monicse09ku :)
It looks like there is some issue and then calling rollback of your update. Could you please share logs during update?

**Comment by alexandergoncharov** [comment]
I see that you opened new issue in react-native-code-push repo: https://github.com/Microsoft/react-native-code-push/issues/1504
Let's continue our conversation there.
