### ISSUE TITLE
documentation for target-binary-version is not correct

### ISSUE THREAD

**Issue by DylanBruzenak** [microsoft/code-push#605]
I'm aware that there are a number of related closed bugs, so bear with me. This is a documentation bug that is causing people to have to keep filing those bugs due to falling into the same subtle trap. 

On: https://github.com/Microsoft/code-push/blob/master/cli/README.md

Under "Target binary version parameter" there is a table that says:

1.2 | Equivalent to >=1.2.0 <1.3.0

This is correct. 

Below that it says: 

"NOTE: If the app store version in the metadata files are missing a patch version, e.g. 2.0, it will be treated as having a patch version of 0, i.e. 2.0 -> 2.0.0. The same is true for app store version equal to plain integer number, 1 will be treated as 1.0.0 in this case."

This note should be removed entirely. It does not match what actually happens. Automatically grabbing the version from the info.plist uses 2.0, and triggers the normal handling for that number as specified in the table. In order to do 2.0.0 you either need to put that directly in info.plist or override using target-binary-version.

Additionally the documentation here: https://docs.microsoft.com/en-us/appcenter/distribution/codepush/cli (apologies if this is the wrong place for comments on that documentation but they are deeply related) has the same note and DOES NOT include the 1.2 | Equivalent to >=1.2.0 <1.3.0 so there's nothing that really handles the case correctly in that documentation. 

In that doc it would be best to add the correct row and remove this note.

https://github.com/Microsoft/code-push/issues/504 mentions the documentation being wrong but the behavior being correct but did not result in a documentation update.

Also: 
https://github.com/Microsoft/code-push/blob/064d70ddaff16b131836ece3723505e01844b5fa/cli/script/command-executor.ts:904

// Allow plain integer versions (as well as '1.0' values) for now, e.g. '1' is valid here and we assume that it is equal to '1.0.0'.
// (missing minor/patch values will be added on server side to pass semver.satisfies check)

I'm not sure if that is in fact happening, server side, and again, if 1.0 is different than 1.0.0 in functionality then that should be called out.

**Comment by DylanBruzenak** [comment]
Thanks for looking into it. 

One further thing I noticed: 1.4.0 targeted distributions don’t seem to patch 1.4 app versions, which means the only way to push to an app with 1.4 (not 1.4.0) in the plist seems to be to push a 1.4 distribution... which patches 1.4.x. Which effectively means you can’t use minor versions for all of 1.4 if you make the mistake of leaving the minor version off when you ship a binary to the App Store.

If it matters I’m testing iOS only at the moment.

**Comment by DylanBruzenak** [comment]
I’ll have to double check 1.4.0 not patching 1.4, as we are going through version churn. Maybe I installed the wrong one. Ignore that note for now, I’ll open a separate bug if it happens again.

Otherwise, I’m not sure if I’m being clear above. The problem isn’t how it works, it is how it is documented.

If you leave out the target binary version from the code deploy command and have a plist entry of 1.2 you will get a codepush distribution that targets 1.2.x and is listed as targeting 1.2 in the codepush metadata. The binary will be seen on the server as 1.2.0. When you naturally distribute a 1.2.1 binary it will be a complete surprise that it gets patched by your 1.2 distribution. You may not have even read the target binary section as you are not using that parameter. You will end up with old code on top of the new binary and it will break things.

If you’re lucky enough to be reading the github doc instead of the app center doc, which is entirely missing the 1.2 == >=1.2.0 < 1.3.0 line, you may be able to puzzle through this. But that note doesn’t make anything clearer because it doesn’t say WHEN it treats it as 1.2.0. It treats it as 1.2 for the client and distribution and treats it as 1.2.0 when checking to see if it should be patched, but it could be saying “I see 1.2 in the plist, i’m going to assume you mean 1.2.0, so that’s what we’ll patch, that’s what we are targeting with the metadata”. And if you’re on the app center doc the table doesn’t list this case so when you see 1.2 in the distribution metadata it doesn’t ring an alarm bell.

There are a couple of ways to prevent users from making this error: 

1. The client should read 1.2 in the plist as 1.2.0 (like it implied in the note in the note) and then create a distribution that explicitly targets 1.2.0. That’s what people expect, they don’t expect that the default plist reading will see 1.2 and think, “I want to patch every future version of this binary too!”... only a machine would ever think that was reasonable.
2. It could warn when creating the distribution that without 3 numbers in the version the handling of the version number might not match what you expect
3. The meta data could have a (targeting version >= 1.2.0 < 1.3) printed out explicitly so that you can catch this reading the metadata and not assume 1.2 is equivalent
4. This note should be changed to read “binary version” instead of “AppStore metadata version” to be consistent with the rest of the doc. 
5. The note could mention that 1.2 in the plist will be interpreted as 1.2.0 for purposes of determine whether to patch that version of the binary,  but this is separate from the handling of the target binary version parameter, which matches the table above. If you are using 1.2 in target binary version you will patch ANY 1.2. Being explicit here will help reduce confusion between the note and the table and help people who have to figure this stuff out at 2 am because customers are suddenly crashing after a codepush build sending versions out unexpectedly.
6. The ms app center note MUST match this documentation as on their own right now they are only part of the story and don’t cover the 1.2 metadata version case at all.

Not all of these would have to be done, probably you could just improve the doc around this section and the automatic version detection section to explicitly cover this case.

I understand that the instinct may be to leave well enough alone here, but the potential consequences of deploying the wrong version are quite bad, and this will have negative implications for usage of the project as frustrated devs vent about it. You can say “they should have read the doc more carefully”... but it’s always on the doc to be clear, and it isn’t here (and is outright missing important info on appcenter).

I hope this makes sense. Thanks!

**Comment by alexandergoncharov** [comment]
Hi @DylanBruzenak,
Sorry for this delay.

1. I updated CLI with warning: https://github.com/microsoft/appcenter-cli/pull/598#event-2469985623
2. Replaced `app store version` with `binary version` in docs:
https://github.com/microsoft/code-push/pull/634
https://github.com/microsoft/react-native-code-push/pull/1614
https://github.com/microsoft/cordova-plugin-code-push/commit/6461b8a06d5c6083310d4893f71b2210fc70201e
and in appcenter docs: https://docs.microsoft.com/en-us/appcenter/distribution/codepush/cli#target-binary-version-parameter

Also added `1.2` case for equivalent table.

I think that it is enough for correctly understanding this part.

Could you please share your thoughts about it?

**Comment by alexandergoncharov** [comment]
Hi @DylanBruzenak ,

I'm going to close this issue for now as I haven't heard from you in a while and issue was fixed, I think.
Please feel free to reopen it if you have any questions.

Thanks,
Alexander

**Comment by DylanBruzenak** [comment]
Sorry, I haven't worked with code push in a bit. The changes look great!

**Comment by hadare1** [comment]
I have the same issue,
I get this log:

![Screen Shot 2020-01-22 at 9 52 35 PM](https://user-images.githubusercontent.com/32154203/72960132-8fafb300-3d61-11ea-966b-24aaf2190107.png)

I'm not sure if I'm doing something wrong
