### ISSUE TITLE
Can I revert my Staging deployment ?

### ISSUE THREAD

**Issue by aleafo** [Microsoft/code-push#608]
code-push --version
2.1.9

I have removed my Staging deployment by using:
```
code-push deployment rm myApp Staging
```
And then I found that the staging deployment is completely remove.
But I have set the staging deployment key in the info.plist. And the binary has been approached. How can I revert the deployment key or is there any way I could custom the deployment key by myself?
tks!

**Comment by alexandergoncharov** [comment]
Hi @aleafo,
Thanks for reporting!

Unfortunately there isn't any approach to revert removing of deployment or specify deployment key as it can break consistency. I'm sorry for that.
Also, in the future you can remove all releases from deployment(without removing deployment and deployment key) with clear command like this: `code-push deployment clear myApp Staging`.  After that you still can use old deployment key and make new releases in this old deployment.

Please let me know if it was helpful or you have any questions.

Thanks,
Alexander
