### ISSUE TITLE
Authentication failed. Your API token could not be created

### ISSUE THREAD

**Issue by cpbmm** [Microsoft/code-push#613]
The code-push-cli@2.1.9 version is being used. Use the command: code-push login. Raise the Google browser to display Authentication failed and Your API token could not be created. It failed for two consecutive days.
![image 2019-01-13 14 14 07](https://user-images.githubusercontent.com/33424569/51082204-80a12880-173d-11e9-8771-8b0615087853.jpg)

**Comment by alexandergoncharov** [comment]
Hi @cpbmm,
Thanks for reporting!

I just tested your case and successfully got API token. Could you please ensure that you logged in correct GitHub or Microsoft account and let me know your results?

Thanks,
Alexander
