### ISSUE TITLE
react-native-code-push mandatory flag is not working

### ISSUE THREAD

**Issue by littlehome-eugene** [Microsoft/code-push#614]
We are seeing logs that only old versions could generate long after we publish mandatory updates. 

We are using following options but I think it shouldn't matter because `mandatory` flag deals with `mandatoryInstallMode`
```

 let codePushOptions = {
   checkFrequency: codePush.CheckFrequency.ON_APP_RESUME,//
   installMode: codePush.InstallMode.ON_NEXT_RESUME//Silent sync everytime the app resume.
 };
```

Are there some suggestions where to look when mandatory update doesn't seem to work for every device? (actually majority of devices are not updating..)

Also, I'd like to log what versions user is using whether they are updating by using one of `getCurrentPackage`, `getUpdateMetadata` or something similar.  
Are they supposed to be meaningful in `mandatory` update scenario?

**Comment by alexandergoncharov** [comment]
Hi @littlehome-eugene,
Thanks for reporting!

I'm sorry but could you please describe your issue more detailed?

Default settings for `mandatory` update is `codePush.InstallMode.IMMEDIATE`.

>Are there some suggestions where to look when mandatory update doesn't seem to work for every device? 

No, Mandatory update should affect some device for installing. All devices should be updated.
Could you please clarify are there some rollbacks or just devices don't try to take updates?

**Comment by alexandergoncharov** [comment]
Hi @littlehome-eugene,

I'm going to close this issue for now as I haven't heard from you in a while unfortunately.
Please feel free to reopen it if you have any questions.

Thanks,
Alexander

**Comment by zmnv** [comment]
@alexandergoncharov hello, Alexander!

I have the same problem with `mandatory`.

1. Update .js code
2. Do the command:
```
appcenter codepush release-react -a <owner>/<App>-iOS -m -d Dev --target-binary-version "1.10.0"
```
3. Look at the application, nothing.

I use that command to update stage named `Dev` or `StageName`.
It sends new js bundle to code-push server, thats ok.
But in application nothing happens. I was waiting for changes but nothing.

Does `mandatory` works only in Production stage? 
I can't try to use it with production now, that need more time...

Also I use `react-native-code-push-saga`. 
Also I used `mandatory` without `push-saga` but directly:
```
codePush(codePushOptions)(App)
```
result the same.

Options:
```
const CODEPUSH_DEV_KEY = ".....key....";
...
syncOptions: {
    installMode: codePush.InstallMode.ON_NEXT_RESUME,
    mandatoryInstallMode: codePush.InstallMode.IMMEDIATE,
    deploymentKey: CODEPUSH_DEV_KEY,
}
```

---

```
React Native 0.60.4
iOS 12.2
appcenter-cli 2.2.1

"appcenter": "2.4.0",
"appcenter-analytics": "2.4.0",
"react-native-code-push": "5.7.0",
"react-native-code-push-saga": "1.0.1",
```
