### ISSUE TITLE
Capacitor Support

### ISSUE THREAD

**Issue by AgDude** [microsoft/code-push#615]
I think the title says it all. https://capacitor.ionicframework.com/

Capacitor is becoming the preferred solution for new Ionic apps, and we are looking at moving some of our existing apps to that as well. We have thus far been very happy with code-push in our cordova apps and would like very much like to continue using it as we make the transition to capacitor.

This was discussed here: https://github.com/Microsoft/cordova-plugin-code-push/issues/450 (but that doesn't seem like the right place for it)

**Comment by botatoes** [comment]
Hi, 

Thanks for the feedback for CodePush. I've added Capacitor to the code-push backlog. We are looking through priorities and adjusting them accordingly. Unfortunately Capacitor support is not on our backlog for this quarter. We are aware of its growth and will continue to monitor its presence to help better prioritize our backlog of feature requests. Closing this for now.

**Comment by sneko** [comment]
Hi @botatoes , do you have any news on this?

Thank you,

**Comment by dylanvdmerwe** [comment]
Capacitor is now fully released on version 1. https://blog.ionicframework.com/announcing-capacitor-1-0/

**Comment by digaus** [comment]
Its no 3rd quarter and I want to switch to capacitor but cannot because code push is not supported...

**Comment by dylanvdmerwe** [comment]
Code push is a blocker for us to move to Capacitor.

**Comment by DavidBajon** [comment]
Still no update on this?

**Comment by caro-health** [comment]
Hi there, code push is also a blocker for us to move to capacitor. Could you please give us an update? Thank you.

**Comment by jacksonGross** [comment]
It's been a while now and Capacitor is past a 1.0 release now ([they are actually working towards a 2.0 release](https://github.com/ionic-team/capacitor/releases/tag/2.0.0-beta.1)). Can anyone share an update on when this might be available? This is a huge blocker for our team to move to Capacitor.

**Comment by thgick** [comment]
same here!

Am Do., 2. Apr. 2020 um 07:57 Uhr schrieb Jackson Gross <
notifications@github.com>:

**Comment by kapten96** [comment]
Any updates on this?

**Comment by darron1217** [comment]
Capacitor is currently 2.3 and working towards 3.0

npm's weekly download count is currently 64,825 and there are plenty of potential users waiting for plugin supports.

Also this is a web resource, which might be easier to implement rather than native scripts (I guess)

**Comment by rajashekarreddy2222** [comment]
any update on this please

**Comment by johannds** [comment]
+1 for Capacitor support. The platform is growing rapidly and the company that heads up development on it have ramped up their development efforts.

**Comment by sta55en** [comment]
This is something that is urgently needed. Capacitor is heading towards a version 3.0 release soon and there's no support, even though there are thousands of projects using Capacitor out there.

When is the plan to support it?

**Comment by HumanX-Life** [comment]
Please? Not sure what else to say.

**Comment by HumanX-Life** [comment]
Please? Not sure what else to say after all the requests on this issue

**Comment by HumanX-Life** [comment]
Please? Not sure what else to say after all the requests on this issue.

**Comment by dylanvdmerwe** [comment]
As per my previous [comment](https://github.com/microsoft/code-push/issues/615#issuecomment-523402984), code push is still a blocker for us before we can migrate to capacitor.

**Comment by rizkyramadhan** [comment]
Current progress is stalled at https://github.com/microsoft/cordova-plugin-code-push/issues/450#issuecomment-524639558

**Comment by mkuchak** [comment]
+1 That would be a very, very desirable feature.

**Comment by alimcharaniya** [comment]
+1 to everyone above. I would prefer using MS CodePush over Ionic's AppFlow. 

Don't forget documentation for mono-repos (lerna), please. As many ionic developers are reusing web-app code.

**Comment by andreidubov** [comment]
Reopened the card due to a large number of requests for capacitor support.

**Comment by edy-ap** [comment]
+1

**Comment by Babsvik** [comment]
> Reopened the card due to a large number of requests for capacitor support.

Hey @andreidubov do you guys have any eta on when this might have a release candidate?

**Comment by rammere** [comment]
Hey ,
The community is very big now,
Can we get ETA for this one ?

**Comment by andrii-z4i** [comment]
Hi @rammere , thank you for your patience, but I think we will not be able to work on it soon.
The reason for this is that we are in maintenance mode now [Roadmap 2020-2021](https://github.com/Microsoft/appcenter/wiki/Roadmap)

```Just like any software engineering team, as we focused on building and scaling App Center, we accumulated technical debt that can no longer be sustained. Therefore, as we look to what is next, the App Center team will prioritize improving reliability and performance for the service through mid-2021. This means new feature work will be significantly reduced. Switching focus to reliability and performance wasn’t an easy decision, but nevertheless an important one.```

Saying that I would expect that we can come back to the feature roadmap review not sooner than the mid of 2021.

**Comment by gillarf** [comment]
+1 for this - please, we really need this to work with Capacitor

**Comment by GalvinGao** [comment]
> DISCLAIMER: This comment proposes a possible "workaround" style answer to the problem and may not be recommended. You shall not use this approach before the AppCenter team call for a real release on Capacitor platform but, with that being said if it works well then it doesn't matter xD

I was trying to just dive in with the Cordova option that AppCenter claims to be supporting and surprisingly it **works** (and very surprisingly almost hassle-free), at least from what I can tell - I saw myself in the Analytics panel of AppCenter.
Here's the steps I taken, basically following the [instructions](https://capacitorjs.com/docs/cordova/using-cordova-plugins#installing-cordova-plugins) on the Capacitor side where you install the Cordova plugins:
1. Install all AppCenter capabilities with `yarn add -D cordova-plugin-appcenter-analytics cordova-plugin-appcenter-crashes cordova-plugin-appcenter-push` (OR if you are using npm: `npm install cordova-plugin-appcenter-analytics cordova-plugin-appcenter-crashes cordova-plugin-appcenter-push`)
2. `npx cap sync`
	- For iOS, if you saw `[Xcodeproj] Unknown object version`, do `gem upgrade xcodeproj` in your project's `ios/` folder as stated in https://github.com/CocoaPods/CocoaPods/issues/7697
3. Add `<preference name="APP_SECRET" value="..." />` (do NOT wrap with `<platform>` tags) to `iOS/App/App/config.xml` and `Android/app/src/main/res/xml/config.xml`
    - **NOTICE**: after you've filled in your `APP_SECRET`, do NOT run `npx cap update` or your `APP_SECRET` will be removed by Capacitor. I haven't found a working method of getting Capacitor copy over the `APP_SECRET` for me (and seems they doesn't support it by-design: See *Important: Configuration* at [here](https://capacitorjs.com/docs/cordova/using-cordova-plugins#important-configuration))
    - After this your `config.xml` shall look like this:
<details>
<summary>`ios/App/App/config.xml` Content</summary>

```xml
<?xml version='1.0' encoding='utf-8'?>
<widget version="1.0.0" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
  <access origin="*" />
  
  <feature name="AppCenterAnalytics">
    <param name="ios-package" value="AppCenterAnalyticsPlugin"/>
    <param name="onload" value="true"/>
  </feature>

  <feature name="AppCenterCrashes">
    <param name="ios-package" value="AppCenterCrashesPlugin"/>
    <param name="onload" value="true"/>
  </feature>

  <feature name="AppCenterPush">
    <param name="ios-package" value="AppCenterPushPlugin"/>
    <param name="onload" value="true"/>
  </feature>

  <feature name="AppCenterShared">
    <param name="ios-package" value="AppCenterSharedPlugin"/>
    <param name="onload" value="true"/>
  </feature>

  <preference name="APP_SECRET" value="00000000-0000-0000-0000-000000000000" />
  
</widget>
```

</details>


4. Go to your project file, build and run it! After you launch your App you should be able to see it in the Analytics panel of AppCenter now.

<details>
<summary>Here's a screenshot</summary>

![image](https://user-images.githubusercontent.com/12567059/104822734-b7a3fa80-587f-11eb-9c4e-2b76da215dec.png)


</details>

Hope this helps!

**Comment by Mahmoud-Masri** [comment]
@GalvinGao the discussion here is about code-push not push notification or app center

**Comment by Mahmoud-Masri** [comment]
Just add this and it will work (at least for android, I haven't tested it on IOS yet)

```typescript
const baseUrl = (
        await Capacitor.Plugins!.Filesystem.getUri({ path: '', directory: FilesystemDirectory.Data })
    ).uri.replace('file://', '')

    codePush.getPendingPackage((localPackage) => {
        if (localPackage) {
            const path = `${baseUrl}${localPackage.localPath}/dist`
            switchToPath(path)
        } else {
            codePush.getCurrentPackage((localPackage) => {
                const path = `${baseUrl}${localPackage.localPath}/dist`
                switchToPath(path)
            })
        }
    })


async function switchToPath(path: string) {
    if ((await Capacitor.Plugins!.WebView.getServerBasePath()).path === path) {
        return
    }

    Capacitor.Plugins!.WebView.setServerBasePath({ path })
    Capacitor.Plugins!.WebView.persistServerBasePath()
}

```

**Comment by leo6104** [comment]
I made a plugin for Capacitor CodePush. It require @capacitor 3.0.0-beta.1 version & plugins. 
https://github.com/mapiacompany/capacitor-codepush 

It has an issue with @capacitor/filesystem plugin for now. After next release, it will be working. 

I tested it in Android & iOS.

**Comment by gillarf** [comment]
> I made a plugin for Capacitor CodePush. It require @capacitor 3.0.0-beta.1 version & plugins.
> https://github.com/mapiacompany/capacitor-codepush
> 
> It has an issue with @capacitor/filesystem plugin for now. After next release, it will be working.
> 
> I tested it in Android & iOS.

Thanks for much for the hard work @leo6104 - do you have any updates on the next release? It would be great to have filesystem working.

**Comment by leo6104** [comment]
It is my working dependencies. (package.json) 
```
    "capacitor-codepush": "git+https://github.com/mapiacompany/capacitor-codepush.git",
    "@capacitor-community/http": "git+https://github.com/leo6104/capacitor-community-http.git#dist",
    "@capacitor/device": "^0.5.3",
    "@capacitor/dialog": "^0.4.3",
    "@capacitor/filesystem": "^0.4.0",
```

There is no issue with capacitor official plugins latest version. (device, dialog, filesystem) 
But, it has an issue with @capacitor-community/http plugin. (Compatibility issue with Capacitor >= 3.0.0-beta.2) 

In my project, i cannot wait for next release of @capacitor-community/http so i fork the `@capacitor-community/http` repository and fix some issue and use the git url `https://github.com/leo6104/capacitor-community-http.git#dist` 

In the future they release 1.0.0 stable version, i will replace my git repository to @capacitor-community/http capacitor v3. 

When its all dependencies to be stable, i have a plan to publish it in npm repository. 
If Capacitor team approve it included on capacitor-community, Its plugin will be named to `@capacitor-community/codepush`. If they not approve, it might be `@mapiacompany/capacitor-codepush` 

I will comment on here when it release on NPM.

**Comment by alexcroox** [comment]
Fingers crossed @leo6104 I'm very curious to know if they accept it into @capacitor-community given their Appflow product 🤞 . Either way thanks again for your hard work on getting this working, there is a ton of people that have been waiting for it to move off Cordova.

**Comment by mkuchak** [comment]
> Fingers crossed @leo6104 I'm very curious to know if they accept it into capacitor-community given their Appflow product  . Either way thanks again for your hard work on getting this working, there is a ton of people that have been waiting for it to move off Cordova and I can't wait to implement it myself!

I expect the same thing. If they do not accept it, it is simply not an open source project and does not deserve to be used.

**Comment by o-alexandrov** [comment]
@andreidubov @andrii-z4i 
Could you kindly update on the plans for this feature?
- hopefully, this project is still alive, even though [since Apr 22nd 2021](https://github.com/microsoft/appcenter/wiki/Roadmap/_compare/18a6dcd7d09ae36d5a616c32cedfa1cc7e6d6e86...d3d0f9d6cacadb9011d135cb05ede4eccf77ccaa), there's no date when the enhancements in this repo will be resumed

The great part is:
- `@leo6104` already made it to work in his repo [mapiacompany/capacitor-codepush](https://github.com/mapiacompany/capacitor-codepush)

It would be great for the community, if you could support the project there by either:
- adopting it into this repo
- or by making sure, the interaction between the capacitor plugin above and App Center is as you envisioned

**Comment by ashish141199** [comment]
Hi @andreidubov @andrii-z4i 
Since now ionic has officially discontinued cordova and are now actively promoting capacitor, more and more developers and organisations are shifting to capacitor. We request you to provide support for capacitor as soon as possible. Or maybe atleast let us know your plans on the same.

**Comment by Gm33** [comment]
Any news?

**Comment by conkyliu** [comment]
> 我为 Capacitor CodePush 制作了一个插件。它需要@capacitor 3.0.0-beta.1 版本和插件。
> https://github.com/mapiacompany/capacitor-codepush
> 
> 目前@capacitor/filesystem 插件存在问题。下一个版本后，它将起作用。
> 
> 我在 Android 和 iOS 上对其进行了测试。

Can capatcitor v2 work?

**Comment by nagdevbharat** [comment]
Is there any update on when the support for code push will be available?

**Comment by Hambat** [comment]
Any updates code-push for capacitor 3?

**Comment by alexcroox** [comment]
@Hambat please read this thread, a working version is here: https://github.com/mapiacompany/capacitor-codepush

**Comment by Ad013** [comment]
Can anyone make a video documentation using [capacitor-codepush](https://github.com/mapiacompany/capacitor-codepush).It will be very much helpful.
I tried every steps but still code push is not working.

**Comment by riderx** [comment]
If needed i made an alternative tool for capacitor : https://github.com/Cap-go/capacitor-updater
