### ISSUE TITLE
App Store Review Guideline 2.3.1 - Performance

### ISSUE THREAD

**Issue by thecachedbyte** [Microsoft/code-push#616]
We have a hybrid app where few screens are in react native and other screens are native. We are using codepush for OTA updates. Recently Apple rejected our app review with reason

> We discovered that your app contains obfuscated code, selector mangling, or features meant to subvert the App Review process by changing this app's concept after approval to the App Store.

https://developer.apple.com/app-store/review/guidelines/#accurate-metadata

Anyone else facing/faced a similar issue?

**Comment by thecachedbyte** [comment]
Hi @alexandergoncharov 

Thanks for the quick response. Although it is little confusing, as the guideline says that interpreted code can be updated over-the-air and at the same time Apple is rejecting updates because React Native OTA update has potential to change, add, remove features.

Based on below comments, it looks like Apple is not in favor of OTA update for React Native apps.

https://github.com/Microsoft/react-native-code-push/issues/1297#issuecomment-416248296
https://github.com/Microsoft/react-native-code-push/issues/1297#issuecomment-419551822
https://github.com/Microsoft/react-native-code-push/issues/1297#issuecomment-392848792

What is your best understanding between these conflicting policy? (interpreted code can be updated v/s react native potential to change the app feature or purpose totally) How codepush team is evaluating this Apple's random rejection?

Currently, we are waiting for a reply from Apple team with proper reasoning.

**Comment by barryvdh** [comment]
Is the also an issue for cordova? Or is that not affected, as it only downloads web files, not 'native' functionality?

**Comment by alexandergoncharov** [comment]
Hi @thecachedbyte,
Sorry for delay.

Have you got reply from Apple team about this rejection?

**Comment by alexandergoncharov** [comment]
Hi @thecachedbyte ,

I'm going to close this issue for now as I haven't heard from you in a while unfortunately.
Please feel free to reopen it if you have any questions.

Thanks,
Alexander

**Comment by andreieuganox** [comment]
Same here. App rejected and resolution clearly states to remove CodePush!
