### ISSUE TITLE
Fix lodash vulnerability in code-push-cli 2.1.9

### ISSUE THREAD

**Issue by cbrwizard** [microsoft/code-push#618]
Hey, please fix the lodash vulnerability in code-push-cli 2.1.9.
To reproduce: run `yarn audit`.

<img width="512" alt="screenshot 2019-02-11 at 12 42 03" src="https://user-images.githubusercontent.com/1615659/52555368-8cdedb00-2dfa-11e9-9ec0-b7b72d727be7.png">

**Comment by alexandergoncharov** [comment]
Hi @cbrwizard,
Thanks for reporting!

Sorry for this delay. We will fix a bit later as soon as possible.
I'll keep this issue open until all vulnerability are fixed.

**Comment by ghiculescu** [comment]
Any updates here?

**Comment by alexandergoncharov** [comment]
Hi @cbrwizard and @ghiculescu ,

Unfortunately, I have to say that `code-push` is deprecated. 
Our recommendation is using `appcenter` cli: https://github.com/microsoft/appcenter-cli

I'm going to close this issue for now. Please feel free to reopen it if you have any questions.

**Comment by ghiculescu** [comment]
@alexandergoncharov is there a migration guide?

**Comment by alexandergoncharov** [comment]
@ghiculescu , we don't have a migration guide unfortunately because it is almost the same tool. Here is commands: https://github.com/microsoft/appcenter-cli#commands
You can find code-push commands that start with `appcenter codepush`.
