### ISSUE TITLE
Distributed version-control system codepush integration

### ISSUE THREAD

**Issue by HighSoftWare96** [Microsoft/code-push#620]
I was wondering if there is a way to bind codepush service to any version-control system (like Git of course) so I can release a build from a specific commit or branch and keep for example the current changes (local or remote) separated from the final releases.

**Comment by alexandergoncharov** [comment]
Hi @HighSoftWare96,
Thanks for reporting!

CodePush doesn't have this functionality but you can create your own automate script.
For release update you should just use console command and you can call it in automate script in case which you need.

Please let me know if it was helpful or you have any questions.

**Comment by HighSoftWare96** [comment]
Thanks @alexandergoncharov for the reply! So in this script what should I do? Make a git checkout, release with codepush and undo to the previous commit?

**Comment by alexandergoncharov** [comment]
Sorry for this delay. Yeah, like so. But I think you don't have to undo the previous commit.
It should be enough if you just checkout to necessary commit, bundle your code and release it or just use  `release-react`(or `release-cordova`) command.
Also, for ignoring the duplicate releases(it can be in automatic release cases) you should use `--disable-duplicate-release-error` field.

Please let me know if it was helpful or you have any questions.

**Comment by HighSoftWare96** [comment]
Okay thanks! I think this can work. In the future this can be a great improvement of this module but maybe it is out from the purpose of this system.
