### ISSUE TITLE
code-push logout error

### ISSUE THREAD

**Issue by nicetu** [Microsoft/code-push#621]
I don't logout on the old code-push-server that don't work now,And I want to login new server by new proxy. It shows "[Error]  You are already logged in from this machine". And I find logout it doesn't work.it also shows the old server of response. like this:
```javascript
[Error]  <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>405 Method Not Allowed</title>
</head><body>
<h1>Method Not Allowed</h1>
<p>The requested method DELETE is not allowed for the URL /**/code-push-server/sessions/username</p>
<hr>
<address>Apache/2.4.18 (Ubuntu) Server at url Port 80</address>
```

code-push version:2.1.9

**Comment by nicetu** [comment]
mobile-center tokens list
mobile-center tokens delete <machineName>

**Comment by NikiLee2016** [comment]
cd ~
ls -a
mv ~/.code-push.config ~/.code-push.config.bak
Then you can login your new server now.
