### ISSUE TITLE
Can I update the release label

### ISSUE THREAD

**Issue by Jeijie** [Microsoft/code-push#623]
My Step:
1.I had release many versions, the current label is v10.
2.execute following cli clear the realease：code-push deployment clear <appName> <deploymentName>
3.release again, but current label is v1, and now can't check update, because v10 > v1.

 If I could publish a version of V11 directly or update the label  It can be solved，any cli or strategies?

**Comment by alexandergoncharov** [comment]
Hi @Jeijie,
Thanks for reporting and sorry for delay.

Unfortunately there isn't any approach to change release label as this is unchangeable and this number is increased sequentially. I think that you have 2 workaround to fix it:
1. Remove updated from device by reinstalling app and then CodePush download the last available update.
2. Release 10 updates to increase release label.

Please be careful with clearing updates in the feature.
Please let me know if it was helpful or you have any questions.

Thanks,
Alexander

**Comment by Jeijie** [comment]
thanks

**Comment by alexandergoncharov** [comment]
Is there anything else that I can help you with?

**Comment by Jeijie** [comment]
no,thanks,I had release 10 updates to increase label.

**Comment by alexandergoncharov** [comment]
Great! Thanks for letting us know.

I'm going to close this issue for as it was resolved. Please feel free to reopen it if you have any questions.

Thanks,
Alexander
