### ISSUE TITLE
Code Push Support for Flutter

### ISSUE THREAD

**Issue by rodydavis** [microsoft/code-push#624]
Would it be possible to support Flutter?

https://flutter.dev/

https://github.com/flutter

**Comment by gagangoku** [comment]
This will be a good feature to have. This was one of the main reasons I went for React Native instead of Flutter.
Btw, Flutter 2019 roadmap does have Android Dynamic updates (https://github.com/flutter/flutter/wiki/Roadmap). I'm not sure how they'll support it though. My guess its something they have to fix in Flutter first, since the dart code is compiled into binary when packaged.

**Comment by alexandergoncharov** [comment]
Hi @AppleEducate,
Thanks for reporting!

That's is good point! But unfortunately we don't have supporting for Flutter item on our roadmap.
I'll investigate if it is possible to support Flutter and discuss with my team a bit later. I'll be keep you posted.

**Comment by AppleEducate** [comment]
@alexandergoncharov thank you!

**Comment by eseidelGoogle** [comment]
Discussion of Google's explorations in https://github.com/flutter/flutter/issues/14330#issuecomment-485565194.  I would be happy to speak with others from code-push further about this if desired.  eseidel@google reaches me.

**Comment by eseidelGoogle** [comment]
No offense taken  :)  (I will also be brief as I wish to be respectful of polluting someone else's bug tracker.)

At the end of the day we all have finite resources. :/  Code push/hot-updates is very exciting, but also high cost and not (yet) not high enough priority relative to the other things Flutter has been asked to do, hence it got bumped off our 2019 roadmap.  🤷‍♂  We get a *ton* of requests for code push/hot-updates/ephemeral-code-delivery/etc. and although Flutter for web can be used to answer some of those concerns there is a lot more I would like to see us do there over time.

**Comment by marceloiavenissi** [comment]
https://pub.dev/packages/dartins

**Comment by chgibb** [comment]
Hydro-SDK now supports codepush for Flutter apps https://hydro-sdk.io/blog/fluttering-over-the-air
