### ISSUE TITLE
New Website Logo: Helo Protocol

### ISSUE THREAD

**Issue by gagangoku** [Microsoft/code-push#626]
Please fill the following out:

- Name: Helo Protocol
- Homepage url: https://www.heloprotocol.in/
- App url: https://play.google.com/store/apps/details?id=com.heloprotocol.customer.app.rn.notificationtester
- Brand Guidelines/Licensing: (or anything we need to know before using your logo)
- Logo: https://images-lb.heloprotocol.in/logo-1024.png-49620-206734-1553339422270.png

> Example:
>
> Name: Microsoft
> Homepage url: https://microsoft.com
> Brand Guidelines/Licensing: https://www.microsoft.com/en-us/legal/intellectualproperty/trademarks/usage/logo.aspx
> Logo: https://news.microsoft.com/microsoft-news-center-photos/msft_logo_rgb_c-gray/

**Comment by gagangoku** [comment]
Ping !
@alexandergoncharov  @Jeijie @nicetu, kindly help.

**Comment by alexandergoncharov** [comment]
Hi @gagangoku,
Thanks for reporting!

I'll do it a bit later as soon as possible. Sorry for this delay.

**Comment by gagangoku** [comment]
No worries @alexandergoncharov 
Kindly migrate Homedruid -> Helo (see my last comment in https://github.com/Microsoft/code-push/issues/592)

**Comment by gagangoku** [comment]
Hi @alexandergoncharov 
Ping.

**Comment by alexandergoncharov** [comment]
Hi @gagangoku ,

Sorry for delay. I updated CodePush friend page with your new logo and link.
https://microsoft.github.io/code-push/community/friends.html

So, I'm going to close this issue for now. Please feel free to reopen it if you have any remarks or questions.

Thanks,
Alexander

**Comment by gagangoku** [comment]
Thank you @alexandergoncharov
