### ISSUE TITLE
codepush release-react -a username/appname failed with exception "Unable to find or read "package.json" in the CWD.

### ISSUE THREAD

**Issue by danieljgp2** [microsoft/code-push#629]
Hello, im getting this error when i try codepush release-react -a username/appname

> Error: Command 'codepush release-react -a usename/appname' failed with exception "Unable to find or read "package.json" in the CWD. The "release-react" command must be executed in a React Native project folder."

I'm running the command from the root project folder, also i have react-native as dependency on my package.json

I created my project with expo init bare template

**Comment by danieljgp2** [comment]
It seems that i already fixe it, key "name":"projectName" was missing on my package.json and that was the cause of my problem

**Comment by azilberbaum** [comment]
I am also having this same problem my package.json file looks like this

{
  "scripts": {
    "postinstall": "jetify",
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "web": "expo start --web",
    "start": "react-native start",
    "test": "jest"
  },
  "dependencies": {
    "@react-native-community/async-storage": "^1.6.2",
    "expo": "^35.0.0",
    "lodash.merge": "^4.6.2",
    "react": "16.8.3",
    "react-dom": "16.8.3",
    "react-native": "0.59.10",
    "react-native-ble-manager": "^6.7.0",
    "react-native-code-push": "^5.7.0",
    "react-native-elements": "^1.2.7",
    "react-native-fetch-polyfill": "^1.1.3",
    "react-native-gesture-handler": "^1.4.1",
    "react-native-keyboard-aware-scroll-view": "^0.9.1",
    "react-native-reanimated": "^1.3.2",
    "react-native-screens": "1.0.0-alpha.23",
    "react-native-slider": "^0.11.0",
    "react-native-unimodules": "0.6.0",
    "react-native-vector-icons": "^6.6.0",
    "react-native-web": "^0.11.7",
    "react-navigation": "^4.0.10",
    "react-navigation-stack": "^1.10.3",
    "react-navigation-tabs": "^2.5.6"
  },
  "devDependencies": {
    "@babel/core": "^7.6.0",
    "babel-jest": "24.9.0",
    "jest": "24.9.0",
    "jetifier": "^1.6.4",
    "metro-react-native-babel-preset": "0.56.0",
    "react-test-renderer": "16.9.0"
  },
  "jest": {
    "preset": "react-native"
  },
  "private": true
}

**Comment by azilberbaum** [comment]
That did seem to work adding "Name": "MyAppName"

But where is this in the docs?!

**Comment by danieljgp2** [comment]
@azilberbaum you are right, is not on the docs and it should.

**Comment by connorpmullins** [comment]
@azilberbaum's and @danieljgp2 's answers worked for me!

**Comment by nandorojo** [comment]
As mentioned above, make sure to add a `name` field to `package.json`. It should match your `ios` project name.

**Comment by tunm1228** [comment]
Please point to the path of your project directory
