### ISSUE TITLE
The CLI doesn't indicate why a release failed when specifying a non-semver compliant app version

### ISSUE THREAD

**Issue by lostintangent** [Microsoft/code-push#63]
The `code-push release` command displays helpful error messages when the specified app and/or deployment aren't valid, but if you specify a non-semver compliant app version label (e.g. `1.0` instead of `1.0.0`), it just silently fails and displays the help output for the command. I'm assuming that means that the issue is actually with the parser, and that the request is never hitting the server.

The command's examples in its help output correctly displays the use of semver version strings, but we should make sure the CLI provides as much guidance as possible. To that end, it would be great if we could catch this scenario and clearly report the issue to the user so they would know how to respond (e.g. change `1.0` to `1.0.0`).

**Comment by silhouettes** [comment]
On it
