### ISSUE TITLE
Get Codepush version so we can tag in Git.

### ISSUE THREAD

**Issue by export-mike** [microsoft/code-push#630]
Hi 

I'd like to be able to get the codepush label for a given app so after deployments we can tag it in GIT.

appcenter codepush deployment list --app <AppName> | ag -Q "Label: v"

results in: ```│ Production │ Label: v39                     │ No installs recorded │``` I can now go ahead and strip the rest and get v39 so i can git tag the changeset.

Is there an undocumented feature or set of tools we can use to manage codepush?

Also are there any tools you know of that can identify native code changes between previous revisions to prevent broken codepushes?

**Comment by alexandergoncharov** [comment]
HI @export-mike,
Thanks for reporting and sorry for the delay.

>set of tools we can use to manage codepush?

What kind of managing do you mean?

Yeah, CodePush has logic for preventing releases with the same code base. If it is issue for you you can use `--disable-duplicate-release-error` argument. When this flag is set, releasing a package that is identical to the release will produce a warning instead of an error.

Please let me know if it was helpful.

Thanks,
Alexander

**Comment by export-mike** [comment]
Hi @alexandergoncharov its more around knowing if theres been JS related changes only. as a native code change can cause incompatibility. and we need to then deploy a new binary to the stores. 

I've added a manual step on our CI (circle CI) which allows us to have control on what type of deployment we'll do with a changeset.

And to keep track in git of deployments, I've had to do write some bash to pull out the version of the latest codepush so we can git-tag. `ag -o 'v\d\d'`

```bash
             yarn appcenter login --token ${APPCENTER_APIKEY} --disable-telemetry
             if [ "${CIRCLE_BRANCH}" == "develop" ]; then
              yarn codepush:dev:android
              yarn codepush:dev:ios
              CPANDROIDVERSION=$(yarn codepush:dev:android:version | ag -o 'v\d\d')
              CPIOSVERSION=$(yarn codepush:dev:ios:version | ag -o 'v\d\d')
              git tag "codepush-android-dev-${CPANDROIDVERSION}"
              git tag "codepush-ios-dev-${CPIOSVERSION}"
              git push --tags
             fi
```

```json
{"codepush:dev:android:version": "appcenter codepush deployment list --app <appName> --disable-telemetry",
    "codepush:dev:ios:version": "appcenter codepush deployment list --app <appName> --disable-telemetry"}
```


```

**Comment by export-mike** [comment]
feels to me there should be a simple command to get the latest app version on codepush

**Comment by alexandergoncharov** [comment]
@export-mike, That's great that you implemented this logic!

Unfortunately no, there isn't any command to getting the latest app version for now. You have to get this info from `appcenter codepush deployment list`. Sorry for this. Possible you can use `--output json` field for getting this info in Json as it's easier to parsing.

**Comment by alexandergoncharov** [comment]
@export-mike please let me know if it was helpful or you have any questions.

**Comment by export-mike** [comment]
```--output json``` :O ok that i can live with.

**Comment by rdewolff** [comment]
I have a similar issue and have created another issue : https://github.com/microsoft/code-push/issues/678
