### ISSUE TITLE
OS version shows iOS Instead of Android

### ISSUE THREAD

**Issue by cullsin** [microsoft/code-push#632]
Hello,

I am using trail version and I successfully pushed through react-native cli. I have noticed that the OS name is showing "iOS" whereas I had pushed for android. Is this right ? or SInce I am in trial, It will be only iOS ?

![image](https://user-images.githubusercontent.com/5137598/58973260-25033480-87dd-11e9-9167-72e6cffce895.png)

**Comment by alexandergoncharov** [comment]
Hi @cullsin,
Thanks for reporting!

CodePush is free to use without any trail or full version. =)

>I successfully pushed through react-native cli

I think you mean `appcenter` cli? As it isn't possible to push a new release through `react-native` cli.

For our reccomendation, you should use different apps for different platforms. So, you should to create one more app for Android.

Please let me know if you have any questions.

**Comment by cullsin** [comment]
Hi,

I run the below command. 

code-push release-react stably android -d 'staging' -m --description 'init launch' 

it chooses the correct platform. 

![image](https://user-images.githubusercontent.com/5137598/59046354-7bd14280-889f-11e9-8813-a43d3e52566d.png)



Please suggest to me what went wrong.

**Comment by alexandergoncharov** [comment]
Hi @cullsin,
Sorry for delay!

It means that your update is identical as already released. To resolve this you should add some changes to your js code part.

Please let me know if it was helpful or you have any questions.

**Comment by alexandergoncharov** [comment]
Hi @cullsin ,

I'm going to close this issue for now as I haven't heard from you in a while, unfortunately.
Please feel free to reopen it if you have any questions.

Thanks,
Alexander
