### ISSUE TITLE
new more information : Active Downloads

### ISSUE THREAD

**Issue by cullsin** [microsoft/code-push#633]
Hi,
I can see an active Installs in the below screen. Is this shows number only if installed from the store? I have pushed the Android App. Can you please suggest me what is the process to download?

How do I download and Install the App for Testing the code push changes?

![image](https://user-images.githubusercontent.com/5137598/58973458-a955b780-87dd-11e9-8507-c51fdf4dc75c.png)

**Comment by alexandergoncharov** [comment]
Hi @cullsin 
Thanks for reporting!

This metrics only for CodePush updates. For testing this you should setup CodePush for your app and try to get an update. Please check this docs for more info about the setup for React-Native: https://github.com/microsoft/react-native-code-push#getting-started
And for Cordova: https://github.com/microsoft/cordova-plugin-code-push#getting-started

Please let me know if you have any questions.

**Comment by cullsin** [comment]
Hi, 

Thanks. I have a question. What do I suppose to do so that In the active install, I can see the number ?  Can you suggest me where do I release the app so that the user will have the option to download? I am talking about for android Installs.

BTW, the chatting service got broken :( which is inside the app center. 

Raja K

**Comment by alexandergoncharov** [comment]
In short words, you should do next steps: 
* Create an app with configured CodePush logic.
* Deliver binary version to your users throw stores or some other way which you prefer.
* Make CodePush release with some changes.
According to your CodePush configs, your users will get an update with your changes.

For more info about release please check this doc: https://docs.microsoft.com/en-us/appcenter/distribution/codepush/react-native#releasing-updates

Please let me know if it was helpful or you have any questions.

**Comment by cullsin** [comment]
Hello, 
I am sorry. I am still trying to understand without involving the app center or app stores.

1. I built an app and generated  pro.apk and installed in my device manually.
2. I have upgraded the react native with codePush changes and generated another apk and Installed on my device.
Is this how it works? Or in step 2. do I need to copy different files into my device, not an apk.

**Comment by alexandergoncharov** [comment]
Hi @cullsin,

The main idea of CodePush is OTA updating. You don't have to generate new `apk` with each new code changes. You should just call `codePush.sync` method for checking new updates and installing it on your device.
Please check this example app: https://github.com/microsoft/react-native-code-push/tree/master/Examples/CodePushDemoApp

Please let me know it was helpful or you have any questions.

**Comment by alexandergoncharov** [comment]
So, you should release an update to appcenter with `appcenter codepush release` command. For more info:  https://docs.microsoft.com/en-us/appcenter/distribution/codepush/#3-release-an-app-update
After that, your update will be available to be downloaded and installed on your device.

Then you should setup deployment key for your app the same as your deployment which used for release update and start the app. Somewhere in the app logic `codepush.sync` method should be called  and this method does 3 things: 1) check for updates on server by provided deployment key. 2) download update if it exists. 3) Install it on your device.

It doesn't matter for CodePush if your app from App Store or not. You can provide you binary version file to your users whatever you want. You don't have to think about it for working with CodePush.

Please let me know if it was helpful or you have any questions.

**Comment by alexandergoncharov** [comment]
Hi @cullsin ,

I'm going to close this issue for now as I haven't heard from you in a while, unfortunately.
Please feel free to reopen it if you have any questions.

Thanks,
Alexander
