### ISSUE TITLE
cli is waiting forever

### ISSUE THREAD

**Issue by brave-merida** [microsoft/code-push#636]
![image](https://user-images.githubusercontent.com/30062357/59970950-0d7dc700-95a5-11e9-84d1-dba13b42c8a5.png)

- version
code-push-cli: 2.1.9
react-native-code-push: 5.6.0
react-native: 0.59.8
@react-native-community/cli: 1.9.10

- description
I have run these command
```code-push release-react appName android```
```code-push release-react appName ios```
But it's waiting forever after output `info Done copying assets`

How can I debug?  Please help me!

**Comment by brave-merida** [comment]
Hi there!

**Comment by alexandergoncharov** [comment]
Hi @brave-merida,
Thanks for reporting!

Our recommendation is using `appcenter` cli instead of `code-push` cli as it has last features and fixings. Here are repo and documentation https://github.com/Microsoft/appcenter-cli.

Please feel free to ask any questions.

**Comment by brave-merida** [comment]
Hi @alexandergoncharov, Thanks.
I did it, but still waiting without any debug logs.
Please see below screenshot:
![image](https://user-images.githubusercontent.com/30062357/60102246-df100f80-978f-11e9-8b6c-48265e1aee32.png)

**Comment by brave-merida** [comment]
```
$ appcenter codepush release-react -a natashache/Soundwise-iOS
Detecting ios app version:

Using the target binary version value "2.0.4" from "ios/soundwise_v2/Info.plist".

Running "react-native bundle" command:

node node_modules/react-native/local-cli/cli.js bundle --assets-dest /var/folders/65/940_4bss3fz_y90jghq6k2bw0000gn/T/code-push119525-5196-rqhndx.0vtvc/CodePush --bundle-output /var/folders/65/940_4bss3fz_y90jghq6k2bw0000gn/T/code-push119525-5196-rqhndx.0vtvc/CodePush/main.jsbundle --dev false --entry-file index.js --platform ios
Loading dependency graph, done.

info Writing bundle output to:, /var/folders/65/940_4bss3fz_y90jghq6k2bw0000gn/T/code-push119525-5196-rqhndx.0vtvc/CodePush/main.jsbundle
info Done writing bundle output
info Copying 127 asset files
info Done copying assets

```

**Comment by brave-merida** [comment]
Hi @alexandergoncharov

**Comment by alexandergoncharov** [comment]
Hi @brave-merida ,
Sorry for the delay. Right now we are working on new CodePush version and during this support will slow down. Sorry for this. Please check the start of `readme.md`:
```
UPDATE: Over the next few months, we will be working on a new version of CodePush that will address some of the most common performance issues our customers are facing. This updated version will allow a better experience, our team to better support CodePush moving forward and have a faster development cycle for new features. We are prioritizing this work because we believe this to be the most valuable thing we can do for our CodePush customers in the long run. Starting June 11th 2019, support will slow down, bug fixes will be limited to critical bugs, and new feature development will pause until we finish this core update.
```

About your issue: it is strange. Is it possible to provide some dummy project with reproducing issue and reprosteps? I would like to debug it.

**Comment by tlays11** [comment]
@brave-merida did you find a solution? I ran into the same issue...

**Comment by brave-merida** [comment]
no, didn't find yet.
for now, deploy with entire app

**Comment by tlays11** [comment]
Some more info:
It's just this command that hangs and I am not sure why.
```
react-native bundle --platform ios \
--entry-file index.ios.js \
--bundle-output ./CodePush/main.jsbundle \
--assets-dest ./CodePush \
--dev false
```

**Comment by tlays11** [comment]
Not sure if this will be helpful to you, but I fixed my issue.

I had react-native-clean-project as an npm dependency that I removed. When I removed, it worked as expected. At least gives you a hint that it has to do with npm modules. I am unsure what the issue was because of the lack of output and logging.

Hope that helps!

**Comment by brave-merida** [comment]
@tlays11 , Thanks.
`Removing react-native-clean-project` is the solution.
