### ISSUE TITLE
Codepush not working from my Google Play App store version

### ISSUE THREAD

**Issue by ElixirMike** [microsoft/code-push#638]
I have successfully setup Codepush and have it working from my local react-native apps via the simulators, etc. I have tried it from my staging/production builds...and everything works.

I then put a release version (react-native run-android --variant=release) on my simulator and tested and again, it worked .

I have then published my "production" code to Google App store. Now, the version I download run from the Appstore does NOT work...it doesn't see any of the updates.

What am I missing? Is there some kind of key or other mechanism that needs to be enabled in order to work from the Google play version?

**Comment by ElixirMike** [comment]
Just another data point here. It now appears that if I sign-out / sign-back into the application, the update gets correctly applied. However, in my app, I have a button that says "Check for updates"
It runs this code:

    checkforUpdates = () => {
      codePush.sync({
        updateDialog: true,
        installMode: codePush.InstallMode.IMMEDIATE
      })
    }

On my local Simulator, this works...the dialog box appears and says there is a new update, do I want to install or cancel. But, my version from Google Play store does nothing.  Any ideas on how I could fix this?

**Comment by alexandergoncharov** [comment]
Hi @ElixirMike,
Thanks for reporting!

There isn't any additional setting for working with Google play store. Possible you published some other version of your app. Could you please double-check it and let me know your results?

**Comment by ElixirMike** [comment]
Like I said in my second post, it appears to be working when I restart the app or log out/back in.
I have the codesync in two places. One on the main component it runs on componentDidMount. I also have a menu item that says ""Check for updates".

The menu item that calls this code for "check for updates" works on my local release version. But it does not work on my Google Play Store version. 

checkforUpdates = () => {
  codePush.sync({
    updateDialog: true,
    installMode: codePush.InstallMode.IMMEDIATE
  })
}

I know I have the  correct production key however, because if I start/stop the app, the code does get updated via the ComponentDidMount action. 

Maybe there is a permission thing with showing that Dialog box in a prod environment?

**Comment by faisal3413** [comment]
Hi @alexandergoncharov 

I'm also facing the same issue. My iOS test flight build and android debug/release build is updating fine. It stopped updating only after publishing the android app to play store. Please have a look into this and guid me.

**Comment by gaurav-chandra** [comment]
I was also stumped with the same issue in my ionic cordova app. If I run the app outside of the playstore, it works fine but the builds which are uploaded to google play store are not executing this code. I have added the key in config.xml:
```
<platform name="android">
        <preference name="CodePushDeploymentKey" value="********EBrrkzQHGoxH" />
```
and the code is supposed to be executed every time the app starts:
```
setTimeout(()=>{
					if(DiService.checkInternet()) {
						let updateDialogOptions = {
							updateTitle: "An update is available",
							optionalUpdateMessage: "An update is available. The app will auto-restart once done. App will be updated in the background.",
							appendReleaseDescription:true,
							descriptionPrefix:"v "+APP_VERSION+" Changes: ",
							mandatoryUpdateMessage : "A mandatory update is available. The app will auto-restart once done. App will be updated in the background.",
							mandatoryContinueButtonLabel:"Install Now"
						};
						codePush.sync(null, {updateDialog: updateDialogOptions, installMode: InstallMode.IMMEDIATE});
					}
				},3000);
```
This does not execute from the installs from app store.

**Comment by gaurav-chandra** [comment]
Any update on this?

**Comment by gaurav-chandra** [comment]
I was able to capture the code-push error on app from google play store:
```
[CodePush] Could not get binary hash.Error: Could not get binary hash. 
```
perhaps this would help.

**Comment by gaurav-chandra** [comment]
There is some binary hash error so install this plugin:
[https://github.com/jp-uq/cordova-plugin-asset-manifest](https://github.com/jp-uq/cordova-plugin-asset-manifest). After this it solved the problem.

**Comment by itenl** [comment]
@ElixirMike  Hello, our company is going to put a RN project with code-push on google play, worrying that the review will not pass. Do you have this situation, use code-push to update the pop-up window to prompt the user? pls reply , guy  :)

**Comment by faisal3413** [comment]
Hi @alexandergoncharov , do you have any update on this issue ? please respond.

**Comment by alexandergoncharov** [comment]
Hi all,
I'm sorry for that big delay.

Could please someone provide a demo app with reproducing issue and reprosteps? I would like to reproduce and investigate it. It will really helpful in an investigation.

**Comment by gaurav-chandra** [comment]
@alexandergoncharov this is not happening anymore with the latest version of the plugin. The bug was filed last year and after that you guys have updated the plugin. This was happening with ```"code-push": "^2.0.6"``` at my end but using ```"code-push": "^3.0.1"```does not produce this bug.

**Comment by Krasavinigor** [comment]
Hi there!
@ElixirMike, @faisal3413 
Do you have any issues now?

**Comment by Krasavinigor** [comment]
Hi @ElixirMike, @faisal3413,

I'm going to close this issue for now as I haven't heard from you in a while, unfortunately.
Please feel free to reopen it if you have any questions.
