### ISSUE TITLE
Specify known errors for ease of error-handling by clients

### ISSUE THREAD

**Issue by ermik** [microsoft/code-push#641]
Know error-cases should be named subclasses of Error or somehow specified otherwise to allow precise logic at the client call-site (e.g. CodePush via cordova sdk).

Example of error that can't be identified upstream:
https://github.com/microsoft/code-push/blob/b5bf80147b46fb963e245e5ca30ed152fad4c03c/sdk/script/acquisition-sdk.ts#L107-L112
I had worked around that in by looking for a substring on `error.message` to respond to this error with a custom behavior. Not ideal, to say the least.

**Comment by alexandergoncharov** [comment]
Hi @ermik ,
Thanks for reporting!

It is a good suggestion! I will discuss it with my team.
I'll keep you updated.

**Comment by Krasavinigor** [comment]
Hi @ermik,
I opened PR for this issue.
Could you please check this: https://github.com/microsoft/code-push/pull/713

**Comment by Krasavinigor** [comment]
We've merged this PR https://github.com/microsoft/code-push/pull/713. 
Closing this issue.
