### ISSUE TITLE
CodePush updateCheck return HTTP ERROR CODE 503

### ISSUE THREAD

**Issue by rvssvl** [microsoft/code-push#659]
I got 2 mobile apps using codepush. Both android and ios are not updating on the fly, as request for version sync ('https://codepush.azurewebsites.net/updateCheck?...params') return status code 503 with message in body "HTTP Error 503. The service is unavailable".
Is it codepush's servers problem? How much time usually it takes, to such problem been resolved?

**Comment by JakeRawr** [comment]
https://github.com/microsoft/react-native-code-push/issues/1664

Same issue with React Native Code Push

**Comment by koyin** [comment]
Looks like Microsoft's issue
https://status.appcenter.ms/

**Comment by cjonsmith** [comment]
Hey all, I addressed this issue in [a comment](https://github.com/microsoft/appcenter/issues/814#issuecomment-526411546) on a similar issue on the main App Center issue tracker that goes over some of our findings around the issue. Feel free to continue the discussion if you have any further questions or concerns about the outage. Thank you for your patience while we addressed this issue!

**Comment by foolishsailor** [comment]
Im running into this same issue now and see that MS shows all systems are working : https://status.appcenter.ms/

Anyone with any updates on this issue?  Never been a problem before...

**Comment by Grohden** [comment]
@foolishsailor having the same issue too
