### ISSUE TITLE
How do i check my current environment?

### ISSUE THREAD

**Issue by sarmad1995** [microsoft/code-push#660]
Hi.
Is there any way from which I can check my current environment (Staging or production).
Inside js.
lets say
Codepush.env

I want to store different env variables for different environments

**Comment by prakharb** [comment]
You can use :
codePush.getUpdateMetadata().then(metadata => {
      console.log('meta data', metadata);
    });

**Comment by sarmad1995** [comment]
it returns undefined ?

**Comment by Rinkuk1993** [comment]
I am not sure I understood your question correctly but here is the answer based on my understanding.

As far as best practices I know, I believe you should maintain different code-push key for Staging and Production. So if you want to modify the code and do code push, you can do individually for Staging and Production. You can check the links below for build env -

https://medium.com/@skiptomyhue/setting-up-environment-variables-for-react-native-builds-b66a2576a218
https://dev.to/calintamas/how-to-manage-staging-and-production-environments-in-a-react-native-app-4naa

**Comment by alexandergoncharov** [comment]
Hi @sarmad1995 ,
Thanks for reporting!

Yeah, @Rinkuk1993 and @prakharb are right. Thanks! 
Also. you can use the multi-deploying testing feature.
Android: https://github.com/microsoft/react-native-code-push/blob/master/docs/multi-deployment-testing-android.md
Ios: https://github.com/microsoft/react-native-code-push/blob/master/docs/multi-deployment-testing-ios.md

I hope it was helpful.
I'm going to close this issue for now. Please feel free to reopen it if you have any questions.
