### ISSUE TITLE
Apple update their terms regarding OTA updates

### ISSUE THREAD

**Issue by alexcroox** [microsoft/code-push#661]
What are the teams thoughts on this and how it impacts code push?

https://developer.apple.com/news/?id=09062019b

@botatoes

**Comment by alexcroox** [comment]
I may be misinterpreting this, the language isn’t that clear.

**Comment by botatoes** [comment]
Thanks for bringing this to our attention. I'm going to look a bit into this and get some opinions from the team and see if it impacts CodePush.

**Comment by iageoghe** [comment]
Hi @alexcroox, we can't opine on the terms of service or guidelines set by other companies. If you have any legal questions around your app's particular usage of CodePush, we recommend that you find qualified legal counsel. You may also consider contacting Developer Support at Apple.
