### ISSUE TITLE
How long is ”the next few months”?

### ISSUE THREAD

**Issue by davidpaulsson** [microsoft/code-push#662]
I'm just wondering how long ”the next few months” is? You mention this right at the top of the repo readme. 

> UPDATE: Over the next few months, we will be working on a new version of CodePush that will address some of the most common performance issues our customers are facing. This updated version will allow a better experience, our team to better support CodePush moving forward and have a faster development cycle for new features. We are prioritizing this work because we believe this to be the most valuable thing we can do for our CodePush customers in the long run. Starting June 11th 2019, support will slow down, bug fixes will be limited to critical bugs, and new feature development will pause until we finish this core update.

This was added three months ago. I want to add code push to my app, but it feels silly with this paragraph at the top. 

Thank you for all your hard work!

**Comment by ludufre** [comment]
+ 1

**Comment by botatoes** [comment]
The new SDK (already out) should resolve most of the performance issues people have been facing. We're wrapping up the last bit of the API proxies. The API proxies are so we don't break existing users. 

The only work we have left after is to spin up the diffing service in a more manageable place for the team and deprecating the legacy service. 

I'm currently working on prioritizing upcoming work for the team and looking through the issues in all the different CodePush repos as well as app center repos and intercom requests over the past year.

**Comment by ludufre** [comment]
Thanks for the update

**Comment by davidpaulsson** [comment]
Thanks @botatoes! Looking forward to a PR removing the paragraph from the README and explaining any new setup changes soon.

**Comment by joshuakelly** [comment]
@botatoes Does the latest version available on npm support RN v0.61+? Thanks for the efforts

**Comment by gaurav-chandra** [comment]
hey any update on this? With the latest firebase changes and google changes, the current plugin leads to build errors. Had to remove this from the project so that other plugins work.

**Comment by pfleidi** [comment]
Our migration project was finished a few weeks ago and we are actively working on fixing SDK issues right now. I'm closing this issue for now.
