### ISSUE TITLE
Request: changelog for version history

### ISSUE THREAD

**Issue by l3ender** [microsoft/code-push#664]
Hello, could you please maintain a changelog or release notes for the repo? This would help give me some context when updating to a new version of the dependency, especially a new major version like [v3.0.1](https://github.com/microsoft/code-push/releases/tag/v3.0.1).

Thank you!

**Comment by mattslight** [comment]
@l3ender did you find any information on updating from cli 1.1.x to 2.x ? I am using codepush for react-native, but can't find any changelog on info about upgrading cli from 1.1.x to 2.x

Thanks

**Comment by l3ender** [comment]
@mattslight Nope, no news or detail on version history. :(

**Comment by alexandergoncharov** [comment]
Hi @l3ender and @mattslight ,
Thanks for reporting!

If you are interested in code-push CLI updates: It has been depricated and removed from repo(but ut is still available here: https://github.com/microsoft/code-push/tree/v3.0.1/cli). Our recommendation is using appcenter-cli: https://github.com/microsoft/appcenter-cli
Changes regarding to CodePush SDK: No any big changes. Just changed the service URL to target new service for the acquisition part. The management part also will be changed in the future.
I hope it was helpful to you.

I'm going to close this issue for now. Please feel free to reopen it if you have any questions.

**Comment by mattslight** [comment]
Thanks @alexandergoncharov it seems react-native-code-push is still using the code-push CLI rather than appcenter-cli. Anyway, thank you I will look into it.
