### ISSUE TITLE
Android: Codepush pending in State [CodePush] Downloading update 

### ISSUE THREAD

**Issue by digital-tcbs** [microsoft/code-push#669]
Hi, i have issue on android when user download update. Codepush pending very long time before start download update. This pending in state: [CodePush] Downloading update. It take 5 min to start download.
In IOS it very fast, take 30s to start.
I using cordova-code-push.
Pls help. Thank

**Comment by alexandergoncharov** [comment]
Hi @digital-tcbs ,
Thanks for reporting!

Looks like it depends on updating the CodePush server side. We are sorry for that. All should work correctly now.

I'm going to close this issue for now. Please feel free to reopen it if you have any questions or you faced this issue again.
