### ISSUE TITLE
[help] is there any method to push a absolutely new apk download url to user?

### ISSUE THREAD

**Issue by iaminvictus1993** [microsoft/code-push#673]

**Comment by alexandergoncharov** [comment]
Hi @iaminvictus1993 ,
Thanks for reporting!

CodePush doesn't have a special feature for that. But you can make a new update with pop up that contains URL to your apk, for example.
I hope it was helpful to you.

I'm going to close this issue for now. Please feel free to reopen it if you have any questions.
