### ISSUE TITLE
getDeployment returns undefined

### ISSUE THREAD

**Issue by j3ski-passion** [microsoft/code-push#674]
Hello, I'm facing issues with the code-push API. The problem first occurred Nov 3. Tested with version 2.0.6 and 3.0.1, both are affected.

Code to reproduce:
```js
codePush
      .addApp(appName, platform, 'React-Native')
      .then(() => {
        return codePush
          .getDeployment(appName, 'Production')
          .then(deployment => {
            resolve(deployment.key)
          })
      })
```

According to the docs, `getDeployment` should return the `Deployment` details, but it returns `undefined`.
`getDeployments` returns 2 deployments, one with the name `Production`, so it definitely exists.

**Comment by alexandergoncharov** [comment]
Hi @j3ski-passion ,
Thanks for reporting!

Yeah, it is a server-side issue. Sorry about that. 
I'll keep this issue open until we fix it. I'll keep you posted.

**Comment by alexandergoncharov** [comment]
HI @j3ski-passion,

Fix was implemented and deployed.

I'm going to close this issue for now. Please feel free to reopen it is you have any questions or face this issue again.
