### ISSUE TITLE
Unable to list deployments (Internal Server Error)

### ISSUE THREAD

**Issue by christophermark** [microsoft/code-push#675]
## Version
Code Push CLI version `2.1.9`

## What is affected
```
code-push deployment list [app]
```

We're seeing a very high error rate when trying to list our deployments from the Code Push CLI. We used to be able to retry a few times and get it to work, but now we only hit the message `[Error] Internal Server Error`. 

Additionally, the AppCenter CLI isn't allowing us to view our deployments. It used to be more reliable when we got errors on the Code Push CLI. 

![image](https://user-images.githubusercontent.com/6303781/68890032-186bfc00-06ec-11ea-9a15-2ba8be1850f4.png)

**Comment by quanzaiyu** [comment]
The same issue.

Maybe Microsoft's servers are being maintained.

![20191115131138](https://user-images.githubusercontent.com/13745132/68918531-7874a800-07a9-11ea-9e80-3088ba06c3b3.png)

![image](https://user-images.githubusercontent.com/13745132/68918538-84f90080-07a9-11ea-9bc6-e95e7482ff10.png)

![image](https://user-images.githubusercontent.com/13745132/68918543-8b877800-07a9-11ea-99f4-5d43fed062dc.png)

**Comment by christophermark** [comment]
This looks to be the same issue as https://github.com/microsoft/appcenter-cli/issues/699

All good now!

**Comment by christophermark** [comment]
Re-opening this issue, I'm getting these errors again

**Comment by matthiaswenz** [comment]
@christophermark Thanks for letting us know - we've taken a look at the service and saw a small spike earlier today. After scaling out some of the service can you take a look if this still reproduces? Does it reproduce all the time or only sporadically?

**Comment by christophermark** [comment]
@matthiaswenz Thanks for getting back so quickly!
I can still reproduce here, running:

```
code-push deployment list [app_name]
```

I'm getting the same `[Error] Internal Server Error`. This seems to reproduce all the time, each time I run that command. Last night I had hit the same error as well.

**Comment by pfleidi** [comment]
@christophermark Hmm. That's interesting. I can't seem to reproduce it on my side at the moment. Have you tried the [App Center CLI}(https://github.com/Microsoft/appcenter-cli) can you check whether you get the same issue with the new CLI?

(I'm just wondering whether this is an issue that is specific to your account or whether it is related to our legacy code-push APIs that the old CLI uses.)

**Comment by christophermark** [comment]
Hey @pfleidi, I only hit this issue with the Code Push CLI but not with the App Center CLI.

I've been using the Code Push CLI for checking deployments as it has a better UI, alphabetizing the deployments instead of listing all versions in random order.

**Comment by christophermark** [comment]
@pfleidi things seem back to normal this morning, with no errors! I guess I'll close out this issue. Was anything changed server-side to fix this?

**Comment by hffariel** [comment]
Getting `[Error] Internal Server Error` again with `code-push deployment ls`
