### ISSUE TITLE
[Help needed] Can we load code-push before splash screen dismisses?

### ISSUE THREAD

**Issue by viktor1915** [microsoft/code-push#677]
Platform: React Native

Just curious to know if somehow we can code push before the user navigates to intro page in an app i.e. before splash screen fades.

Why ? we want to do A/B test on our intro page. Problem is if we do it via code push, the intro page would appear before the codepush operation takes place in the app. Is there any way we can smoothly load codepush operation on splash screen so that user would see A or B build on intro page itself instead of it loading again.

**Comment by alexandergoncharov** [comment]
Hi @viktor1915 ,
Thanks for reporting!

It depends on your app. CodePush sync update when you call `codePush.sync` function or with launch app. I think that you can try the next approach:
1. During wrapping component set `checkFrequency` as `Manual`.
Like 
```
let codePushOptions = { checkFrequency: CodePush.CheckFrequency.MANUAL };

App = CodePush(codePushOptions)(App);
```
2. Call `codePush.sync` method in the place where you would like.

It should work. I hope it was helpful.

I'm going to close this issue for now. Please feel free to reopen it if you have any questions.
