### ISSUE TITLE
[error] Deployment "Staging" does not exist.

### ISSUE THREAD

**Issue by rajatgalav** [microsoft/code-push#683]
`code-push release-react MyApp android`

this command is generating error
```
[Error]  Deployment "Staging" does not exist.
Use "code-push deployment list" to view any existing deployments and "code-push deployment add" to add deployment(s) to the app.
```

**Comment by pfleidi** [comment]
@rajatgalav Did you create the staging deployment using the CLI or on [App Center](https://appcenter.ms)?

You should see something like this: 
![image](https://user-images.githubusercontent.com/118549/73704155-f52b6a00-46a6-11ea-97af-70db505e8f45.png)

**Comment by alexandergoncharov** [comment]
Hi @rajatgalav ,

I'm going to close this issue for now. Please feel free to reopen it if you have any questions.
