### ISSUE TITLE
ios app crashes after an update have been installed

### ISSUE THREAD

**Issue by LKhromov** [microsoft/code-push#685]
Hello,

I have faced with a problem of installing an update that was delivered via codepush on ios platform (works fine on android). After and update is identified, downloaded and installed, app immediately crashes. Since then, app always instantly crashes when trying to open it again (i will attach the crash log from ios at a very bottom).
We are using codepush cli 2.1.9 . For example to release an update we do:
>code-push release com.marketech.app-ios dist\mobile\marketech\code-push-update\ios\www\ 1.0.2 -d Test

The folder structure of our payload that is sent to codepush is:
![Untitled](https://user-images.githubusercontent.com/8263161/71054573-6f526e80-218d-11ea-800f-f5c35fec53b3.png)
We use phonegap to generate the content of www folder.

We were using this approach about 12 month ago and it used to work fine. Looks like some things had changed since then, and we are unable to do it same way as we used to.
I would appreciate any assistance! Thanks!

**ios app crash log**
_{"app_name":"Focus","timestamp":"2019-12-18 11:25:05.65 +0800","app_version":"1.0.2","slice_uuid":"d5bb060e-f100-3622-9fd7-0c308548268e","adam_id":0,"build_version":"1.0.2","bundleID":"com.marketech.app","share_with_app_devs":false,"is_first_party":false,"bug_type":"109","os_version":"iPhone OS 11.4.1 (15G77)","incident_id":"DE8C1FFD-047F-4BD6-A979-6007B71CA281","name":"Focus"}
Incident Identifier: DE8C1FFD-047F-4BD6-A979-6007B71CA281
CrashReporter Key:   6d35be5f572d6578f2ca62ddc74745a6b36acbd7
Hardware Model:      iPhone7,2
Process:             Focus [16824]
Path:                /private/var/containers/Bundle/Application/156DCE0B-F176-43EB-A887-A520DF61D987/Focus.app/Focus
Identifier:          com.marketech.app
Version:             1.0.2 (1.0.2)
Code Type:           ARM-64 (Native)
Role:                Foreground
Parent Process:      launchd [1]
Coalition:           com.marketech.app [1217]

Date/Time:           2019-12-18 11:25:05.4676 +0800
Launch Time:         2019-12-18 11:24:22.4435 +0800
OS Version:          iPhone OS 11.4.1 (15G77)
Baseband Version:    6.80.00
Report Version:      104

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Triggered by Thread:  7

Application Specific Information:
abort() called

Filtered syslog:
None found

Last Exception Backtrace:
(0x184112d8c 0x1832cc5ec 0x1840ab750 0x183fdea18 0x183feac78 0x100cf21f8 0x100cf0d10 0x183a04aa0 0x183a04a60 0x183a0bb84 0x183a11cac 0x183a119fc 0x183d37fac 0x183d37b08)

Thread 7 name:  Dispatch queue: com.apple.root.default-qos
Thread 7 Crashed:
0   libsystem_kernel.dylib        	0x0000000183b992e0 0x183b77000 + 140000
1   libsystem_pthread.dylib       	0x0000000183d3a288 0x183d37000 + 12936
2   libsystem_c.dylib             	0x0000000183b07d0c 0x183aa5000 + 404748
3   libc++abi.dylib               	0x00000001832a32c8 0x1832a2000 + 4808
4   libc++abi.dylib               	0x00000001832a3470 0x1832a2000 + 5232
5   libobjc.A.dylib               	0x00000001832cc8d4 0x1832c4000 + 35028
6   libc++abi.dylib               	0x00000001832bd37c 0x1832a2000 + 111484
7   libc++abi.dylib               	0x00000001832bcccc 0x1832a2000 + 109772
8   libobjc.A.dylib               	0x00000001832cc720 0x1832c4000 + 34592
9   CoreFoundation                	0x00000001840ab750 0x183fcd000 + 911184
10  CoreFoundation                	0x0000000183fdea18 0x183fcd000 + 72216
11  CoreFoundation                	0x0000000183feac78 0x183fcd000 + 121976
12  Focus                         	0x0000000100cf21f8 0x100cc0000 + 205304
13  Focus                         	0x0000000100cf0d10 0x100cc0000 + 199952
14  libdispatch.dylib             	0x0000000183a04aa0 0x183a03000 + 6816
15  libdispatch.dylib             	0x0000000183a04a60 0x183a03000 + 6752
16  libdispatch.dylib             	0x0000000183a0bb84 0x183a03000 + 35716
17  libdispatch.dylib             	0x0000000183a11cac 0x183a03000 + 60588
18  libdispatch.dylib             	0x0000000183a119fc 0x183a03000 + 59900
19  libsystem_pthread.dylib       	0x0000000183d37fac 0x183d37000 + 4012
20  libsystem_pthread.dylib       	0x0000000183d37b08 0x183d37000 + 2824

Binary Images:
....
<b123e03cb4353068838f7ca31ebd6c0b> /usr/lib/libMobileGestaltExtensions.dylib
0x1ac806000 - 0x1ac821fff OnBoardingKit arm64  <8438c0292de837ea8a6b5fbd25b84cc2> /System/Library/PrivateFrameworks/OnBoardingKit.framework/OnBoardingKit
0x1ac90b000 - 0x1ac93bfff libclosured.dylib arm64  <e61ffac51cae3e1fb9eb6a6e2801777b> /usr/lib/closure/libclosured.dylib

**Comment by alexandergoncharov** [comment]
Hi @LKhromov ,
Thanks for reporting!

Looks like it is the same issue as https://github.com/microsoft/code-push/issues/681.
So, I'm going to close this issue as duplicate for now. Please feel free to reopen it if you have any questions.
