### ISSUE TITLE
[Question] One build - two codepush keys?

### ISSUE THREAD

**Issue by adamgajzlerowicz** [microsoft/code-push#692]
Is it possible to:

* make a build (staging codepush config)
* push code to testers staging with codepush
* push some more
* after tests, promote build to production
* make the same build use production codepush config

It would be so simple if it is possible to do it this way.

Otherwise (correct me if I am wrong) I need to have two separate branches with separate configs (ex flavours) and *build from them separately*. This setup then has to be doubled for ios and android.

Is this how this is supposed to work?

Thank you so much!

**Comment by alexandergoncharov** [comment]
Hi @adamgajzlerowicz ,
Thanks for reporting!

You can use multi-deployment testing feature. There are settings that provide different deployments key for different build type(debug, release, etc.)
For Android: https://github.com/microsoft/react-native-code-push/blob/master/docs/multi-deployment-testing-android.md
For Ios: https://github.com/microsoft/react-native-code-push/blob/master/docs/multi-deployment-testing-ios.md

I hope it was helpful for you.
I'm going to close this issue for now. Please feel free to reopen it if you have any questions.
