### ISSUE TITLE
When rollout is less than 100, no devices receive update

### ISSUE THREAD

**Issue by seankwalker** [microsoft/code-push#693]
CLI version: 2.1.2

Hello, I've been experiencing an issue for a while where a release's rollout must be 100 or no devices at all get the update. 

I've been making new releases to roll out to 10% of devices with
```
appcenter codepush promote --app <app name> --mandatory -s <source deployment> -d <destination deployment> -t <binary version> --rollout 10
```

and the AppCenter webapp GUI does reflect that rollout is set to 10%. However, no devices receive the update no matter how long I wait. Even if I manually increase the rollout to any number below 100, no devices get the update. Only making it a full rollout will result in any devices installing the update.

**Comment by pfleidi** [comment]
@seankwalker Just to keep you in the loop: We're currently actively working on a fix for this. We'll let you know when it's deployed and ready.

**Comment by seankwalker** [comment]
Thanks so much for the update @pfleidi

**Comment by alexandergoncharov** [comment]
Hi @seankwalker,

We just deployed fix for this issue. Could you please test it and let us know if issue is still here?

**Comment by seankwalker** [comment]
Hey @alexandergoncharov just confirmed the issue has been fixed! 🎉 thanks so much :)

**Comment by pfleidi** [comment]
@seankwalker Thank you for reporting this. I'm closing this issue for now.
