### ISSUE TITLE
Missing documentation on how to access app_secret

### ISSUE THREAD

**Issue by cawfree** [microsoft/code-push#694]
### Version Info

```json
  "dependencies": {
    "code-push": "3.1.0"
  }
```

I'm currently using Code Push in a deployment pipeline, where new application instances are created dynamically. This requires the CLI to access the generated `app_secret` after a call to `addApp`, but that doesn't seem to be possible, nor mentioned in the documentation.

**Comment by alexandergoncharov** [comment]
Hi @cawfree ,
Thanks for reporting!

`code-push` cli is deprecated. Our recommendation is using appcenter cli: https://github.com/microsoft/appcenter-cli
Also, `appcenter` cli provide your `app_secret` after creating an app.

I'm going to close this issue for now. Please feel free to reopen it if you have any questions.

**Comment by cawfree** [comment]
Ah, perfect! Thank you very much for letting me know.
