### ISSUE TITLE
Receiving 503 random error

### ISSUE THREAD

**Issue by Grohden** [microsoft/code-push#696]
Not sure if the referenced issue is tracked or something, but just in case I'm gona open a new one since the last one is closed.

-- My comment on the issue
This service is really random, look at this:
![image](https://user-images.githubusercontent.com/7496871/72469483-4211d400-37be-11ea-8ff6-dd416a633499.png)

It's totally random... at least on a `curl` call.
But look at this:
![image](https://user-images.githubusercontent.com/7496871/72469670-a765c500-37be-11ea-841e-51bc0daf5ec0.png)

On the browser it's almost deterministic, on firefox it doesn't work at all (sometimes not even a response is obtained), and using chrome on the same machine, it works.
I would believe in a rate limit if it wasn't for the browser part.

The URL used is this one:
https://codepush.azurewebsites.net/updateCheck?deploymentKey=[PROBABLY_SECRET]&appVersion=1.8&packageHash=[PROBABLY_SECRET]&isCompanion=&label=&clientUniqueId=[PROBABLY_SECRET]

And I got it from a sentry error report due our outdated app version usage..

Could this issue please be reopened? @alexandergoncharov

_Originally posted by @Grohden in https://github.com/microsoft/code-push/issues/547#issuecomment-574849153_

**Comment by pfleidi** [comment]
Hi there,

We'll look into this issue and see what we can do do mitigate.

In the meantime: Which SDK version are you using? While this endpoint is still supported at the moment, it has been replaced with a new one that's used by newer versions of our SDK. If you'd be willing to upgrade, this could mitigate your issue and future-proof your project in the long run.

**Comment by Grohden** [comment]
@pfleidi I'm using react native, I'm not sure which version of the SDK I'm using..

Gradle says:
```
appcenter-react-native:2.6.1
appcenter:2.5.1
appcenter-push:2.5.1

```

Our package.json:
```
"react-native-code-push": "5.6.1"
"appcenter": "2.6.1",
```

>If you'd be willing to upgrade, this could mitigate your issue and future-proof your project in the long run.

Oh ok, we didn't updated because we still have some problems with apple builds everytime we touch/add native codes. But I'll try to update the package soon then..

**Comment by Dan-Williams93** [comment]
@pfleidi I have also been having this issue today using the **Cordova plugin v1.11.18**. A number of clients received the update with no issue however a number returned 503 from the **checkForUpdate** call.

**Comment by pfleidi** [comment]
@Dan-Williams93, @Grohden is this a fairly recent problem or have you been seeing these issues for a while now?

**Comment by pfleidi** [comment]
@Grohden The dependencies in your Gradle file look like the regular App Center SDKs you've included in your app. `react-native-code-push` is the package that you are looking for. The current version is [6.0.0](https://www.npmjs.com/package/react-native-code-push/v/6.0.0).

**Comment by Dan-Williams93** [comment]
@pfleidi this seems to be a fairly recent issue for us, however we have only just started releasing updates via code push, so others may have seen this longer than us. There are some other threads open that seem to suggest it could be a longer term issue.

**Comment by pfleidi** [comment]
I was able to reproduce the issue on our side. I've scaled a few things and this seems to have resolved this issue on my side. Can you confirm that?

From what I can get out of our metrics, I can't see any recent legacy spikes, either.

**Comment by Dan-Williams93** [comment]
@pfleidi I will run some tests in the morning and report back, thanks for your help so far! :)

**Comment by Grohden** [comment]
@pfleidi our first log about the 503 error is was on January 8

**Comment by Dan-Williams93** [comment]
@pfleidi All looks good from our end, all remaining clients have now received the update.

**Comment by Grohden** [comment]
For us too, everything seems fine now, I'm gona close this issue. Thanks for the help @pfleidi

**Comment by pfleidi** [comment]
Awesome. Thanks for reporting it!
