### ISSUE TITLE
New Website Logo: Sonar TIM

### ISSUE THREAD

**Issue by ludufre** [microsoft/code-push#697]
- Name: Sonar TIM
- Homepage (or app store) url: https://apps.apple.com/us/app/sonar-tim/id1465699298
- Brand Guidelines/Licensing: Free
- Logo: https://is5-ssl.mzstatic.com/image/thumb/Purple113/v4/39/89/ac/3989accf-3f4d-b014-1972-d80648f27da9/AppIcon-0-0-1x_U007emarketing-0-0-0-10-0-0-sRGB-0-0-0-GLES2_U002c0-512MB-85-220-0-0.png/492x0w.png

**Comment by alexandergoncharov** [comment]
Hi @ludufre ,
Thanks for reporting!

Your logo has been added. Thanks for using CodePush!
