### ISSUE TITLE
Connect to the server failed from China

### ISSUE THREAD

**Issue by bsw85** [Microsoft/code-push#70]
Hi,
I'm using code-push in our new product. Unfortunately we found that the connection to the server is failed  from China because of the server is deployed in USA, so how to solve this problem? Will Microsoft deploy the service in China later?

**Comment by silhouettes** [comment]
Hi, yes we are currently looking at geographically distributing our servers, especially as we have several users from outside the US and from the Asia-Pacific region in general. May I ask for more details on your connection failure? Was there an error message? We expect higher latency, but not a complete failure.

**Comment by bsw85** [comment]
The error message is "[Error]  connect ETIMEDOUT 23.101.203.117:443" when I using code-push deployment command. And connecting to the server using api "https://codepush.azurewebsites.net/updateCheck" is success today, so I can not list more failure info.

**Comment by ryanlin1986** [comment]
+1, I'm Chinese developer as well, the connection speed is really kind of slow.

**Comment by bsw85** [comment]
So what can I do? Waiting for the servers deployed in Asia? Do you have other alternatives that are available?

**Comment by ryanlin1986** [comment]
@bsw85  I'm wndering if we can write our own service implementation and use the SDK client( replace the http url with our own)

**Comment by bsw85** [comment]
@ryanlin1986 That is what I want to do. BTW, I'm in Hangzhou too.

**Comment by silhouettes** [comment]
My recommendation is simply to keep using the service as it is now while we make improvements. For example, we have a release progress indicator coming soon, and we are actively working on performance improvements right now. Please keep in mind that the service is still in beta and we are using this time as an evaluation period to iron out any issues.

@bsw85: Did the ETIMEDOUT error happen consistently for you, or only the one time? You said you got it when running the 'deployment command' - do you mean 'code-push release' specifically, or is this a general issue with all of the CLI commands?

@bsw85 and @ryanlin1986:
Is the performance problem primarily with the CLI (e.g. running 'code-push deployment list'), compared to the client SDK (e.g. sync())? The CLI commands are much more server-intensive, performing several roundtrips, and are definitely an area we can optimize.

We imagine that the most important area of optimization is for the end users (i.e. in the client SDK). With that in mind, we're considering the possibility of rolling out a CDN that will cache the packages for your app. If we were to do this in the future, and fix only major performance problems in the CLI, would this be enough to solve your problem?

**Comment by bsw85** [comment]
@silhouettes The ETIMEOUT happens sometime, but a bit frequent. Comparing to the client SDK, connection failures with the CLI is not a big deal (because I can use VPN to deploy my new version), actually, sometimes the end users can't use our app because of failed to connect the servers using sync(). So for our chinese developers, I'm afraid that it's not a good solution if rolling out CDN and servers(check for update) outside China.

**Comment by magicismight** [comment]
Is it possible Microsoft will open source the back-end code?
So we can deploy our own server,It will totally resolve this problem.
Programmers in China have a lots of network issues..

**Comment by ryanlin1986** [comment]
+1

**Comment by lostintangent** [comment]
We do plan to eventually open source the back-end, but it's not an immediate priority for us right now unfortunately. We're a small team, and we're laser focused on the cloud-hosted scenario right now, since that is what the vast majority of our users are looking for. As @silhouettes said, once we exit the beta stage, the service will definitely have a presence in China to help alieve these issues. Thanks for the feedback and I apologize for the inconvenience.

That said, I would like to see us improve our reliability such that using the service from China should be possible, but slow. Any timeouts or unreliability in the usage of the service, is absolutely something we would like to address.

**Comment by bsw85** [comment]
@lostintangent Thanks for your reply. And what time were you planning release this project?

**Comment by magicismight** [comment]
Awesome!
looking forward to it.

**Comment by lostintangent** [comment]
@bsw85 Release date for which? Open sourcing the back-end or extending the cloud service into Chinese data centers? I don't have any specific dates in place for either one right now unfortunately, but we should be able to give an update on dates in the next month or so. Stay tuned and thanks for the patience!

**Comment by lostintangent** [comment]
I'm going to close this issue for now, since we know we need to optimize the service for non-US based users in general once we exit the beta stage. China will be a big priority for us, and we'll announce those improvements very soon. Thanks!

**Comment by andyhu** [comment]
+1 for an open sourced backend

**Comment by ryanlin1986** [comment]
@andyhu  We have already used cordova-hot-code-push plugin instead of this one, much better control over the server because it is just plain http/ftp.

**Comment by lostintangent** [comment]
@ryanlin1986 Thanks for the endorsement :)

**Comment by andyhu** [comment]
@ryanlin1986 Thanks for your info. How about react-native?
