### ISSUE TITLE
[Question] Can code-push be used with this case use?

### ISSUE THREAD

**Issue by W1nstar** [microsoft/code-push#701]
Hello,

I've been learning how codepush works, but I fear that my case scenario can't be covered by it, unless I hack the process in some way.

I have a scenario where I'll have multiple groups of users who need to be updated at different speeds. I need control over when and wich groups get the new version of my app.

For example, let's say I have users A, B and C. Each client will receive a signed apk file, directly handed to them.

After some time, Clients B and C are ready to get the updates I made to the app, but C is not, because of real life reasons. I have to update B and C, and when I get the order, I need to update client C.

Sometimes everyone will be ready and I'll have to send the update to everyone.

I was hoping code-push to have some sort of way for the app to listen to 2 "channels", but I can apply only one deployment key per app.

Also, theres no release-react command that sends the app to every deployment channel.

My best guess so far is to have a deployment key for every user, and hack the build process so the strings.xml is changed before the apk is built & signed so every user group is getting an app listing to their own deployment key. This seems a lot like a mess and error prone.

Any insight or help would be appreciated.

**Comment by alexandergoncharov** [comment]
Hi @W1nstar ,
Thanks for reporting!

Unfortunately it isn't possible to make update for one deployemnt and different groups. But you can do it with dirrefent deployments. Just provide different deployments key for different groups and make updates for each deployments. It should works for you.
I hope it was helpful for you.

I'm going to close this issue for now. Please feel free to reopen it if you have any questions.
