### ISSUE TITLE
Debug code push status on iOS production device

### ISSUE THREAD

**Issue by yaronlevi** [microsoft/code-push#710]
Hi (-:

For no apparent reason we suddenly can't get new JS updates to be installed on one of our production ios apps. We are stuck trying to figure out why the update is not being downloaded and applied. 

On an Android app, we can just run "react-native log-android", connect a device running the production app, and see all the debug info from Code Push (package being downloaded, already updated, etc...) 

The question is how can we do the same on the iOS app or alternatively, find some way to get those real-time logs about whats happening inside Code Push.

Any help on the issue would be much appreciated 🙏

**Comment by alexandergoncharov** [comment]
Hi @yaronlevi,
Thanks for reporting!

I'm not sure if it is possible to get logs from Production on IOS as IOS hides these logs for security reasons. You can reproduce your issue on debug mode or use some logs collection utils like [bugsnag](https://docs.bugsnag.com/platforms/ios/).

Please let me know if It was helpful or you have any questions.

**Comment by alexandergoncharov** [comment]
Hi @yaronlevi ,

I'm going to close this issue for now as I haven't heard from you in a while, unfortunately.
Please feel free to reopen it if you have any questions.

Thanks,
Alexander.
