### ISSUE TITLE
All return types are `any`

### ISSUE THREAD

**Issue by henrikra** [microsoft/code-push#712]
If you are using `code-push` with TypeScript (tested with version 3.7.5) then basically all of the return types of the code push functions are `any`.

Here is minimal code to prove my point:
```ts
import CodePush from 'code-push';
// apps type is any
const apps = new CodePush('myToken').getApps();
```

I did some digging and the reason might be that something called `rest-definitions` is not included in the module when installed with npm 🤔 Can someone else confirm they have the same problem?

**Comment by andreidubov** [comment]
Hi @henrikra 

We opened [PR](https://github.com/microsoft/code-push/pull/721) to fix this issue. You can test it

**Comment by andreidubov** [comment]
@henrikra 
We made a new release to fix this issue.

I'm going to close this issue for now. Please feel free to reopen it if you have any questions.

**Comment by henrikra** [comment]
Thx 👍

**Comment by tropii** [comment]
It seems the return types are still `any`:

![image](https://user-images.githubusercontent.com/3875435/85289846-b99c0b80-b4a0-11ea-972a-b8e6d99e2ffa.png)

Looks like the reason is `Q.Promise`:

![image](https://user-images.githubusercontent.com/3875435/85290084-15669480-b4a1-11ea-9604-ca40226343b1.png)

**Comment by andreidubov** [comment]
@tropii @henrikra 
Thank you for your participation.

We removed the **Q** promises and made a new release (v3.1.5). Could you test it and confirm that now all types are available?

**Comment by tropii** [comment]
The types seem to work properly now with version 3.1.5. Big thanks the fix!
