### ISSUE TITLE
--version parameter undocumented

### ISSUE THREAD

**Issue by WouterFlorijn** [microsoft/code-push#714]
The `--version` parameter in all of the release commands is undocumented. [See documentation](https://docs.microsoft.com/en-us/appcenter/distribution/codepush/cli). Could someone explain what it's used for, and add it to the documentation?

**Comment by alexandergoncharov** [comment]
Hi @WouterFlorijn ,
Thanks for reporting!

I'm not sure what kind of field you mean. Could you please provide some link to the code or where did you find it?

**Comment by WouterFlorijn** [comment]
@alexandergoncharov In the documentation page I linked, many parameters are explained in their own paragraph, but the `-v|--version` is not. I also couldn't find any reference to it on other documentation pages. So it's not clear what it does.
