### ISSUE TITLE
how to use range of targetbinaryversion ?

### ISSUE THREAD

**Issue by Masoooo** [microsoft/code-push#718]
if my app version is 5.1.10, and i release a package targeting "5.1.7 - 5.1.11",  the result is my app keep downloading this package and never installing it. i checked source code,  in there:
`            if (packageMetadata == null || !isPackageBundleLatest(packageMetadata) && hasBinaryVersionChanged(packageMetadata)) {
                CodePushUtils.log("Skipping initializeUpdateAfterRestart(), binary version is newer");
                return;
            }`
would skip installing package.
and this code:
`
    private boolean hasBinaryVersionChanged(JSONObject packageMetadata) {
        String packageAppVersion = packageMetadata.optString("appVersion", null);
        return !sAppVersion.equals(packageAppVersion);
    }`
just use 'equals' to compare version, '5.1.10' is not equals with '5.1.7 - 5.1.11' of course.

so, am i doing wrong to using range? so confused.

**Comment by alexandergoncharov** [comment]
Hi @Masoooo ,
Thanks for reporting!

App versions comparing are placed on the server side. I just tested your cases and I can successfully get update for your case and also tested with other versions that are not fit into your range and I successfully got nothing. So, I can say that comparing version logic working correctly.

Possibly it can be other reason for the issue. Could you please provide your logs during installing and demo app with reproducing issue and reprosteps? I would like to reproduce and investigate it.

**Comment by alexandergoncharov** [comment]
Hi @Masoooo ,

I'm going to close this issue for now as I haven't heard from you in a while, unfortunately.
Please feel free to reopen it if you have any questions.

Thanks,
Alexander.
