### ISSUE TITLE
Can we we resume download after failed?

### ISSUE THREAD

**Issue by hamam99** [microsoft/code-push#720]

**Comment by alexandergoncharov** [comment]
Hi @hamam99 ,
Thanks for reporting!

If I understand correctly you would like to download bundle even if it was rollbacked? If so, you can use `rollbackRetryOptions`. But it is available only for react-native SDK. Could you please check this docs: https://github.com/microsoft/react-native-code-push/blob/master/docs/api-js.md#codepushoptions

Please let me know if it was helpful or you have any questions?

**Comment by alexandergoncharov** [comment]
Hi @hamam99 ,

I'm going to close this issue for now as I haven't heard from you in a while, unfortunately.
Please feel free to reopen it if you have any questions.

Thanks,
Alexander.
