### ISSUE TITLE
Multi Deployment - Wrong Production bundle shipped to Staging apps

### ISSUE THREAD

**Issue by daveGregorian** [microsoft/code-push#726]
Hi,

currently our staging android apps (distributed via app-center) are always receiving the latest production release bundle instead of the staging release bundle.

Probably I have configured something wrongly, even though I followed the docs.
-> appcenter cli version 2.6.0

The command that I use to deploy a new bundle for our staging configuration:

`APP_ENVIRONMENT_BABEL=testing appcenter codepush release-react -a XXX/XXX -d Staging --extra-bundler-option="--reset-cache"`

And the buildTypes in our `app/build.gradle` look like this:

```
    buildTypes {
        debug {
            signingConfig signingConfigs.debug
            resValue "string", "CodePushDeploymentKey", '""'
        }
        releaseStaging {
            resValue "string", "CodePushDeploymentKey", '"XXX_STAGING_KEY_XXX"'
            signingConfig signingConfigs.release
            matchingFallbacks = ['release']
        }
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            signingConfig signingConfigs.release
            resValue "string", "CodePushDeploymentKey", '"XXX_RELEASE_KEY_XXX"'
        }
    }
```

In App-Center in the code-push tab I added 2 different configs:
1. `Release`
2. `Staging`

With iOS we have the same structure, but no problems with our staging / release builds.
I hope someone can give me some hints.

Thanks in advance :)

**Comment by alexandergoncharov** [comment]
Hi @daveGregorian ,
Thanks for reporting!

It is strange because your settings look right. Could you please provide some demo app with reproducing issue and reprosteps? I would like to reproduce and investigate it.

**Comment by alexandergoncharov** [comment]
Hi @daveGregorian ,

I'm going to close this issue for now as I haven't heard from you in a while, unfortunately.
Please feel free to reopen it if you have any questions.
