### ISSUE TITLE
Uncaught module code-push./utils/code-push-error not found

### ISSUE THREAD

**Issue by darron1217** [microsoft/code-push#729]
Related Issue : https://github.com/microsoft/cordova-plugin-code-push/issues/610

Platform : Ionic 5 with capacitor
cordova-plugin-code-push@1.12.5
code-push@3.1.5

Working version : code-push@3.1.2

I guess this commit below is related to this error
https://github.com/microsoft/code-push/commit/136946a4b497fa79a849e7d9112cc64199f3903b

**Comment by andreidubov** [comment]
Hi @darron1217 
Thanks for your find.
We fixed this issue in **v4.0.1**

Please let me know if you have any questions.
