### ISSUE TITLE
Is it possible to implement our own service instead of use Microsoft one?

### ISSUE THREAD

**Issue by ryanlin1986** [Microsoft/code-push#73]
Since there is currently no server at China, the connection is not reliable enough for Production use.
So I'm thinking about write our own service implementation instead of use Microsoft one.
Since the request sent from code-push client is just HTTPS request, I guess it will be not hard to do this, write our own service and replace the url https://codepush.azurewebsites.net/ to url of ours.
Is this scenario you are going to support or I will have to investigate the client sdk code to guess what I should write, or I should never do this at all? Please give me some hints, thanks.

**Comment by silhouettes** [comment]
Hi @ryanlin1986, while it is possible to reverse-engineer the client sdk to build your own server, we don't recommend it and we can not spend any resources to support this scenario at the moment. Backwards compatibility may be a problem with future CLI versions, and you will also be missing out on future improvements that we make both on the client and the server.

Please keep in mind that the CodePush service is still in beta, so it is not intended to be at production quality while we gather feedback and make improvements. Please keep in mind that we do intend to have a server in Asia before we exit beta.

**Comment by ryanlin1986** [comment]
Thanks, so I guess I will hold on to see what's going on into final version. This project is really great, will helps us tremendously.
