### ISSUE TITLE
addApp returns 400 bad request

### ISSUE THREAD

**Issue by h-des** [microsoft/code-push#742]
We cannot create new CodePush apps since September 12th

Here's our implementation
```
import CodePush from 'code-push'
... 
const codePush = new CodePush(process.env.CODE_PUSH_ACCESS_KEY)
...
await codePush.addApp('random-name', 'iOS', 'React-Native')
```
on v3.0.2 
`codepush.appcenter.ms/v0.1/legacy/apps/` returns `Internal sever error [500]`

on v.4.0.2
`api.appcenter.ms/v0.1/orgs/ORG_NAME/apps` returns `Bad request [400]`

We haven't changed anything in our codebase for a while and we've been able to create hundreds of CodepPush apps using the snippet above before.

**Comment by Definitely-Not-Vlad** [comment]
Experiencing the exact same thing.

It's a bit hit or miss, sometimes it goes through, sometimes it fails to, sometimes it goes through without a hitch.

Additionally, using both `code-push-cli` and `appcenter-cli` (latest at time of writing), I was able to successfully create new apps, but when run via `addApp` (latest at time of writing), it will fail to create the app.

I hate to tag people directly, but @andreidubov is there any chance this could be investigated? I'm certain this is blocking a lot of people.

**Comment by andreidubov** [comment]
Hi @Definitely-Not-Vlad  @h-des 
Thanks for your find.

I will definitely investigate this soon. We are currently working on the server-side, after that, I will definitely come back to this and will keep you updated.

**Comment by h-des** [comment]
After some more investigation we figured out it was the 2000 apps limit that was recently introduced. I think we can close this issue, but we would really appreciate better error messages.

**Comment by andreidubov** [comment]
Hi, @h-des I am glad that you managed to establish the reason for the issue.

Unfortunately, this error is not common and comes from the **api.appcenter.ms** side and we cannot influence the content of the error.

I will close this issue, Feel free to reopen if needed.
