### ISSUE TITLE
CodePush updateCheck return HTTP ERROR CODE 503

### ISSUE THREAD

**Issue by andrei-m-code** [microsoft/code-push#745]
CLI v - 2.1.9
react-native-code-push: 5.7.0

**Comment by tedkimzikto** [comment]
having same issue

**Comment by CvekCoding** [comment]
Same issue

**Comment by andreidubov** [comment]
Hi everyone, 
Thanks for the reporting.

We know about this issue and we are investigating it at this time, you can find more information https://github.com/microsoft/react-native-code-push/issues/1952. I think we can continue our conversation there. I will close this card as a duplicate.
