### ISSUE TITLE
Update not installed on Restarting an app.

### ISSUE THREAD

**Issue by jayaveluT2S** [microsoft/code-push#752]
I have mentioned installation mode as "ON_NEXT_RESTART" on code push sync options. It's working as expected on IOS and android when the user kills the app and relaunch. But same is not working when the user exit from the app by hitting back(Native back button) button on android. It would be great if someone helps me with this.

**Comment by pravinkumarputta** [comment]
@jayaveluT2S I'm also facing the same. I can see on my app center dashboard that the user has downloaded the update but not installed it. So it shows as rollback.
I'm seeing the same count for rollback as a download count. It means no single device has installed an update.

Please let me know if you found the solution for this?

Thanks in advance!!
