### ISSUE TITLE
Unable to find either of the following pbxproj files

### ISSUE THREAD

**Issue by fpgce** [microsoft/code-push#754]
I'm having trouble sending releases for ios projects do react-native.

I renamed folder "ios" from the project written in react-native to "ios-appname". With this change, codepush cannot identify a correct folder from my "info.plist".

Now when I try to send a project release with the command:
``
appcenter codepush release-react -a my-name / ios-appname -d Production --plist-file 'ios-appname / appname / Info.plist'
``

I get the following error:

``
"We could not find one of the following pbxproj files to infer the binary version of your application:" ios / appname.xcodeproj / project.pbxproj "," ios / project.pbxproj "
``

The name of the app in package.json is correct, it may be necessary to update the code-push so that I can explicitly pass the path to a folder.

appcenter version 2.7.3
code-push version 4.0.2

**Comment by phillipkey** [comment]
I'm facing a similar issue. Working with a react native app that was migrated from fully native and the folder structure does not fit the normal schema. At first, i was encountering the error: 

```
"Unable to find either of the following plist files in order to infer your app's binary version: "
```

I resolved this by passing in the path for the plist. It seems like we should be able to pass in this directory as a parameter as well.

**Comment by dariodumlijan** [comment]
To help anybody facing this error out, my problem was that in the `package.json` where apparently codepush looks to decide what the folders are called.

Previous `package.json `
```
{
  "name": "app_name"
  ...
}
```

The FIX
```
{
  "name": "appname"
  ...
}
```

and my `app.json` is
```
{
  "name": "AppName",
  "displayName": "App Name"
}
```
