### ISSUE TITLE
App Store rejection

### ISSUE THREAD

**Issue by andreieuganox** [microsoft/code-push#756]
Guys,

Anyone had experienced rejection on Apple App Store due using CodePush? I got App several times rejected for the same reason, went through Apple appeal and got a final statement from Review Board today requesting to remove CodePush.
Quoting Review Board:
“_The App Review Board evaluated your app and determined that the original rejection feedback is valid. Specifically, it would be appropriate to remove any and all remote code importing or hot updating functionality from this app before resubmitting for review, such as via this app’s CodePush dynamic updating._”

The App was on the Store for around a year and got rejected a few weeks ago on a simple update.

Has anyone had experience appealing such cases? Any solid argument I can use to get the app through with CodePush?

Thank you in advance!

**Comment by kbrownlees** [comment]
https://github.com/microsoft/react-native-code-push#store-guideline-compliance is probably relevant?

**Comment by andreieuganox** [comment]
@kbrownlees no, this is outdated as the wording changed on the Apple side.

**Comment by kbrownlees** [comment]
@andreieuganox 

This appears to be the new wording?

`3.3.2 Except as set forth in the next paragraph, an Application may not download or install executable code.  Interpreted code may be downloaded toan Application but only so long as such code: (a) does not change the primary purpose of the Application by providing features or functionality that are inconsistent with the intended and advertised purpose of the Application as submitted to the App Store, (b) does not create a store or storefront for other code or applications, and (c) does not bypass signing, sandbox, or other security features of the OS.`

Still seems pretty cut & dry to me, code push only modifies interpreted code?
