### ISSUE TITLE
What are the breaking changes?

### ISSUE THREAD

**Issue by makenova** [microsoft/code-push#763]
`"code-push-cli": "2.1.9"`

npm and dependabot both inform me that there are security vulnerabilities in the version of `code-push-cli` that I am using(`2.1.9`). `npm audit` wants me to upgrade to `3.0.0` since that is the latest version published to npm as of the time I am writing this.
In the [releases](https://github.com/microsoft/code-push/releases), I cannot find a tagged release for `3.0.0` and it actually looks like there have been several releases after `3.0.0` all the way up to `4.0.4`.
That is two major version bumps which I'm not sure what the breaking changes are or if there are any.

Can i upgrade from `2.1.9` to `3.0.0`?
Should I upgrade straight to `4.0.4` with the git sha?

I'd appreciate some clarity on the upgrade path.

Thank you for your work and time.

**Comment by doomkit** [comment]
@makenova code-push-cli is deprecated in favour of [appcenter-cli](https://docs.microsoft.com/en-us/appcenter/cli/)

**Comment by makenova** [comment]
@doomkit Is there a place where we can see a changelog?
The one that comes up in a web search has not been updated since 2019.
https://docs.microsoft.com/en-us/appcenter/general/changelog
