### ISSUE TITLE
🐛 Patch command is broken starting 3.x.x

### ISSUE THREAD

**Issue by A-Tokyo** [microsoft/code-push#767]
code-push-cli version: 3.0.0

`code-push patch` command doesn't work as documented -> Returns `Error not found`

Command:
`yarn code-push patch OrgName/AppName Production --disabled true` // This command marks all production codepushes as disabled

Output of 3.0.0:
`Error not found`

Output of 2.1.9:
`Successfully updated the "latest" release of "OrgName/AppName" app's "Production" deployment.
✨  Done in 3.43s.`

**Comment by aarontewor** [comment]
COD GAME INTERNET PROTOCOL

61056e64f70b0001481c8a896b0a0

Cod profile called Nejendary
Changing username soon to something shorter

Please help random crashes on game
  WiFi ip  192.168.0.24 sky thanks

**Comment by doomkit** [comment]
@A-Tokyo since v3.0.0 code-push-cli was migrated to appcenter-cli - [Migration notice](https://github.com/microsoft/code-push/blob/master/migration-notice.md) and no longer supported.
