### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by JamieSlome** [microsoft/code-push#775]
Hey there!

I'd like to report a security issue but cannot find contact instructions on your repository.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by markyrbc** [comment]
@JamieSlome Other Microsoft repos have a consistent [SECURITY.md](https://github.com/microsoft/vscode/blob/main/SECURITY.md) with instructions/contact info, though it _is_ missing in this one.

**Comment by alexnekrashevich** [comment]
@JamieSlome Now our repo contains SECURITY.md with all the information, feel free to use it in the future.

**Comment by JamieSlome** [comment]
@alexnekrashevich - great, thanks for the support!
