### ISSUE TITLE
gulp build failed

### ISSUE THREAD

**Issue by j78742** [microsoft/code-push#779]
When I tried to build this repo( version: 2.1.9)，I got info below:
![image](https://user-images.githubusercontent.com/16643891/139228169-c1013df1-8335-4368-b6c9-6aa4f3355672.png)

code-push version: 2.1.9
node: 8.17.0
gulp: 3.9.1

**Comment by doomkit** [comment]
Version 2.1.9 was released almost 3 years ago. Please, upgrade to a newer version.
