### ISSUE TITLE
Generate bundles with Management SDK?

### ISSUE THREAD

**Issue by sopranolinist** [microsoft/code-push#781]
Can the Management SDK be used to generate the actual app bundles, similar to what `react-native bundle` in the CodePush CLI does?

I currently have `code-push` v4.0.5 installed.

**Comment by doomkit** [comment]
@sopranolinist No. Management SDK provides some of App Center CLI functionality so you can use it programmatically in your code. You can check the list of available methods here: [https://github.com/microsoft/code-push#methods](https://github.com/microsoft/code-push#methods)
