### ISSUE TITLE
App Center Status: Over 4 days that "Distribute is Experiencing Issues"

### ISSUE THREAD

**Issue by shawarmaz** [microsoft/code-push#800]
It's been over 4 days that the status page has been showing "Distribute is Experience Issues"

All of my apps using codepush have become categorically unusable

If I release a new bundle and try and download it (4.5MB) over LTE, I get 10 max 15kbps download speeds. 

I have seen other threads suggesting this may be the start of Microsoft sunsetting CodePush.

Could we get some update on the current status of the service AND the project ?

**Comment by ferchorecalt** [comment]
Hi! We discovered the same issue!

Do you have any update of this?
