### ISSUE TITLE
CodePushHttpError pass response as error cause 

### ISSUE THREAD

**Issue by retyui** [microsoft/code-push#806]
Hi team! Could you please pass a network response as `Error.prototype.cause`, too simply logic with handling response statuses

Example: 
```tsx
const err = new CodePushHttpError(msg, {cause: response})

if(err.cause.status === 500){
  // my logic
}
```

meta: 
- `code-push@4.0.4`
- [`Error.prototype.cause`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/cause)

**Comment by davydspotnana** [comment]
no

**Comment by retyui** [comment]
.
