### ISSUE TITLE
[Documentation][React-native] FAQ still says that only iOS is supported

### ISSUE THREAD

**Issue by Bhullnatik** [Microsoft/code-push#81]
At the question http://microsoft.github.io/code-push/faq/index.html#5-which-react-native-platforms-are-supported, it says that the Android version is still under development, which I believe is not true anymore.

**Comment by lostintangent** [comment]
Ah good catch. We'll update that today. Thanks!

**Comment by lostintangent** [comment]
Updated! Thanks for reporting this :+1:
