### ISSUE TITLE
4.1.0 has no d.ts files

### ISSUE THREAD

**Issue by pjc0247** [microsoft/code-push#811]
https://www.npmjs.com/package/code-push?activeTab=explore

4.0.5 works fine.

**Comment by pjc0247** [comment]
a

**Comment by saurav0705** [comment]
any update on this?

**Comment by saurav0705** [comment]
Please find the pr for the above issue https://github.com/microsoft/code-push/pull/827

**Comment by regalstreak** [comment]
bumping ^ @DmitriyKirakosyan

**Comment by DmitriyKirakosyan** [comment]
@regalstreak , @saurav0705 , @pjc0247 ,

I tried to find the problem with d.ts files not being created using Node 12 and 16, but everything worked fine for me.

Can you tell me exactly what steps you took? This will help me understand the issue better.

Also, I looked at versions 4.0.5 and 4.1.0 and didn't see any big changes that could cause this problem. If you noticed something, please share.

**Comment by regalstreak** [comment]
@DmitriyKirakosyan try creating a new typescript project and adding the latest version of code-push, the package misses the declarations (checked in node_modules)

4.0.5 also didn't have the d.ts for me

**Comment by saurav0705** [comment]
@DmitriyKirakosyan the issue the release is pushed with the `npm run build` command due to which no `.d.ts` files are generated and package is published with that command

**Comment by velimir-jankovic** [comment]
@saurav0705 thank you for the help! We've fixed our internal release process, so next release will include definition files properly.

**Comment by victor-chan-groundswell** [comment]
I'm actually running into this right now, going from 4.0.5 to 4.2.0..... I double checked what's in the node_modules directory and the .d.ts files are definitely missing in the new version.
