### ISSUE TITLE
User Data Privacy Policy

### ISSUE THREAD

**Issue by NilsBaumgartner1994** [microsoft/code-push#834]
Which data is sent to the "Code-Push" Servers in order to use the service from my device? The privacy policy page does not mention that.

**Comment by velimir-jankovic** [comment]
The only data that is sent to the servers is your deployment key.

**Comment by NilsBaumgartner1994** [comment]
Well that's not right. They sent more data but it seems there are no tracking or analysis data.

**Comment by velimir-jankovic** [comment]
That's right, there's no personal data being sent.
