### ISSUE TITLE
Can we test a new React Native App which is not uploaded or published on Playstore?

### ISSUE THREAD

**Issue by Prashant-epam** [microsoft/code-push#835]
I have started a React Native Kickstarter app which is not uploaded or published on Playstore yet. I have done the setup required for Code-push. 

**After running below command from terminal:**
`appcenter codepush release-react -a <owner/appName> -d Staging`

> I get success response and I can also find new version listed on App Center portal.

**But when I run the app on simulator, I always get response as:**
[CodePush] Checking for update.
[CodePush] App is up to date.

**Questions:**

1. Can I test codePush on react native app which is not yet published or even uploaded on playstore.
2. Can I test Codepush on android simulator, if yes what are the steps to do so?

**Comment by DmitriyKirakosyan** [comment]
Hi @Prashant-epam , thank you for reaching out.
The app is not required to be uploaded to store for the code-push to work. Also, it should work on simulator.

Have you configured all steps from our [doc](https://learn.microsoft.com/en-us/appcenter/distribution/codepush/rn-get-started)?
If you believe you've set it up correctly but are still encountering issues, we would appreciate it if you could provide a demo app for us to investigate your specific scenario.
