### ISSUE TITLE
React Native app: update native code

### ISSUE THREAD

**Issue by alex-devico** [microsoft/code-push#840]
I create react native application and use Code Push for quite update my application.

"react-native-code-push": "^8.0.0",
"appcenter": "^5.0.0",

I cover root component by CodePush and push my code to appcenter.
`CodePush(codePushOptions)(App)`
Add all changes to android folder.

The main question: 
I have old apk user install app.
After that I made some changes in native code (folder android) f.e. add print pdf library. 
And push it to github 
Than pipeline `appcenter codepush release-react -a ...` push my code to app center 
And when user open the app changes to native code do not applied (changes for js is applied)
Only when user reinstall app with new apk file this changes was applied.

So do we have ability to quite update also native code with codepush ??

**Comment by MikhailSuendukov** [comment]
Hello and thanks for reaching out to us!
Unfortunately, CodePush does not support distributing the native component of React Native applications.
