### ISSUE TITLE
Newlines in a release description aren't handled correctly

### ISSUE THREAD

**Issue by lostintangent** [Microsoft/code-push#87]
If you add an "\n" to the description of a release, the slash will be escaped, and therefore, turned into "\\\n". When the description property is then displayed within the app or deployment history, the literal value "\n" is displayed as opposed to an actual newline.

![Update prompt](https://cdn.discordapp.com/attachments/107883037156466688/130382682126417921/Screenshot_20151227-001632.png)

**Comment by geof90** [comment]
Is there any other place that we want strings like "\n" "\r" to be parsed? e.g. app names?
