### ISSUE TITLE
try-json dependency

### ISSUE THREAD

**Issue by cmcewen** [Microsoft/code-push#96]
Just a small note, got this warning when installing the cli
 
`npm WARN engine try-json@1.0.0: wanted: {"node":"0.x"} (current: {"node":"5.3.0","npm":"3.3.12"})`

Seems like a pretty simple helper function just to include https://github.com/sorensen/try-json.js/blob/master/index.js

**Comment by lostintangent** [comment]
Yeah, I'm all for not duplicating work, but I agree, there's not a ton of value in us using this library :) I'll remove it and clean up this warning tomorrow. Thanks for reporting this @cmcewen!

**Comment by lostintangent** [comment]
This has been fixed in master and we'll release an update including this to NPM early next week.
